### ISSUE TITLE
ObstacleData is empty from DJI Mini 3 Pro.

### ISSUE THREAD

**Issue by sikbongda** [dji-sdk/Mobile-SDK-Android-V5#100]
Hello! 
Thank you for supporting the model DJI Mini 3 Pro in V5.3.0.

I have problem to get ObstacleData from DJI Mini 3 Pro.
I tested with DJI sample app.
It seems that the ObstacleDataListener is called but the data is empty in the onUpdate(ObstacleData obstacleData) function. 
How can I get the ObstacleData?

![Screenshot_20230413-171221](https://user-images.githubusercontent.com/16881516/231697777-e24e6f59-afb4-4c80-ae12-5e140fc991fb.png)

**Comment by DJI-William** [comment]
The consumer level products such as Mini 3 Pro has no protocols to giving out the obstacle data. The only setting you can set for the obstacle system is the obstacle avoidance type- brake, bypass and close. Other functions are all not settable.
