### ISSUE TITLE
项目运行闪退

### ISSUE THREAD

**Issue by yanshangluobai** [dji-sdk/Mobile-SDK-Android-V5#101]
Unable to get provider dji.v5.inner.background.BackGroundWatcherInstaller: java.lang.ClassNotFoundException: Didn't find class "dji.v5.inner.background.BackGroundWatcherInstaller" on path: DexPathList

**Comment by DJI-William** [comment]
你是在真机上运行的吗？设备的架构是什么？MSDK v5仅支持arm64-v8a架构。

**Comment by yanshangluobai** [comment]
是在真机上运行的，除了arm64-v8a，其他的都没配置

**Comment by DJI-William** [comment]
你的设备是什么型号，架构是什么？查询一下：adb shell getprop ro.product.cpu.abi

**Comment by dji-dev** [comment]
你可以是否在application初始化的是调用com.secneo.sdk.Helper.install(this)吗？例如这样：https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-sample/app-aircraft/src/main/java/dji/sampleV5/aircraft/DJIAircraftApplication.kt
