### ISSUE TITLE
DJI 5 SDK, SurfaceView display of YUV in 4:3 resolution

### ISSUE THREAD

**Issue by neilyoung** [dji-sdk/Mobile-SDK-Android-V5#102]
This should be centered in the SurfaceView, but is left aligned 

![image](https://user-images.githubusercontent.com/731020/233828805-d514faf0-5f29-497f-b174-5bf2abd3bf07.png)

With SDK 4 I did the conversion and drawing by myself using a GLSurfaceView. There was a way to intercept `onSurfaceChanged` and use `GLES20.glViewPort()` to align the drawing centered, but now the SurfaceView is drawn by the SDK. 

How to achieve centered view?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>V5 is able to adjust the size of the decoded video stream.
In your use case, is the size of SurfaceView larger than the size of VideoDecoder?
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
What is "size of VideoDecoder"? You mean the video resolution reported by DJI? This is usually smaller than the SurfaceView resolution, but should be re-evaluated.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>What is "size of VideoDecoder"? You mean the video resolution reported by DJI?
--> It is the width and height .
 ![](https://djisdksupport.zendesk.com/attachments/token/mJfVxTj4WC9Y5ufTNRn6cGeUv/?name=image.png)

The position of the video stream in the surfaceView may not be able to be specified. Would adjusting the position of the surfaceView in the middle, with the video stream filling the surfaceViews meet your needs?<br><a href='https://djisdksupport.zendesk.com/attachments/token/mJfVxTj4WC9Y5ufTNRn6cGeUv' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
Well, I'm instantiating the VideoDecoder always with "don't care" for width and hight, so I suppose I will get what is common currently. I suppose, in any case the SurfaceView is larger.

>The position of the video stream in the surfaceView may not be able to be specified. Would adjusting the position of the surfaceView in the middle, with the video stream filling the surfaceViews meet your needs?

Yes, I guess, that is what is desired.

**Comment by neilyoung** [comment]
Re-reading your post. What I would like to achieve is ro have a 4:3 video centered on Surface with black bars left and right

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>MSDK V5 does not provide this type of functionality.
If you implement this feature yourself, what information would you like to learn about it?
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
I don’t understand your question. I don’t think that i will be able to horizontally shift a drawing on a Surface view which is drawn by you. It’s a cosmetic issue: people are used to see misfitting original video like described centered with some black bars aside or top/bottom. This is so since centuries. You know it from TV, from other solutions or even from Cinema, if an old show is presented. Ok, if you think you are free to do it differently, then I cannot convince you from the contrary. I would rather take out my old DJI GLSurfaceView again and kick out your drawing

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>Sorry, there is indeed no corresponding parameter or interface on the sdk at the moment. Currently sdk can only control the size of the decoded video stream.
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
I think you wouldn't need to provide any additional parameter. You simply would just have to react on changes of either Surface or YUV resolution. This was the solution I was using in my code, when I was drawing the stuff using GLSurfaceView.

I'm sharing it here, because I'm not even sure, that it has grown on my crap. Use it in your next release and it would be fine.

```
    @Override
    public void onSurfaceChanged(GL10 gl, int width, int height) {

        float videoProportion = (float) yuvWidth / (float) yuvHeight;        // globals
        float surfaceProportion = (float) width / (float) height;

        int newWidth, newHeight;
        if (videoProportion > surfaceProportion) {
            newWidth = width;
            newHeight = (int) ((float) width / videoProportion);
        } else {
            newWidth = (int) (videoProportion * (float) height);
            newHeight = height;
        }

        // Align centered
        int xOffs = (width - newWidth) / 2;
        int yOffs = (height - newHeight) / 2;
        if (xOffs < 0)
            xOffs = 0;
        if (yOffs < 0)
            yOffs = 0;

        GLES20.glViewport(xOffs, yOffs, newWidth, newHeight);
    }
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>Thank you for sharing,！ And it will help people with the same intention as yours.
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
In fact it should only help you to integrate that into your code. I can't see how it could help others, unless they are drawing by themselfs

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>I'll let the engineers think about it. But many users simply want to spread the entire surfaceView, and this feature may not be supported either.
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
Meanwhile I worked around by reactivating my old GLES20 code for using a GLSurfaceView. This gives me the chance to apply the onSurfaceChanged function above. I'm not letting you draw the surface (again) and it works.

As a matter of fact, you need to keep the aspect ratio. I got triggered by seeing the 4:3 photo camera image glued to the left side, with a fat black area right, that is uncommon. Now it is centered, the background provides the black bars left and right, and the aspect ratio is kept. Fullscreen with 16:9 input fills the GLSurfaceView entirely

But of course, I would like to get rid of this extra GLES20 dependency again, because it is also hardware relevant, and stick with the SurfaceView drawn by the SDK

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>I will send your comments back to the engineers. In fact, we are sorting out the optimization points, but whether we can implement them needs to be evaluated by the team.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81784'>Zendesk ticket #81784</a>:<br><br>The results I got from the engineers are that it is highly unlikely that this feature will be supported. This is a showcase feature, and the priority of this type of feature is currently low.
<br><p><em><small>°°°</small></em></p>

**Comment by neilyoung** [comment]
We worked around.
