### ISSUE TITLE
Model and payload numbers (droneEnumValue, droneSubEnumValue) for Mini 3 Pro?

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#103]
Looking at the official documentation references
- https://developer.dji.com/doc/cloud-api-tutorial/en/feature-set/dji-wpml/common-element.html
- https://sdk-forum.dji.net/hc/en-us/articles/11580925155353-Model-and-payload-numbers-required-for-route-documentation

I can see proper values for the M30, M30T, Mavic 3 E, etc but not for the Mini 3 Pro. Could you please provide values for the Mini 3 Pro as well?

I'm trying to use Mini 3 Pro with DJI RC Pro controller. The SDK version is 5.3.0.

Thanks,

Ray

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81902'>Zendesk ticket #81902</a>:<br><br>Dear Client

Thank you for contacting DJI.

The mini 3 pro is not supported by Cloud API, so there is no corresponding value, and it does not support routes.
Currently the mini series does not support flight routes.

Hopefully our solution can help you.

Kindly Regards,

DJI Developer Support
<br><p><em><small>°°°</small></em></p>
