### ISSUE TITLE
DJI Fly app 1.10.0 conflicts with apps using Mobile SDK V5.3.0 (fights over control over aircraft endlessly) despite being swiped away from recent apps screen

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#104]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

## Screenshots / Videos

![dji_mini3pro_latest_firmware](https://user-images.githubusercontent.com/131709565/234383913-d61267c9-ba61-4298-8e12-73d3e9bddae3.png)

**Video**: https://drive.google.com/file/d/1mXx8OAehZcg8jF8Oy4hKSPOdWDq06RNn/view?usp=share_link

## Repro steps

1. Insert API keys appropriately
2. Build Mobile-SDK-Android-V5 app in Android Studio
3. Open DJI Fly app
4. Make sure the Drone is paired correctly
5. Install the Mobile SDK V5 Sample App
6. Swipe away the DJI Fly app
7. Run the Sample App
8. Observe the Sample App constantly disconnecting and reconnecting from the drone, and the model name flickering from "UNRECOGNIZED" to the actual model and back and forth constantly.
9. If you go back to DJI Fly app, you'll also notice similar behavior there, where the app constantly loses control.

## Acceptance criteria

DJI Fly app and an app that uses the SDK must be able to co-exist together and not fight. If the user is using an SDK app, the SDK app must have and retain full control over the drone throughout the entire session.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81986'>Zendesk ticket #81986</a>:<br><br>DJI RC Pro does not support running DJI official App and MSDK application at the same time: Why is the connection of RC Pro or RC Plus very unstable?
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to me. This is not about running at the same time - notice the user **swipes away** the DJI Fly app from recents screen at step 6. At step 8 when they come back to MSDK application, the issue occurs where DJI Fly app is still somehow interfering with the MSDK app **despite swiping the DJI Fly app away**.

This can be confirmed by **Force stopping** the DJI Fly app in the System settings after step 8 **AFTER the DJI Fly app was already swiped away,** which alleviates the issue. But, this is impractical/infeasible to ask of the user.

**Comment by rayw-dronesense** [comment]
I highly recommend watching the video for the full picture  https://drive.google.com/file/d/1mXx8OAehZcg8jF8Oy4hKSPOdWDq06RNn/view?usp=share_link

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81986'>Zendesk ticket #81986</a>:<br><br>DJI RC Pro currently does not support running DJI official app and MSDK application at the same time, it is indeed necessary to kill one of the applications to alleviate the problem. I have already understood your appeal, and I will give feedback to see if this problem can be optimized in the future.
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Hi there - why is this being closed? The issue is not resolved.
