### ISSUE TITLE
Physical zoom wheel does not work with Mobile SDK V5.3.0 on DJI RC Pro & DJI Mini 3 Pro

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#105]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

## Screenshots

![dji_mini3pro_latest_firmware](https://user-images.githubusercontent.com/131709565/234383913-d61267c9-ba61-4298-8e12-73d3e9bddae3.png)

## Repro steps

1. Insert API keys appropriately
2. Build Mobile-SDK-Android-V5 app in Android Studio
3. Open the Sample App
4. Click Default View
5. Attempt to Zoom In with the zoom wheel - nothing happens.

## Acceptance criteria

User must be able to zoom in while using an SDK app just like in the DJI Fly app.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>Dear Client

Thank you for contacting DJI.

I try to realize the zoom of the zoom lens by binding the pulsator, it is ok

Hopefully our solution can help you.

Kindly Regards,

DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

I'm not quite sure what you mean by "pulsator", but what we mean is this,

![zoomwheel](https://user-images.githubusercontent.com/131709565/234875789-ec45916e-0055-4386-ae08-4c9766986a76.jpg)

In the DJI Fly app, this wheel controls zoom. But, it does not work in MSDK app.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>I tested that zooming is possible with the left scroll wheel

    KeyManager.getInstance() .listen(KeyTools.createKey(RemoteControllerKey.KeyLeftDial), this) { _, newValue -> Log.i("波轮到的","$newValue") if (newValue != null) { if(newValue>0){ KeyManager.getInstance().setValue(KeyTools.createCameraKey(CameraKey.KeyCameraZoomRatios,ComponentIndexType.LEFT_OR_MAIN,CameraLensType.CAMERA_LENS_ZOOM),2.0*newValue,object : CommonCallbacks.CompletionCallback { override fun onSuccess() { Log.i("设置成功","") } override fun onFailure(error: IDJIError) { Log.i("设置失败","${error.description()}") } }) } } }
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

While it does sound like the proposal could work, I am having some doubts as to whether that is the most appropriate way to go. If the left dial is already able to perform gimbal operations on its own without manual intervention (i.e. manually hooking up listeners), then shouldn't the zoom wheel (right dial) do the same?

**Comment by rayw-dronesense** [comment]
Just to confirm, it is expected behavior that the right wheel / zoom wheel works in DJI Fly as expected, but does not work in MSDK app?

At the same time, it is expected behavior that the left wheel / gimbal wheel works in both?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>In the sample of MSDK5.3.0, I can zoom in and out through the right scroll wheel on the default page, see the video for details：https://pan-sec.djicorp.com/s/sB5inzD7o4Jxzxf
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to me. I took a look at the video - that looks like it was done with Mavic 3 Enterprise...would you mind trying the same with the Mini 3 Pro, which is the drone I'm having issues with?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>I will try to test it with mini 3 pro and will get back to you with the results
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>I tried to use Mini 3 pro to adjust the zoom by monitoring the change of the right scroll wheel, and it was successful. See below for details:
 ![](https://djisdksupport.zendesk.com/attachments/token/BAapQlCojTWzl6Yst9TcpfWTP/?name=image.png)<br><a href='https://djisdksupport.zendesk.com/attachments/token/BAapQlCojTWzl6Yst9TcpfWTP' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

Thanks for showing that using additional code, we can manually initiate zoom logic through the zoom dial.

However, I still don't understand, is there a reason why the zoom does not work on its own without additional code in MSDK Default Page but the Gimbal tilt works automatically without additional code?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81987'>Zendesk ticket #81987</a>:<br><br>In this case, it is possible that the firmware itself implements the action of the scroll wheel, so there is a corresponding function in MSDK even if the code is not implemented. For the zoom action, there may be no corresponding implementation in the firmware, so the user needs to monitor the action to implement it.
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Hi there, 

I finally had a chance to give this a try.

Unfortunately, it is not actually working with triggering zoom on Mini 3 Pro with RC Pro, despite the "onSuccess" callback,

https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/131709565/47b115a4-032e-40b2-9105-8f10db36ba25


Please advise.

Thanks,

Ray
