### ISSUE TITLE
Radar Chart not working with Mobile SDK V5.3.0 on DJI RC Pro & DJI Mini 3 Pro

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#106]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

## Repro steps

1. Insert API keys appropriately
2. Build Mobile-SDK-Android-V5 app in Android Studio
3. Open the Sample App
4. Click Default View
5. Initiate take off and get the aircraft off the ground.
6. Get close to stuff at the top or bottom.
7. No visual radar / radar chart shows up.

## Acceptance criteria

User must be able to see visual radar / radar chart in an SDK app just like in the DJI Fly app.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82088'>Zendesk ticket #82088</a>:<br><br>能把你显示的页面图片发过来不？
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

Here is the DJI Fly app showing the Radar Chart feature in action,

![Screenshot 2023-04-27 at 9 41 14 AM](https://user-images.githubusercontent.com/131709565/234882204-80bbbf61-3db2-4e7b-858d-f130e1e94b0c.png)


But it does not seem to work with Mobile SDK 5.3.0, here is the MSDK Sample app,

![Screenshot 2023-04-27 at 9 42 35 AM](https://user-images.githubusercontent.com/131709565/234882221-9bfdf885-ed17-4336-8396-45a2bf310d5f.png)

I'm guessing it might have something to do with the callback not being invoked when aircraft gets this data,
```
perceptionManager.addObstacleDataListener
```

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82088'>Zendesk ticket #82088</a>:<br><br>Sorry, Dji mini 3 pro, MSDK does not currently support enabling radar charts
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

Just to clarify - so even though Radar Chart on the Mini 3 Pro works in the DJI Fly app, MSDK support is not there yet? Is that correct?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82088'>Zendesk ticket #82088</a>:<br><br>Yes, currently MSDK does not support opening the radar chart
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
The issue has been fixed in version 5.9.
