### ISSUE TITLE
How to change/set storage location (SD Card, Internal) programmatically using Mobile SDK V5.3.0?

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#107]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

## Description

In the **DJI Fly** app, one can switch storage locations within the app,

![Screenshot 2023-04-27 at 9 50 47 AM](https://user-images.githubusercontent.com/131709565/234911114-ee319fd7-7687-47df-a5fa-5f2257fce05b.png)

![Screenshot 2023-04-27 at 9 51 00 AM](https://user-images.githubusercontent.com/131709565/234911121-972221cf-72af-48cc-b4c7-a47d5513c95d.png)

But for some reason, I'm not able to find a way to do this programmatically using Mobile SDK V5.3.0.

I tried using,
```
RxUtil.setValue(KeyTools.createKey(CameraKey.KeyCameraStorageLocation, ComponentIndexType.LEFT_OR_MAIN), CameraStorageLocation.SDCARD)
```

But it didn't change anything.

Would you mind helping with this matter? Thanks!

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82171'>Zendesk ticket #82171</a>:<br><br>what is your aircraft type？
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

**Comment by rayw-dronesense** [comment]
The aircraft is DJI Mini 3 Pro, thanks!

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82171'>Zendesk ticket #82171</a>:<br><br>At present, this key is not open to the outside world, but I use your model Mini 3 pro to test the switch in the 5.3.0 sample of MSDK and it can be successfully switched. I can also switch successfully on DJI fly. You can try to Use it to see.
 ![](https://djisdksupport.zendesk.com/attachments/token/CYPL7rXTIaNezoWwKsVT358KD/?name=12984e5da44f248991881aa240bb450.jpg)<br><a href='https://djisdksupport.zendesk.com/attachments/token/CYPL7rXTIaNezoWwKsVT358KD' target='zd_attach'>12984e5da44f248991881aa240bb450.jpg</a>
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to me.

Would you mind confirming whether the following code snippet is the correct way to achieve this?

```
RxUtil.setValue(KeyTools.createKey(CameraKey.KeyCameraStorageLocation, ComponentIndexType.LEFT_OR_MAIN), CameraStorageLocation.SDCARD)
```

**Comment by rayw-dronesense** [comment]
I took another look through that section of the MSDK sample app, it looks like this is the snippet that works,

```
            val storageLocationKey = KeyTools.createKey(CameraKey.KeyCameraStorageLocation)
            KeyManager.getInstance().setValue(storageLocationKey, CameraStorageLocation.SDCARD, object : CompletionCallback {
                override fun onSuccess() {
                    Toast.makeText(ctx, "IT WAS SUCCESFUL", Toast.LENGTH_LONG).show()
                }

                override fun onFailure(error: IDJIError) {
                    Toast.makeText(ctx, "IT WAS A FAILURE ${error.description()}", Toast.LENGTH_LONG).show()
                }

            })
```

Thanks for your help!

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82171'>Zendesk ticket #82171</a>:<br><br>You're welcome, glad to be able to solve your problem
<br><p><em><small>°°°</small></em></p>
