### ISSUE TITLE
Horizontal Obstacle Avoidance not toggleable on Mavic 3 Enterprise

### ISSUE THREAD

**Issue by timothyolt-dronesense** [dji-sdk/Mobile-SDK-Android-V5#108]
### Environment
Drone: DJI Mavic 3T Enterprise
Controller: DJI RC Pro Enterprise
DJI Pilot 2 app version: 6.1.1.1
Mobile SDK version: 5.3.0
Aircraft Firmware version: 06.01.0606
RC Firmware version: 02.00.0407

### Description
In the DJI Pilot 2 app, Horizontal Obstacle Avoidance is toggleable in Brake mode

https://user-images.githubusercontent.com/132092688/235217021-e9a8dd38-5ab6-4a03-8389-6562914d43cd.mp4

Via the MSDK, while the upward and downward directions are toggleable, the horizontal direction shows an error: `OPERATION_NOT_SUPPORT`

https://user-images.githubusercontent.com/132092688/235217648-df821504-7dd5-4201-972b-9f4e4eaff513.mp4

**Comment by DJI-William** [comment]
Reproducible, I will report to the dev team.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/82251'>Zendesk ticket #82251</a>:<br><br>We have made code modifications for this issue, and it will be released in version 5.6.
<br><p><em><small>°°°</small></em></p>

**Comment by timothyolt-dronesense** [comment]
So strange, that's exactly how I expected it to work. Here's a full video of what we see on the M3T.

https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/56d70160-63ff-422e-94b2-97b9ef65f715

**Comment by dji-lyt** [comment]
This issue has been fixed in 5.6.
