### ISSUE TITLE
Failed to instantiate one or more classes

### ISSUE THREAD

**Issue by ernesto13edop** [dji-sdk/Mobile-SDK-Android-V5#109]
When I use MSDK code in a custom view I get the error "Failed to instantiate one or more classes".

I am using:
```
Android Studio Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true
```
`MSDK: 5.3.0`
 For this error i can't see the preview of my views on previews screen.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/82423'>Zendesk ticket #82423</a>:<br><br>You can try using other versions of Android studio, such as Android Studio Chipmunk | 2021.2.1 RC 1.
 ![](https://djisdksupport.zendesk.com/attachments/token/g1UDOexmnCuHDodPTVvrzi5xR/?name=image.png)

It's true that there may be something that needs to be adapted on the latest Android studio.<br><a href='https://djisdksupport.zendesk.com/attachments/token/g1UDOexmnCuHDodPTVvrzi5xR' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>
