### ISSUE TITLE
Support armeabi-v7a, armeabi ?

### ISSUE THREAD

**Issue by vancuong0429** [dji-sdk/Mobile-SDK-Android-V5#110]
It has support for armeabi-v7a, armeabi ?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82724'>Zendesk ticket #82724</a>:<br><br>Now MSDK V5 support architecture is 'arm64-v8a', not yet support armeabi-v7a, armeabi
<br><p><em><small>°°°</small></em></p>
