### ISSUE TITLE
MSDK V5 supports phantom, mini series?

### ISSUE THREAD

**Issue by vancuong0429** [dji-sdk/Mobile-SDK-Android-V5#111]

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/82767'>Zendesk ticket #82767</a>:<br><br>MSDKV5 does not support phantom, supports mini3 and mini3 pro
<br><p><em><small>°°°</small></em></p>
