### ISSUE TITLE
Unresolved reference: BuildConfig

### ISSUE THREAD

**Issue by timelikeswind** [dji-sdk/Mobile-SDK-Android-V5#112]
In android-sdk-v5-uxsdk\src\main\java\dji\v5\ux\core\base\widget\FrameLayoutWidget.kt, when import Unresolved reference: BuildConfig, error occurs: 
`e: E:\File\Android\MyApplication\app\libs\android-sdk-v5-uxsdk\src\main\java\dji\v5\ux\core\base\widget\FrameLayoutWidget.kt: (179, 13): Unresolved reference: BuildConfig`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/83151'>Zendesk ticket #83151</a>:<br><br>Did you trigger this issue when you imported the UXSDK module? Or is it when running this demo?
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
No reply for a long time, close the issue.
