### ISSUE TITLE
DJI mobilke sdk 5 with flighthub 2

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Mobile-SDK-Android-V5#113]
Is there anyway to work with flighthub 2 in a similar way to FlightHubManager in MSDK4?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/83367'>Zendesk ticket #83367</a>:<br><br>MSDK does not have the function of connecting to flighthub 2. If you need this function very much, you can submit your request through this address: https://sdk-forum.dji.net/hc/zh-cn/requests/new?ticket_form_id=900001474643
<br><p><em><small>°°°</small></em></p>
