### ISSUE TITLE
Physical zoom wheel does not work with Mobile SDK V5.3.0 on DJI RC Pro & DJI Mini 3 Pro (reopening #105)

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#114]
## Environment

**Drone:** DJI Mini 3 Pro
**Controller:** DJI RC Pro
**DJI Fly app version:** 1.10.0
**Mobile SDK version:** 5.3.0
**Aircraft Firmware version:** 01.00.0600
**RC Firmware version:** 03.02.0100

## Screenshots

![dji_mini3pro_latest_firmware](https://user-images.githubusercontent.com/131709565/234383913-d61267c9-ba61-4298-8e12-73d3e9bddae3.png)

![zoomwheel](https://user-images.githubusercontent.com/131709565/234875789-ec45916e-0055-4386-ae08-4c9766986a76.jpg)

## Repro steps

1. Insert API keys appropriately
2. Build Mobile-SDK-Android-V5 app in Android Studio
3. Open the Sample App
4. Click Default View
5. Attempt to Zoom In with the zoom wheel - nothing happens.

## Acceptance criteria

User must be able to zoom in while using an SDK app just like in the DJI Fly app.

## Addendum

In the previous issue #105 , some code snippets were provided to try to fix this issue. However, when we tried this, it did not work,

------------------------------------------------

Hi there, 

I finally had a chance to give this a try.

Unfortunately, it is not actually working with triggering zoom on Mini 3 Pro with RC Pro, despite the "onSuccess" callback,

https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/131709565/47b115a4-032e-40b2-9105-8f10db36ba25

Please advise.

Thanks,

Ray

------------------------------------------------

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/84427'>Zendesk ticket #84427</a>:<br><br>I can set it up successfully according to the following code, see the video for details
video address: https://pan-sec.djicorp.com/s/KGgbW2mYfQB9BqD

    KeyManager.getInstance() .listen(KeyTools.createKey(RemoteControllerKey.KeyRightDial), this) { _, newValue -> Log.i("value","$newValue") if (newValue != null) { if(newValue>0){ KeyManager.getInstance().setValue(KeyTools.createCameraKey(CameraKey.KeyCameraZoomRatios,ComponentIndexType.LEFT_OR_MAIN, CameraLensType.CAMERA_LENS_ZOOM),2.0,object : CommonCallbacks.CompletionCallback { override fun onSuccess() { Log.i("success","") } override fun onFailure(error: IDJIError) { Log.i("fail","${error.description()}") } }) } } }
<br><p><em><small>°°°</small></em></p>

**Comment by rayw-dronesense** [comment]
Thanks for getting back to us.

This new snippet is an improvement upon the previous behavior, but still does not fully replicate the original functionality. 

In the DJI Fly app, moving the wheel to the right results in the feed smoothly and gradually zooming in. Moving the same wheel  to the left results in the feed smoothly and graduating zooming out. 

However, with this snippet it instantly jumps to 2.0 and stays there.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/84427'>Zendesk ticket #84427</a>:<br><br>The code snippet I gave you is just to express that the function is available, if you want to achieve zooming, the code implementation needs to be implemented by yourself.
<br><p><em><small>°°°</small></em></p>
