### ISSUE TITLE
Video Recording Throws Error

### ISSUE THREAD

**Issue by jwcharp** [dji-sdk/Mobile-SDK-Android-V5#116]
We are having issue implementing the SDK, it is very cumbersome to working with compared to v4, or perhaps we are are not visualizing it properly.

We have successfully issued the camera to take a photo but when we try to start recording of a video we keep getting an error.

Here is our code:

```

KeyManager.getInstance().performAction(KeyTools.createKey(CameraKey.KeyStartRecord), object :
    CommonCallbacks.CompletionCallbackWithParam<EmptyMsg> {
    override fun onSuccess(t: EmptyMsg?) {
        toast("start record success")
    }

    override fun onFailure(error: IDJIError) {
        toast(error.errorCode() +":"+ error.description())
    }
})

```

Can you point out where we are going wrong.

We are gettting the following error returned:
CANNOT_START_TASK_VLOTAGE_ALARM

Thank you,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/84922'>Zendesk ticket #84922</a>:<br><br>Did you switch the camera to the corresponding mode before using KeyStartRecord?  That is KeyCameraMode
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
@dji-dev thank you that is what we were missing!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/84922'>Zendesk ticket #84922</a>:<br><br>Glad to have assisted you, the issue will be closed.
<br><p><em><small>°°°</small></em></p>
