### ISSUE TITLE
sometimes preview will stuck with Surfaceview

### ISSUE THREAD

**Issue by gangwang2020** [dji-sdk/Mobile-SDK-Android-V5#117]
the original issue is here: 
https://sdk-forum.dji.net/hc/en-us/community/posts/19629969040537-%E4%BD%BF%E7%94%A8SurfaceView%E6%92%AD%E6%94%BE%E7%9B%B8%E6%9C%BA%E7%95%8C%E9%9D%A2-%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E5%90%8E%E5%8D%A1%E4%BD%8F%E4%B8%8D%E5%8A%A8

we also faced same issue.

**Comment by gangwang2020** [comment]
We have tried with DJI demo app,  preview will stuck also

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>Could you please let me know what type of device you are using? This issue may be a known problem.
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
We have produced the issue with following devices:
1. Mate20  HarmonyOS 3.0.0.168，more possibilities to reproduce it
2. S10  OneUI 4.1 Android 12 
3. S20 OneUI 5.1 Android 13

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>I reproduced the problem and have submitted it to the engineer for confirmation.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>将这段话翻译成礼貌的英文：
现在的MSDK V5还未支持Android 10以上的设备，您可以尝试使用版本较低的设备，看看是否还会存在这个问题。我们已经将问题升级给了工程师进行分析。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
We apologize for any inconvenience caused. We regret to inform you that the current MSDK V5 does not support devices with Android 10 or higher. 
However, you may try using a device with a lower version to see if the issue persists. Please be assured that we have escalated the issue to our engineers for further analysis.

If you have any further questions or concerns, please do not hesitate to contact us.

**Comment by gangwang2020** [comment]
If the SDK only support devices with android 9 or lower, most of Android phones can not use it I think.
Any timeline to support  Android 10 or later version.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>We will adapt to Android 13 in version 5.5, which is expected to be released in the next two months. I hope that the SDK can be used stably on higher version devices in version 5.5.
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
Got it, thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>I'm glad I could help you.Wish you have a wonderful day.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
Version 5.5 has been released, which implements Android 13 adaptation.

**Comment by gangwang2020** [comment]
DJI SDK v5.5 does not resolve preview hung issue as I described in the title. another developer report the issue also:
https://sdk-forum.dji.net/hc/en-us/community/posts/19629969040537-%E4%BD%BF%E7%94%A8SurfaceView%E6%92%AD%E6%94%BE%E7%9B%B8%E6%9C%BA%E7%95%8C%E9%9D%A2-%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E5%90%8E%E5%8D%A1%E4%BD%8F%E4%B8%8D%E5%8A%A8

**Comment by gangwang2020** [comment]
We used DJI demo with v5.5 SDK also reproduced the preview hung issue.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>Could you please provide us with a video of the frozen screen as a sample? Here is the upload address：https://pan-sec.djicorp.com/s/Y864LBTZaWDJaw8
In addition, what device are you using?
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
Please check following uploaded files:

1. V5.5-Huawei_mate20_dji_demo_ui_responding_problem.mp4:
Parts of views will not responding while the ones with a new window still working.

2. V5.5-SAMSUNG_S22_MSDK Aircraft_preview_problem.mp4 and V5.5-Huawei_mate20_dji_demo_preview_problem.mp4
The surface view renders no data while the drone is still connecting

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>Thank you for your patient response.
I have forwarded your issue to our engineers for analysis, which will take some time. I hope you can understand. I will keep you updated with the information regarding your issue as soon as possible.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85203'>Zendesk ticket #85203</a>:<br><br>I hope this message finds you well.
I wanted to inform you that a new version, 5.8.0-a2, has been released. This update includes new camera streaming and live streaming interfaces that support features such as adaptive screen display and no-screen live streaming. Additionally, we have conducted tests and found that the rendering lag issue has been significantly reduced.

I would recommend upgrading to this version to experience these improvements. Please let me know if you have any questions or need further assistance.
<br><p><em><small>°°°</small></em></p>
