### ISSUE TITLE
Crash  when change RC mode during  wayPointMission . M3T used . App developed on MSDK v5.3.0

### ISSUE THREAD

**Issue by 72chen** [dji-sdk/Mobile-SDK-Android-V5#118]
Crash log :

# main(2)
SIGSEGV(SEGV_MAPERR)

#00 pc 000000000007fa70 /apex/com.android.runtime/lib64/bionic/libc.so (strlen+16) [arm64-v8a::21847aa9757f000b0461310a9f5e6e51]

#01 pc 00000000013654f0 /data/app/com.airia.drone-sAmj_DeuanqLR5VhYtBpwg==/lib/arm64/libdjisdk_jni.so (dji::sdk::jni::JNI_Waypoint3Manager_QueryWaypointV3BreakPointInfo(_JNIEnv*, _jobject*, long, long, _jstring*, _jobject*, _jobject*)+100) [arm64-v8a::]

#02 pc 0000000000012350 /apex/com.android.runtime/lib64/libart.so [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#03 pc 00000000000095b8 /apex/com.android.runtime/lib64/libart.so [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#04 pc 000000000001800c /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#05 pc 00000000001b504c /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#06 pc 00000000001b135c /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+692) [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#07 pc 0000000000477b58 /apex/com.android.runtime/lib64/libart.so (MterpInvokeStaticRange+236) [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#08 pc 0000000000003c94 /apex/com.android.runtime/lib64/libart.so [arm64-v8a::ca513fca91ea31d6038275c9a3d1ef47]

#09 pc 000000001593d25c <unknown>

java:

dji.sdk.waypointv3.jni.Waypoint3Manager.queryWaypointV3BreakPointInfo(Waypoint3Manager.java:1)

com.dji.industry.mission.co_g.co_a(WaypointMissionV3Impl.java:64)

com.dji.industry.mission.co_g.co_a(WaypointMissionV3Impl.java:6)

com.dji.industry.mission.co_g.access$lambda$7(Unknown Source:0)

com.dji.industry.mission.co_g$$Lambda$8.invoke(Unknown Source:5)

dji.jni.callback.CallbackHelper.lambda$callWaypointV3MissionStateCallback$41(CallbackHelper.java:1)

dji.jni.callback.CallbackHelper$$Lambda$42.run(Unknown Source:8)

android.os.Handler.handleCallback(Handler.java:883)

android.os.Handler.dispatchMessage(Handler.java:100)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85263'>Zendesk ticket #85263</a>:<br><br>Would changing the RC mode definitely cause a crash? Have you tested it on version 5.4, which is the latest version?
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
We will be fixing similar crashes in 5.5, which you can test after the 5.5 release, but there is no way to determine when 5.5 will be released yet.

**Comment by dji-lyt** [comment]
Version 5.5 has been released.
