### ISSUE TITLE
SDK是否支持大疆手机云台Osmo Mobile 6

### ISSUE THREAD

**Issue by pengwei1024** [dji-sdk/Mobile-SDK-Android-V5#120]
RT，能支持大疆手机云台吗，其他app想获取云台当前的运行状态，以及电量的信息

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/85671'>Zendesk ticket #85671</a>:<br><br>非常感谢您联系我们。很抱歉地告诉您，我们的MSDK目前不支持Osmo Mobile 6。非常抱歉给您带来不便。
<br><p><em><small>°°°</small></em></p>

**Comment by pengwei1024** [comment]
> Agent comment from ekho.feng in [Zendesk ticket #85671](https://djisdksupport.zendesk.com/agent/tickets/85671):非常感谢您联系我们。很抱歉地告诉您，我们的MSDK目前不支持Osmo Mobile 6。非常抱歉给您带来不便。
> 
> _°°°_

请问下我们想获取手机云台的电量有其他方式能实现不

**Comment by dji-lyt** [comment]
我们没有其他推荐方法去拿云台的电量。SDK没有适配Osmo Mobile 6，即便SDK可以识别到机型，但不确定可以稳定使用。
