### ISSUE TITLE
多次上传航线后，执行航线飞行时，航线任务执行状态返回次数过多，以及航线信息返回

### ISSUE THREAD

**Issue by doncc** [dji-sdk/Mobile-SDK-Android-V5#121]
复现步骤：
1. 设置 `addWaypointMissionExecuteStateListener()` 航线任务状态监听
2. 设置 `addWaylineExecutingInfoListener()` 航线信息的监听器
3. 一次以上（两次或多次）调用 `pushKMZFileToAircraft()` 上传航线
4. 调用 `startMission()` 执行航线飞行

问题描述：
1. 当多次上传航线后，航线任务的执行状态监听 `onMissionStateUpdate()` 方法内，`WaypointMissionExecuteState` 状态会多次返回状态结果；
2. 当多次上传航线后，执行飞行过程中，航线信息 `onWaylineExecutingInfoUpdate()` 方法内，`WaylineExecutingInfo.getCurrentWaypointIndex()` 函数，会在第一个点位置，出现当前执行的航点序号错误的问题。
3. 当未到达第一个航点时，`getCurrentWaypointIndex()` 返回的值0，与第一个航点所返回的0，无法做区分 。

问题复现频率：
必现

影响设备：
M3T

MSDK版本：
v5.3.0、v5.4.0

伪代码：
```
waypointMissionManager.addWaypointMissionExecuteStateListener(new WaypointMissionExecuteStateListener() {
    @Override
    public void onMissionStateUpdate(WaypointMissionExecuteState missionState) {
        Log.d(TAG, "航线任务状态：" + missionState);
    }
});
waypointMissionManager.addWaylineExecutingInfoListener(new WaylineExecutingInfoListener() {
    @Override
    public void onWaylineExecutingInfoUpdate(WaylineExecutingInfo excutingWaylineInfo) {
        //当执行的航线信息发生变化时会回调此方法。
        System.out.println("航线信息onWaylineExecutingInfoUpdate: " +
                " WaylineID:" + excutingWaylineInfo.getWaylineID() +
                " CurrentWaypointIndex:" + excutingWaylineInfo.getCurrentWaypointIndex());
    }
});
```

参考日志：
![QQ截图20230627202801](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/3993101/d63ed4ad-d0a8-430b-8223-6fea56977e02)

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/85809'>Zendesk ticket #85809</a>:<br><br>可以提供一下您的kmz文件给我们么？上传地址：https://pan-sec.djicorp.com/s/RgWd9xCETwQmoB2
<br><p><em><small>°°°</small></em></p>

**Comment by doncc** [comment]
兄弟，实在抱歉，kmz包含了位置信息，有些敏感，不太方便提供。
但您这边可以通过DJI Pilot2 App，首页航线->创建航线->航点飞行->地图选点，任意戳几个航点，便可生成跟我类似的kmz航线。

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/85809'>Zendesk ticket #85809</a>:<br><br>感谢您的联系，想请问一下您该问题有在官方的demo中尝试过是否会出现同样的现象么？
<br><p><em><small>°°°</small></em></p>

**Comment by doncc** [comment]
您好，感谢DJI的兄弟们的支持。
目前又经历了大量测试，问题描述的1、2部分没再出现过，官方Demo也未出现过。不知是稳定性问题还是什么，没再出现了。但问题描述的3依然存在，官方Demo也尝试过同样现象。

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85809'>Zendesk ticket #85809</a>:<br><br>问题 3，你可以通过结合航点状态去区分。WaypointMissionExecuteState为ENTER_WAYLINE的时候飞机还没有到达航点位置，当WaypointMissionExecuteState为EXECUTING，飞机就已经达到航点位置了。
<br><p><em><small>°°°</small></em></p>

**Comment by doncc** [comment]
确实可以通过结合WaypointMissionExecuteState状态，来判断航点编号是否到达。我可能理解的这个接口是，不到达航点位置时，回调函数不会有航点位置编号的回调。
目前我可以结合WaypointMissionExecuteState状态，来做判断了。您这边如果确认，不是因为实现上的疏忽，导致现在的现象就没问题。

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85809'>Zendesk ticket #85809</a>:<br><br>确实可以通过结合WaypointMissionExecuteState状态，来判断航点编号是否到达。我可能理解的这个接口是，不到达航点位置时，回调函数不会有航点位置编号的回调。
目前我可以结合WaypointMissionExecuteState状态，来做判断了。您这边如果确认，不是因为实现上的疏忽，导致现在的现象就没问题。
-->WaypointMissionExecuteState在没有到达航点前回调0或航线暂停时回调0是正常的，这里是0表示的是无效或者默认的航点序号。
<br><p><em><small>°°°</small></em></p>

**Comment by doncc** [comment]
WaypointMissionExecuteState在没有到达航点前回调0或航线暂停时回调0是正常的，这里是0表示的是无效或者默认的航点序号。
--> 好的，了解您这边设计情况就ok了。
目前问题1、2无再次复现。此issue我暂时关闭了。感谢兄弟们的支持。
