### ISSUE TITLE
Video stream disconect

### ISSUE THREAD

**Issue by wailbabou** [dji-sdk/Mobile-SDK-Android-V5#124]
### Environment
Drone: DJI Mini 3 Pro
Controller: DJI FPV Drone Remote Controller 2
Goggles: DJI goggles 2 awaken 
Mobile SDK version: 5.4.2
Aircraft Firmware version: 01.00.0600
Android version : tested using both Android 8 and Android 13
### Repro steps
- Install V5 sample app
- Testing tool -> Multi video decoding

I'm getting :

![V5 Sample](https://i.ibb.co/0Fb7Ct6/msdk.jpg)

## Debug
I added some logs to see the available streams and I'm seeing :
 
 **[StreamSource{physicalDeviceCategory = CAMERA, physicalDeviceType = DJI_MINI_3_PRO, physicalDevicePosition = PORTSIDE, streamId = -1}]**

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86166'>Zendesk ticket #86166</a>:<br><br>We have not adapted MSDK and mini 3 pro for the DJI FPV Drone Remote Controller 2.
Currently, you can check this article for the available controllers.：Do DJI MINI 3 and DJI MINI 3 PRO support airline flight?
<br><p><em><small>°°°</small></em></p>
