### ISSUE TITLE
Changing Video Resolutions

### ISSUE THREAD

**Issue by jwcharp** [dji-sdk/Mobile-SDK-Android-V5#125]
Hello we are struggling to change to any resolution other then 1920x1080 on the Mini 3 Pro

Here is our call that works

```
KeyManager.getInstance().setValue(KeyTools.createKey(CameraKey.KeyVideoResolutionFrameRate),
    VideoResolutionFrameRate(VideoResolution.RESOLUTION_1920x1080, VideoFrameRate.RATE_30FPS),
    object:CommonCallbacks.CompletionCallback{
        override fun onSuccess() {
            toast("Successfully updated frame rate and resolution")
        }

        override fun onFailure(error: IDJIError) {
            toast("FAILED TO update frame rate and resolution")
        }
    })


```

Here is one that fails

```
KeyManager.getInstance().setValue(KeyTools.createKey(CameraKey.KeyVideoResolutionFrameRate),
    VideoResolutionFrameRate(VideoResolution.RESOLUTION_1280x720, VideoFrameRate.RATE_30FPS),
    object:CommonCallbacks.CompletionCallback{
        override fun onSuccess() {
            toast("Successfully updated frame rate and resolution")
        }

        override fun onFailure(error: IDJIError) {
            toast("FAILED TO update frame rate and resolution")
        }
    })
```

We receive the following error:
CANNOT_START_TASK_VLOTAGE_ALARM

what are the supported resolutions and frame rates.

We want to record at 1280x720 @ 120fps

Thank you,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86486'>Zendesk ticket #86486</a>:<br><br>Have you confirmed that 1280x720 is the supported resolution for DJI MINI 3 PRO? The KeyVideoResolutionFrameRate can be used to obtain the resolution supported by the current aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
@dji-dev Thank you for your response!

The Mini 2 in its spec sheet also did not say it supported 1280x720 @ 60fps, but it did and was able to record at that resolution with no issue.

I understand the Mini 3 is a complete rebuild -
The specs state this:
4K: 3840×2160@24/25/30/48/50/60fps
2.7K: 2720×1530@24/25/30/48/50/60fps
FHD: 1920×1080@24/25/30/48/50/60fps
Slow Motion: 1920×1080@120fps

But any time I try to make the resolution anything but 1920x1080, I get the error mentioned.
I will play around with the key today to see what responses I can get.

Thank you,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86486'>Zendesk ticket #86486</a>:<br><br>I used KeyVideoResolutionFrameRateRange to get a list of supported parameters for the MINI 3 and then switching the screen to 1280x720 @ 60fps was successful.
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
Thank for your reply, we are using the Mini 3 Pro, unfortunately we are unable able to get any 1280x720 to work.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86486'>Zendesk ticket #86486</a>:<br><br>Is it through KeyVideoResolutionFrameRateRange to get the list that there is no 1280x720 option? So is it possible to set 1280x720 in DJI Fly?
<br><p><em><small>°°°</small></em></p>
