### ISSUE TITLE
GeneratedMediaFileInfo FileSize is Integer, probably should be Long

### ISSUE THREAD

**Issue by lucas-skyebrowse** [dji-sdk/Mobile-SDK-Android-V5#126]
Noticed, that sending newly generated file size to server produce negative values in logs. 

In MediaFile, the file size type is Long.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86589'>Zendesk ticket #86589</a>:<br><br>We have taken note of the issue with the Integer type and have forwarded it to our team for further investigation and resolution.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
This issue has been fixed in 5.6.
