### ISSUE TITLE
Video stream data listener I-frame interval too large

### ISSUE THREAD

**Issue by simonblee** [dji-sdk/Mobile-SDK-Android-V5#127]
I'm having trouble with the H.264 encoded live video stream coming out of my Mini3 drone using MSDK 5.4.0. 

I've added a listener to the primary stream video channel using `addStreamDataListener`. The listener is correctly called and is providing H.264 encoded frames, which I'm able to decode using `libav`. However, the decoder takes up to a minute to display the first frame (which appears to be correctly decoded), and then the quality dramatically degrades after the initial frame. I believe the cause is due to the interval between I-frames in the video stream being exactly (or close to) 60 seconds, which seems to be much too large. Is there a way to reduce the interval between I-frames in the encoded stream data that is sent to the channel data listener?

Test stream data listener:

```kotlin
MediaDataCenter
    .getInstance()
    .videoStreamManager
    .getAvailableVideoChannel(VideoChannelType.PRIMARY_STREAM_CHANNEL)
    ?.let { channel ->
        channel.addStreamDataListener(StreamDataListener { frame ->
            if (frame.isIFrame)
                Log.i(TAG, "is i frame: ${frame.isIFrame}")
        })
    }
```

The log message above prints every I-frame, which is every 60 seconds

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86597'>Zendesk ticket #86597</a>:<br><br>I would like to ask if you have been using videoDecoder to display live video while using addStreamDataListener to get data. In fact, videoDecoder's work causes an increase in I-frames in the data output by addStreamDataListener.
<br><p><em><small>°°°</small></em></p>

**Comment by simonblee** [comment]
Thanks for the response. I'm not using a `VideoDecoder`, but I will try that and let you know if it fixes the problem.

**Comment by simonblee** [comment]
I've performed some tests and I did not see an increase in the rate of I-frame production when using a `VideoDecoder` to display the live stream in a `SurfaceView`. Do you have any sample code, in case I'm doing something incorrectly?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86597'>Zendesk ticket #86597</a>:<br><br>We do not have any sample code available for the mentioned request.

Regarding the VideoDecoder and the video channel associated with the addStreamDataListener, they should be the same for the functionality to take effect. Could you kindly provide me with details on how you have implemented this?
<br><p><em><small>°°°</small></em></p>

**Comment by simonblee** [comment]
Sure. Here's how I'm creating the decoder and then adding the stream data listener to the channel:

``` kotlin
MediaDataCenter.getInstance().videoStreamManager.getAvailableVideoChannel(
    VideoChannelType.PRIMARY_STREAM_CHANNEL
)?.let { channel ->
    mVideoDecoder = VideoDecoder(
        this,
        channel.videoChannelType,
        DecoderOutputMode.SURFACE_MODE,
        mVideoSurfaceView,
        -1,
        -1,
        true)

    channel.addStreamDataListener(StreamDataListener { frame ->
        if (frame.isIFrame)
            Log.i(TAG, "is i frame")
    })
}
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86597'>Zendesk ticket #86597</a>:<br><br>I have a few questions and requests for you regarding the mVideoSurfaceView.

Firstly, could you kindly confirm if the mVideoSurfaceView is a non-empty SurfaceView that can display content? If it is, then your logic seems to be perfectly fine!

Secondly, if you still believe that there is a decrease in video stream quality after a certain period of time, even when using the VideoDecoder, would it be possible for you to provide us with a video clip to help us confirm this issue? We have provided an upload address for your convenience：https://pan-sec.djicorp.com/s/8bP7wjzk2ACjJdk

Lastly, I would like to mention that the video stream decoded by the VideoDecoder should be consistent with the one obtained through the addStreamDataListener. Therefore, if there is a decrease in video stream quality, the displayed image through the VideoDecoder should exhibit similar behavior.

Thank you for your cooperation and assistance! We look forward to resolving this matter with you.
<br><p><em><small>°°°</small></em></p>
