### ISSUE TITLE
onProductDisconnect callback sometimes not received.

### ISSUE THREAD

**Issue by andrewdittmer** [dji-sdk/Mobile-SDK-Android-V5#128]
Using the sample app, put logs in all connect / disconnect events such as onProductConnect, onProductDisconnect etc...

Connect drone and run app. After you can see the drone name, disconnect the cable.

Expected result:
Always receive a disconnect event callback

Actual result:
Sometimes the disconnect event callback is received and sometimes not.

Tested on Google Pixel 4a and Pixel 4.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86633'>Zendesk ticket #86633</a>:<br><br>Under what circumstances will onProductDisconnect be triggered? You can find this information in the following article：How do I get and listen to the connection status of the drone and each component?

I would like to inquire if you did not receive the onProductDisconnect callback even when the remote controller and SDK were disconnected. Could you please confirm this?
<br><p><em><small>°°°</small></em></p>

**Comment by andrewdittmer** [comment]
Thanks for sending the [article](https://sdk-forum.dji.net/hc/en-us/articles/8864644851865-How-do-I-get-and-listen-to-the-connection-status-of-the-drone-and-each-component-) that tells me how to check in v5. I'll try it out. 

I did not receive the onProductDisconnect callback even when the remote controller was disconnected from the phone.

Thanks.

**Comment by andrewdittmer** [comment]
Also, using the following code, there doesn't appear to be any value update on the disconnect of flight controller. I always receive "true" and never "false". Even after disconnecting the controller from the phone. Is this expected? It's unclear from the [documentation ](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_FlightController_FlightControllerKey.html#key_flightcontroller_connection_inline) whether I should expect to receive false.

`FlightControllerKey.KeyConnection.create().listen(this) {
           Log.d(TAG, "FlightControllerConnected: $it")
       }`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86633'>Zendesk ticket #86633</a>:<br><br>I did not receive the onProductDisconnect callback even when the remote controller was disconnected from the phone.
-->
We would like to inform you that there is a known issue with MSDK. We are currently working on resolving this issue and it will be fixed in version 5.5.
<br><p><em><small>°°°</small></em></p>

**Comment by andrewdittmer** [comment]
Great. Thanks for the confirmation of the bug and the expected fix version.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86633'>Zendesk ticket #86633</a>:<br><br>I'm glad I could help you.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
Version 5.5 has been release.
