### ISSUE TITLE
MediaFile中有对文件进行校验的方法吗

### ISSUE THREAD

**Issue by chenglongsheng** [dji-sdk/Mobile-SDK-Android-V5#129]
相册中有对文件进行校验的需要，我试过使用isValid()，一直都是返回false

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/86657'>Zendesk ticket #86657</a>:<br><br>请问您提到的校验是要校验什么？
<br><p><em><small>°°°</small></em></p>

**Comment by chenglongsheng** [comment]
比如说，一个拍摄的文件通过文本编辑器修改了一些内容导致这个文件损坏。但是在sdk中还可以读取到，但是不能进操作。我想要预处理这个文件，但是没有找到相关可以校验文件的接口。
以及有一些视频文件的缩略图正常获取，但是无法获取预览图，且在成功和失败的回调都没有执行。

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/86657'>Zendesk ticket #86657</a>:<br><br>很抱歉，SDK没有提供这样的接口，您可以看看有没有其它第三方库能检测文件是否损坏。
<br><p><em><small>°°°</small></em></p>
