### ISSUE TITLE
Cannot get video with Mini2 (but I can in v4 SDK)

### ISSUE THREAD

**Issue by petered** [dji-sdk/Mobile-SDK-Android-V5#13]
As the title says, 

I have a Mini 2, I have built the `android-idk-v5-as` app, launched it on my Android phone, successfully registered, and connected to the drone.  I know I'm connected to the drone because when I click "Default Layout" I see the roll/pitch/yaw numbers changing when I move the drone around.  

But I cannot get any video stream - it just shows black background.  When I go `Testing Tools -> Live Stream -> Start Live Stream` it just give me an error: `Start Live Stream Failed: live stream param is invalid`.

I have the latest version of the code (as of today): 

```
commit 7febbd3bb915b2af87826339c41c9ae4d9194743 (HEAD -> dev-sdk-main, origin/dev-sdk-main, origin/HEAD)
Author: hoker.wu <hoker.wu@dji.com>
Date:   Wed Jun 8 15:07:39 2022 +0800
```

On the V4 SDK: https://github.com/dji-sdk/Mobile-SDK-Android I can successfully connect and view video from the Drone.

**Comment by Hoker-** [comment]
V5 SDK dont not support mini2 yet.

**Comment by petered** [comment]
Thank you @Hoker- , is it planned for the future?

**Comment by DJI-William** [comment]
There is no plan to support any old models in the future, please read this article, [Chapter 1 - Hello, MSDK V5!](https://sdk-forum.dji.net/hc/en-us/articles/5976502476441-Chapter-1-Hello-MSDK-V5-?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjg0OTA5OTg4NDA2MDEsInRpY2tldF9pZCI6Njc2ODIsImNoYW5uZWxfaWQiOjYzLCJ0eXBlIjoiU0VBUkNIIiwiZXhwIjoxNjYwNDU5NTM3fQ.yItOmEcdIHyGo1OYrG8dlgZKncPnAWZcbA7nAFrtgac)

**Comment by petered** [comment]
Thank you for your response.  The article says it will support the mavic 3
series around the end of August. Does the Mavic 3 Series include the Mini3
(Which seems to sometimes be called mavic mini 3)?

**Comment by DJI-William** [comment]
It does not include Mini 3 Pro, actually the SDK will focus on Enterprise level products in the future. The consumer level products such as Mini 3 Pro will have the lowest priority in terms of SDK support. I am sure it won't happen this year, maybe next year.
