### ISSUE TITLE
ConcurrentModificationException when finishing KZM Waypoint Mission

### ISSUE THREAD

**Issue by lucas-skyebrowse** [dji-sdk/Mobile-SDK-Android-V5#130]
Just after WaypointMissionExecuteState.FINISHED was observed, crash from SDK happended.

ConcurrentModificationException

Stacktrace:

java.util.ArrayList$Itr                  in next at line 860
com.dji.industry.mission.co_g     in co_a at line 59
com.dji.industry.mission.co_g.    in co_a at line 6
com.dji.industry.mission.co_g.    in access$lambda$5
com.dji.industry.mission.co_g$$Lambda$6 in invoke at line 5
dji.jni.callback.CallbackHelper in lambda$callWaypointV3MissionStateCallback$41 at line 1
dji.jni.callback.CallbackHelper$$Lambda$42 in run at line 8
android.os.Handler in handleCallback at line 883
android.os.Handler in dispatchMessage at line 100
android.os.Looper in loop at line 214
android.app.ActivityThread in main at line 7400
java.lang.reflect.Method in invoke com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 492
com.android.internal.os.ZygoteInit.  in main at line 935

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86762'>Zendesk ticket #86762</a>:<br><br>I would like to inquire about the probability of occurrence for the mentioned crash. Could you kindly provide us with information regarding the stability of this issue? Additionally, we would appreciate it if you could inform us about the device on which you are performing the flight missions.
<br><p><em><small>°°°</small></em></p>

**Comment by lucas-skyebrowse** [comment]
This happened at the end of the mission flight, and caused a crash. Happens sometimes. 
Using M3E V07.00.0102 + RC Pro Enterprise V02.00.0501 + MSDK V5.4

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86762'>Zendesk ticket #86762</a>:<br><br>Could you kindly provide us with the SDK logs located in the application path when the crash occurs? This would greatly assist us in analyzing the crash issue.

Here is the upload address：https://pan-sec.djicorp.com/s/MnbEBFYigZAWfLG   Here is the log storage path：Android/data/app name/files/LOG/CSDK.
<br><p><em><small>°°°</small></em></p>

**Comment by lucas-skyebrowse** [comment]
I've uploaded all there was, hopefully it will be of any help.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86762'>Zendesk ticket #86762</a>:<br><br>Thank you for uploading the large number of log files. However, we only need the logs that occurred during the crashes. Could you please provide us with the complete crash logs? This will help us determine the time of the crashes. Alternatively, can you tell us the exact time when the crash happened?
<br><p><em><small>°°°</small></em></p>
