### ISSUE TITLE
Crash when call MediaManager.pulllMediaFileListFromCamera  , M3T used ,  DJI  msdk v5.4.0

### ISSUE THREAD

**Issue by 72chen** [dji-sdk/Mobile-SDK-Android-V5#131]
Crash Log:

java.lang.ArrayIndexOutOfBoundsException
src.length=4 srcPos=0 dst.length=73 dstPos=73 length=4
1	java.lang.System.arraycopy(Native Method)
2	dji.sdk.keyvalue.value.ByteStreamHelper.integerToBytes(ByteStreamHelper.java:4)
3	dji.sdk.keyvalue.value.file.FileTaskRequest.toBytes(FileTaskRequest.java:7)
4	dji.sdk.keyvalue.value.file.FileTaskRequest.toBytes(FileTaskRequest.java:9)
5	dji.media.album.jni.JNIMediaTaskManager.fileTaskPushFront(JNIMediaTaskManager.java:1)
6	dji.media.album.co_e.co_b(MediaTaskManager.java:2)
7	dji.v5.manager.datacenter.media.MediaManager.co_p(MediaManager.java:18)
8	dji.v5.manager.datacenter.media.MediaManager.co_a(MediaManager.java:144)
9	dji.v5.manager.datacenter.media.MediaManager.access$lambda$9(Unknown Source:0)
10	dji.v5.manager.datacenter.media.MediaManager$$Lambda$10.onValueChange(Unknown Source:6)
11	dji.v5.common.utils.CallbackUtils.onValueChange(CallbackUtils.java:1)
12	dji.v5.manager.KeyManager.co_a(KeyManager.java:1)
13	dji.v5.manager.KeyManager.access$lambda$0(Unknown Source:0)
14	dji.v5.manager.KeyManager$$Lambda$1.co_a(Unknown Source:2)
15	dji.sdk.keyvalue.push.co_b.co_a(PushRecorder.java:60)
16	dji.sdk.keyvalue.push.co_b.co_a(PushRecorder.java:50)
17	dji.sdk.keyvalue.push.co_b.access$lambda$1(Unknown Source:0)
18	dji.sdk.keyvalue.push.co_b$$Lambda$2.run(Unknown Source:8)
19	android.os.Handler.handleCallback(Handler.java:883)
20	android.os.Handler.dispatchMessage(Handler.java:100)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86803'>Zendesk ticket #86803</a>:<br><br>Could you please confirm if this crash can be consistently reproduced? It seems that the crash type might be related to how you are using the product. Is it possible that you are passing parameters that are outside the specified range?
<br><p><em><small>°°°</small></em></p>

**Comment by 72chen** [comment]
I don't think so. The function used to work fine . Here is the Code :

mediaManager.pullMediaFileListFromCamera(
                PullMediaFileListParam.Builder().filter(MediaFileFilter.PHOTO).orderType(
                    FileListRequestTimeOrderType.NEW_FIRST
                ).mediaFileIndex(newPhotoInfo.mediaIndexInDJI)
                    .count(1).build(),
                object : CommonCallbacks.CompletionCallback {

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86803'>Zendesk ticket #86803</a>:<br><br>Could you provide us with the SDK logs when the crash occurred and the complete code（.java or .kt） you used for pulllMediaFileListFromCamera? I will submit this information to the engineer for further confirmation.
Here is the upload address: https://pan-sec.djicorp.com/s/W6GAZAcr3s6m7sH
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
I noticed that there has been no response for a long time, so I will go ahead and close this ticket for now. If you encounter this issue again, feel free to reopen it.
