### ISSUE TITLE
How to get bitmap from FPVWidget

### ISSUE THREAD

**Issue by alexmihalyk23** [dji-sdk/Mobile-SDK-Android-V5#133]
I create getBitmap inside FPVWidget. However, this did not help. I need to get a bitmap from an FPVWidget, is it possible to do that. There was an example camera application in the V4 documentation, but it doesn't work in V5, please help with this part of the code

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86982'>Zendesk ticket #86982</a>:<br><br>I apologize, but there is no interface in MSDK that can retrieve a bitmap. You may consider obtaining a bitmap through surfaceView or YUV data. Some methods can be found in the shared resources from other developers：https://stackoverflow.com/questions/4742868/android-creating-a-bitmap-with-surfaceview-content

We would like to inform you that getting bitmaps through surfaceView can be even more challenging. Therefore, we recommend using YUV data converted to bitmap as an alternative solution.
In addition, we would like to highlight that MSDK V5 supports multiple video decoders. You have the option to create a decoder specifically for processing YUV data.
<br><p><em><small>°°°</small></em></p>
