### ISSUE TITLE
Crash because of  libdjifs_jni-CSDK.so 

### ISSUE THREAD

**Issue by 72chen** [dji-sdk/Mobile-SDK-Android-V5#134]
# Thread-25511(4430)
SIGSEGV(SEGV_MAPERR)
解析原始

#00 pc 00000000000b9670 /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libdjifs_jni-CSDK.so (Str2JString+24)

#01 pc 00000000000c0b84 /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libdjifs_jni-CSDK.so (_Z31OnAircraftDatabaseVersionChangeRKNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE+116)

#02 pc 000000000053dab8 /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libDJIFlySafeCore-CSDK.so

#03 pc 00000000004e0fd8 /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libDJIFlySafeCore-CSDK.so

#04 pc 000000000041f570 /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libDJIFlySafeCore-CSDK.so (_ZNSt6__ndk113packaged_taskIFvvEEclEv+88)

#05 pc 00000000004973ec /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libDJIFlySafeCore-CSDK.so (_ZZN3dji7flysafe6WorkerC1ERKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEENKUlvE_clEv+520)

#06 pc 000000000049714c /data/app/com.airia.drone-bN7hpmI4eHg1z93PXZOqaA==/lib/arm64/libDJIFlySafeCore-CSDK.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3dji7flysafe6WorkerC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEUlvE_EEEEEPvSK_+44)

#07 pc 00000000000e68a0 /apex/com.android.runtime/lib64/bionic/libc.so

#08 pc 0000000000084b6c /apex/com.android.runtime/lib64/bionic/libc.so

**Comment by 72chen** [comment]
It happened twice

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87038'>Zendesk ticket #87038</a>:<br><br>I would like to kindly request some information from you. Could you please provide me with the version of MSDK that you are using? Additionally, it would be greatly appreciated if you could send us the complete crash log along with the corresponding SDK log.

Thank you in advance for your cooperation. Please find the upload address below.
https://pan-sec.djicorp.com/s/Zt4WLZSkL46oAZE
<br><p><em><small>°°°</small></em></p>

**Comment by 72chen** [comment]
MSDK5.4.0
M3T
The crash log was gathered by Bugly , and that was all.
I will upload the sdk log as soon as I can .

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87038'>Zendesk ticket #87038</a>:<br><br>We kindly request that you inform us after uploading the files. Please note that the uploaded logs should correspond to the time of the crash occurrence.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87038'>Zendesk ticket #87038</a>:<br><br>I hope this message finds you well. I would like to inquire if the issue you experienced is still persisting and causing any further inconvenience to you.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
I noticed that there has been no response for a long time, so I will go ahead and close this ticket for now. If you encounter this issue again, feel free to reopen it.
