### ISSUE TITLE
Mini 3 Pro Video Decoder Orientation issue

### ISSUE THREAD

**Issue by jwcharp** [dji-sdk/Mobile-SDK-Android-V5#137]
Hello,
When rotating the Mini 3 gimbal to take vertical videos (using KeyGimbalVerticalShotEnabled), we've noticed that the VideoDecoder linked to our SurfaceView does not automatically rotate as well. Below is a screenshot of the camera feed in the sample application after rotating the gimbal vertically:

![sample_app_orientation_issue](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7977270/4c4d7e14-f0bd-4ff9-b059-2fa4c329f037)

We've attempted to rotate the SurfaceView programmatically after rotating the gimbal, but the video feed does not rotate with it.
Is there any way to rotate the VideoDecoder to have the camera feed reflect the new orientation without having to interpret every frame and rotate them ourselves?

The DJI FLY app has the correct logic in place, for reference. Below is a screenshot of the camera feed correctly adjusted for the rotated gimbal:

![fly_app_orientation_issue](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7977270/f3cd4b73-52ce-4a04-bdf8-951cdf669bf5)

Thank you for your help in this manner
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87301'>Zendesk ticket #87301</a>:<br><br>This is indeed an area that can be optimized. I will provide feedback to our engineers and inform you if there is a solution available.
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
Hi!

Any update available here? can you provide any recommendations on how to handle this better? or what you do in the DJI Fly App? we are trying handle this better.

Thank you, any insight or guide you can show us or even links methods, would be greatly appreciated.

Thank you,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87301'>Zendesk ticket #87301</a>:<br><br>Currently, you can try selecting the surfaceView to display the camera image for vertical screen display. However, the SDK adaptation still needs to wait for the team to schedule.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87301'>Zendesk ticket #87301</a>:<br><br>Sorry for keeping you waiting.
The feature has been rejected by SDK team. We have conducted research on the usage scenarios of vertical screens and found that DJI Fly should be able to meet the needs in most daily life situations. Therefore, there are no plans to adapt the vertical screen mode for the MINI 3 series in the near future.

If you have any specific usage scenarios, please feel free to provide us with your feedback.
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
Thank for your response.

But that is the issue, The DJI Fly app handles the new gimbal ability to shoot vertical video properly. We want to recreate what the DJI Fly app is doing (showing a letter boxed video).
There does not seem to be an easy way to take the video stream which always comes in as horizontal and rotate it to be vertical. We have tried to manipulate the feed, however the phones and tablets are not strong enough to process the frame manipulation, and either causes lag in the feed or the app to crash.

How is the DJI Fly app doing it so effortlessly?

Thank you,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87301'>Zendesk ticket #87301</a>:<br><br>Can you tell us in what situations users need to use portrait mode?
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
The use case is seen above in the images. It is hard for the user to operate the drone when the camera is in portrait mode because the view is not properly oriented in the display.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87301'>Zendesk ticket #87301</a>:<br><br>I understand what you mean.
However, the SDK team has considered that the specific use case for vertical screen functionality is not for production purposes. For example, for personnel using mini 3 for inspections or other work, the vertical screen functionality may be rarely used. If vertical screen functionality is necessary in certain scenarios, could you please let us know?
<br><p><em><small>°°°</small></em></p>

**Comment by Himanshu6124** [comment]
I want to use the camera in verical mode to capture and record the moments for posting on social media, to capture video in best quailty it is required that we get the live stream  in vertical mode as well, as this will help is to achive the best quality shots otherwise its not suitable to look horizontally and record vertical video
