### ISSUE TITLE
The connection of MSDK V5.5.0 has a bad influence on Other MSDK APP and Pilot 2

### ISSUE THREAD

**Issue by 72chen** [dji-sdk/Mobile-SDK-Android-V5#138]
After running the up-to-date SDK demo app on M3T and  shutdown it when Aircraft connected for a while. The DJI Pilot2 could't work fine then , same as my app.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87381'>Zendesk ticket #87381</a>:<br><br>Could you provide us with a video for confirmation? It seems that we haven't encountered the same issue. Here is the upload address.：https://pan-sec.djicorp.com/s/BAAgAZfxqawjLkm
In addition, may I know what version of Pilot 2 you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by 72chen** [comment]
I have upload the video. The Pilot 2  app is up to date.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87381'>Zendesk ticket #87381</a>:<br><br>You can try entering Settings --> App and force stop MSDK V5. At this point, Pilot 2 should be able to function normally. From the video, it seems that the MSDK App has not been completely cleared.
<br><p><em><small>°°°</small></em></p>

**Comment by 72chen** [comment]
But MSDK 5.4.0 Demo works fine . I don't think forcing a stop is what users want. Can you do a more in-depth examination of MSDK 5.5.0 ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87381'>Zendesk ticket #87381</a>:<br><br>We are considering the possibility of implementing MSDK and Pilot 2 coexistence, so this issue may be completely resolved later.
<br><p><em><small>°°°</small></em></p>

**Comment by tukez** [comment]
@dji-dev, any news on the MSDK and Pilot 2 coexistence? Would this also apply for the DJI Fly app? This feature would greatly help on creating background integrations without needing to create your own flight app.

**Comment by dji-lyt** [comment]
We anticipate that the coexistence of Pilot 2 and MSDK on the remote controller will be implemented in version 5.6.

**Comment by tukez** [comment]
@dji-lyt What about the DJI Fly app? Will it also coexist?

**Comment by dji-lyt** [comment]
The coexistence of pilot and MSDK has been implemented in version 5.6.

**Comment by dji-lyt** [comment]
Hi @tukez  ,The DJI FLY was not specifically adapted in this version. I'm curious to know if you're still experiencing any interference issues after updating to version 5.6.

**Comment by tukez** [comment]
@dji-lyt Yes there is still interference with DJI Fly in 5.6.

**Comment by dji-lyt** [comment]
I think this should be considered as a new requirement. Could you please submit a new request for this? I will follow up on the conflict issues caused by DJI Fly.
