### ISSUE TITLE
No SD Card visible on simulator for M3E and SDK V5.5

### ISSUE THREAD

**Issue by lucas-skyebrowse** [dji-sdk/Mobile-SDK-Android-V5#139]
Mavic 3E V07.00.0102 
DJI Assistant 2 (Enterprise series) v 2.1.7 
DJI RC Pro Enterprise V02.00.0501

No sd card visible in the drone. No way to observe new files during tests on simulator.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87402'>Zendesk ticket #87402</a>:<br><br>What system are you using? DJI Assistant 2 is not a tool developed for SDK development. It seems to have this issue on Mac, but it cannot be resolved.
<br><p><em><small>°°°</small></em></p>

**Comment by lucas-skyebrowse** [comment]
Yes, this is on Macbook with M1 chip.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87402'>Zendesk ticket #87402</a>:<br><br>I'm sorry, but the SDK cannot solve the issue on your Macbook. If you would like to further confirm the situation of this problem, you can try contacting support@dji.com.
<br><p><em><small>°°°</small></em></p>
