### ISSUE TITLE
DJI FPV SDK

### ISSUE THREAD

**Issue by OKSHIJIAN** [dji-sdk/Mobile-SDK-Android-V5#14]
DJI FPV SDK. Please, I really need it

**Comment by Hoker-** [comment]
sorry, we have no plans to support this model yet.

**Comment by DJI-William** [comment]
There is no plan to support any old models in the future, please read this article, [Chapter 1 - Hello, MSDK V5!](https://sdk-forum.dji.net/hc/en-us/articles/5976502476441-Chapter-1-Hello-MSDK-V5-?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjg0OTA5OTg4NDA2MDEsInRpY2tldF9pZCI6Njc2ODIsImNoYW5uZWxfaWQiOjYzLCJ0eXBlIjoiU0VBUkNIIiwiZXhwIjoxNjYwNDU5NTM3fQ.yItOmEcdIHyGo1OYrG8dlgZKncPnAWZcbA7nAFrtgac)
