### ISSUE TITLE
Preview will stuck with DJI demo and V5.5 SDK

### ISSUE THREAD

**Issue by gangwang2020** [dji-sdk/Mobile-SDK-Android-V5#140]
Original report is here: https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/117

test phone model: huawei mate 20 and samsung S22
test drone: DJI mini 3

**Comment by gangwang2020** [comment]
test phone model is huawei mate 20 and samsung S22

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>I have received your video. Could we communicate on a single issue?
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
OK, do you want to talk on this ticket or #117 ? , I created this new ticket because #117 was closed.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>We can communicate on this ticket. I have already submitted the issue you reported to the engineers for analysis.
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
May I know when we can get the fix version?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>We will optimize the camera image issue to some extent in version 5.6.  The future versions of MSDK V5 will also be optimized in this aspect, as this issue is quite complex.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>I'm sorry for keeping you waiting for so long. The new video transmission interface has been released in version 5.8.0-a2, which enables stable display of images and adaptive rendering. You can try updating to this version and see if it works.
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
Where can I get the version 5.8.0-a2,  I only see the version v5.7.1 in https://developer.dji.com/doc/mobile-sdk-tutorial/en/

**Comment by gangwang2020** [comment]
OK，we will try it

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>Here you are：https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
We have tested the 5.8.0-a2 version, the stuck issue is gone.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87415'>Zendesk ticket #87415</a>:<br><br>I'm glad to hear this news. We also think that this version of the rendering will be much more useful.
<br><p><em><small>°°°</small></em></p>
