### ISSUE TITLE
DJI Air 3 Support? 

### ISSUE THREAD

**Issue by ntliem95** [dji-sdk/Mobile-SDK-Android-V5#141]

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/87737'>Zendesk ticket #87737</a>:<br><br>We regret to inform you that at this time, air3 does not have any plans to provide support for the SDK.
<br><p><em><small>°°°</small></em></p>

**Comment by BasementEngineer** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #87737](https://djisdksupport.zendesk.com/agent/tickets/87737):We regret to inform you that at this time, air3 does not have any plans to provide support for the SDK.
> 
> _°°°_

I would like to request that DJI strongly consider making this SDK. I know myself, and several others have not bought the Air 3 because it is difficult to map with otherwise. The Mini 3 Pro has an SDK, why not the Air 3?

Air 3 stands to distinguish itself as the ultimate budget mapping machine, but only with SDK support.

**Comment by dji-lyt** [comment]
Thank you for your suggestion. We have received it. Currently, the focus of our SDK team is on enterprise drones. The customer series drones may be supported in future versions, but not all of them.

**Comment by JuCoutinho0911** [comment]
Boa tarde.
Eu adquiri um Air 3 essa semana e nem tirei da caixa, já vou vender, pois como não tem previsão para liberação do SDK, não serve para o que eu preciso. Foi um erro ter comprado sem antes me certificar de todos os detalhes, mas jamais pensei que um drone com esse desempenho não seria possível realizar mapeamentos. Super frustrada!

**Comment by wyldwestaz** [comment]
Please add the Air 3 MSDK. If you’re adding the Mini 4 MSDK than the Air 3 should as well. Both are Consumer drones and even the Mini 3’s are as well. None of the Mini’s are Enterprise drones. I know a lot of Air 3 pilots have been requesting this on the DJI forum and are very disappointed. Please add MSDK support. Thank you.

**Comment by mind33** [comment]
I would like to urge you to reconsider your decision. It does not make sense that the mini 4 will get SDK support while the more expensive Air 3 won't get it.

**Comment by flavioperucchi** [comment]
MSDK support for the Air 3 would be great because of its tele camera.
