### ISSUE TITLE
Ability to control the beacon (Mavic 3T, DJI SDK v5.5.0)

### ISSUE THREAD

**Issue by Qubiz** [dji-sdk/Mobile-SDK-Android-V5#142]
Hello,

I am trying to find a way to turn on the beacon of the Mavic 3T. After some digging I found `BeaconKey.KeyIsBeaconOpened` and `BeaconKey.KeyFlashingFrequency`, however when trying to set them I get the error code `REQUEST_HANDLER_NOT_FOUND`. Are these functions not implemented in the SDK yet or am I doing something wrong?

Thanks in advance.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87879'>Zendesk ticket #87879</a>:<br><br>Do you have a question about turning on the auxiliary lights on the aircraft.? I recommend checking out this article for more information：How to enable the auxiliary light functions?（https://sdk-forum.dji.net/hc/en-us/articles/9876028900121-How-to-enable-the-auxiliary-light-functions-）
<br><p><em><small>°°°</small></em></p>

**Comment by Qubiz** [comment]
Thanks for your quick response. 

I am asking about how I can control this beacon light:
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/946270/716ab5a2-46ce-4670-9a75-58af2cfbe3bd)

Is it possible to control that through `FlightAssistantKey.KeyTopAuxiliaryLightMode`? If so, how should the key be created and what value should I write to it?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87879'>Zendesk ticket #87879</a>:<br><br>To control this light, you need to use KeyLEDsSettings. Here is the documentation for LEDsSettings: [LEDsSettings Documentation](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Value_FlightController_Struct_LEDsSettings.html?search=ledssettings&amp;i=0)

Below is an example code:

    var alm: LEDsSettings = LEDsSettings()alm.navigationLEDsOn = truealm.frontLEDsOn = falsealm.rearLEDsOn = falsealm.statusIndicatorLEDsOn = falseKeyManager.getInstance().setValue(KeyTools.createKey(FlightControllerKey.KeyLEDsSettings),alm,null)
<br><p><em><small>°°°</small></em></p>

**Comment by Qubiz** [comment]
Awesome, that did the trick. Thanks for the help!
