### ISSUE TITLE
FlyZoneLicenseInfo.isValid is always false

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#143]
Mobile SDK Version: `5.5.0`
Drone: Mavic 3 Enterprise

I am implementing Unlock Geo Zones into my app and am running into a strange issue when pulling Restricted Fly Zone Licenses from the drone. My license has a start timestamp of Jul 27, 2023 at 06:00:00 UTC and an end timestamp of July 29, 2023 at 05:59:00 UTC. I am able to enable/disable the license.

The problem is `FlyZoneLicenseInfo.isValid` always returns `false`. Per the docs:

> Gets whether the restricted fly zone licnese is valid. If the licnese has expired, please re-apply the license on the DJI official website.
> Return:boolean | Returns whether the restricted fly zone licnese is valid.

I verified in the Pilot app that the license is considered valid. However, when I check in the sample app, `isValid` is still false. I believe the Pilot app is performing a date check instead of looking at the `isValid` flag.

Pilot App:
<img width="673" alt="Screenshot 2023-07-27 at 2 11 54 PM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7491879/fe3ef978-cb99-45b7-8483-80be10f0b5e6">

Sample App:
<img width="911" alt="Screenshot 2023-07-27 at 2 12 34 PM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7491879/f3fdc578-b81d-4c90-87d7-47200fd55794">

Is this a bug or am I misunderstanding the documentation and need to perform a date check instead of using `isValid`?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87896'>Zendesk ticket #87896</a>:<br><br>If "isValid" is still false after enabling certificates, this should be considered an error. We will first validate this locally and if there is a solution that immediately restores normal operation, we will provide it to you.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87896'>Zendesk ticket #87896</a>:<br><br>I have provided your feedback to the engineer regarding your issue. He informed me that this value is directly transmitted by the aircraft, so it may vary on different aircraft. Are you able to take off normally after enabling the certificate?
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
Hello @dji-dev,

We are experiencing a similar or same issue, in our development process. We properly get approval in a authorize zone, while DJI Fly App properly see it our App does not, or does, but does not seem to get applied to the drone proplery.

Here is our code can you help determine where the error is?

This is the function that start the process to check if the drone can fly in the Auth Zone:
```
private fun logInAccountAndSyncZones(){
    updateDJILoginButton()
    UserAccountManager.getInstance().logInDJIUserAccount(this, false, object: CommonCallbacks.CompletionCallback{
        override fun onSuccess() {
            syncAuthZones()
        }

        override fun onFailure(error: IDJIError) {
            toast("Login to DJI failure")
        }
    })
}
```

Here is the syncAuthZones function:
```
private fun syncAuthZones(){
    FlyZoneManager.getInstance().downloadFlyZoneLicensesFromServer(object: CommonCallbacks.CompletionCallbackWithParam<List<FlyZoneLicenseInfo>>{
        override fun onSuccess(t: List<FlyZoneLicenseInfo>?) {
            toast("downloadFlyZoneLicensesFromServer success")
        }

        override fun onFailure(error: IDJIError) {
            toast("downloadFlyZoneLicensesFromServer failure")
        }
    })

    FlyZoneManager.getInstance().pullFlyZoneLicensesFromAircraft(object: CommonCallbacks.CompletionCallbackWithParam<List<FlyZoneLicenseInfo>>{
        override fun onSuccess(t: List<FlyZoneLicenseInfo>?) {
            toast("pullFlyZoneLicensesFromAircraft success")
        }

        override fun onFailure(error: IDJIError) {
            toast("pullFlyZoneLicensesFromAircraft failure")
        }
    })

    FlyZoneManager.getInstance().pushFlyZoneLicensesToAircraft(object: CommonCallbacks.CompletionCallback{
        override fun onSuccess() {
            toast("pushFlyZoneLicensesToAircraft success")
        }

        override fun onFailure(error: IDJIError) {
            toast("pushFlyZoneLicensesToAircraft failure")
        }
    })
}
```

We seem to get into all the success message but still can't fly from our App, and drone still blinks red. There is a point while these functions are running, the light stays red longer than the standard pulsing. Whereas when that happens in the DJI Fly app after the longer red hold, it goes to green.

Again, any insight you can provide is always greatly appreciated!

Thank you,
Joe

**Comment by tkocik92** [comment]
@jwcharp Gotta ask: are you enabling the license after it is pushed to the drone?

**Comment by jwcharp** [comment]
> @jwcharp Gotta ask: are you enabling the license after it is pushed to the drone?

Hmm... I've tried to duplicate my logic from what worked with the v4SDK so perhaps I am missing a call.
What call would then enable the license after it is pushed to the drone?

Thanks for your assistance!
Joe

**Comment by tkocik92** [comment]
@jwcharp From what I've seen, v5 license handling got an overhaul compared to v4. The method you want `FlyZoneManager.getInstance().setFlyZoneLicensesEnabled`. Keep in mind that (based on what I've seen) you can only have one license enabled at a time. The SDK will automatically disable all other licenses when you enable the next one. See [doc](https://developer.dji.com/api-reference-v5/android-api/Components/IFlyZoneManager/IFlyZoneManager.html#iflyzonemanager_setflyzonelicensesenabled_inline)

**Comment by jwcharp** [comment]
@tkocik92 Thank you!

I will implement this to see if all is good, appreciate the quick help.

**Comment by tkocik92** [comment]
@dji-dev Sorry for the late follow up. I have confirmed that the drone can still take off with the appropriate licenses enabled.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87896'>Zendesk ticket #87896</a>:<br><br>Thank you for your feedback. Regarding the FlyZone certificate, FlyZoneLicenseInfo.isValid should be a value that can be ignored. You can determine the validity of the certificate by using FlyZoneLicenseInfo.isEnable and the certificate's expiration date.
<br><p><em><small>°°°</small></em></p>

**Comment by jwcharp** [comment]
@dji-dev and @tkocik92 

upgrade our app from 5.5 to 5.4 and it looks like something broke with getting the FlyZones

this call is giving a "DISCONNECTED" response:

`FlyZoneManager.getInstance().pushFlyZoneLicensesToAircraft(object: CommonCallbacks.CompletionCallback{`

this call below yields "Login to DJI failure"

```
UserAccountManager.getInstance().logInDJIUserAccount(this, false, object: CommonCallbacks.CompletionCallback{
    override fun onSuccess() {
        syncAuthZones()
    }

    override fun onFailure(error: IDJIError) {
        toast("Login to DJI failure")
    }
})
```

Do you have any quick tips on what changed from 5.4 to 5.5 in this regard to FlyZoneManager and UserAccountManager? The Log into DJI prompt came up fine Logged in fine, then after that the fly zone fails to sync and on app re-open, I don't need to login again but get the "Login to DJI failure" message.

Thanks,
Joe

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/87896'>Zendesk ticket #87896</a>:<br><br>When you call pushFlyZoneLicensesToAircraft, is the device connected to the aircraft? It needs to be connected to the aircraft in order to use it.
As for logInDJIUserAccount, it will prompt an error if the account is already logged in. Calling logInDJIUserAccount again will trigger onFailure.。
<br><p><em><small>°°°</small></em></p>
