### ISSUE TITLE
No variants found for ':sample-app-aircraft'. Check build files to ensure at least one variant exists. at:

### ISSUE THREAD

**Issue by TaylorsZ** [dji-sdk/Mobile-SDK-Android-V5#144]
运行demo，Android studio报错No variants found for ':sample-app-aircraft'. Check build files to ensure at least one variant exists. at:
jdk版本换了以下几个试过都不行，请问该怎样解决？
<img width="843" alt="image" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/20639094/40bd7fd6-a6c8-48c4-8830-d15db86b7837">

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88203'>Zendesk ticket #88203</a>:<br><br>目前MSDK V5还没有测试过JDK 11以上的版本，建议您使用JDK 11或者以下的版本
另外，您可以先确认一下是否与这篇文章导入MSDK V5的sample的导入方法相同：第二章：官方Sample（https://sdk-forum.dji.net/hc/zh-cn/articles/5983558993433）
<br><p><em><small>°°°</small></em></p>
