### ISSUE TITLE
FPVWidget 展示画面变形，直播画面宽高不跟着视频变化

### ISSUE THREAD

**Issue by shuaisong** [dji-sdk/Mobile-SDK-Android-V5#145]

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88388'>Zendesk ticket #88388</a>:<br><br>videoDecoder是不会跟随surfaceView的变化更改渲染画面的大小的。至于展示画面拉伸的问题已经在计划优化，但优化问题相较于需求和bug的优先级会更低。
<br><p><em><small>°°°</small></em></p>

**Comment by shuaisong** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/27810283/af783cb2-63c4-49db-8e65-0bc7922e22c6)
链接不存在

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88388'>Zendesk ticket #88388</a>:<br><br>这个链接需要一定权限才可以打开，它是与问题无关的。
<br><p><em><small>°°°</small></em></p>
