### ISSUE TITLE
Can I create a project with MSDK V4 and MSDK V5 ?

### ISSUE THREAD

**Issue by ntliem95** [dji-sdk/Mobile-SDK-Android-V5#146]
Can I create a project with MSDK V4 and MSDK V5 ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/88485'>Zendesk ticket #88485</a>:<br><br>No. It is impossible to do that. You can only use MSDK V4 and V5 to develop one APP respectively.
<br><p><em><small>°°°</small></em></p>
