### ISSUE TITLE
"toPointAndPassWithContinuityCurvature" response different in the M3E and M350

### ISSUE THREAD

**Issue by dylandrones** [dji-sdk/Mobile-SDK-Android-V5#147]
Hello, 

When uploading a waypoint kml file to the M350 and the M3E, each waypoint's `waypointTurnMode` is set to `toPointAndPassWithContinuityCurvature`, and `useStraightLine` is set to `1`. `waypointTurnDampingDist` is also set.

The M350 then flies with wide arcs, while the M3E flies straight to each point. 

Is this different response expected? I would expect both drones to have the same response to the wayline/template kml file. 

I am trying to recreate what was stated in the cloud api reference for wpml file creation:

> Note: The setting method of "Turns before waypoint. Flies through." mode in DJI Pilot2/FlightHub 2 is 
> 1）Set the "wpml:waypointTurnMode" to "toPointAndPassWithContinuityCurvature".
> 2）Set the "wpml:useStraightLine" to 1.

Environment:
DJISDK v5.5.0

M350 firmware: 07.00.0002
RC Plus firmware: 01.02.0445

M3E firmware: 07.00.0102
RC Pro firmware: 02.00.0501

Thanks,
Dylan Shackelford

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88605'>Zendesk ticket #88605</a>:<br><br>First of all, we can confirm that both the M350 and M3E have the capability for curved flight. I would like to know if the performance of the curved flight file generated on Pilot 2 is different on both aircraft as well?
We treat the file generated by Pilot 2 as the standard file, and it is correct, so we use the file generated by it to eliminate the influence of the file.

Thank you!
<br><p><em><small>°°°</small></em></p>

**Comment by dylandrones** [comment]
Is there a _"Turns before waypoint. Flies through"_ option for waypoint flight with the M350RTK/M300 in DJISDK 5.5.0?

In DJI Pilot 2 on the M3E with the RC Pro, when creating a waypoint flight, there is an option for "Turns before waypoint. Flies Through". 

I don't see this option in DJI Pilot 2 for the M350 on the RC Plus, nor on the M300 RC. See the attached photos below: (M350 in DJI Pilot 2 only has 4 options, where M3E has a fifth option).

![M350](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/88062342/feb31a61-32c2-4faf-b4d8-81eec5a97658)
![M3E](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/88062342/e5e700a4-f2a8-4736-bb60-6edc452e4ac3)

M3E / RC Pro DJI Pilot 2 Version : 7.0.2.2

M350RTK / RC Plus DJI Pilot 2 Version : 7.0.3.9

M300 / RC DJI Pilot 2 Version : 7.0.2.5

Thanks,
Dylan Shackelford

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88605'>Zendesk ticket #88605</a>:<br><br>Sorry, there may be an issue with the photo you uploaded and we are unable to view it. However, I have switched to the Pilot 2 model and found that the M350 and M3E have the same options for waypoint types.

Could you please let me know if the "Turns before waypoint. Flies through" route you built on M3E can be executed on M350? If there are no waypoint actions involved, the route generated by the M3E controller can also be executed on M350.
<br><p><em><small>°°°</small></em></p>

**Comment by dylandrones** [comment]
Hello,

The M3E has the option "Turns before waypoint. Flies through"
![M3E_](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/88062342/13390a05-9b93-4fe6-abdc-39f3333d7bcb)

The M350 (and my M300) does not have that option.
![M350_](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/88062342/7642e652-39a2-4152-bd20-05c9b31e3285)

The "Turn before waypoint. Flies through" waypoint mission created on M3E is flown _incorrectly_ on the M350 - it flies as if it is in "Curved Route, Aircraft Continues" , seemingly disregarding the `useStraightLine` value. 

If I can't fly "turn before waypoint. Flies through" in DJI Pilot 2, on the M350, then I can't create it with the MSDK v5.5.0. 

Any information on how to proceed would be greatly appreciated. 

Thanks,
Dylan

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88605'>Zendesk ticket #88605</a>:<br><br>Sorry for keeping you waiting for so long.
I have confirmed with my colleagues from M350 that there is indeed no "Turns before waypoint. Flies through" function on the M350. The M350 only supports the "toPointAndPassWithContinuityCurvature" mode, and the curvature of the curve is controlled using wpml:waypointTurnDampingDist.
<br><p><em><small>°°°</small></em></p>
