### ISSUE TITLE
RC Pro Shutter Button Disabled

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#149]
Drone: Mavic 3 Enterprise
SDK Version: `5.5`
RC Firmware: `02.00.0501`
Drone Firmware: `07.00.0102`

Added versions for clarity but the issue has existed prior to all versions.

I am unsure if this is a bug or an intended function. When I run the Pilot app or the Sample app and use the RC Pro's shutter button, a photo is captured. In my own app, the app can reach a state where pressing the shutter button does nothing. This does not always happen. I do not know how it enters this state or how to leave it.

I can confirm that using `CameraKey.KeyStartShootPhoto` to take a photo works. I have verified the Camera Mode and Shoot Photo Mode are both set to `NORMAL`. 

I have noticed in the Sample app that there is code written around `RemoteControllerKey.KeyShutterButtonDown` inside one of the widgets to take a photo. Is this required in my own app implementation? I assumed this was default behavior and should not be necessary.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88836'>Zendesk ticket #88836</a>:<br><br>You need to listen to RemoteControllerKey.KeyShutterButtonDown to get the status of the shutter button, and then call CameraKey.KeyStartShootPhoto to take a photo. If pressing the shutter button directly on the remote controller does not trigger the photo-taking action, it means that the remote controller itself is not bound to the photo-taking action.
<br><p><em><small>°°°</small></em></p>
