### ISSUE TITLE
MapWidget无法使用

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android-V5#15]

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/67155'>Zendesk ticket #67155</a>:<br><br>sample中的Mapwidget被注释掉，应该是还存在问题。如果想要体验地图功能可以先参考航线部分，也就是WayPointV3Fragment。
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
后续MapWidget会更新，更新后就会取消注释，预计8月底支持。

**Comment by DJI-William** [comment]
@Swordce MapKit和MapWidget已经开发好，开源并且合并到Github了。
