### ISSUE TITLE
When loading heavy GPU rendering, it will cause the app to crash.

### ISSUE THREAD

**Issue by jimmyleeking** [dji-sdk/Mobile-SDK-Android-V5#150]
>2023-08-18 16:23:30.011 22703-22813 DJIV5/RXUtil            com.test.sample            E  (co_a:27) io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.rxjava3.exceptions.MissingBackpressureException: Can't deliver value due to lack of requests 

My activity has a heavy GPU render task. When I start the GPU render, I receive a DJI error message that indicates it will crash my app. Please fix it.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89366'>Zendesk ticket #89366</a>:<br><br>Could you please let us know the version of MSDK you are using? Additionally, would it be possible for you to provide us with a complete log?
<br><p><em><small>°°°</small></em></p>
