### ISSUE TITLE
Unable to turn on or turn off the motors

### ISSUE THREAD

**Issue by cmillauriaux** [dji-sdk/Mobile-SDK-Android-V5#151]
Environment
Drone: DJI Matrice M300 RTK
Controller: DJI Smart Controller
DJI Pilot 2 app version: 7.0.2.5
Mobile SDK version: 5.5.0
Aircraft Firmware version: 07.00.0100
RC Firmware version: 07.00.0101

Repro steps :
- I'm trying to turn on motors and turn off motors. I just found "KeyTurnOnTheMotor" key to do it :
```java
return DJISDKModel.getInstance().performActionWithOutResult(KeyTools.createKey(FlightControllerKey.KeyTurnOnTheMotor));
```
But when I try to execute the action, I have an exception :
```
java.lang.RuntimeException: RxError{djiError=ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'}}
io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1462)
```
Everything is fine when I try to takeOff :
```java
return DJISDKModel.getInstance().performActionWithOutResult(KeyTools.createKey(FlightControllerKey.KeyStartTakeoff));
```

I really need to turn on/off motors because we use several M300 and we need to be sure the "drone 1" is the "drone 1" before landing. To make sure the drone n°1 is the drone n°1, we turn on the motors.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89385'>Zendesk ticket #89385</a>:<br><br>For safety reasons, the option to open and close the motor has been removed in MSDK V5. However, you can still control the motor by using the takeoff and landing interfaces. If you need to differentiate between aircraft using commands, I suggest trying the lights：KeyLEDsSettings
<br><p><em><small>°°°</small></em></p>
