### ISSUE TITLE
Get Fly Zones sometimes hangs indefinitely

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#152]
Drone: Mavic 3 Enterprise
SDK: `5.5`

I have implemented the display of Geo Zones into my app. This is accomplished by displaying data returned by `FlyZoneManager.getInstance().getFlyZonesInSurroundingArea`. Generally, this works great.

On occasion, however, the callback supplied to the above method is never fired (as in, log statements in both methods are never shown in logcat). This most consistently happens on a fresh install of the app WITH location permissions disabled. The QA team working on my app finds it through other flows as well, but never with consistent, reproducible steps.

An additional item to note: if the user EVER signs in to their DJI account, they NEVER have issues fetching fly zones. This is true even if they manually sign out of their DJI account.

A workaround that I put in place for fresh install issue mentioned above is to call `FlyZoneManager.getInstance().init()` after the user has accepted location permissions. I'm not sure this is a solution as the problem still randomly occurs.

Is there something that can cause `getFlyZonesInSurroundingArea` to never fire its callbacks? Or are there certain permissions that must be obtained before the `FlyZoneManager` can be used?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89826'>Zendesk ticket #89826</a>:<br><br>This is strange. It should push a result to you no matter when you call it. Do you not have a stable reproduction method? Can you describe the process and environment before calling getFlyZonesInSurroundingArea on your end? Are you connected to the internet? Are you connected to the aircraft?

getFlyZonesInSurroundingArea cannot be obtained when not connected to the aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Controller: RC Pro Enterprise
Controller Firmware (if it matters): `02.00.0501`
Android Version: 10

I am connected to the internet, but I'm not sure if that matters since I can fetch Fly Zones later on even if I'm not connected.

Drone connection status does not matter. I see this issue regardless of connection when performing reproduction steps.

The flow is something like this:

1. Turn on the controller. Verify that DJI Pilot has NOT launched (might be important for reproduction)
2. App install (not update)
3. Initialize the Mobile SDK (happens in the launching `Activity.onCreate`)
4. Request location services (this is the only permission that gets requested in our app on the RC Pro Enterprise that we use)
5. Sign-In to proprietary account (has no relation to DJI and requires internet)
6. Navigate to a screen that requests Fly Zones for a specific site (basically the lat/long that we pass into `getFlyZonesInSurroundingArea`). See that fly zones are not returning and no error is thrown.

That's all I do. If I sign-in to a DJI account between steps 5 and 6, I don't see this issue. If I kill the app when it hangs on step 6 and re-launch, the issue is gone.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89826'>Zendesk ticket #89826</a>:<br><br>I have successfully reproduced the issue following your method. This problem only occurs during the initial installation and will not appear again when reopened.

I have reported the issue to our development team for analysis. Please bear with us for a while. We will provide you with the results as soon as possible.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/89826'>Zendesk ticket #89826</a>:<br><br>I have followed the instructions you provided on version 5.8 and the issue did not occur again. You can use the sample code from version 5.8 to test and confirm if the problem has been fixed.
<br><p><em><small>°°°</small></em></p>
