### ISSUE TITLE
SDKManager.getInstance().isRegistered() gives java.lang.IllegalStateException: SDKManager is not initialized

### ISSUE THREAD

**Issue by Rick-v-E** [dji-sdk/Mobile-SDK-Android-V5#153]
In SDK 5.4, I was able to register the app using:

```java
if (!SDKManager.getInstance().isRegistered()) {
    SDKManager.getInstance().init(this, registerCallback);
}
```

with `registerCallback` being a `SDKManagerCallback()`.

However, I noticed that since the upgrade to SDK 5.5, this results in `java.lang.IllegalStateException: SDKManager is not initialized`.

Running it without the check if the `SDKManager` is initialized works, however, I don't see why `SDKManager.getInstance().isRegistered()` should throw an error.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/90352'>Zendesk ticket #90352</a>:<br><br>From version 5.5 onwards, you need to call SDKManager.getInstance().init before you can use the interfaces of SDKManager. The reason for this adjustment in version 5.5 is that we found some cases where the SDK was not functioning properly in version 5.4. Therefore, we have made changes to the logic of SDKManager in this part.
<br><p><em><small>°°°</small></em></p>
