### ISSUE TITLE
 If the MSDK sample app is registered as 'Auto start application selection', Megaphone does not work.

### ISSUE THREAD

**Issue by chano1025** [dji-sdk/Mobile-SDK-Android-V5#155]
If I register the DJI Pilot 2 as a startup app, the DJI Pliot 2 will automatically launch when I turn on the remote controller. 
And I close the DJI Pilot 2 and run the MSDK app, the megaphone will work.

However, when I register the MSDK app as a startup app, Megaphone does not work. 
And I close the MSDK app and run it again, it works.

The megaphone is successfully mounted.

Aircraft : DJI mavic 3T
Aircraft Version : 07.01.1003
Remote Controller Version : 02.01.0003
MSDK App Version : 5.5.0, 1065

![Screenshot_20230907_165506](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/36180870/6a489a7f-afe7-46bd-8b76-7d434bccc1ac)

![Screenshot_20230907_163318](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/36180870/c71ee16c-335a-4e3e-96dd-9f91bb1af707)

Thank you.

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/50ad5ab9-bbe8-4e4d-bad6-98a2fa81ac6e)
The position on the image is used to set the location of the megaphone. You can set the location of the megaphone once before using it, and the interface is setMegaphoneIndex.

**Comment by chano1025** [comment]
Thanks for your help.
Is there any other way other than setting the megaphone position manually? 
Is there an API to get the location where the megaphone is mounted?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/90571'>Zendesk ticket #90571</a>:<br><br>Currently, the megaphone does not have such an interface. However, it is relatively easy to confirm the installation position for aircraft with only one expansion port. For aircraft with multiple expansion interfaces, such as the M300, they do not have a megaphone produced by DJI. Therefore, you can use the PayloadBasicInfoListener to obtain payload information to determine if it is a megaphone .
<br><p><em><small>°°°</small></em></p>
