### ISSUE TITLE
Cannot get serial number of Zenmuse P1

### ISSUE THREAD

**Issue by GregCornis** [dji-sdk/Mobile-SDK-Android-V5#158]
With the SDK v5, there is no documented way to get the serial number of the camera (that I could find). On the M3E, wa can use the (undocumented) `CameraKey.KeySerialNumber`, but it throws an error with "No hander" for the M350 + Zenmuse P1.

I have also tried using the `PayloadManager`, which does give a `PayloadBasicInfo`, but the serial number is wrong.
```kotlin
Received info : PayloadBasicInfo{
  payloadType=X_PORT, 
  isConnected=true, 
  uploadBandwidth=5000, 
  payloadProductName='Zenmuse P1', 
  payloadProductPhaseType=PHASE_DEVELOPMENT, 
  isFeatureOpened=true, 
  firmwareVersion='99.00.00.06', 
  firmwareVersion='99.00.00.06'}
Serial number : 4TSDK8Q001P18Z
```

What is the correct way to know the serial number of the camera attached to the M350 gimbal ?  
Thanks

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/90779'>Zendesk ticket #90779</a>:<br><br>I hope this message finds you well. I would like to inform you that the P1 has been developed using our X-PORT gimbal as its foundation. The Serial Number (SN) obtained through the MSDK (Mobile SDK) is actually the SN of the X-PORT gimbal itself. Unfortunately, at present, the MSDK does not have the capability to retrieve the SN of the entire machine. However, you can utilize a table to correlate the SN of the X-PORT gimbal with the SN of the entire machine.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Hi, thanks for your answer. So does it mean that if I use a different camera (say H20), the X-PORT serial number will be the same ?

> You can utilize a table to correlate the SN of the X-PORT gimbal with the SN of the entire machine.

That sounds like a good idea, is there a way to know the SN of the P1 from the XPORT one ? Actually I was wondering how the serial numbers are generated. I'm guessing the "MDK" stands for the Mobile SDK, and "SDK" for the payload SDK ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/90779'>Zendesk ticket #90779</a>:<br><br>I hope this message finds you well. I wanted to bring to your attention that I have come across a key with the serial number "serialNumber" in the cameraKey. It appears that this key has not been released yet. I kindly request you to verify if this key can successfully obtain the correct serial number. Unfortunately, I was unable to conduct a complete test as I did not have P1 available. However, I did test it on H20 and it proved to be functional.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
As mentioned in my previous comment, this key doesn't work with the P1. It throws an error with "No handler found"

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/90779'>Zendesk ticket #90779</a>:<br><br>I apologize for any inconvenience caused. I would like to inform you that currently, the serial number (SN) of the P1 can only be obtained through the PayloadBasicInfo. It is important to note that the X-PORT is the gimbal of the P1, and its serial number is distinct from that of the H20.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
I'm sorry but it's still unclear to me : is there a way to get the camera serial number of the P1 through the MSDK ? I mean the serial number written in the EXIF of the pictures, like `3XMDK8P001N256`.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/90779'>Zendesk ticket #90779</a>:<br><br>I regret to inform you that the current version of MSDK does not have the capability to retrieve this serial number.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Ok, thanks for the clear answer
