### ISSUE TITLE
Unresolved reference: Theme_AppCompat_Dialog

### ISSUE THREAD

**Issue by dronematt** [dji-sdk/Mobile-SDK-Android-V5#159]
MyApplication/android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/core/extension/ViewExtensions.kt: (180, 42): Unresolved reference: Theme_AppCompat_Dialog

Followed the guide and this is the end result.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/90786'>Zendesk ticket #90786</a>:<br><br>I wanted to provide you with a solution to the error you encountered. You can modify the error location to androidx.appcompat.R.style.Base_AlertDialog_AppCompat. The reason for the error is a conflict between the R files. By emphasizing the ownership of the R files, you should no longer encounter the "not found" issue.
<br><p><em><small>°°°</small></em></p>
