### ISSUE TITLE
SDK build failed“Unable to make field private final java.lang.String”

### ISSUE THREAD

**Issue by TianmingLi** [dji-sdk/Mobile-SDK-Android-V5#160]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/5005440/330c5a52-a1a1-4912-af4b-a082b251cf61)

```
Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @39830260

```

what's the verison of jdk and gradle should i use?

**Comment by TianmingLi** [comment]
``` 
.\java.exe --version
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7-67)
OpenJDK 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
```


```
KOTLIN_VERSION = 1.6.20
```

BUILD SUCCESSFUL in 15s

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91204'>Zendesk ticket #91204</a>:<br><br>Your problem has already been solved by yourself. This error seems to occur frequently when there is a conflict between the Gradle version and the JDK version. Adjusting one of these versions may allow for a successful compilation.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
> ```
> .\java.exe --version
> openjdk 16.0.2 2021-07-20
> OpenJDK Runtime Environment (build 16.0.2+7-67)
> OpenJDK 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
> ```
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
> ```
> 
> ```
> KOTLIN_VERSION = 1.6.20
> ```
> 
> BUILD SUCCESSFUL in 15s

Excuse me would you please explain how did you solve it ?

I face with the same error but how can I change them to solve the problem ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91204'>Zendesk ticket #91204</a>:<br><br>Could you please let me know which versions of JDK and Gradle you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
> Agent comment from yating.liao in [Zendesk ticket #91204](https://djisdksupport.zendesk.com/agent/tickets/91204):Could you please let me know which versions of JDK and Gradle you are using?
> 
> _°°°_

Hi Zendesk thank you for your replay. 

I found the problem. my JDK version was 17 and I change it to 1.8 from Project Structure -> SDK Location -> Gradle Setting and I run the app successfully.

**Comment by PeimanAtaei** [comment]
Thank you so much Zendesk for your replay

I solve the problem. My JDK was 17 and I changed it to 1.8 and now it is soved

**Comment by iakshatgandhi** [comment]
i want to work on it

**Comment by dji-lyt** [comment]
@iakshatgandhi  Do you still face this problem? You can try tweaking your JDK version or gradle version. It is often caused because of them.
