### ISSUE TITLE
Dji Mini 2 SE support

### ISSUE THREAD

**Issue by Suxsem** [dji-sdk/Mobile-SDK-Android-V5#162]
Any plan to support dji mini 2 SE?
it's almost identical to the supported mini 2, should be easy to add.
Thank you

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91578'>Zendesk ticket #91578</a>:<br><br>I apologize for any inconvenience caused, but currently, there are no plans to support the SDK for the mini 2SE.
<br><p><em><small>°°°</small></em></p>

**Comment by Suxsem** [comment]
this is really unfortunate. Hope they change plans in the future.

**Comment by dji-lyt** [comment]
If we add the mini 2 se to our supported plan in the future, we will make an announcement. Thank you for your attention and understanding.
