### ISSUE TITLE
为什么在上传航线时 onSuccess 和 onFailure 回调方法都会被调用？

### ISSUE THREAD

**Issue by Merpyzf** [dji-sdk/Mobile-SDK-Android-V5#163]
连接大疆模拟器进行的测试
- MSDK：V5.5.0
- 无人机型号：M350_RTK

```
      waypointMissionManager.pushKMZFileToAircraft(
            wayPointFile.path, object : CommonCallbacks.CompletionCallbackWithProgress<Double> {
                override fun onProgressUpdate(progress: Double?) {
                    Log.i(TAG, "onProgressUpdate=> ${progress}")
                }

                override fun onSuccess() {
                    Log.i(TAG, "onSuccess")
                }

                override fun onFailure(error: IDJIError) {
                    Log.i(TAG, "onFailure, $error")
                }
            }
        )
```
我通过上述代码执行了一个航线上传的任务。当航线上传进度为 100 ，航线的状态会从 UPLOADING 转为 READY，接着会去回调 onSuccess()。到这里一切都符合预期，但之后又会去调用一次 onFailure()。这让我感到很困惑，“成功” 与 “失败” 难道不是竞态的吗？

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91801'>Zendesk ticket #91801</a>:<br><br>5.5版本有个bug，pushKMZFileToAircraft会回调多次，这个bug 5.6修复了，建议您升级看看。
<br><p><em><small>°°°</small></em></p>

**Comment by Merpyzf** [comment]
谢谢，升级到 v5.6.0 后问题已解决。
