### ISSUE TITLE
DJI Mini 4 SDK support

### ISSUE THREAD

**Issue by godfreynolan** [dji-sdk/Mobile-SDK-Android-V5#164]
Do you have an ETA on when the DJI Mini 4 will be supported by the SDK v5?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91825'>Zendesk ticket #91825</a>:<br><br>I hope this message finds you well. I would like to inform you that, at present, the mini 4 does not have support for the SDK. However, I am pleased to inform you that support for the SDK will be available in the future. We anticipate that this support will be implemented in the first half of next year. We kindly request your patience and understanding in the meantime.
<br><p><em><small>°°°</small></em></p>

**Comment by probonopd** [comment]
Please also allow apps to run on the DJI RC2, otherwise the SDK is not useful. Thanks!

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91825'>Zendesk ticket #91825</a>:<br><br>We regret to inform you that RC2 is unable to install third-party applications as a result of hardware limitations.
<br><p><em><small>°°°</small></em></p>

**Comment by shaji-Dev** [comment]
Hi, is the Mini 4 Pro now supported?

**Comment by pietertolsma** [comment]
Hi, I am wondering the same.

**Comment by lamont-granquist** [comment]
Yeah I'm thinking of buying a Mini 4 Pro and wondering about the same and when Litchi and Dronelink will support it.

**Comment by probonopd** [comment]
...on the RC2 that comes with the Mini 4 Pro.

**Comment by elderdrake** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #91825](https://djisdksupport.zendesk.com/agent/tickets/91825):We regret to inform you that RC2 is unable to install third-party applications as a result of hardware limitations.
> 
> _°°°_

To clarify, this means that when the SDK is released, it will not be compatible with an RC2 controller? If so, that is disheartening, to say the least.

**Comment by marceloraceteam** [comment]
Do you already know a date for the release of the SDK?

**Comment by dodger-999** [comment]
So when is the SDK for the Mini Pro 4 being published? Earlier post from DJI said “expect it in the first half of 2024” - RC2 controller support or not, we need that SDK.

**Comment by sawyermade** [comment]
Still not available, this is pretty crazy how long this is taking. Looks like all our new drones will be old mini 3 drones?

**Comment by probonopd** [comment]
Indeed this is quite disappointing. It's been a year now...

**Comment by sawyermade** [comment]
I think it’s actually a little over a year now but yeah, not sure what’s taking so long. Kind of crazy imo.

**Comment by FelipeCornejo** [comment]
Hi, are there any news of the mini 4 pro support for msdk v5?

**Comment by joaquinperaza** [comment]
@dji-dev what is your definition of first half of the year?

**Comment by 02nowicki** [comment]
@dji-dev Where can I expect SDK for Mini 4 Pro?

**Comment by P-Mindz** [comment]
@dji-dev 
Hello,
I bought a Mini 4 Pro in December, because it was stated before that an SDK will arrive in the first half of  2024. Now 2024 is going to end and there is still no SDK or even a release date. Please provide more information when it will be available. Thanks!

**Comment by FelipeCornejo** [comment]
> @dji-dev Hello, I bought a Mini 4 Pro in December, because it was stated before that an SDK will arrive in the first half of 2024. Now 2024 is going to end and there is still no SDK or even a release date. Please provide more information when it will be available. Thanks!

@P-Mindz 
Have you tried using the sample app on the Mini 4 pro? Im just courious, i used the MSDK V5 sample on the DJI Mini Air 2 and worked partially (the camera couldn't connect).

**Comment by joaquinperaza** [comment]
> @dji-dev 
> 
> Hello,
> 
> I bought a Mini 4 Pro in December, because it was stated before that an SDK will arrive in the first half of  2024. Now 2024 is going to end and there is still no SDK or even a release date. Please provide more information when it will be available. Thanks! 

Same here. @dji-dev would you mind escalating this question and getting and estimate on the actual date before providing a default answer?

**Comment by Antr0** [comment]
¿Para cuando?. Yo compre el mini 4 pro contando que en unos meses estaria el SDK y podría usar aplicaciones externas para planificar rutas, pero ahora me arrepiento de no haber comprado en mini 3, mas barato. En fin, estoy enormemente decepcionado con esto.

**Comment by dodger-999** [comment]
The more people who complain, the better the chances we will eventually see
a Mini 4 Pro SDK. DJI stated it would be released in the first half of
2024. I very much dislike companies who lie to their customers. I too
bought the Mini 4 Pro only because DJI said they would be releasing the
SDK… I think maybe I will start going to DJI’s competitors for my drone
needs, and convince all my droning friends to do the same. For shame DJI!
Good companies don’t lie to their customers. Please release the damned SDK!!

**Comment by ivangayton** [comment]
If you're interested in mapping using the Mini 4 Pro, you could take a look at this: https://dronetm.org/

**Comment by ech2112** [comment]
Same here. I only recently got my first drone - the mini 4 pro - without doing my due diligence regarding what I eventually wanted to start learning, which is mapping. Again, I know it's my fault for not reading more about it, but I am in awe that in most of these programs it's one of the few models NOT supported and I never regret not buying the older version. 

To be clear, I love flying the Mini 4 Pro and I think it's great if you're just wanting to fly and make photos/videos. But yeah with the current situation regarding availability of the Mavic 3E I'm really regretting that I didn't go with the Air 2S so I could at least take steps towards the thing I want to do. I've seen some workaround solutions but I'm not interested in learning to hack files and use a bunch of workarounds to get a simple mission loaded into DJI fly.

**Comment by joaquinperaza** [comment]
I agree, we shouldn't accept to use hacky solutions for something as ridiculous as this.

I will buy the m4pro after they release the sdk in thr meantime complaining and putting pressure is the only thing we, customers can do. Btw I don't know why this issue is closed if you are getting more than one post per week @dji-dev

**Comment by P-Mindz** [comment]
> I agree, we shouldn't accept to use hacky solutions for something as ridiculous as this.
> 
> I will buy the m4pro after they release the sdk in thr meantime complaining and putting pressure is the only thing we, customers can do. Btw I don't know why this issue is closed if you are getting more than one post per week @dji-dev

@dji-dev as mentioned above this issue was closed by @dji-lyt in November 2023, when in fact the issue still exists as there is no SDK available. And while it took you only 1 day to reply when this issue was opened, your last reply is from more than 1 year ago.

**Comment by Aless55** [comment]
@P-Mindz The ticket is closed, that is why no one is probably responding anymore. There was a pretty clear announcement that it will be released in the first half of 2024. There is another ticket that mentions this one, you might have a better chance of getting an answer there or if you open one yourself.
