### ISSUE TITLE
Hotpoint Support on SDK 5.6 or future

### ISSUE THREAD

**Issue by zt1983811** [dji-sdk/Mobile-SDK-Android-V5#167]
Following https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/46
I am wondering if you have plan to support the hotpoint mission in SDK5.6 or future release?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92065'>Zendesk ticket #92065</a>:<br><br>I apologize for any inconvenience caused. At the moment, we do not have any plans in place to provide support for the Hotpoint mission.
<br><p><em><small>°°°</small></em></p>
