### ISSUE TITLE
Remote Controller Location

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#168]
Hi . in MSDK V5 how we can observe the location of the remote controller?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92072'>Zendesk ticket #92072</a>:<br><br>I hope this message finds you well. I would like to inform you that the MSDK does not offer a specific method to retrieve the location of the remote control. However, you can obtain the remote control position by utilizing the method provided by Android itself. For instance, you can retrieve the location information of Android devices by using the LocationManager.
<br><p><em><small>°°°</small></em></p>
