### ISSUE TITLE
M30T thermal spot returns an error

### ISSUE THREAD

**Issue by eric-dk** [dji-sdk/Mobile-SDK-Android-V5#17]
Steps-to-reproduce:
With the correct `ComponentIndexType` and `CameraLensType.CAMERA_LENS_THERMAL` use `CameraKey.KeySpotMeteringTargetPoint.set(…)` with `IntPoint2D` where [*x* is 0…12](https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/cameracore/widget/fpvinteraction/FPVInteractionWidgetModel.java#L65) and [*y* is 0…8](https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/cameracore/widget/fpvinteraction/FPVInteractionWidgetModel.java#L64).

Expected:
Camera updates thermal measuring spot.

Actual:
```
DJIError{errorCode='CORE_INVALID_PARAMETERS', innerCode='', description='null', hint='error code = -483'}
```

Notes:
The constraints are pulled from the [**FPV Interaction Widget**](https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/cameracore/widget/fpvinteraction/FPVInteractionWidgetModel.java). Interestingly, tapping on that in the *Widget List* crashes the sample application regardless of whether a drone is connected or not.

**Comment by DJI-William** [comment]
CameraLensType.CAMERA_LENS_THERMAL is not corresponded with CameraKey.KeySpotMeteringTargetPoint. The KeySpotMeteringTargetPoint does not mean measuring thermal spot. You should use KeyThermalTemperatureMeasureMode first to set the thermal measurement mode to Spot and then call KeyThermalSpotMetersurePoint to measure the temperature at a specific spot.
![image](https://user-images.githubusercontent.com/77274755/179167931-badc17d6-2e83-4820-ab1d-f56faf88ce52.png)

**Comment by eric-dk** [comment]
Doh! Thanks.
