### ISSUE TITLE
Create KMZ file for waypointmission V3

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#170]
Hi 

I am developing the app for performing some actions with the drone during the waypoint mission.

I know how to push the KMZ file and start and finish the mission But I do not know how to create that KMZ file.

I need to create a waypoint mission based on the list of my points and add several actions to each of them.

Would you please guide me on how to create that KMZ file?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92156'>Zendesk ticket #92156</a>:<br><br>Please refer to the introduction of kmz file https://developer.dji.com/doc/cloud-api-tutorial/en/api-reference/dji-wpml/overview.html
<br><p><em><small>°°°</small></em></p>
