### ISSUE TITLE
UNDEFINE_ERROR when executing KeyStartShootPhoto.create().action()

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#172]
Most of the time get an error when when attempting to take a photo in `CameraMode.PHOTO_NORMAL`. The photo is saved to the SD card 95% of the time but sometimes it fails and no photo is taken.

I get the following error:

```
ErrorImp{errorType='CORE', errorCode='UNDEFINE_ERROR', innerCode='', description='null', hint='error code= -511'}
```
My code

```kotlin
  CameraKey.KeyStartShootPhoto.create().action(
                {
                    println("Photo complete")
                },
                { e: IDJIError ->
                    println("StartShootPhoto Error $e")
                })
```

In a separate function I set the camera to photo mode normal

```kotlin
  CameraKey.KeyCameraMode.create().set(CameraMode.PHOTO_NORMAL, {
            println("Camera set to Photo mode")
        }, { e: IDJIError ->
            println("Set Photomode error $e")
        })
```

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92184'>Zendesk ticket #92184</a>:<br><br>I hope this message finds you well. I would like to inquire about the current versions of your SDK and aircraft firmware. Could you kindly confirm if you are using the latest versions? Additionally, I would appreciate it if you could provide me with the model of the aircraft you are currently utilizing.
<br><p><em><small>°°°</small></em></p>
