### ISSUE TITLE
Key KeyDewarpingEnabled missing in the documentation

### ISSUE THREAD

**Issue by rishabhSkylark** [dji-sdk/Mobile-SDK-Android-V5#175]
Hello! I'm currently exploring the API documentation, but I couldn't locate the "KeyDewarpingEnabled" entry within the documentation. Interestingly, this key is available in the SDK, allowing me to toggle Dewarping on or off for Mavic 3 Enterprise Drones.

Can I contribute to the Documentation and add the missing Key to the Documentation?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/92436'>Zendesk ticket #92436</a>:<br><br>Thank you for your enthusiasm, but I understand that the API documentation does not allow external submissions. We will forward your request to the documentation engineer. It is true that some keys on MSDK V5 cannot be viewed in the API documentation.
<br><p><em><small>°°°</small></em></p>
