### ISSUE TITLE
航线上传错误

### ISSUE THREAD

**Issue by MissTeven** [dji-sdk/Mobile-SDK-Android-V5#176]
AircraftService pushKMZFileToAircraft onFailure: ErrorImp{errorType='WAYPOINT', errorCode='FILE_TRANSFER_FAIL', innerCode='null', description='航线上传失败，请重新上传航线', hint=''}

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92454'>Zendesk ticket #92454</a>:<br><br>这个报错是缺少读写权限。看下是不是kmz文件的位置没有读写权限，或者APP没有申请读写权限。
<br><p><em><small>°°°</small></em></p>

**Comment by MissTeven** [comment]
&nbsp;
***@***.***





确认已经获取了权限存储权限，并且在调push接口前，打印了权限的授权情况，显示为已授权


                       
Original
                       
                     

From:"DJI"< ***@***.*** &gt;;

Date:2023/10/10 17:21

To:"dji-sdk/Mobile-SDK-Android-V5"< ***@***.*** &gt;;

CC:"Hello word!"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [dji-sdk/Mobile-SDK-Android-V5] 航线上传错误 (Issue #176)




 
Agent comment from Hummels Lei in Zendesk ticket #92454:

这个报错是缺少读写权限。看下是不是kmz文件的位置没有读写权限，或者APP没有申请读写权限。
 


°°°

**Comment by dji-lyt** [comment]
您还在遇到这个问题吗？
