### ISSUE TITLE
WaylineDroneType Documentation

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#177]
SDK Version: `5.6.0`

I am utilizing the newly introduced `WPMZManager` and am attempting to build out a `Template`. When supplying data to `WaylineDroneInfo`, I need to provide the appropriate enum from `WaylineDroneType`. The problem is that, at a glance, it is not immediately obvious which of the following corresponds to a Mavic 3 Enterprise:

```
Phantom4 (11),
Phantom4Pro (18),
Phantom4Advanced (27),
Phantom4RTK (59),
PM430 (60),
PM320 (67),
WM260 (68),
WM630 (76),
WM265 (77),
TA101 (78),
WM2605 (86),
PM431 (89),
EA220 (91),
WA345 (99),
UNKNOWN (0xFFFF);
```

I can assume based on other documentation that the value I want in this case is `WaylineDroneType.WM265` since the value of `77` matches what is expected (see [here](https://developer.dji.com/doc/cloud-api-tutorial/en/api-reference/dji-wpml/common-element.html)).

If this interpretation is correct, that's great. Can it be documented somewhere so this issue doesn't repeat with the M30 or future v5 SDK drones? If not, what value should I use?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92456'>Zendesk ticket #92456</a>:<br><br>I would like to acknowledge that your observation is indeed correct. The WaylineDroneType.WM265 is indeed associated with the Mavic 3 Enterprise model.

We deeply apologize for the oversight on our part. We will rectify this issue by modifying the codenames to accurately reflect the corresponding model names.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
> SDK Version: `5.6.0`
> 
> I am utilizing the newly introduced `WPMZManager` and am attempting to build out a `Template`. When supplying data to `WaylineDroneInfo`, I need to provide the appropriate enum from `WaylineDroneType`. The problem is that, at a glance, it is not immediately obvious which of the following corresponds to a Mavic 3 Enterprise:
> 
> ```
> Phantom4 (11),
> Phantom4Pro (18),
> Phantom4Advanced (27),
> Phantom4RTK (59),
> PM430 (60),
> PM320 (67),
> WM260 (68),
> WM630 (76),
> WM265 (77),
> TA101 (78),
> WM2605 (86),
> PM431 (89),
> EA220 (91),
> WA345 (99),
> UNKNOWN (0xFFFF);
> ```
> 
> I can assume based on other documentation that the value I want in this case is `WaylineDroneType.WM265` since the value of `77` matches what is expected (see [here](https://developer.dji.com/doc/cloud-api-tutorial/en/api-reference/dji-wpml/common-element.html)).
> 
> If this interpretation is correct, that's great. Can it be documented somewhere so this issue doesn't repeat with the M30 or future v5 SDK drones? If not, what value should I use?

Excuse me I have started developing with new SDK and I have some problems with creating a waypoint mission, would you please help me a bit.

In SDK 4.16, we were uploading the waypoint mission and actions that we have created to WaypointV2MissionOperator. But I do not know how to do that in SDK v5.

I know we should create a folder which is called "missionName.kmz" and inside it, we should have another folder with "wpmz" and inside it we should have the wayline.wpml file.

I know it but My question is how should we create these? I mean for example we should use the WPMZManager instance and add the actions and waypoints to that and finally by calling a method we can create these files (or something like this) or we should manually create a file, write the xml codes and create the folders in the path.

as you understand, I am a bit confused. please tell me the steps if it is possible. I have a list of points and I want to create the KMZ file and push it to the drone.

Thank you so much

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92456'>Zendesk ticket #92456</a>:<br><br>I would like to provide you with some guidance regarding the creation of a kmz file using the WPMZManager method. While both approaches are acceptable, it is advisable to utilize the WPMZManager method as it reduces the likelihood of encountering errors. I kindly suggest referring to the sample code for assistance with the writing process.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #92456](https://djisdksupport.zendesk.com/agent/tickets/92456):I would like to provide you with some guidance regarding the creation of a kmz file using the WPMZManager method. While both approaches are acceptable, it is advisable to utilize the WPMZManager method as it reduces the likelihood of encountering errors. I kindly suggest referring to the sample code for assistance with the writing process.
> 
> _°°°_

OK so as I understood we can use WPMZManager instance to configure the mission, create the waypoints and actions, and so on.

Would you please mention here the sample of these codes?

Thank you so much

**Comment by tkocik92** [comment]
@PeimanAtaei Please see the [this file](https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-sample/module-aircraft/src/main/java/dji/sampleV5/moduleaircraft/pages/WayPointV3Fragment.kt) inside of the DJI V5 Sample App (this Github codebase)

**Comment by PeimanAtaeiJPDroni** [comment]
> @PeimanAtaei Please see the [this file](https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-sample/module-aircraft/src/main/java/dji/sampleV5/moduleaircraft/pages/WayPointV3Fragment.kt) inside of the DJI V5 Sample App (this Github codebase)

Thank you so much for your response

But in this sample project we do not have any reference for waypoint actions (not wayline action).

for example I need to start distance interval shooting in the fist waypoint but I did not find any reference.

do you have any experiance about it ?
