### ISSUE TITLE
Is it possible to get an aircraft altitude if gps is not available? (mini 3 pro, 5.6, android 13)

### ISSUE THREAD

**Issue by egm108** [dji-sdk/Mobile-SDK-Android-V5#178]
From what I see no key FlightControllerKey.KeyAircraftLocation3D change. 

Thanks

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92458'>Zendesk ticket #92458</a>:<br><br>I would like to inform you that the key provides the altitude of the aircraft in relation to the take-off point. May I kindly inquire if your plane has taken off?
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Yep, it was flying, but gps wasn't available. I would like to get an altitude without gps. Is it possible?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92458'>Zendesk ticket #92458</a>:<br><br>You can get altitude through KeyAltitude.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #92458](https://djisdksupport.zendesk.com/agent/tickets/92458):You can get altitude through KeyAltitude.
> 
> _°°°_

You have helped me a lot. KeyAltitude works for me (Unfortunately, I didn't find that in the docs). Thank you. 
If you don´t mind one more question. Should GPS be enabled somehow (KeyFCGPSEnabled returns null for me)? More exactly,
I need keys KeyAircraftLocation3D/2D) Thanks!

**Comment by egm108** [comment]
KeyAltitude works for me
