### ISSUE TITLE
Error in main screen ( product name unkown)

### ISSUE THREAD

**Issue by engalotaibi** [dji-sdk/Mobile-SDK-Android-V5#179]
Hello 

i placed the aircraft id in the code but i have the error shown in picture below can you help me plz. 
![Screenshot_20231010-122217_MSDK Aircraft](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/29451102/3c788961-afd0-4be4-a1f3-0036a8d0a104)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92530'>Zendesk ticket #92530</a>:<br><br>
What is your aircraft model?
<br><p><em><small>°°°</small></em></p>

**Comment by engalotaibi** [comment]
the problem was with the rc i was using the rc but when i used rc n1 it worked perfectlly thanks

**Comment by dji-lyt** [comment]
This could be due to the impact of pilot 2. You can try updating to a higher version of MSDK or forcibly disabling pilot 2.
