### ISSUE TITLE
Mavic 3E 3T skipping waypoints on second wayline. 

### ISSUE THREAD

**Issue by lukasz-bialek** [dji-sdk/Mobile-SDK-Android-V5#180]
Aircraft: 07.01.2001 RC 02.01.0007

After firmware update Aircraft skips all waypoints on second wayline - jumps from 0 to 25 (start and stop is in the same place). 

Worked fine on previous firmwares. 
Please provide a link where to upload KMZ file with issues.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92769'>Zendesk ticket #92769</a>:<br><br>Thank you for reaching out to us. We kindly request that you submit a formal request by visiting the following link: https://sdk-forum.dji.net/hc/en-us/requests/new. In your request, please provide a comprehensive description of the steps required to reproduce the issue you are experiencing.
<br><p><em><small>°°°</small></em></p>
