### ISSUE TITLE
Gimbal lock causes exceedingly fast and hazardous drone yaw rates beyond RC stick limits

### ISSUE THREAD

**Issue by jm-avetics** [dji-sdk/Mobile-SDK-Android-V5#181]
We are developing an autonomous drone feature that uses the virtual stick mode of the MSDK to control the drone. We have encountered a serious and unexpected issue, where the drone will yaw at a very high rate that exceeds double of the maximum yaw rate in the sports mode of the remote controller. This issue occurs even when we send zero commands (0, 0, 0, 0) to the virtual sticks (roll, pitch, yaw, throttle). This issue is sporadic and unpredictable, and it poses a great risk to the safety of the drone and its surroundings.

We have observed this issue mainly on the first run after a new build of the application, but it can also happen at any time during the normal operation of our feature (i.e., the feature works fine for a while, and then suddenly the yaw issue occurs, and then it goes back to normal again). We have not enabled the virtual stick advanced parameters mode in our code. We have also tried to explicitly disable the advanced mode while running our feature, but the issue still occured. This issue only started happening when we upgraded our drone firmware from v06 to v07.

**MSDK version**: 5.6.0

**RC firmware versions tested**:
- RC PLUS (v02.02.0405)
- RC PLUS (v01.02.0445)

**Drone models and firmware versions tested**:
- M30 (v08.00.0003)
- M30T (v07.01.0026)

We have attached a video that demonstrates this issue in more detail: [video link](https://youtu.be/ZZfVRwhi-os?si=K7HmMBEIMlK7i4S4). By frame analysis as seen in the video, during the issue, the yaw rates are an average of **212°/s**, which is more than **double** of the maximum allowable yaw rate as stated on the [Matrice 30 Specs Sheet](https://enterprise.dji.com/matrice-30/specs) of **100°/s**.

We would appreciate it if you could investigate this issue and provide a solution or a workaround as soon as possible. Thank you for your attention and support.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92846'>Zendesk ticket #92846</a>:<br><br>We kindly request that you get in touch with us by utilizing the Zendesk form https://sdk-forum.dji.net/hc/en-us/requests/new. Additionally, we kindly ask that you provide us with the flight data for the specific flight in question, as well as the precise time at which the issue occurred.I will provide you with a link to update through zendesk.
<br><p><em><small>°°°</small></em></p>

**Comment by jm-avetics** [comment]
**UPDATE**: We have pinpointed the root cause and replicated the yaw issue consistently. It is triggered by a gimbal lock issue. To reproduce the bug, follow these steps:

1. Set `enum GimbalMode` to `YAW_FOLLOW`

    This mode enables the gimbal yaw angle to synchronize with the aircraft yaw angle, while the pitch and roll angles of the gimbal and camera remains controllable.

2. Yaw the gimbal to its extreme left or right

    This will place the gimbal near its singularity state (gimbal lock).

3. Create a `class GimbalAngleRotation` with these parameters:

    ```java
    GimbalAngleRotationMode = ABSOLUTE_ANGLE
    pitch = -90.0
    yaw = 0.0
    roll = 0.0
    duration = 0.0
    ```

4. Use `KeyRotateByAngle` to invoke the above class repeatedly

    The intention is to pitch the gimbal vertically down and maintain it there.

5. Observe the yaw bug and take precautions. The aircraft will begin to rotate erratically.

    The gimbal will attempt to attain a yaw of 0, but it will be immobilized in the singularity state. Moreover, since the aircraft yaw is coupled with this operation, the aircraft will try to adjust by rotating, but it will not achieve the desired value. Hence, the aircraft will spin wildly as long as this gimbal operation is being called.

**Possible work-around**:

Ensure that the gimbal is in a non-locking position before executing any gimbal commands. For example, call `KeyGimbalReset` to reset the gimbal first.

_P.S. Thank you for your reply, Hummels Lei. We will submit a Zendesk form with more details about the issue. I hope our information will help you resolve the problem as soon as possible._

**Comment by jm-avetics** [comment]
Refer to this [YouTube video](https://youtu.be/nTDA_LXLJkk) for a quick walkthrough on how to reproduce this yaw bug:

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92846'>Zendesk ticket #92846</a>:<br><br>Thank you for providing us with the information. We have successfully reproduced the issue you reported. Our team will now proceed to report the problem to our Research and Development department for resolution.
<br><p><em><small>°°°</small></em></p>
