### ISSUE TITLE
Drone not moving when high wind

### ISSUE THREAD

**Issue by GregCornis** [dji-sdk/Mobile-SDK-Android-V5#183]
It appears that the M350 will not move when in virtual joystick and calling `sendVirtualStickAdvancedParam()` to send speed orders, if there is a lot of speed.  
We have done a test flight with 17 m/s (as received with `FlightControllerKey.KeyWindSpeed`) and observed this behavior. At the end of the day, the wind lowered and the drone behaved normally again.

Is that a desired behavior ? Is there a way to know that the drone will not respond to the order sent and why ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92981'>Zendesk ticket #92981</a>:<br><br>I hope this message finds you well. I would like to inform you that the M350 aircraft has a maximum wind speed tolerance of 12m/s. It is important to note that the aircraft is unable to operate under excessively high wind conditions.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Thanks for your answer. My question is whether there is a feature that prevents the drone from moving in virtual stick mode if the wind is too high ? Because the drone was moving fine in manual mode, despite the wind

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92981'>Zendesk ticket #92981</a>:<br><br>I hope this message finds you well. I would like to inform you that in situations where the wind speed exceeds 15m/s, the flight can only be controlled using the physical joystick. Please note that all other control methods will not be effective during such conditions.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Ok thanks !
