### ISSUE TITLE
Support for ActiveTrack in SDK v5

### ISSUE THREAD

**Issue by lorenzo-eng** [dji-sdk/Mobile-SDK-Android-V5#184]
Hello,

I would like to know if support for ActiveTrack to perform automatic orbit operations is scheduled in the SDK v5 as supported by the SDK v4.

Thank you

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/93068'>Zendesk ticket #93068</a>:<br><br>I would like to inform you that V5 has plans to incorporate ActiveTrack into its system. However, it is important to note that this particular feature has been assigned a lower priority. As a result, we are unable to provide a specific release date at this time. We kindly request that you keep an eye on the release notes for updates regarding the availability of this feature.
<br><p><em><small>°°°</small></em></p>

**Comment by johnnokomis** [comment]
How is this low on the priority? We have been pressing for this ability since day one. Read your own forums, there's a new post almost every week where someone is asking for it or confused because they think they can't find it.

**Comment by dji-lyt** [comment]
Currently, we plan to fix the most fundamental camera video streaming issue. After that, we expect to proceed with the adaptation of the ActiveTrack feature according to the plan.
