### ISSUE TITLE
Integrating DSM Data into Mission Config for M300 RTK Drone on Android App

### ISSUE THREAD

**Issue by ghost** [dji-sdk/Mobile-SDK-Android-V5#187]
Hello DJI developers,

I am currently working on an Android app, specifically focusing on the terrain functionality for the M300 RTK drone. However, I've encountered a problem where the DSM data (.tif file) does not seem to render within the DJI simulator.

In my pursuit to resolve this, I stumbled upon the method JNIWPMZManager.generateKMZFile, which seemed somewhat elusive initially but caught my attention as one of its parameters was dsmFilePaths. Consequently, I integrated this method within my function, as illustrated below. The mission initiates flawlessly, and a KMZ file is generated as expected. Upon unzipping the KMZ file, I discovered my .tif file residing within the dsm folder, which is nestled within the res folder. Adjacent to the res folder, I have the waylines.wpml and the template file.

Here’s a snippet of my code pertaining to the generation of the KMZ mission file:
```
fun convertToSDKFormat(showWaypoints: ArrayList<WaypointInfoModel>, rootDir: String, dsmFilePaths: List<String>): String {
    val kmzOutPath = rootDir + "generate_waypoint_file.kmz"
    val waylineKMZPath = rootDir + "generate_wayline_kmz_file.kmz"
    // Generate WaylineMission, MissionConfig, and Template
    val waylineMission: WaylineMission = createWaylineMission()
    val missionConfig: WaylineMissionConfig = KMZTestUtil.createMissionConfig()
    val template: Template = KMZTestUtil.createTemplate(showWaypoints)

    val waylineTemplate = transToWaylineTemplate(template);
    // Create a list and add the WaylineTemplate
    val templateList = ArrayList<WaylineTemplate>()
    if (waylineTemplate != null) {
        templateList.add(waylineTemplate)
    }
    // Generate the KMZ file
    WPMZManager.getInstance()
        .generateKMZFile(waylineKMZPath, waylineMission, missionConfig, template)
    val parseInfo = JNIWPMZManager.getWaylines("1.0.0", waylineKMZPath)
    var waylines = parseInfo.waylines
    val executeMissionConfig = createExecuteConfig(missionConfig)
    JNIWPMZManager.generateKMZFile(
        VERSION,
        waylineMission,
        missionConfig,
        templateList,
        waylines,
        executeMissionConfig,
        ArrayList(),
        dsmFilePaths,
        kmzOutPath
    )

    ToastUtils.showToast("Save Kmz Success. Path is: $kmzOutPath")
    return kmzOutPath
}
```
I am reaching out to discern if there's a precise method to read the DSM file and integrate it within my mission configuration. Any guidance or suggestions regarding the code or the correct approach to achieve this would be immensely appreciated. Thank you!

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/93429'>Zendesk ticket #93429</a>:<br><br>I hope this message finds you well. I would like to kindly request your attention to the following article: How to make the WaypointMission follows the terrain. In order to achieve a flight that imitates the follows-the-terrain feature, it is necessary to include the appropriate fields in the kmz file.
<br><p><em><small>°°°</small></em></p>

**Comment by ghost** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #93429](https://djisdksupport.zendesk.com/agent/tickets/93429):I hope this message finds you well. I would like to kindly request your attention to the following article: How to make the WaypointMission follows the terrain. In order to achieve a flight that imitates the follows-the-terrain feature, it is necessary to include the appropriate fields in the kmz file.
> 
> _°°°_

Thanks for the reply!
I am sorry but the page you gave me seems to be broken,,
can i maybe have a screenshot?
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/146692790/0e7d08c1-b02b-4f8d-99f5-7e58ed0789a7)
