### ISSUE TITLE
Ability to control the bottom auxiliary light (Mavic 3 Enterprise, DJI SDK v5.6.0)

### ISSUE THREAD

**Issue by apdofficial** [dji-sdk/Mobile-SDK-Android-V5#188]
Hello,

I am trying to find a way to turn on the bottom auxiliary light of the Mavic 3 Enterprise drone. 

Setting  **FlightAssistantKey.KeyBottomAuxiliaryLightMode** to **AuxiliaryLightMode.ON**, doesn't turn on the light.
I found **FlightControllerKey.KeyLEDsSettings** using which I can control the top light. However, I still can't control the bottom light.

Is there a way to control the bottom auxiliary light mode for Mavic 3 Enterprise? (only switching between **ON**  and **AUTO** would be sufficient)

Thanks in advance.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/93504'>Zendesk ticket #93504</a>:<br><br>I used sample to set FlightAssistantKey.KeyBottomAuxiliaryLightMode is working. Are you sure you were successful in setting it?
<br><p><em><small>°°°</small></em></p>

**Comment by apdofficial** [comment]
I do not get any errors when calling the API.

I also can not control the bottom auxiliary light mode using the DJI Pilot app. Setting is to ON does not turn on any light (see the attached picture).
![Screenshot_20231025_164427](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/43278252/51f3a1a2-5c83-412b-a419-bce172abe9a3)

Could it be related to the fact that I am in the EU? I just read this forum thread: https://forum.dji.com/forum.php?mod=viewthread&tid=285300. Based on the reply in the thread, it seems the drone firmware is locked to the AUTO mode for the drones sold in the EU. Is this true?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/93504'>Zendesk ticket #93504</a>:<br><br>The default automatic mode is a limitation for customer series aircraft, but not for enterprise series. I understand that if the fill light is on for too long, it will overheat and the aircraft will automatically turn it off. In this case, even if the mode is turned on, the light will not turn on. I suggest that you wait for a while after shutting down and then try to see if it can be turned on. If it still doesn't work, I think you can contact our aircraft after-sales team to troubleshoot this issue.
<br><p><em><small>°°°</small></em></p>
