### ISSUE TITLE
YUV format different with M300 / M350

### ISSUE THREAD

**Issue by GregCornis** [dji-sdk/Mobile-SDK-Android-V5#190]
When using the streaming API (VideoDecoder + addYUVDataListener), the data sent in the callback is not in a consistent format:
 - on the M350 + P1, we receive 420 Planar data : `YYYYUUVV`
 - on the M300 + P1, we receive 420 Semi Planar data : `YYYYUVUV`
 - on the Mavic 3E, we receive 420 Planar as well

Moreover, this information is not provided in the attached `MediaFormat`. On M300, the format is
```
{ image-data=java.nio.HeapByteBuffer[pos=0 lim=104 cap=104], 
 mime=video/raw, 
 crop-top=0, 
 crop-right=1619, 
 slice-height=1080, 
 color-format=0, 
 height=1080, 
 width=1620, 
 crop-bottom=1079, 
 crop-left=0, 
 stride=1620 }
```

This is probably due to the codec used by VideoDecoder. I have two questions :
 - is this the normal behavior or is it a bug ? Is it documented anywhere ?
 - is there a way to know what IS the actual format of the YUV data provided ?

Thanks in advance

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/93901'>Zendesk ticket #93901</a>:<br><br>- is this the normal behavior or is it a bug ? Is it documented anywhere ?  -- If the YUV data format is obtained through the `mediaFormat` parameter in `onReceive(mediaFormat: MediaFormat?, data: ByteArray?, width: Int, height: Int)`, then it is considered a normal behavior.
- is there a way to know what IS the actual format of the YUV data provided ?  -- The YUV format might also be related to the remote control you're using. Is the remote control you're using on the M300 the same as the one on the M350?
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
> If the YUV data format is obtained through the mediaFormat parameter

No it isn't unfortunatly. As I mentioned above, the MediaFormat does not say whether the adata is planar or semi-planar

I am indeed using a different remote : the Smart Controller Enterprise for the M300 and the DJI RC Plus for the M350

**Comment by tukez** [comment]
Check out how the VideoChannelFragment resolves the YUV format: (https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/c4430a68b34bef62f5b8c6ecea1ebc9915f524f7/SampleCode-V5/android-sdk-v5-sample/module-common/src/main/java/dji/sampleV5/modulecommon/pages/VideoChannelFragment.kt#L511C17-L511C17). It seems color format 0 means semi-planar.

**Comment by GregCornis** [comment]
Great ! Tested, it does provide the info. Thanks for the help
