### ISSUE TITLE
当云台转动模式为 Yaw_Follow 时，在执行云台回中操作时会导致无人机转动。

### ISSUE THREAD

**Issue by Merpyzf** [dji-sdk/Mobile-SDK-Android-V5#193]
您好，我们在测试无人机云台回中时发现：
当云台模式设置为 **Yaw_Follow** 时，即使云台已经处于**回中状态**，执行云台回中操作也会导致无人机发生旋转。如果持续执行云台回中操作，无人机将会在原地打转，导致不必要的运动。我们原以为是云台回中的力带动的无人机的转动，但当云台模式设置为 Yaw 时在执行回中则不会出现上述问题。

无人机：M350
云台：H20T

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94144'>Zendesk ticket #94144</a>:<br><br>请问pilot有这样的问题吗？
<br><p><em><small>°°°</small></em></p>

**Comment by Merpyzf** [comment]
您好，未在 pilot 上发现问题。我们使用的 MSDK 版本为 5.6.0。

云台回中的代码如下：
```
        val rotation = GimbalAngleRotation()
        rotation.mode = GimbalAngleRotationMode.ABSOLUTE_ANGLE
        rotation.pitch = pitch
        rotation.setDuration(1.0)
        rotation.yaw = 0.0
        KeyManager.getInstance().performAction(
            KeyTools.createKey(GimbalKey.KeyRotateByAngle),
            rotation,
            null
        )
```

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94144'>Zendesk ticket #94144</a>:<br><br>云台回中应该调用 KeyGimbalReset，您调用这个key试一下。
<br><p><em><small>°°°</small></em></p>
