### ISSUE TITLE
Impelement UXSDK 

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#195]
Hi

I am trying to add UXSDK to my project . in the document it is written to add this line to top level of the build.gradle(project) : 
apply from:rootProject.file('dependencies.gradle')

But in new version of build.gradle we can not add it.

would you please tell me where should i put this code 

My gradle file : 
`
plugins {
    id 'com.android.application' version '8.0.2' apply false

    id 'com.android.library' version '8.0.2' apply false

    id 'org.jetbrains.kotlin.android' version '1.8.20' apply false

    id("com.google.dagger.hilt.android") version "2.44" apply false
}
`

my setting.gradle :

`

pluginManagement {

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

}
dependencyResolutionManagement {

    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {

        google()
        mavenCentral()
        maven {

            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {

                basic(BasicAuthentication)

            }
            credentials {

                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = MAPBOX_DOWNLOADS_TOKEN

            }
        }
    }
}

rootProject.name = "JPVision"
include ':app'
include ':uxsdk'// uxsdk模块
project(':uxsdk').projectDir = new File(rootProject.projectDir, '../android-sdk-v5-uxsdk')

`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94227'>Zendesk ticket #94227</a>:<br><br>Actually, the SDK is not yet compatible with gradle 8.X. Therefore, the documentation and tutorials we provide are based on gradle 6.x or 7.x. Is gradle 8.x necessary for you?
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
No But From the beggining I started the project with the new version of Gradle

So now the only way is to downgrade the gradle?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94227'>Zendesk ticket #94227</a>:<br><br>I would recommend downgrading your Gradle version. Alternatively, you can start using Gradle 8.0, but currently we do not have any documentation on how to configure it. Moreover, we have not tested Gradle 8.0, so we cannot guarantee the stability of the SDK with this version.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
To test how to implement the uxsdk, I downloaded and built the MYApplication project you provided in this link :

https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/MyApplication.zip

The project is built and run on the app and registration is successful. but when I try to build the project I face with this error :

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

What is the prblem ?

**Comment by PeimanAtaeiJPDroni** [comment]
> Agent comment from yating.liao in [Zendesk ticket #94227](https://djisdksupport.zendesk.com/agent/tickets/94227):I would recommend downgrading your Gradle version. Alternatively, you can start using Gradle 8.0, but currently we do not have any documentation on how to configure it. Moreover, we have not tested Gradle 8.0, so we cannot guarantee the stability of the SDK with this version.
> 
> _°°°_

To test the implementation of the UXSDK, I downloaded the MyApplication project you provided from this link and run it on the device :

https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/MyApplication.zip

The project is built and run and registration is success too in main activty.

But I have no access to the UXSDK elements in xml layouts.

How can I use these elements in our layout ?

![Capture](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/46ecc5a9-3c00-4671-be90-d9bf1ea61c63)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94227'>Zendesk ticket #94227</a>:<br><br>Was your Android studio previously running kotlin version 1.4.0? From the error message, this is a kotlin version conflict. You can check the version of gradle and whether the Android studio you are using supports the version of gradle configured by sample. If everything is fine, you can try to clear the cache and run it again.
<br><p><em><small>°°°</small></em></p>
