### ISSUE TITLE
Action Node List

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#196]
Hi 

I am trying to add my actions to the mission and I know after adding action infos to the actiongroup we should addd the node list.

I tried to follow the sample project in this part and this is my code :

`

        val nodeList = ArrayList<WaylineActionNodeList>()
        val root = WaylineActionNodeList()
        val treeNodes = ArrayList<WaylineActionTreeNode>()
        val rootNode = WaylineActionTreeNode()

        rootNode.nodeType = WaylineActionsRelationType.SEQUENCE
        rootNode.childrenNum = actionInfos.size
        treeNodes.add(rootNode)
        root.nodes = treeNodes
        nodeList.add(root)

        val children = WaylineActionNodeList()
        val childrenNodeList = ArrayList<WaylineActionTreeNode>()
        actionInfos.forEachIndexed { i, e ->
            val child = WaylineActionTreeNode()
            child.nodeType = WaylineActionsRelationType.LEAF
            child.actionIndex = i
            childrenNodeList.add(child)
        }
        children.nodes = childrenNodeList
        nodeList.add(children)

        actionGroup.nodeLists = nodeList
`

But the result is not OK 

Please explain a bit more about how to create the structure of the node list.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94401'>Zendesk ticket #94401</a>:<br><br>I would like to suggest that you compare the disparity between the nodeList generated by your code and the nodeList generated by our sample code. It is worth noting that this particular section of the code is written in a standardized manner, allowing you to simply copy our code directly into your project.
<br><p><em><small>°°°</small></em></p>
