### ISSUE TITLE
Potentially incorrect field in SPS NAL of H265 frame from Mini3 video stream

### ISSUE THREAD

**Issue by simonblee** [dji-sdk/Mobile-SDK-Android-V5#197]
I'm attempting to decode a H265 video frame coming from the stream data listener. I am able to decode the frame using FFMPEG, but I cannot decode the same frame when I send it to my Chrome web browser and use a `VideoDecoder` from the WebCodecs API. I am receiving an error in Chrome which says the SPS NAL is missing. Given that I was able to decode using FFMPEG, this didn't seem right, so I decided to parse the NAL units in the byte stream and check what is going on. 

It turns out the `log2_max_mv_length_horizontal` and `log2_max_mv_length_vertical` fields from the VUI parameters both appear to be set to 16 in the frame data coming from the drone, but the H265 specification (see section E3.1) says that the range must be 0 to 15, inclusive, which would indicate an erroneous value. 

FFMPEG may ignore these fields, or maybe it runs out of spec, but it appears the browser does not, hence the error. Are you able to see the same thing on your end?

**Comment by simonblee** [comment]
Please pause this issue, or close if that's not an option. I have some inconsistent testing results on my end and I'll respond or open a new issue when I have some more information.

Thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94436'>Zendesk ticket #94436</a>:<br><br>Okay, I will pause this issue. If you have any new findings, we can reopen it.
<br><p><em><small>°°°</small></em></p>

**Comment by gianlu33** [comment]
Hi @simonblee, are you still experiencing the I-Frame interval issue you mentioned in #127? I have the same problem with my Mini 3.

**Comment by dji-lyt** [comment]
Hi @gianlu33 , I recommend you can refer to this article to learn about the methods to obtain I-frames(https://sdk-forum.dji.net/hc/en-us/articles/11417166355481-What-is-the-encoding-type-of-the-output-data-from-the-StreamDataListener-), or you can update MSDK to version 5.8.0-a2, which will provide an interface for evenly pushing I-frames.

**Comment by simonblee** [comment]
@gianlu33 I hadn't, but the solution that @dji-lyt mentioned is being added in 5.8 sounds promising

**Comment by simonblee** [comment]
@dji-dev while the `log2_max_mv_length_horizontal` and `log2_max_mv_length_vertical` fields from the VUI parameters do appear to be out of range, they weren't causing my issue. The frame data coming from the drone looks like it has two identical AUD NAL units at the beginning of the bitstream, which WebCodecs didn't like. After analysing the Chromium's source code, I was able to see that it will only accept a stream with a single AUD NAL as the first NAL unit. According to section 7.4.2.4.4 of the HEVC specification, more than one AUD NAL for the same `nuh_layer_id` is not allowed:

> When an access unit delimiter NAL unit with nuh_layer_id equal to 0 is present, it shall be the first NAL unit. There
> shall be at most one access unit delimiter NAL unit with nuh_layer_id equal to 0 in any access unit.

After stripping one of the AUD NALs from the bitstream, I was able to successfully decode the remainder of the bitstream in the browser. 

I'm using version 5.7.0 of the SDK.

**Comment by dji-lyt** [comment]
Could you please provide me with the information regarding the aircraft model you are currently using?

**Comment by dji-lyt** [comment]
The latest MSDK version 5.8.0-a2, which has been released recently, no longer has this issue. You can now use the CameraStreamManager.addReceiveStreamListener method to set up a listener for receiving video data. You can give this version a try.

**Comment by simonblee** [comment]
Thanks. Do you have any documentation available for that version?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94436'>Zendesk ticket #94436</a>:<br><br>Here is the sample code and documentation：https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha
<br><p><em><small>°°°</small></em></p>

**Comment by gianlu33** [comment]
Hi,

I'm experimenting with version 5.8.0-a3 and the new ICameraStreamManager interface, but I have some issues (tested on Mini 3). I set up a listener with `cameraStreamManager.addReceiveStreamListener`, and this is what I'm getting:

- The live stream is encoded in H.264 (which is good for me, I had other issues with H.265 as discussed in this thread)
- Every time new stream data is received via `onReceiveStream`, `info.isKeyFrame()` always returns `true`, even when the frame is *not* a key frame (I checked the NAL type manually)
- The key frames seem missing important parameters such as SPS and PPS
- The SPS and PPS are sent only at the beginning of the stream (I believe it's the first frame I receive), and then never again
- In the end I cannot stream via RTMP correctly, the video cannot start. I tested both on my own RTMP server and Youtube

Hope this can help.

**Comment by mtpdog** [comment]
> The latest MSDK version 5.8.0-a2, which has been released recently, no longer has this issue. You can now use the CameraStreamManager.addReceiveStreamListener method to set up a listener for receiving video data. You can give this version a try.

Is there a recommended way to save the input stream from addReceiveStreamListener to a local MP4 file in the most efficient way?

**Comment by dji-lyt** [comment]
@gianlu33  The issue with isKeyFrame() has been submitted to the engineer for handling. The issue with sps and pps is not present in our testing. The image represents our test results, where NAlU Type = 7 indicates sps, NAlU Type = 8 indicates sps, and NAlU Type = 5 indicates idr. Since MSDK currently uses hardware decoding, different devices may have different behaviors. Is this issue only present on a specific type of device?
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/a2a67a3d-795f-4395-8f7d-6689ba2d8e63)

**Comment by dji-lyt** [comment]
https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/197#issuecomment-1817983013
@mtpdog You can try using MediaMuxer and then call MediaMuxer.writeSampleData to write the data.

**Comment by gianlu33** [comment]
> @gianlu33 The issue with isKeyFrame() has been submitted to the engineer for handling. The issue with sps and pps is not present in our testing. The image represents our test results, where NAlU Type = 7 indicates sps, NAlU Type = 8 indicates sps, and NAlU Type = 5 indicates idr. Since MSDK currently uses hardware decoding, different devices may have different behaviors. Is this issue only present on a specific type of device? ![image](https://user-images.githubusercontent.com/104296295/284255774-a2a67a3d-795f-4395-8f7d-6689ba2d8e63.png)

Hi, I have only tested on Mini 3 (it's the only drone I have that supports SDK V5).

I repeated the test a few minutes ago and I confirm what I said in my previous comment. The NALU types 7 and 8 are only received at the very beginning of the stream. Then, the only NALU types I encountered are 1 and 5 (plus other types that show up very occasionally, like 19 and 6).

Is there a way to solve this issue? Thanks.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94436'>Zendesk ticket #94436</a>:<br><br>Could you please let us know the model of the Android device you are using? Also, did you experience the same issue when you switched to a different Android device?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
> > @gianlu33 The issue with isKeyFrame() has been submitted to the engineer for handling. The issue with sps and pps is not present in our testing. The image represents our test results, where NAlU Type = 7 indicates sps, NAlU Type = 8 indicates sps, and NAlU Type = 5 indicates idr. Since MSDK currently uses hardware decoding, different devices may have different behaviors. Is this issue only present on a specific type of device? ![image](https://user-images.githubusercontent.com/104296295/284255774-a2a67a3d-795f-4395-8f7d-6689ba2d8e63.png)
> 
> Hi, I have only tested on Mini 3 (it's the only drone I have that supports SDK V5).
> 
> I repeated the test a few minutes ago and I confirm what I said in my previous comment. The NALU types 7 and 8 are only received at the very beginning of the stream. Then, the only NALU types I encountered are 1 and 5 (plus other types that show up very occasionally, like 19 and 6).
> 
> Is there a way to solve this issue? Thanks.

Our engineers have identified this issue, but due to the use of hardware decoding in MSDK, compatibility may vary across different devices. Therefore, we cannot guarantee the same performance on all devices. We will strive to make it compatible with as many devices as possible, and the next alpha version will include the fix code.
If you are willing to let us know the devices with the issue , it would be helpful for us.

**Comment by gianlu33** [comment]
Hi @dji-lyt , sorry for the late response. I was able to run some experiments today with different Android devices:
- Xiaomi Redmi Note 5 Pro (Android 9)
- OnePlus Nord (Android 11)
- Samsung Galaxy S22 (Android 14)

It turns out that _only_ the Xiaomi Redmi Note 5 Pro has this issue. With the other two devices, I correctly get the SPS and PPS every second inside key frames, and I am able to stream to a RTMP server without errors.

However, I am now facing another problem. With both OnePlus Nord and Samsung Galaxy S22, the live stream is not displayed correctly. In the picture below you can see the original frame (above) vs the frame displayed by the RTMP client (below):

<img width="780" alt="issue" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/36645341/1643b0e1-5b09-4742-8050-586624e20d26">

I tried different RTMP servers/clients with the same result. Do you have an idea what the issue might be?

**Comment by dji-lyt** [comment]
Thank you for your patient response. We will do our best to fix the issues with SPS and PPS in the next version.
Regarding the issue with rtmp, we will conduct tests to investigate. Currently, we have not encountered a similar problem.

**Comment by dji-lyt** [comment]
> Thank you for your patient response. We will do our best to fix the issues with SPS and PPS in the next version.
> Regarding the issue with rtmp, we will conduct tests to investigate. Currently, we have not encountered a similar problem.

Thank you for your patient response. We will do our best to fix the issues with SPS and PPS in the next version.
Regarding the issue with rtmp, we will conduct tests to investigate. Currently, we have not encountered a similar problem.

**Comment by dji-lyt** [comment]
> Hi @dji-lyt , sorry for the late response. I was able to run some experiments today with different Android devices:
> 
> * Xiaomi Redmi Note 5 Pro (Android 9)
> * OnePlus Nord (Android 11)
> * Samsung Galaxy S22 (Android 14)
> 
> It turns out that _only_ the Xiaomi Redmi Note 5 Pro has this issue. With the other two devices, I correctly get the SPS and PPS every second inside key frames, and I am able to stream to a RTMP server without errors.
> 
> However, I am now facing another problem. With both OnePlus Nord and Samsung Galaxy S22, the live stream is not displayed correctly. In the picture below you can see the original frame (above) vs the frame displayed by the RTMP client (below):
> 
> <img alt="issue" width="780" src="https://private-user-images.githubusercontent.com/36645341/289050600-1643b0e1-5b09-4742-8050-586624e20d26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTk4MzAsIm5iZiI6MTcwMjI5OTUzMCwicGF0aCI6Ii8zNjY0NTM0MS8yODkwNTA2MDAtMTY0M2IwZTEtNWIwOS00NzQyLTgwNTAtNTg2NjI0ZTIwZDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyNTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MmUwZjBlYzFkYTFlN2NjZTFmMDc2MjYxNGQ2N2IwYTJkN2MyZjE0YzUzYTA4YTVjZmU5ODJjY2Q2YjA5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n7OqLw3Pxt-6GjvJ6pRRZbTMrbJnSYTfJs8PdLfbio0">
> I tried different RTMP servers/clients with the same result. Do you have an idea what the issue might be?

Version 5.8.0-a4 has just been released. This version fixes the issue of no pps and sps on some models.

**Comment by gianlu33** [comment]
Hi,

I just tested version 5.8.0-a4 on all my Android devices (using DJI Mini 3) and I confirm that the streaming is now working well on all devices, and even the issue shown in the picture above seems solved now.

Thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94436'>Zendesk ticket #94436</a>:<br><br>I'm glad to hear this news.Wish you have a good day.
<br><p><em><small>°°°</small></em></p>
