### ISSUE TITLE
Cannot get/listen to KeyLinkZoomEnabled

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#198]
SDK: `5.7.1`

Per the [docs](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html#key_camera_enablezoomlinkage_inline) for `CameraKey.KeyLinkZoomEnabled`, I should be able to get, set, and listen to this key. I can set, but the changes are not reflected in subsequent get/listen calls.

Implementation:
```
keyManager.listen(
    KeyTools.createCameraKey(
        CameraKey.KeyLinkZoomEnabled,
        ComponentIndexType.LEFT_OR_MAIN, 
        CameraLensType.CAMERA_LENS_THERMAL),
    this
) { _, newValue ->
    Log.e("TEST", "LinkZoomEnabled: $newValue")
}
```
When I first start the app, I will see `LinkZoomEnabled: false` in Logcat. But it will not fire when I change the value via setValue.

Is this a bug or am I missing something?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94544'>Zendesk ticket #94544</a>:<br><br>Could you please provide me with information about the aircraft you are currently using?
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Apologies. Mavic 3 Thermal

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94544'>Zendesk ticket #94544</a>:<br><br>You can set the CameraLensType to CAMERA_LENS_DEFAULT in order to listen for changes.
During my testing, I have found that CameraLensType.CAMERA_LENS_THERMAL prevents the retrieval of the KeyLinkZoomEnabled status.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Verified that switching the lens to `CameraLensType.CAMERA_LENS_DEFAULT` works. Can the documentation be updated to reflect this? The docs say to use the thermal lens.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94544'>Zendesk ticket #94544</a>:<br><br>Thank you for your feedback. I will forward this issue to the documentation engineer.
<br><p><em><small>°°°</small></em></p>
