### ISSUE TITLE
5.8.0-a2 preview issue on HUAWEI devices with MINI 3

### ISSUE THREAD

**Issue by w109438907** [dji-sdk/Mobile-SDK-Android-V5#199]
Bug description: no preview in demo application

Application: sample-app-aircraft with sdk 5.8.0-a2

Test devices: 

1. HUAWEI Mate30 HarmonyOS 4.0.0.116
2. HUAWEI Mate60 pro HarmonyOS 4.0.0.126

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94582'>Zendesk ticket #94582</a>:<br><br>Have you tried viewing the video display in the Multi-Video Decoding View (New)? Is there also no preview on this page?
<br><p><em><small>°°°</small></em></p>

**Comment by w109438907** [comment]
I've tried both Multi-Video Decoding (VideoStreamManager - Deprecated) and Multi-Video Decoding (CameraStreamManager - New) in Testing Tools. Neither works.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/94582'>Zendesk ticket #94582</a>:<br><br>Thank you for your feedback. Could you please record a video for us? We would like to understand the information displayed on these two pages. You can upload the video to this address:https://pan-sec.djicorp.com/s/FATqMFTFMbXBm8Q password：dji123
<br><p><em><small>°°°</small></em></p>

**Comment by mtpdog** [comment]
According to my tests the picture is not displayed until the Surface view's size is changed (e.g. view is resized). 
P.S. putCameraStreamSurface() can be called and successfully run several times - it doesn't help. Until the Surface is resized.

**Comment by dji-lyt** [comment]
@mtpdog  You need to place putCameraStreamSurface（） in the callback of surfaceChanged. Additionally, putCameraStreamSurface（） requires passing the accurate size of the SurfaceView and it can be called multiple times to update the parameters.
