### ISSUE TITLE
M30T thermal digital zoom is stuck at 2×

### ISSUE THREAD

**Issue by eric-dk** [dji-sdk/Mobile-SDK-Android-V5#20]
Steps-to-reproduce:
With the correct `ComponentIndexType` and `CameraLensType.CAMERA_LENS_THERMAL` use `CameraKey.KeyThermalDigitalZoomFactor.set(…)` with `ThermalDigitalZoomFactor` other than `FACTOR_X2`.

Expected:
IR camera zooms in or out.

Actual:
There is no error with other `ThermalDigitalZoomFactor` but the camera does not zoom at all. Perhaps this is due to the fact that the M30T zoom levels are 2×, **5×**, **10×**, **20×**; which do not have corresponding `ThermalDigitalZoomFactor` enum values.

**Comment by DJI-William** [comment]
Please use KeyThermalZoomRatios instead of ThermalDigitalZoomFactor. 
![image](https://user-images.githubusercontent.com/77274755/179169365-5f9c60e4-6662-4da8-947f-7bfcb977fbac.png)

**Comment by eric-dk** [comment]
Thanks!
