### ISSUE TITLE
DJI Mini 2 SE | SDK release request

### ISSUE THREAD

**Issue by reddy75** [dji-sdk/Mobile-SDK-Android-V5#200]
Dear Development Team,

I am fresh owner of DJI Mini 2 SE, but unfortunately I am missing possibility to use other application due to incompatibility with camera. Would be great that your new release of SDK will contain also "DJI Mini 2 SE".

Thank you in advance.

**Comment by rwandaz** [comment]
kami momohon untuk melrilis SDK hntuk DJI Mini 2 SE

**Comment by rwandaz** [comment]
We kindly request the release of an SDK for the DJI Mini 2 SE

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94776'>Zendesk ticket #94776</a>:<br><br>I regret to inform you that there are currently no plans to support the SDK for the mini 2 SE. Sorry for the inconveniences caused.
<br><p><em><small>°°°</small></em></p>

**Comment by Tufak2** [comment]
There are too many of us waiting for the SDK for DJI mini 2 SE, please can you tell us approximately what is planned on this topic.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94776'>Zendesk ticket #94776</a>:<br><br>We apologize for any inconvenience caused. We regret to inform you that in the future, the majority of consumer drones will no longer be compatible with the Software Development Kit (SDK). As a result, it is highly unlikely that the Mini 2SE will support the SDK. We apologize for any inconvenience this may cause.
<br><p><em><small>°°°</small></em></p>

**Comment by Tufak2** [comment]
I wonder if there are any changes regarding the DJI mini 2 SE related to the SDK?
Greeting.

**Comment by dji-lyt** [comment]
Right now, we have received no plans for the mini 2 se.
