### ISSUE TITLE
Is it possible to crop a video stream?

### ISSUE THREAD

**Issue by mtpdog** [dji-sdk/Mobile-SDK-Android-V5#201]
Is it possible to crop a video stream received in FPVWidget using something like "center crop" way keeping its aspect ratio (without distortions)? Currently in my setup the video stream stretches to the window size with an aspect ratio distorted. 
The task is to crop the video stream to one half of the screen (cutting its left and right parts).

**Comment by PeimanAtaeiJPDroni** [comment]
> Is it possible to crop a video stream received in FPVWidget using something like "center crop" way keeping its aspect ratio (without distortions)? Currently in my setup the video stream stretches to the window size with an aspect ratio distorted. The task is to crop the video stream to one half of the screen (cutting its left and right parts).

Excuse me may I ask you to guide me a bit how to implement the uxsdk ?

To test the implementation of the UXSDK, I downloaded the MyApplication project in from this link and run it on the device :

https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/MyApplication.zip

The project is built and run and registration is success too in main activty.

But I have no access to the UXSDK elements in xml layouts.

How can I use these elements in our layout ?

![Capture](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/0fbdf02e-6954-476e-9816-925297d12215)

**Comment by dji-lyt** [comment]
Hi @mtpdog , the functionality you are looking for has been implemented in the new interface of MSDK 5.8-a2. You can check its release notes for more information：[https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha](url)

**Comment by dji-lyt** [comment]
@PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.

**Comment by mtpdog** [comment]
> Hi @mtpdog , the functionality you are looking for has been implemented in the new interface of MSDK 5.8-a2. You can check its release notes for more information：[https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha](url)

Thank you! I will check. Is there any documentation on this already?

**Comment by PeimanAtaeiJPDroni** [comment]
> @PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.

Thank you so much for your response. I will fo that and send you the result. but I have a verry important question. to use the widgets like FPV, the only way is to use the UXSDK or we can implement them by ourselves too ?

I ask it because for developping the application I was ussing the kotlin version 1.9 and gradle version 8 but I understood these versions are not supported by the UXSDK module. 

If we can implement these widgets please write the link of a sample of one of them.

Thank you so much

**Comment by PeimanAtaeiJPDroni** [comment]
> @PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.

As you told, I  included the UXSDK module in the dependencies section of the build.gradle(app). and now all the ux elements are avaiable. but when I use them in my layout it seems they are not connected and I do not have any data from the drone llike FPV, batteries and others.

What is the resean and solution ?

I am using MSDK:v5.7.1, kotlin:1.6.10 and gradle:7.0.4

![gradle](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/6660092b-a88a-4fa8-a045-945075d44f57)

![Screenshot_20231113-100926](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/50dfeda7-6123-46e0-b6ff-50d7b71eba22)


This is my gradle (app) file :

`
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 29

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdk 23
        targetSdk 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }

    packagingOptions {
        doNotStrip "*/*/libconstants.so"
        doNotStrip "*/*/libdji_innertools.so"
        doNotStrip "*/*/libdjibase.so"
        doNotStrip "*/*/libDJICSDKCommon.so"
        doNotStrip "*/*/libDJIFlySafeCore-CSDK.so"
        doNotStrip "*/*/libdjifs_jni-CSDK.so"
        doNotStrip "*/*/libDJIRegister.so"
        doNotStrip "*/*/libdjisdk_jni.so"
        doNotStrip "*/*/libDJIUpgradeCore.so"
        doNotStrip "*/*/libDJIUpgradeJNI.so"
        doNotStrip "*/*/libDJIWaypointV2Core-CSDK.so"
        doNotStrip "*/*/libdjiwpv2-CSDK.so"
        doNotStrip "*/*/libffmpeg.so"
        doNotStrip "*/*/libFlightRecordEngine.so"
        doNotStrip "*/*/libvideo-framing.so"
        doNotStrip "*/*/libwaes.so"
        doNotStrip "*/*/libagora-rtsa-sdk.so"
        doNotStrip "*/*/libc++.so"
        doNotStrip "*/*/libc++_shared.so"
        doNotStrip "*/*/libmrtc_28181.so"
        doNotStrip "*/*/libmrtc_agora.so"
        doNotStrip "*/*/libmrtc_core.so"
        doNotStrip "*/*/libmrtc_core_jni.so"
        doNotStrip "*/*/libmrtc_data.so"
        doNotStrip "*/*/libmrtc_log.so"
        doNotStrip "*/*/libmrtc_onvif.so"
        doNotStrip "*/*/libmrtc_rtmp.so"
        doNotStrip "*/*/libmrtc_rtsp.so"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'com.dji:dji-sdk-v5-aircraft:5.3.0'
    compileOnly 'com.dji:dji-sdk-v5-aircraft-provided:5.3.0'
    runtimeOnly 'com.dji:dji-sdk-v5-networkImp:5.3.0'

    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation project(':android-sdk-v5-uxsdk')
}

`

**Comment by dji-lyt** [comment]
> > Hi @mtpdog , the functionality you are looking for has been implemented in the new interface of MSDK 5.8-a2. You can check its release notes for more information：[https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha](url)
> 
> Thank you! I will check. Is there any documentation on this already?

In the address I provided, there will be an introduction to the API documentation under the DOCS path. The readme explains the updates for this version, and the sample code provides the usage method for the new interface.

**Comment by dji-lyt** [comment]
> > @PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.
> 
> Thank you so much for your response. I will fo that and send you the result. but I have a verry important question. to use the widgets like FPV, the only way is to use the UXSDK or we can implement them by ourselves too ?
> 
> I ask it because for developping the application I was ussing the kotlin version 1.9 and gradle version 8 but I understood these versions are not supported by the UXSDK module.
> 
> If we can implement these widgets please write the link of a sample of one of them.
> 
> Thank you so much

You can implement similar small widgets yourself, as all the widgets in UXSDK are open source.

**Comment by dji-lyt** [comment]
> > @PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.
> 
> As you told, I included the UXSDK module in the dependencies section of the build.gradle(app). and now all the ux elements are avaiable. but when I use them in my layout it seems they are not connected and I do not have any data from the drone llike FPV, batteries and others.
> 
> What is the resean and solution ?
> 
> I am using MSDK:v5.7.1, kotlin:1.6.10 and gradle:7.0.4
> 
> ![gradle](https://user-images.githubusercontent.com/128388408/282415132-6660092b-a88a-4fa8-a045-945075d44f57.JPG)
> 
> ![Screenshot_20231113-100926](https://user-images.githubusercontent.com/128388408/282415185-50dfeda7-6123-46e0-b6ff-50d7b71eba22.png)
> 
> This is my gradle (app) file :
> 
> ` plugins { id 'com.android.application' id 'org.jetbrains.kotlin.android' }
> 
> android { compileSdk 29
> 
> ```
> defaultConfig {
>     applicationId "com.example.myapplication"
>     minSdk 23
>     targetSdk 29
>     versionCode 1
>     versionName "1.0"
> 
>     testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> 
>     ndk {
>         abiFilters 'arm64-v8a'
>     }
> }
> 
> packagingOptions {
>     pickFirst 'lib/arm64-v8a/libc++_shared.so'
>     pickFirst 'lib/armeabi-v7a/libc++_shared.so'
> }
> 
> packagingOptions {
>     doNotStrip "*/*/libconstants.so"
>     doNotStrip "*/*/libdji_innertools.so"
>     doNotStrip "*/*/libdjibase.so"
>     doNotStrip "*/*/libDJICSDKCommon.so"
>     doNotStrip "*/*/libDJIFlySafeCore-CSDK.so"
>     doNotStrip "*/*/libdjifs_jni-CSDK.so"
>     doNotStrip "*/*/libDJIRegister.so"
>     doNotStrip "*/*/libdjisdk_jni.so"
>     doNotStrip "*/*/libDJIUpgradeCore.so"
>     doNotStrip "*/*/libDJIUpgradeJNI.so"
>     doNotStrip "*/*/libDJIWaypointV2Core-CSDK.so"
>     doNotStrip "*/*/libdjiwpv2-CSDK.so"
>     doNotStrip "*/*/libffmpeg.so"
>     doNotStrip "*/*/libFlightRecordEngine.so"
>     doNotStrip "*/*/libvideo-framing.so"
>     doNotStrip "*/*/libwaes.so"
>     doNotStrip "*/*/libagora-rtsa-sdk.so"
>     doNotStrip "*/*/libc++.so"
>     doNotStrip "*/*/libc++_shared.so"
>     doNotStrip "*/*/libmrtc_28181.so"
>     doNotStrip "*/*/libmrtc_agora.so"
>     doNotStrip "*/*/libmrtc_core.so"
>     doNotStrip "*/*/libmrtc_core_jni.so"
>     doNotStrip "*/*/libmrtc_data.so"
>     doNotStrip "*/*/libmrtc_log.so"
>     doNotStrip "*/*/libmrtc_onvif.so"
>     doNotStrip "*/*/libmrtc_rtmp.so"
>     doNotStrip "*/*/libmrtc_rtsp.so"
> }
> 
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>     }
> }
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> kotlinOptions {
>     jvmTarget = '1.8'
> }
> ```
> 
> }
> 
> dependencies { implementation 'com.dji:dji-sdk-v5-aircraft:5.3.0' compileOnly 'com.dji:dji-sdk-v5-aircraft-provided:5.3.0' runtimeOnly 'com.dji:dji-sdk-v5-networkImp:5.3.0'
> 
> ```
> implementation 'androidx.core:core-ktx:1.3.2'
> implementation 'androidx.appcompat:appcompat:1.3.1'
> implementation 'com.google.android.material:material:1.2.1'
> implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
> 
> testImplementation 'junit:junit:4.13.2'
> androidTestImplementation 'androidx.test.ext:junit:1.1.5'
> androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
> implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
> 
> implementation project(':android-sdk-v5-uxsdk')
> ```
> 
> }
> 
> `

We haven't encountered this situation before. Could you please provide us with more information? For example, in the case shown in the picture, has the SDK already identified the aircraft model? If so, can you retrieve aircraft data using the SDK?

**Comment by PeimanAtaeiJPDroni** [comment]
> > > @PeimanAtaeiJPDroni Have you included the UXSDK module in the dependencies section of the build.gradle(app) file？It seems that the issue you are encountering is related to the inability to locate the UXSDK components.
> > 
> > 
> > As you told, I included the UXSDK module in the dependencies section of the build.gradle(app). and now all the ux elements are avaiable. but when I use them in my layout it seems they are not connected and I do not have any data from the drone llike FPV, batteries and others.
> > What is the resean and solution ?
> > I am using MSDK:v5.7.1, kotlin:1.6.10 and gradle:7.0.4
> > ![gradle](https://user-images.githubusercontent.com/128388408/282415132-6660092b-a88a-4fa8-a045-945075d44f57.JPG)
> > ![Screenshot_20231113-100926](https://user-images.githubusercontent.com/128388408/282415185-50dfeda7-6123-46e0-b6ff-50d7b71eba22.png)
> > This is my gradle (app) file :
> > ` plugins { id 'com.android.application' id 'org.jetbrains.kotlin.android' }
> > android { compileSdk 29
> > ```
> > defaultConfig {
> >     applicationId "com.example.myapplication"
> >     minSdk 23
> >     targetSdk 29
> >     versionCode 1
> >     versionName "1.0"
> > 
> >     testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> > 
> >     ndk {
> >         abiFilters 'arm64-v8a'
> >     }
> > }
> > 
> > packagingOptions {
> >     pickFirst 'lib/arm64-v8a/libc++_shared.so'
> >     pickFirst 'lib/armeabi-v7a/libc++_shared.so'
> > }
> > 
> > packagingOptions {
> >     doNotStrip "*/*/libconstants.so"
> >     doNotStrip "*/*/libdji_innertools.so"
> >     doNotStrip "*/*/libdjibase.so"
> >     doNotStrip "*/*/libDJICSDKCommon.so"
> >     doNotStrip "*/*/libDJIFlySafeCore-CSDK.so"
> >     doNotStrip "*/*/libdjifs_jni-CSDK.so"
> >     doNotStrip "*/*/libDJIRegister.so"
> >     doNotStrip "*/*/libdjisdk_jni.so"
> >     doNotStrip "*/*/libDJIUpgradeCore.so"
> >     doNotStrip "*/*/libDJIUpgradeJNI.so"
> >     doNotStrip "*/*/libDJIWaypointV2Core-CSDK.so"
> >     doNotStrip "*/*/libdjiwpv2-CSDK.so"
> >     doNotStrip "*/*/libffmpeg.so"
> >     doNotStrip "*/*/libFlightRecordEngine.so"
> >     doNotStrip "*/*/libvideo-framing.so"
> >     doNotStrip "*/*/libwaes.so"
> >     doNotStrip "*/*/libagora-rtsa-sdk.so"
> >     doNotStrip "*/*/libc++.so"
> >     doNotStrip "*/*/libc++_shared.so"
> >     doNotStrip "*/*/libmrtc_28181.so"
> >     doNotStrip "*/*/libmrtc_agora.so"
> >     doNotStrip "*/*/libmrtc_core.so"
> >     doNotStrip "*/*/libmrtc_core_jni.so"
> >     doNotStrip "*/*/libmrtc_data.so"
> >     doNotStrip "*/*/libmrtc_log.so"
> >     doNotStrip "*/*/libmrtc_onvif.so"
> >     doNotStrip "*/*/libmrtc_rtmp.so"
> >     doNotStrip "*/*/libmrtc_rtsp.so"
> > }
> > 
> > buildTypes {
> >     release {
> >         minifyEnabled false
> >         proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
> >     }
> > }
> > compileOptions {
> >     sourceCompatibility JavaVersion.VERSION_1_8
> >     targetCompatibility JavaVersion.VERSION_1_8
> > }
> > kotlinOptions {
> >     jvmTarget = '1.8'
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > dependencies { implementation 'com.dji:dji-sdk-v5-aircraft:5.3.0' compileOnly 'com.dji:dji-sdk-v5-aircraft-provided:5.3.0' runtimeOnly 'com.dji:dji-sdk-v5-networkImp:5.3.0'
> > ```
> > implementation 'androidx.core:core-ktx:1.3.2'
> > implementation 'androidx.appcompat:appcompat:1.3.1'
> > implementation 'com.google.android.material:material:1.2.1'
> > implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
> > 
> > testImplementation 'junit:junit:4.13.2'
> > androidTestImplementation 'androidx.test.ext:junit:1.1.5'
> > androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
> > implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
> > 
> > implementation project(':android-sdk-v5-uxsdk')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> > `
> 
> We haven't encountered this situation before. Could you please provide us with more information? For example, in the case shown in the picture, has the SDK already identified the aircraft model? If so, can you retrieve aircraft data using the SDK?

Yes the drone is registered and connected and also I can get the drone info.

I have this problem with the Martice and Mavic 3 Enterprise series. 

But as you can see in the screenshot of the default layout, at the top left of the screen, the info about flight status (In Flight(GPS)) is working and when I land it turns to (Ready To Go (GPS))

![product info](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/7ca36df1-a5be-46f0-a8f1-dcfc4f7d721b)

**Comment by mtpdog** [comment]
> > > Hi @mtpdog , the functionality you are looking for has been implemented in the new interface of MSDK 5.8-a2. You can check its release notes for more information：[https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha](url)
> > 
> > 
> > Thank you! I will check. Is there any documentation on this already?
> 
> In the address I provided, there will be an introduction to the API documentation under the DOCS path. The readme explains the updates for this version, and the sample code provides the usage method for the new interface.

Thank you! I can confirm that center crop now works, which is great!
A couple more questions if you don't mind:
1) What is the best way to find out the full frame width / height (before crop) of an input stream? This is needed to identify which part of the screen is cropped.
2) Is there a way now to receive two streams from different lenses of a main camera simultaneously and show them in different FPVWidgets? For example from the Wide cam and Zoom cam? Or from Zoom and Thermal cam (without using PIP, because I want a vertical layout).

**Comment by dji-lyt** [comment]
> > > > Hi @mtpdog , the functionality you are looking for has been implemented in the new interface of MSDK 5.8-a2. You can check its release notes for more information：[https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha](url)
> > > 
> > > 
> > > Thank you! I will check. Is there any documentation on this already?
> > 
> > 
> > In the address I provided, there will be an introduction to the API documentation under the DOCS path. The readme explains the updates for this version, and the sample code provides the usage method for the new interface.
> 
> Thank you! I can confirm that center crop now works, which is great! A couple more questions if you don't mind:
> 
> 1. What is the best way to find out the full frame width / height (before crop) of an input stream? This is needed to identify which part of the screen is cropped.
> 2. Is there a way now to receive two streams from different lenses of a main camera simultaneously and show them in different FPVWidgets? For example from the Wide cam and Zoom cam? Or from Zoom and Thermal cam (without using PIP, because I want a vertical layout).

1.ICameraStreamManager.addFrameListener can provide you with the original image size.
2.It is not possible to simultaneously output video streams from multiple lenses. This is a limitation of the camera.
