### ISSUE TITLE
Pitch update rate

### ISSUE THREAD

**Issue by mtpdog** [dji-sdk/Mobile-SDK-Android-V5#202]
The UAV attitude and pitch, roll, yaw data refresh rates are critical for a smooth AR experience. 
I've noticed that the worst situation is with a pitch update rate on M3T. It is only about 5 Hz (once every 200 ms) which is almost unusable. 

Is there any way to enable faster refresh rates for some keys? At least for a pitch? It would be nice to have at least 10Hz as for other data or better 20Hz, 30Hz, 60Hz.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94845'>Zendesk ticket #94845</a>:<br><br>If this feature is important to you, please feedback your requirements to us in the format below.
-[Feature Description]:
-[company]: Introduction to your company
- [Demand Scenario]: Could you please provide us with an analysis of the original demand scenario? It would be helpful to understand who the end user is and what the scenario requirements are.
- [Aircraft Type]: Aircraft models that need support
- [Scenario value]: We would appreciate it if you could describe the actual value, social value, and economic value for users.
- [Priority]: It would be great if you could explain the importance of the requirement (high, medium, low). If it is high, please let us know why it is important. Additionally, if the degree of urgency (high, medium, low) is high, please explain why it is urgent.
<br><p><em><small>°°°</small></em></p>
