### ISSUE TITLE
generateKMZFile crashes on Mavic 3 Enterprise serise 

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#203]
Hi. I have completed the code for generating the KMZ file and pushing it to the drone and it works correctly with Matrice 300 RTK.

But when I run the app on the controller of the Mavic 3T and Mavic 3M.

Do you know how I can solve this problem? I can not find the exact error in Logcat which causes the crash

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94989'>Zendesk ticket #94989</a>:<br><br>I hope this message finds you well. I would like to kindly request your assistance in providing information on how to replicate the issue you are experiencing. Could you please provide detailed steps on how to reproduce the problem?

Additionally, I would like to inquire if the program crashes when uploading your kmz file.

Furthermore, I would like to know if you have tested uploading your kmz file using our sample code.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
So sorry for my mistake, the crash happens when I try to generate the KMZ file not pushing (I modified the title).

As you can see in this screenshot, I created the WaylineMission, WaylineMissionConfig, and template exactly like your sample code (and this code works in Matrice 300 RTK and generates the file). But in the Mavic 3 Enterprise series, It crashes. I have no problem in Matrice 300 RTK and it generates the file, pushes and starts it correctly. 

![generate KMZ file](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/1437145e-6fde-43d3-874f-9416111a4800)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94989'>Zendesk ticket #94989</a>:<br><br>I kindly request you to verify whether the issue at hand pertains to read and write permissions. In order to accurately identify the root cause, it would greatly assist us if you could provide us with clear error logs.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
I think the problem is not because of the permissions. I send the the manifest permissions screenshot. app works on the older version of the smart controller for Matrice 300 rtk but not on the new controllers which are used for Mavic3 enterprise.

and unfortunately, I can not find any specific error log for this crash in Logcat 

Manifest :

![manifest](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/ca66a744-43b8-42f2-9b9b-32b455039da7)

**Comment by PeimanAtaeiJPDroni** [comment]
Problem Solved by adding this code under the application tag in the manifest :

android:requestLegacyExternalStorage="true"
