### ISSUE TITLE
Can i use it for mavic 2 Pro ?

### ISSUE THREAD

**Issue by FawadAbbas12** [dji-sdk/Mobile-SDK-Android-V5#204]
Hello there it sounds confusing to ask this question as it is not mentioned in supported list but on help forum i was told that i can use it for better RTMP streaming so can it be used for mavic 2 pro ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95036'>Zendesk ticket #95036</a>:<br><br>MSDK V5 does not support Mavic 2 Pro. However, you can use MSDK V4 instead. You can find it at this address:https://github.com/dji-sdk/Mobile-SDK-Android
<br><p><em><small>°°°</small></em></p>

**Comment by FawadAbbas12** [comment]
Thanks I will

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95036'>Zendesk ticket #95036</a>:<br><br>I'm glad to assist you.
<br><p><em><small>°°°</small></em></p>

**Comment by csuwipeout** [comment]
Will the mavic 2 pro be supported by v5 at some point in the future?
