### ISSUE TITLE
Video feed corruption with alpha 5.8.0-a2 and Mini 3 Pro

### ISSUE THREAD

**Issue by tukez** [dji-sdk/Mobile-SDK-Android-V5#205]
I am testing the new ICameraStreamManager API. The video feed gets corrupted randomly for few seconds. This does not happen with 5.7.1.

I am using Mini 3 Pro /w RC Pro.

Looks like this:
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/5762429/c4e6d783-ebd2-4b4d-a0f8-f713caa0168f)

**Comment by tukez** [comment]
I just tested the new alpha 5.8.0-a3 and could not reproduce this anymore, seems to be fixed.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95095'>Zendesk ticket #95095</a>:<br><br>The 5.8.0-a3 version offers options for smooth display and emphasizes on the quality of the visuals. I think that this feature should be able to resolve the issue you are facing.
<br><p><em><small>°°°</small></em></p>
