### ISSUE TITLE
Clarification request regarding multiple cameras (Matrice 30T)

### ISSUE THREAD

**Issue by egm108** [dji-sdk/Mobile-SDK-Android-V5#207]
Hi,
as for the single camera drones (say mini3 pro), I can get zoom working (the picture increases while turning the wheel, and I get correct focal length CameraKey.KeyCameraHybridZoomFocalLength to compute everything...).

The question is: How to get the same for multiple camera. The docs says: 
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html?search=zoomfocallength&i=0&#key_camera_camerazoomfocallength_inline

1. To use this function, please call [KeyCameraVideoStreamSource] to set the video source to [ZOOM_CAMERA]
2. When using [KeyTools] to create a [DJIKey] instance, please set [CameraLensType] to [CAMERA_LENS_ZOOM].

As for i1 everything's clear: KeyManager.getInstance().setValue(DJIKey.create(CameraKey.KeyCameraVideoStreamSource),               CameraVideoStreamSourceType.ZOOM_CAMERA... (completes successfully)
As for i2: what is the key to set it to CameraLensType.CAMERA_LENS_ZOOM?

Further, I select PORTSIDE camera (in listener):
for (StreamSource streamSource: sources) {
                        if ( streamSource.getPhysicalDevicePosition().equals(PhysicalDevicePosition.PORTSIDE)) {
                            ss = streamSource;
                            break;
                        }
                    }

and corresponding channel.

So, the question is what's I'm doing wrong as video doesn't change(increase-decrease) while I turning the zoom wheel? (Let me repeat on drones with the single camera everything is working). Thank you!

Any sample code for this?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95684'>Zendesk ticket #95684</a>:<br><br>As for i2: what is the key to set it to CameraLensType.CAMERA_LENS_ZOOM?
-->When creating a key, include CameraLensType.CAMERA_LENS_ZOOM, for example: KeyTools.create(CameraKey.KeyCameraZoomFocalLength, ComponentIndexType.LEFT_OR_MAIN, CameraLensType.CAMERA_LENS_ZOOM).

You can see from the example above that when creating a key, we can actually specify the camera position using the ComponentIndexType. In general, PhysicalDevicePosition.PORTSIDE refers to LEFT_OR_MAIN. However, the prerequisite for completing the zoom action is that the CameraVideoStreamSource is currently a zoom lens.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Thanks this is regarding focal length, I'll try. But what´s about why video on RC doesn´t change while turning the wheel? Where could I see some minimal sample code for this?

Thank you!

**Comment by egm108** [comment]
"However, the prerequisite for completing the zoom action is that the CameraVideoStreamSource is currently a zoom lens."

Could you please clarify at which moment should be set KeyManager.getInstance().setValue(DJIKey.create(CameraKey.KeyCameraVideoStreamSource), CameraVideoStreamSourceType.ZOOM_CAMERA... ? Before we start the channel?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95684'>Zendesk ticket #95684</a>:<br><br>why video on RC doesn´t change while turning the wheel? Where could I see some minimal sample code for this?
-->This is because the wheel of RC PLUS does not have this function bound. It requires the implementation of the zoom function in the software.

Could you please clarify at which moment should be set KeyManager.getInstance().setValue(DJIKey.create(CameraKey.KeyCameraVideoStreamSource), CameraVideoStreamSourceType.ZOOM_CAMERA... ? Before we start the channel?
-->When you need to zoom, it is necessary to switch the current image to the zoom lens image through KeyCameraVideoStreamSource. In fact, for the zoom lens, it is also necessary to switch to the zoom lens image if you need to set the parameters of the lens, such as exposure compensation.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
"This is because the wheel of RC PLUS does not have this function bound. It requires the implementation of the zoom function in the software."
Could you please help me with some sample code on this?

Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95684'>Zendesk ticket #95684</a>:<br><br>We do not have any sample code for this. You can refer to the following code snippet, which implements listening to the left dial and then calling zoom:

    KeyManager.getInstance() .listen(KeyTools.createKey(RemoteControllerKey.KeyLeftDial), this) { _, newValue -> Log.i("波轮到的","$newValue") if (newValue != null) { if(newValue>0){ KeyManager.getInstance().setValue(KeyTools.createCameraKey(CameraKey.KeyCameraZoomRatios,ComponentIndexType.LEFT_OR_MAIN,CameraLensType.CAMERA_LENS_ZOOM),2.0*newValue,object : CommonCallbacks.CompletionCallback { override fun onSuccess() { Log.i("设置成功","") } override fun onFailure(error: IDJIError) { Log.i("设置失败","${error.description()}") } }) } } }
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Thank you! Will try!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95684'>Zendesk ticket #95684</a>:<br><br>I hope it is helpful for you.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Could you please clarify what happens exactly when I set

"KeyManager.getInstance().setValue(DJIKey.create(CameraKey.KeyCameraVideoStreamSource), CameraVideoStreamSourceType.ZOOM_CAMERA"?

Do I switch to ZOOM_CAMERA or this is just some flag for MSDK to handle Zoom? (If I need to switch to thermal camera and use zoom there will it work?)

Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95684'>Zendesk ticket #95684</a>:<br><br>It indicates that the camera video source will switch to the zoom lens. If you need to use the thermal lens, you need to pass in CameraVideoStreamSourceType.INFRARED_CAMERA and then use the corresponding zoom interface for the thermal lens: KeyThermalZoomRatios.
<br><p><em><small>°°°</small></em></p>
