### ISSUE TITLE
IVideoChannel.startChannel() erroring with error code "UNSUPPORTED"

### ISSUE THREAD

**Issue by EmilyGoose** [dji-sdk/Mobile-SDK-Android-V5#208]
Hi, I'm trying to get a video stream going on the Mini 3 - Here's my code:

```Kotlin
val sources = streamManager.availableStreamSources
val channels = streamManager.availableVideoChannels

Log.d(debugTag, "Got ${sources.size} sources and ${channels.size} channels")

// Grab the primary channel
// We can assume this channel exists as long as channels are returned
val primaryChannel = channels.filter {
     it.videoChannelType == VideoChannelType.PRIMARY_STREAM_CHANNEL
}[0]

// Since Mini 3 only has one source we can assume the first source returned is the correct one
// We can then bind that source to the video channel
// In multi-camera drones this tells the drone which stream to prioritize when bandwidth is low
primaryChannel.startChannel(sources[0], object : CompletionCallback {
    override fun onSuccess() {
        Log.d(debugTag, "Successfully joined video channel")
    }

    override fun onFailure(error: IDJIError) {
        Log.d(debugTag, "Failed to join video channel: ${error.errorCode()} : ${error.description()}")
     }
})
```

The resulting debug output is as follows:
```
Got 1 sources and 2 channels
Failed to join video channel: UNSUPPORTED : Not supported.
```

The two channels returned are `PRIMARY_STREAM_CHANNEL` and `EXTENDED_STREAM_CHANNEL` and using either still returns this error. Other aircraft data such as position and altitude is working properly. Is there something I'm doing wrong? What's the intended way of getting video feed data from a Mini 3?

Drone and controller are both on latest firmware.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95801'>Zendesk ticket #95801</a>:<br><br>Could you provide us with information about the StreamSource you have obtained？Additionally, I  also would like to know if it is possible to retrieve the video stream using the sample.

Thank you in advance for your assistance.
<br><p><em><small>°°°</small></em></p>
