### ISSUE TITLE
KeyListener Callbacks run on UI/Main thread by default?

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#209]
Is it expected behaviour that KeyListeners run on the main/UI thread by deafult? Is there a way to set this via the SDK to run all callbacks on a background thread by default?

In sdk 4, callbacks ran on a `dji_callback_thread` by default and there was an option to `setCallbackRunInUIThread` in the `DJISDKManager` class.

I noticed I was getting a warning in Logcat
```
Skipped 54 frames!  The application may be doing too much work on its main thread.
```

My Aircraft Listener code
```kotlin
private var aircraftLocationListener: CommonCallbacks.KeyListener<LocationCoordinate3D> =
        CommonCallbacks.KeyListener { _: Any?, newValue: Any? ->
            newValue?.let {
                Log.d("DEBUG_THREAD", "aircraftLocationListener thread name: ${Thread.currentThread().name}")
            }
        }
```

output
```
aircraftLocationListener thread name: main
```

SDK version: 5.7.1
DJI Product: Mini 3

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95894'>Zendesk ticket #95894</a>:<br><br>I would like to confirm with our engineers. Please wait for a while.
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
Thank you, your help would be much appreciated!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95894'>Zendesk ticket #95894</a>:<br><br>Sorry for the long wait. I have confirmed with the development team. The callback for the Key is indeed completed on the main thread.
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
Thanks for confirming! Is there a way in the sdk to **not** run Key listeners and getters on the main thread?

Running these listeners on the main thread causes performance issues as it blocks UI updates. Particularly when using Virtual Stick to listen to flight controller state and use that state to control the drone.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95894'>Zendesk ticket #95894</a>:<br><br>There is no other way to adjust the callback of the Key to another thread, except for modifying the logic of the SDK at the lower level. This is because the SDK is designed to forcefully switch to the main thread to complete the push.

I can submit this requirement to my team to try and optimize it.
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
I think I have figured out some work arounds to solve the issue I was having by running the calls to get values on a background thread thank you!
