### ISSUE TITLE
There are some string resources not found in sdk-v5-uxsdk sample. Please check over uxsdk.

### ISSUE THREAD

**Issue by cc-shifo** [dji-sdk/Mobile-SDK-Android-V5#210]
These files have string resource absent:
uxsdk_sdr_freq_view.xml,
uxsdk_setting_battery_widget.xml,
uxsdk_setting_menu_about.xml,
uxsdk_setting_menu_frequency_tab_select_layout.xml,
uxsdk_view_battery_info.xml,
arrays.xml,
"not_a_num", "normal" in uxsdk_setting_menu_sdr_video_rate_text_layout.xml, uxsdk_view_battery_info.xml

SDK version: 5.7.1.

**Comment by cc-shifo** [comment]
uxsdk_setting_ui_rc_smart_controller_wheel_calibration_view.xml
uxsdk_view_battery_info_detail_bottom.xml
uxsdk_setting_ui_imu_cal_view.xml
uxsdk_setting_ui_imucal_desc_item.xml
uxsdk_setting_ui_rc_smart_controller_calibration.xml
uxsdk_setting_ui_rc_smart_controller_stick_calibration_view.xml
uxsdk_setting_ui_rc_smart_controller_wheel_calibration_view.xml
uxsdk_setting_menu_sdr_channel_select_layout.xml
uxsdk_setting_menu_sdr_band_width_select_layout.xml
uxsdk_setting_menu_perception_vps_layout.xml
uxsdk_setting_menu_perception_precision_landing_layout.xml
uxsdk_setting_menu_omni_apas_layout.xml
uxsdk_setting_menu_imu_status_layout.xml
uxsdk_setting_menu_compass_status_layout.xml
uxsdk_setting_menu_frequency_tab_select_layout.xml
uxsdk_setting_menu_common_device_rename.xml
uxsdk_setting_menu_aircraft_go_home_mode_layout.xml
uxsdk_cell_text_layout.xml
...
...

**Comment by cc-shifo** [comment]
uxsdk_widget_vision_position_widget_layout.xml
uxsdk_widget_rc_check_frequency_layout.xml
uxsdk_widget_precision_landing_widget_layout.xml
uxsdk_setting_menu_sdr_video_rate_text_layout.xml
attrs.xml

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96000'>Zendesk ticket #96000</a>:<br><br>These files are placed inside the MSDK. Perhaps you can try modifying the way UXSDK depends on the SDK, for example, changing it to implementation deps.aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by kapipapi** [comment]
Dear @cc-shifo,
did you resolve this problem?

I have the same issue, my sample app (clean copy of this repo) does not build 😭 

```
> Task :uxsdk:processDebugAndroidTestResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml","position":{"startLine":146,"startColumn":4,"startOffset":7617,"endLine":149,"endColumn":19,"endOffset":7794}}],"original":"ERROR:/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml:147:5-150:20: AAPT: error: resource string/setting_ui_hd_channel_auto (aka dji.v5.ux.test:string/setting_ui_hd_channel_auto) not found.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml","position":{"startLine":146,"startColumn":4,"startOffset":7617,"endLine":149,"endColumn":19,"endOffset":7794}}],"original":"ERROR:/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml:147:5-150:20: AAPT: error: resource string/setting_ui_hd_channel_custom (aka dji.v5.ux.test:string/setting_ui_hd_channel_custom) not found.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml","position":{"startLine":150,"startColumn":4,"startOffset":7799,"endLine":153,"endColumn":12,"endOffset":7975}}],"original":"ERROR:/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml:151:5-154:13: AAPT: error: resource string/hdmi_system_setting_mode_same (aka dji.v5.ux.test:string/hdmi_system_setting_mode_same) not found.\n    ","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml","position":{"startLine":150,"startColumn":4,"startOffset":7799,"endLine":153,"endColumn":12,"endOffset":7975}}],"original":"ERROR:/Users/kacper/StudioProjects/Mobile-SDK-Android-V5/SampleCode-V5/android-sdk-v5-uxsdk/build/intermediates/packaged_res/debug/values/values.xml:151:5-154:13: AAPT: error: resource string/hdmi_system_setting_mode_fpv (aka dji.v5.ux.test:string/hdmi_system_setting_mode_fpv) not found.\n    ","tool":"AAPT"}

Execution failed for task ':uxsdk:processDebugAndroidTestResources'.
```

Greetings

**Comment by dji-lyt** [comment]
@kapipapi  You can try to add "android.nonTransitiveRClass = false" in gradle.build.
