### ISSUE TITLE
Sensor beep sound not working

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android-V5#211]
Hi DJI Dev,

I am implementing this sdk, all working fine except sensor beep sound, could you help me how to do that?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br> Is it referring to the alert sound on the Pilot 2? Could you please provide us with information on when it is used?

Currently, the beep sound that can be opened through the SDK is:https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_FlightController_FlightControllerKey.html?search=keyescbeepenabled&i=0&#key_flightcontroller_escbeepenabled_inline
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Yes, during flight when any obastacle found then drone is stopped, but sound is not working in sample code... how to achieve this?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>From the description you provided, it appears that the phenomenon you are experiencing is the sound alert implemented internally in Pilot 2. You will need to develop the corresponding alerts yourself, for example, when the aircraft detects an obstacle at a distance less than the warning distance, it will start sounding the alarm.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
ok dev, thanks for support...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>I hope this will be helpful to you.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Hi Dev,

How to get distance when the aircraft detects an obstacle during flight ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>The addPerceptionInformationListener function allows you to add a listener for obstacle information. This function enables you to retrieve the distance of obstacles detected by the sensor.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Hi Dev,

How to listen in onAttachwindow? here is my code below:-

PerceptionManager.getInstance().addPerceptionInformationListener(new PerceptionInformationListener() {
                        @Override
                        public void onUpdate(@NonNull PerceptionInfo information) {
                            Log.e(TAG, "Perception info updated: "+information.getDownwardObstacleAvoidanceBrakingDistance());
                           
                        }
                    });

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>I have reviewed your code and I cannot identify any issues. It is possible to set a listener for onAttachwindow as well. The problem you are currently facing is that the listener is not working when set in onAttachwindow. Have you tried setting the listener in other locations and found success?
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
I tried this method in onAttachedWindow but it invoked only once at time but i want to get information continously. how to do that?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>I understand what you mean. The interface I provided to you earlier does not meet your requirements. The PerceptionInformationListener itself only calls back when there are changes in data such as braking or warning distance. To try to obtain the obstacle distance detected by the sensor, you can use addObstacleDataListener.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Hi dev, 

I have tried PerceptionInformationListener to get data but in attached window it works once but how to get continously
<img width="836" alt="Screenshot 2024-01-02 154526" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/40540336/9073fc36-e843-4487-a82e-1cc0b32fdc73">

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96155'>Zendesk ticket #96155</a>:<br><br>What is it that you would like to obtain? If you are looking for obstacle data detected by the sensors, you will need to use the addObstacleDataListener. However, if you are interested in monitoring the parameters of the obstacle avoidance feature, you should use the PerceptionInformationListener. This listener will callback when there are changes in the parameters, such as when you reset the barking distance.

I have a question regarding the usage of the PerceptionInformationListener. Does it push data when there are changes? Could you please let me know the reason why you need it to continuously push data?
<br><p><em><small>°°°</small></em></p>
