### ISSUE TITLE
DJI Sample and Pilot 2 app not working properly

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android-V5#212]
Hi Dev,

I have integrated Sample sdk v5 for mavic 3... well it is working properly but sometime during using of my sample apk i want to use pilot 2 app, which is not working properly connection is fluctuating even after clear from background of sample sdk.. do you have any solution?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96554'>Zendesk ticket #96554</a>:<br><br>Could you please provide us with the version? Additionally, it would be helpful if you could upload a video demonstrating the issue using sample code. You can upload the video to the following address: https://pan-sec.djicorp.com/s/QGkczJ4ZzWzFb8w. The password is dji123.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Currently we are using 5.3.0.. and i have uploaded a demonstrating video to the given address

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96554'>Zendesk ticket #96554</a>:<br><br>There is indeed a conflict between Pilot 2 and MSDK in version 5.3. To resolve this issue, it is recommended that you upgrade to version 5.6, as it includes a fix for this problem：https://developer.dji.com/doc/mobile-sdk-tutorial/en/#android-msdk-v5-6-0-release-notes
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Got it.. Thanx a lot

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96554'>Zendesk ticket #96554</a>:<br><br>I'm glad I could help you.
<br><p><em><small>°°°</small></em></p>
