### ISSUE TITLE
Sample code for work with multiple batteries on rc plus and aircraft

### ISSUE THREAD

**Issue by egm108** [dji-sdk/Mobile-SDK-Android-V5#213]
Could you please provide some sample code to work with 2 batteries on both aircraft and rc plus. Say, percentage remaining.
(Everything's ok with a single battery, my question is about 2 batteries).

Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96786'>Zendesk ticket #96786</a>:<br><br>Would  you like to know the remaining battery level of the battery pack？
 If you only want to know the individual battery levels, you can simply modify the value of the componentIndex：https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Battery_BatteryKey.html
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Thank you. What about rc plus batteries (2 batteries)?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96786'>Zendesk ticket #96786</a>:<br><br>RemoteControllerKey.KeySecondBatteryInfo can retrieve the battery level of the additional battery installed on the remote control, while KeyBatteryInfo can retrieve the battery level of the remote control itself.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Thank you so much, will try

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96786'>Zendesk ticket #96786</a>:<br><br>I'm glad to help you.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
one more question
How could I find out whether a dron has  multiple batteries (on both a dron per se and on RC)? Any keys for this?

Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96786'>Zendesk ticket #96786</a>:<br><br>Currently, there is no API available to determine if the current aircraft or remote controller supports multiple batteries. However, the number of devices that support multiple batteries is limited. Only RC PLUS, RM500 (the old version of the M300 remote controller), M300, M30 series, and M350 support multiple batteries.
<br><p><em><small>°°°</small></em></p>
