### ISSUE TITLE
Mini 4 Pro support

### ISSUE THREAD

**Issue by time4Wiley** [dji-sdk/Mobile-SDK-Android-V5#214]
Hi, 

which version works with Mini 4 Pro?

I just got an Mini 4 Pro. No luck recognize the drone using the dev-sdk-main branch.

Does any version of V5 Mobile SDK support Mini 4 Pro? Be it released or in development?

If not, how to add it? what's the planned date?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/96792'>Zendesk ticket #96792</a>:<br><br>We regret to inform you that the mini 4 pro does not currently have support for the SDK. We anticipate that support for the SDK will not be available until the first half of next year.
<br><p><em><small>°°°</small></em></p>
