### ISSUE TITLE
Clarification request about CameraKey.KeyCameraHybridZoomFocalLength

### ISSUE THREAD

**Issue by egm108** [dji-sdk/Mobile-SDK-Android-V5#216]
Could you please clarify?
CameraKey.KeyCameraHybridZoomFocalLength allows to get focalLength min and max values.

The question is:
Which camera is this related to? Say, I have mavic 3t where different pairs min-max could be available for different cameras. How can I find out parameters corresponging for different cameras?

Thank you as always!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96808'>Zendesk ticket #96808</a>:<br><br>The CameraKey.KeyCameraHybridZoomFocalLength is currently not an open key. I am unsure if it can be used on all cameras supported by MSDK V5. Its functionality is limited to retrieving the current focal length of the lens and does not provide information about the range.

If you need to obtain the zoom range, you will need to use the corresponding key for reading, such as CameraKey.KeyCameraZoomRatiosRange.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
"If you need to obtain the zoom range, you will need to use the corresponding key for reading, such as CameraKey.KeyCameraZoomRatiosRange."

Is this related to currently selected camera?

Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96808'>Zendesk ticket #96808</a>:<br><br>It is related to the camera you have chosen. Different cameras have different ranges, just like H20T and H20 have different ranges. When creating a Key, you can specify the position of the camera using the ComponentIndexType parameter.
<br><p><em><small>°°°</small></em></p>

**Comment by egm108** [comment]
Thank you, will try

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96808'>Zendesk ticket #96808</a>:<br><br>Hope this is helpful to you.
<br><p><em><small>°°°</small></em></p>
