### ISSUE TITLE
What should I do to rotate gimbal?

### ISSUE THREAD

**Issue by darkangel20156** [dji-sdk/Mobile-SDK-Android-V5#217]
I have a button which is used to rotate by a random angle. What should I do to do it? Thank you everyone.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96811'>Zendesk ticket #96811</a>:<br><br>Why is it a random angle?
The GimbalKey.KeyRotateByAngle can be used to rotate the gimbal by a certain angle.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
> Agent comment from yating.liao in [Zendesk ticket #96811](https://djisdksupport.zendesk.com/agent/tickets/96811):Why is it a random angle? The GimbalKey.KeyRotateByAngle can be used to rotate the gimbal by a certain angle.
> 
> _°°°_

Honestly, I still don't understand how the gimbal can rotate when pressing a button on the app, so I'm asking in general, hoping everyone can help.

**Comment by dji-lyt** [comment]
The interface GimbalKey.KeyRotateByAngle triggers the rotation of the gimbal. To further understand, you need to check the parameters received by GimbalKey.KeyRotateByAngle, which are described in [GimbalAngleRotation](https://developer.dji.com/cn/api-reference-v5/android-api/Components/IKeyManager/Value_Gimbal_Struct_GimbalAngleRotation.html#value_gimbal_struct_gimbalanglerotation). [GimbalAngleRotation](https://developer.dji.com/cn/api-reference-v5/android-api/Components/IKeyManager/Value_Gimbal_Struct_GimbalAngleRotation.html#value_gimbal_struct_gimbalanglerotation) is a class composed of properties such as rotation angle, rotation time, and rotation mode, determining how the gimbal rotates. If you set the Pitch value of [GimbalAngleRotation](https://developer.dji.com/cn/api-reference-v5/android-api/Components/IKeyManager/Value_Gimbal_Struct_GimbalAngleRotation.html#value_gimbal_struct_gimbalanglerotation) to 0, the rotation mode to absolute mode, and the rotation time to 1, the pitch axis of the gimbal will return to the center position and complete within 1 second.

**Comment by darkangel20156** [comment]
Thanks for your help. I read docs and started to program. But I have some question about CompletionCallbackWithParam<??>.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/123035738/37ae2327-9810-4906-a709-28de411313ff)

What parameter shoud I return there?

**Comment by darkangel20156** [comment]
Yeah, I found a answer.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/123035738/9dd8db83-3019-4e12-a10b-052908b1c40f)
