### ISSUE TITLE
MSDK version 5.8

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#218]
Hi,

in one of open issues, you have told that MSDK 5.8.0-a2 has released new screen rendering and live streaming features. It fixes some crashes and provides adaptive screen display and streaming without rendering. You can try this version to see if the same issues still exist. 

https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/191#issuecomment-1794173898

How can we access to this version? and also about the samples to know how to use these new features for streaming video

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96872'>Zendesk ticket #96872</a>:<br><br>The current version has been updated to 5.8.0-a4. The new version fixes more crash issues and adapts to more devices. You can check the release notes, API documentation, and sample code at the following link for instructions on how to use it: https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha
<br><p><em><small>°°°</small></em></p>

**Comment by LilliaZ3** [comment]
Did the 5.8.0-a4 version of the SDK fix the video error you were experiencing?   
Please see 
[https://stackoverflow.com/questions/77433794/dji-sdk-5-1-7-rtmp-streaming-on-primary-channel-crashes-main-app-android/77588941#77588941](url)  for a stack dump and details.
Thank you.

**Comment by dji-lyt** [comment]
> Did the 5.8.0-a4 version of the SDK fix the video error you were experiencing? Please see [https://stackoverflow.com/questions/77433794/dji-sdk-5-1-7-rtmp-streaming-on-primary-channel-crashes-main-app-android/77588941#77588941](url) for a stack dump and details. Thank you.

I suggest that you directly use the latest version 5.8.0-a6. Indeed, there have been some fixes for fdsan starting from version 5.8.0-a4. The crash logs you provided indicate that the crash was caused by fdsan.

Mobile SDK does not support Android 14. Please take note of this information.

**Comment by LilliaZ3** [comment]
Hello.  
Does the new release (last week) of 5.8.0 at  https://github.com/dji-sdk/Mobile-SDK-Android-V5/releases/tag/V5.8.0 have the alpha 5.8.0**-a6** in it?  I am not sure how the release cycle and numbering work. 
Thank you for the warning on versions of Android OS.  I am using Android 13.
Thank you.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96872'>Zendesk ticket #96872</a>:<br><br>Last week's release of version 5.8 includes 5.8.0-a6. You can directly use the official version 5.8.
<br><p><em><small>°°°</small></em></p>

**Comment by LilliaZ3** [comment]
Hello.  

The sample in the newly released 5.8.0  version uses the deprecated VideoStreamManager and does not run.  Would it be possible to update the 
` MediaDataCenter.getInstance().getVideoStreamManager().addStreamSourcesListener(sources -> runOnUiThread(() -> 
                                                                                                              updateFPVWidgetSource(sources)));
  ;`
to the new 
`MediaDataCenter.getInstance().getCameraStreamManager(........)`
instead of the deprecated **VideoStreamManager?**

I am unsure of the parameters and the signature of the listener.  Commenting out the video stream manager line did not fix the problem. The API documentation for Camera Stream Manager did not help.

Thank you very much in advance for any help or sample.

**Comment by dji-lyt** [comment]
May I confirm your issue with you? 
Is your current issue that the FPVWidget is not working? Are you currently using version 5.8 of the UXSDK module? Or have you only updated the MSDK version?

In the CameraStreamManager, a similar method to addStreamSourcesListener is addAvailableCameraUpdatedListener. you can replace it with this method. However, the controls of the UXSDK in version 5.8 should be working fine.

**Comment by LilliaZ3** [comment]
Thank you for responding.  I am using version 5.8 of the UXSDK and have updated my android project to the new version.  When I run I do not see the camera images streaming to the app (as before).  Apart from the widgets, it is blank.  
I suspect these lines:

`MediaDataCenter.getInstance().getVideoStreamManager().addStreamSourcesListener(sources -> runOnUiThread(() -> updateFPVWidgetSource(sources)));
        primaryFpvWidget.setOnFPVStreamSourceListener((devicePosition, lensType) -> {
            cameraSourceProcessor.onNext(new CameraSource(devicePosition, lensType));
        });
`

have been deprecated and need to be replaced with  addAvailableCameraUpdatedListener.  I am unsure of the parameters.  I imagine you all would want to update your samples with the newer CameraStreamManager as well.  I am quoting the code from the **sample** at [https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-uxsdk/src/main/java/dji/v5/ux/sample/showcase/defaultlayout/DefaultLayoutActivity.java](url)

All help would be greatly appreciated!  Thank you.

**Comment by dji-lyt** [comment]
Hello @LilliaZ3 ,
We kindly request you to provide us with the model of the aircraft and remote control you are using. If possible, it would be even better if you could take a photo and share it with us.

**Comment by LilliaZ3** [comment]
Hello.
Again thank you for your help.  Here is a photo:
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/135996432/f153a5aa-6166-4c04-9636-c70b1c8a43a3)
Thank you.

**Comment by dji-lyt** [comment]
From the photo, it seems that you are using the mini 3 aircraft. I was able to successfully obtain the video stream by running the example code on the mini 3 with version 5.8. Do you have the same issue when running the example code?

It is true that FPVwidget may need to switch to the new interface, but the previous interface should still work fine. If the old interface is not working, the 5.8 example code should have the same behavior.
![df0b9c8f8d35b16a5d43aeb882085aa](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/a2ec1467-0034-4f1f-b45b-da2194a0c08c)
![bdfc88e264a6aef3f347250734de790](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/5cef5023-8e90-4fca-a9f6-172654df2fac)
![c1389fa0b12cc8c9e39600ec41cbde5](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/b3eef840-e673-4a4e-9689-db7da4cfe25f)

**Comment by huongta157** [comment]
I run the sample code with alpha branch, but Default Layout screen is always black.
- Drone version: Air 2S
- Smartphone: Pixel 4xl
![Screenshot_20240320_095020](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/46671455/ac608225-b67d-41e4-93bc-ee9289b89af5)
