### ISSUE TITLE
Waypoint Mission Pause Confusion

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#219]
SDK: `5.7.1`
Drone: M30 and Mavic 3 Thermal

**Note**: I am not sure if these are bugs or intended behavior, but there is confusion surrounding them regardless.

### Item 1
When I pause a Waypoint mission (via `WaypointMissionManager.getInstance.pauseMission`), the reported Flight Mode (see `FlightControllerKey.KeyFlightMode`) changes from `WAYPOINT` to either:

1. `GPS_NORMAL` for the M30
2. `APAS` for the Mavic 3 Thermal (I've been told M3E as well)

If this is intended behavior, is there a reason for this?

### Item 2
If I execute the following: 

1. Start a Waypoint mission with a **_global_** yaw mode of `WaylineWaypointYawMode.MANUALLY`
2. Pause the mission
3. Use the joysticks to move the drone (but not change the yaw)
4. Resume the Waypoint mission

The drone will turn to face the direction it flies and never returns to the drone's yaw to what it was prior to resume.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/96905'>Zendesk ticket #96905</a>:<br><br>With regards to item 1, it is important to note that the flight control designs vary among different aircraft models. Therefore, it is necessary to make adaptations and modifications to accommodate the specific requirements of each model.

Regarding item 2, when the global yaw is set to WaylineWaypointYawMode.MANUALLY, it means that the aircraft will not automatically adjust its yaw angle. Instead, you will need to manually adjust the yaw angle as per your requirements.
<br><p><em><small>°°°</small></em></p>
