### ISSUE TITLE
关于viewbinding

### ISSUE THREAD

**Issue by fail572872916** [dji-sdk/Mobile-SDK-Android-V5#220]
我在使用viewbinding遇到如下问题
java.lang.reflect.InvocationTargetException
具体问题如下
Binary XML file line #28 in com.suntoon.suntoonfly_v2:layout/activity_main: Binary XML file line #28 in com.suntoon.suntoonfly_v2:layout/activity_main: Error inflating class dji.v5.ux.core.widget.fpv.FPVWidget
![微信截图_20231212135704](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/37a33e79-50b9-4df6-9cc6-aa182e1c3581)
我该如何解决？

**Comment by fail572872916** [comment]
![Uploading 微信截图_20231212141040.png…]()

**Comment by fail572872916** [comment]
![Uploading 微信截图_20231212141040.png…]()

**Comment by fail572872916** [comment]
![微信截图_20231212141040](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/252db53c-2b40-4811-94f9-97e278e9c13f)

**Comment by fail572872916** [comment]
![微信截图_20231212141526](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/c2f91356-3fa6-483a-90e6-ca2b5319a00d)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96949'>Zendesk ticket #96949</a>:<br><br>从报错来看是app:uxsdk_videoChannelType="primarystreamChannel"导致了这个问题，你可以选择删除掉这个属性，它表示这个窗口与主通道绑定在一起了。UXSDK的控件没有适配过viewbinding，你需要自行适配。
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
我已了解该问题 ，根据我项目中的配置，需要去掉android-sdk-v5-uxsdk中的kotlin-android-extensions，我手动改为了viewbinding,这样的运行是正常的，如果引用了module-common，也需要去掉 kotlin-android-extensions，改为viewbinding

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/96949'>Zendesk ticket #96949</a>:<br><br>感谢你的耐心回复，这对有着相同问题的开发者是十分有帮助的。
<br><p><em><small>°°°</small></em></p>
