### ISSUE TITLE
Get altitude in meter  

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android-V5#221]
Hi Dev,

How to get altitude in meter, which method will work?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/96955'>Zendesk ticket #96955</a>:<br><br>I hope this message finds you well. I would like to inform you that the altitude of the aircraft relative to the takeoff point can be obtained by utilizing the KeyAircraftLocation3D feature.
<br><p><em><small>°°°</small></em></p>
