### ISSUE TITLE
关于libc++_shared.so

### ISSUE THREAD

**Issue by fail572872916** [dji-sdk/Mobile-SDK-Android-V5#224]
是否能够去掉这个东西，目前我得项目里有其他aar引用这个东西，pickFirst 我也增加了，结果导致我导入的aar的功能无法正常使用

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97079'>Zendesk ticket #97079</a>:<br><br>libc++_shared.so应该是与直播功能有关的，你这边会使用到直播功能吗？
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
我已经解决了，是我引用的另一个aar里报错信息不清晰，导致错误判断，经过排查已解决
