### ISSUE TITLE
Gimbal yaw and aircraft yaw issues.

### ISSUE THREAD

**Issue by chano1025** [dji-sdk/Mobile-SDK-Android-V5#225]
When the gimbal is looking toward the center, the yaw of the gimbal and the yaw of the aircraft sometimes appear different.

Can the IMU status of drones and gimbals have an impact?
The APIs used are GimbalKey.KeyGimbalAttitude and FlightControllerKey.KeyAircraftAttitude.

Thank you.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97091'>Zendesk ticket #97091</a>:<br><br> I would like to ask for some additional information regarding the issue you are experiencing. Could you please provide us with the model of the aircraft you are using? Additionally, I would like to confirm if this issue occurs only after the aircraft has taken off.
<br><p><em><small>°°°</small></em></p>
