### ISSUE TITLE
Problem in starting wayline mission

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#226]
Hi DJI developers,

I want to run the mission on DJI Mavic 3T, the kmz file is generated successfully  and pushed on the drone. 

But when I try to start the mission, after some second I receive this error :

`onMissionStartFailure: SEND_PACK_TIMEOUT Command timed out`

the KMZ file is valid and I can run this mission from DJI Pilot2. also the code is correct because it works on Matrice 300RTK.

Would you please help me solve this problem?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97117'>Zendesk ticket #97117</a>:<br><br>It is important to note that the waypoint mission name parameter should not include the kmz suffix. Could you please verify if this is the cause of the problem?
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Thank you so much for your response. Yes it was the exact issue and when I removed the .kmz suffix, it started the mission
