### ISSUE TITLE
FlightMode does not change to GPS_TRIPOD

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#227]
SDK: `5.7.1`
Drone: Mavic 3 Thermal

I have implemented a listener for `FlightControllerKey.KeyFlightMode`. When I change the Remote Control Flight Mode toggle from `N` to `F`, the flight mode does not change to `GPS_TRIPOD` and remains in `APAS`. This problem does not occur if I change the `F` mode to be Attitude.

The listener I have for `FlightControllerKey.KeyRemoteControllerFlightMode` does report correctly.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97120'>Zendesk ticket #97120</a>:<br><br>I would like to inquire about the operations that were being performed when the aircraft status was indicated as "APAS". In normal circumstances, the FlightMode of M3T should be set to "GPS_NORMAL" when in the N position. Could you kindly provide me with more information regarding the activities that were being carried out at that time?
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
There was nothing special going on. This is the default flight mode of the M3T when I turn on the drone. It remains in that mode until I change the RC Flight Mode (via toggle) or start a Waypoint mission. When I return to `N` or pause/stop/finish the Waypoint mission, the flight mode returns to `APAS`.

I would like to mention that I brought this up in a separate issue [here](https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/219) and was told that the default depends on the drone.

I should mention that the rc and drone are on the latest firmware.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97120'>Zendesk ticket #97120</a>:<br><br>It is important to note that the scenario you are experiencing is considered to be within the normal range of operation. To provide you with a relatable analogy, you can compare it to the pilot APP. In a similar manner, when transitioning to F mode in APAS mode, the pilot display may still indicate that the flight mode is APAS.
<br><p><em><small>°°°</small></em></p>
