### ISSUE TITLE
请问御mini能使用v5吗

### ISSUE THREAD

**Issue by CtrlAndZ** [dji-sdk/Mobile-SDK-Android-V5#228]
我看御mini好像能够使用v4，v5的产品支持列表没有写御mini，请问御mini能使用v5吗？

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97139'>Zendesk ticket #97139</a>:<br><br>V5不支持mini。
<br><p><em><small>°°°</small></em></p>
