### ISSUE TITLE
使用MSDK5.8.0A4进行直播，直播推出来的流是不是缺少了某些NALU?

### ISSUE THREAD

**Issue by Fujimiya-Asuka** [dji-sdk/Mobile-SDK-Android-V5#229]
使用MSDK5.8.0A4后推到线上的流媒体服务器会卡住一开始的2秒，或者大概10几秒会断一次流，然后需要重新拉取。
我电脑上的流媒体服务是 mediamtx  推到我自己电脑上的流媒体服务提示这个  
2023/12/16 17:22:41 WAR [RTMP] [conn 192.168.31.47:56444] unable to decode AVCC: invalid NALU
2023/12/16 17:22:54 WAR [RTMP] [conn 192.168.31.47:56444] unable to decode AVCC: invalid NALU
2023/12/16 17:23:14 WAR [RTMP] [conn 192.168.31.47:56444] unable to decode AVCC: invalid NALU

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97289'>Zendesk ticket #97289</a>:<br><br>在其他主流平台上也存在相同的问题吗？例如VLC或者虎牙等直播平台
<br><p><em><small>°°°</small></em></p>
