### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by ghost** [dji-sdk/Mobile-SDK-Android-V5#23]
Hi,

I've download the project and opened it in android studio but, why is there so many androidManifest and what I'm supposed to do from here ?

![image](https://user-images.githubusercontent.com/85866455/182151563-02e4c21a-f0ca-4b5e-9c9d-d880487daa34.png)

Thanks

**Comment by DJI-William** [comment]
Please read this artcle [Chapter 2 - The Sample](https://sdk-forum.dji.net/hc/en-us/articles/5983558993433-Chapter-2-The-Sample), this project contains 3 app. So there are 3 Manifests, you can jsut stick to the ALL project, it means it contains both aircraft and handheld products functionalities.
