### ISSUE TITLE
Absolute altitude of drone (Above Sea Level)

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#230]
Hi DJI,

In the DJI Pilot 2 application we have 2 types of altitude of drone. relative height and absolute altitude which shows the drone's altitude according to the sea level. 

But in MSDK as I know we have only "KeyAircraftLocation3D" which gives us the relative altitude of the drone (altitude according to the start point).

How we can have access to the absolute altitude too?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97388'>Zendesk ticket #97388</a>:<br><br>I hope this message finds you well. I would like to inquire about the type of aircraft you are using. It is generally recommended to obtain absolute altitude through RTK (Real-Time Kinematic) as it is more accurate compared to GPS and barometric altimeters. The method to obtain absolute altitude through RTK is by using the "getReal3DLocation" function.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
Hi @dji-dev 

As you told me, to get the above sea level (asl) altitude by use of rtk, I used getReal3DLocation but it shows the relative altitude (above ground level). But exactly in that place in DJI Pilot2 we have the correct asl value. How can I get the asl value like dji app?

I send you the code :

![code](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/7ca40187-6167-43f0-8555-4a54ac6c96e4)

and the logs ---------------------------------------------------------------------------------------------------------------------

![hhh](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/986917c0-43a0-4fde-8b98-c760acf8075c)

 and dji asl value ----------------------------------------------------------------------------------------------------------------

![Screenshot_20231221-162703](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/817fcab4-b6b3-4aca-8219-a67b2e0ce637)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97388'>Zendesk ticket #97388</a>:<br><br> I would like to inform you that in order to obtain the absolute RTK altitude, you will need to include the RtkMobileStationKey.KeyRTKTakeoffAltitudeInfo.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
Excuse me But I need the absolute altitude at realtime when I am performing the wayline mission, not just the asl at takeoff point.

would you please explain more ? @dji-dev

**Comment by PeimanAtaei** [comment]
Hi @dji-dev 

Excuse me But I think you did not understand what I mean

I need the asl value real time during the mission, not just for the takeoff point. would you please explain more about it ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97388'>Zendesk ticket #97388</a>:<br><br>I would like to inform you that you can obtain the absolute altitude of the aircraft by using the real3DLocation.altitude combined with the RtkMobileStationKey.KeyRTKTakeoffAltitudeInfo.
<br><p><em><small>°°°</small></em></p>
