### ISSUE TITLE
Support Gradle version 8.0

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#231]
Hi DJI,

As you told me befor in this ticket: https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/195#issuecomment-1801059663

![tikcket](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/e96ebc5d-bfb6-4df1-9f98-f30d5b285044)

the current version of sample project does not support the gradle version 8. 

Do you have any plan to cover this version too in the next updates ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97392'>Zendesk ticket #97392</a>:<br><br>We have received your request for adapting to Gradle 8, but at the moment, we do not have a concrete plan in place. I would like to inquire if Gradle 8 is absolutely necessary for you?

Additionally, I would like to inform you that Mobile SDK version 5.8 will be adapted to Gradle 7.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
And do you have any plan to update the sample project too, to be adapted with the gradle 7 ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97392'>Zendesk ticket #97392</a>:<br><br>The latest sample code has been updated to be compatible with Gradle 7. You can find the code at the following address: https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha.
<br><p><em><small>°°°</small></em></p>
