### ISSUE TITLE
5.8.0-a4 Compass and IMU calibration seems to be broken

### ISSUE THREAD

**Issue by mtpdog** [dji-sdk/Mobile-SDK-Android-V5#232]
I noticed that Compass and IMU calibration requests fail on 5.8.0-a4 (as well as 5.8.0-a3). On 5.7.0 it worked fine. Please check.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97414'>Zendesk ticket #97414</a>:<br><br>Could you provide us with information about the aircraft you are using?

Thank you in advance for your assistance.
<br><p><em><small>°°°</small></em></p>

**Comment by mtpdog** [comment]
Mavic 3T

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/6852ef95-dbff-4467-a943-3c1bd145c03b)
I hope this message finds you well. I wanted to address your question regarding the calibration of the compass on the a4 version. Did you have any metal or other objects nearby that could have affected the magnetic field during the calibration process?
I have successfully conducted the test. You can view the attachment for more details.
