### ISSUE TITLE
Gimble Rotation Problem

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#233]
Hi DJI,

I have a problem with gimble rotation with this code : 

![gimble rotation](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/e679bb37-ba98-4b2e-9a99-c39f13c70c32)

The problem is that when I set the yaw value to 0, in the simulation test in the office, it rorates the gimble correctly (camera looks forward of the drone), but in real mission in the field, it is not looking forward (it has 45 degree). and ro solve  it I have to set the yaw on -45.

what is the reason and what should I do to solve it

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97634'>Zendesk ticket #97634</a>:<br><br>In relative rotation mode, you set the rotation angle of the Yaw axis to 0. Is my understanding correct?
When the aircraft performs this action, does the yaw axis of the gimbal actually change? How do you observe this change?
<br><p><em><small>°°°</small></em></p>
