### ISSUE TITLE
Payload mode activation in V5 sdk

### ISSUE THREAD

**Issue by Conjuror1279** [dji-sdk/Mobile-SDK-Android-V5#234]
Hi,

This is in reference to the issue [1148](https://github.com/dji-sdk/Mobile-SDK-Android/issues/1148). 
In the DJI Fly App there's a toggle button to enable/disable payload mode (payload mode compensates extra weight of e.g. propeller guards).
There is a key in the V5 SDK, KeyPropellerCoverLimitEnabled. Setting the value of the key to false returns success callback,  but it does not seem to have any effect on the distance limit.

Please help with this issue,
Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97660'>Zendesk ticket #97660</a>:<br><br>I hope this message finds you well. Could you please provide us with a screenshot of the buttons on DJI Fly?
<br><p><em><small>°°°</small></em></p>
