### ISSUE TITLE
Multiple type of Thermal Image View

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#235]
In MSDK V5 how to show multiple type of thermal image like  Dji Pilot 2 showing multiple type of Thermal view of image

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97672'>Zendesk ticket #97672</a>:<br><br>I would like to clarify your request for better understanding. Are you referring to modifying the color palette of the infrared camera or switching the display mode? By color palette, I mean modes like iron red, and by display mode, I mean options like split-screen or center mode.
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
yes i need Diffrent type of color palette on thermal camera

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97672'>Zendesk ticket #97672</a>:<br><br>You can utilize KeyThermalPalette for your needs. For detailed instructions on how to use it, please refer to the online documentation:https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html?search=keythermalpalette&i=0&#key_camera_camerathermalpalette_inline
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
To set palette type. Settable palette range can be obtained through [KeyThermalPaletteRange](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html#key_camera_camerathermalpaletterange).

KeyThermalPaletteRange  is not working in Mavic 3 Drone Enterprise to view different type of thermal image from camera .

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97672'>Zendesk ticket #97672</a>:<br><br>I would like to first confirm if your usage meets the following two points.
**Notice：**
**1. To use this function, please call** `KeyCameraVideoStreamSource` **to set the video source to** `INFRARED_CAMERA`**.**
**2. When using** `KeyTools` **to create a** `DJIKey` **instance, please set** `CameraLensType` **to** `CAMERA_LENS_THERMAL`**.**
<br><p><em><small>°°°</small></em></p>
