### ISSUE TITLE
Checking when Virtual Stick is enabled bugs

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#236]
There seems to be three boolean values provided by the sdk to determine whether Virtual stick is enabled but only one of them works reliably. 

Scenario:
A call to `VirtualStickManager.getInstance().enableVirtualStick()` enables virtual stick

Expected: 
- `VirtualStickState.isVirtualStickEnable` is set to `true`
- `FlightControllerKey.KeyVirtualStickEnabled` is set to `true`
- `FlightControllerKey.KeyVirtualStickControlModeEnabled` is set to `true`

Actual:
- `VirtualStickState.isVirtualStickEnable` is set to `true` ✅ 
- `FlightControllerKey.KeyVirtualStickEnabled` is set to `true` on the Mini 3 but `null` on the Mini 3 Pro ❌ 
- ` FlightControllerKey.KeyVirtualStickControlModeEnabled` always returns `false` ❌ 

I cannot see any documentation that explains the `KeyVirtualStickControlModeEnabled` key in case I am misinterpreting what it means.

Tested with `5.8.0-a6` and `5.7.2` with a Mini 3 and a Mini 3 Pro

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97717'>Zendesk ticket #97717</a>:<br><br>I would like to inform you that the keys "KeyVirtualStickControlModeEnabled" and "KeyVirtualStickEnabled" are not documented and are considered as restricted keys. Therefore, we do not recommend using them. Instead, we suggest using the method "VirtualStickState.isVirtualStickEnable" to determine whether the virtual stick is enabled.
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
Thank you so much for clarifying that! Can I have multiple `VirtualStickStateListener`s? For example a separate instance of the `VirtualStickStateListener` in two different unrelated classes or is only a single instance of the listener allowed in my app?

e.g.
```kotlin
class TestClass() {
  private val vsStateListener = object : VirtualStickStateListener {
        override fun onVirtualStickStateUpdate(stickState: VirtualStickState) {
            println(stickState.isVirtualStickEnable)
        }

        override fun onChangeReasonUpdate(reason: FlightControlAuthorityChangeReason) {}
    }
}

class AnotherClass() {
  private val vsListener = object : VirtualStickStateListener {
        override fun onVirtualStickStateUpdate(stickState: VirtualStickState) {
            println(stickState.isVirtualStickEnable)
        }

        override fun onChangeReasonUpdate(reason: FlightControlAuthorityChangeReason) {}
    }
}
```

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/97717'>Zendesk ticket #97717</a>:<br><br>I would like to inform you that it is possible to have multiple instances of VirtualStickStateListener. However, in order for them to take effect, they must be registered as listeners using the setVirtualStickStateListener method. Please note that only one listener can be set using the setVirtualStickStateListener method.
<br><p><em><small>°°°</small></em></p>
