### ISSUE TITLE
Gimbal Pitch Action problem in Mavic 3T

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#237]
Hi DJI,

I am trying to rotate the gimbal as an action in my wayline mission. the value for pitch is 60 and it works fine with Matrice 300 RTK, but when I run the app on Mavic 3T, the rotation speed is so slow and also it rotates it more that 60 (around 80 degree).

what is the problem and how can I solve it?

code : 

![gimble rotation](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/3cc8df09-11c2-42cc-aa0b-43a68655a5fc)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/97770'>Zendesk ticket #97770</a>:<br><br>Regarding the Mavic 3T, if you set enableRotateTime to true, this action will not use the rotation time you have set, but instead, it will use the default time. We recommend setting enableRotateTime to false and then testing it again.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
Thank you 

yes the problem was because of RotateTime. I set it false and problem solved.
