### ISSUE TITLE
Integration MSDK and UX in new android studio version

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#238]
HI DJI.

Do you have any plan to update the documentation of integrating MSDK in an empty project to support new version of android studio?

As we know after the Bumblebee version, the structure of gradle files (like build.gradle of the project) is changed and it is impossible to follow the documentation.

**Comment by dji-dev** [comment]
Agent comment from yxin in <a href='https://djisdksupport.zendesk.com/agent/tickets/97956'>Zendesk ticket #97956</a>:<br><br>Dear developer,

We will update the documentation (integrating MSDK in an empty project) in the next version of MSDK. And the next version will be released soon.

We hope you a nice day! Thanks for your feedback and patience!
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Hi DJI, Would you please tell me if you have updated the documentation or  not ?

**Comment by dji-lyt** [comment]
@PeimanAtaeiJPDroni  We have now updated the documents.
