### ISSUE TITLE
5.8.0  crash problem when the method cameraStreamManager.addReceiveStreamListener() is called too early

### ISSUE THREAD

**Issue by w109438907** [dji-sdk/Mobile-SDK-Android-V5#239]
在 demo 中, CameraStreamDetailFragment.kt  initViewModel 时 addReceiveStreamListener, 如果打开 demo 后快速进入 Multi-Video Decoding (CameraStreamManager - New)  会引起 crash，延迟一段时间进入则正常。 VideoStreamManager - Deprecated 调用 channel.addStreamDataListener 过早一样有这个问题。

Application: sample-app-aircraft with sdk 5.8.0

Test devices: SAMSUNG S22  HUAWEI MATE 20

​	

```kotlin
private fun initViewModel() {
    /*demo code*/
    /*register the stream listener*/
	MediaDataCenter.getInstance().cameraStreamManager.addReceiveStreamListener(cameraIndex,
            object : ICameraStreamManager.ReceiveStreamListener {
                override fun onReceiveStream(frameData: ByteArray, offset: Int, length: Int, format: StreamInfo) {
                }
            })
}
```

```java
FATAL EXCEPTION: StreamEncoder_LEFT_OR_MAIN
Process: com.dji.sampleV5.aircraft, PID: 4787
java.lang.NullPointerException: Attempt to invoke virtual method 'int 
    java.lang.Integer.intValue()' on a null object reference 
    at android.media.MediaFormat.getInteger(MediaFormat.java:1732)
    at dji.v5.manager.datacenter.camera.StreamEncoder$EncodeAndDispatchRunnable.run(StreamEncoder.java:9)
    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by w109438907** [comment]
The aircraft is mini 3

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98327'>Zendesk ticket #98327</a>:<br><br>在 demo 中, CameraStreamDetailFragment.kt initViewModel 时 addReceiveStreamListener, 如果打开 demo 后快速进入 Multi-Video Decoding (CameraStreamManager - New) 会引起 crash，延迟一段时间进入则正常。 VideoStreamManager - Deprecated 调用 channel.addStreamDataListener 过早一样有这个问题。
-->有确认是完成了SDK的注册吗？
<br><p><em><small>°°°</small></em></p>

**Comment by w109438907** [comment]
注册成功回调已经调用，并且同一个节点，其它 API 例如 addFrameListener 就没有问题

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98327'>Zendesk ticket #98327</a>:<br><br>我已经提交给研发进行处理了，感谢您的反馈。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98327'>Zendesk ticket #98327</a>:<br><br>这个崩溃将会在5.9版本修复，你可以等待5.9版本发布之后进行升级以进行体验。
<br><p><em><small>°°°</small></em></p>
