### ISSUE TITLE
Add flying support with unlocked zones already installed and configured on the aircraft, without the need of having an active session with DJI account

### ISSUE THREAD

**Issue by LuisVargasVic** [dji-sdk/Mobile-SDK-Android-V5#241]
Hello DJI team

We wanted to elevate the request to add flying support with unlocked zones already installed and configured on the aircraft, without the need of having an active session with DJI account on MSDK v5, same as v4 had.

The reasoning mainly is that we often fly in offline mode for compliance and security reasons, but also need to get the best of what MSDK v5 brings that is not available on v4.

Do you have a timeline for this already? Thanks!

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/98466'>Zendesk ticket #98466</a>:<br><br>We apologize for the inconvenience. At the moment, we have not yet planned for this feature. However, we would appreciate it if you could kindly provide us with your feature request. https://sdk-forum.dji.net/hc/en-us/requests/new
<br><p><em><small>°°°</small></em></p>
