### ISSUE TITLE
MSDK5.8.0，开发的负载相机(h264)无法预览视频

### ISSUE THREAD

**Issue by TsClown** [dji-sdk/Mobile-SDK-Android-V5#243]
MSDK5.8.0，使用ICameraManager预览视频FPV正常，官方的云台正常。开发的负载相机无法预览视频
使用PSDK开发的视频流(DJI_CAMERA_VIDEO_STREAM_TYPE_H264_CUSTOM_FORMAT)在Pilot 2上正常显示，但是在MSDK的demo(Sample-V5)中显示黑屏。
无人机： M350 RTK (09.00.0503)
遥控器：DJI RC Plus (02.02.0803)
问题版本：MobileSdk5.8.0;PSDK3.8.0
主要报错信息:
17:36:57.132 7517-7517 DJIV5/RXUtil com.dji.sampleV5.aircraft E (onFailure:1) FetchWidgetFile-onFailure ErrorImp{errorType='CORE', errorCode='INVALID_REQUEST_IN_CURRENT_STATE', innerCode='', description='null', hint='error code = -13'}
17:36:57.132 7517-7517 DJIV5/co_c@2d9779f com.dji.sampleV5.aircraft E (co_a:17) initPSDKDevice error，componentIndex=0，ErrorImp{errorType='CORE', errorCode='INVALID_REQUEST_IN_CURRENT_STATE', innerCode='', description='null', hint='error code = -13'}
17:36:57.154 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.183 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.213 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.254 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.283 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.314 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.343 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.374 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found
17:36:57.414 7517-7678 StreamObserver com.dji.sampleV5.aircraft W (co_a:67) （LEFT_OR_MAIN） Need to wait for keyframes: frameIndex not found

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98656'>Zendesk ticket #98656</a>:<br><br>我们有收到其他开发者类似的问题反馈，正在验证5.8版本是否存在这个问题。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98656'>Zendesk ticket #98656</a>:<br><br>我们复现到这个问题，已经提交给研发进行分析了。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98656'>Zendesk ticket #98656</a>:<br><br>CUS H264无法在MSDK上播放的问题已经在5.9版本修复，您可以等待5.9版本发布之后进行更新和体验。
<br><p><em><small>°°°</small></em></p>
