### ISSUE TITLE
DJI RC Pro Enterprise 5.8.0 example code 

### ISSUE THREAD

**Issue by hyunah96** [dji-sdk/Mobile-SDK-Android-V5#244]
Hi, I'm studying the Mobile-SDK-Android-V5 example code. 
While studying, I found some errors. 
1. my DJI RC Pro Enterprise is connected to the PC, but the example app shows unknown (in Android Studio it says it is connected fine, and when I build the example app, the app runs on the DJI RC Pro Enterprise controller, but the example app shows unknown).
DJIMainActivity.kt 
```
text_view_product_name.text = StringUtils.getResStr(R.string.product_name, it.productType.name)
```
2. keystore exception android.os.ServiceSpecificException: (code 7) An error occurred. 
I can't find the cause of this error. 
Thank you for your help.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/98670'>Zendesk ticket #98670</a>:<br><br> We kindly suggest that you refer to the following article: https://sdk-forum.dji.net/hc/en-us/articles/5983558993433-Chapter-2-The-Sample to check if there are any issues with your operating process. Additionally, please ensure that your Android Studio version is compatible with MSDK 5.8. We recommend verifying your Android Studio version to be 2022.3.1.
<br><p><em><small>°°°</small></em></p>
