### ISSUE TITLE
After importing sdk...

### ISSUE THREAD

**Issue by ersien** [dji-sdk/Mobile-SDK-Android-V5#245]
The project is using an incompatible version (AGP 7.4.2) of the Android Gradle plugin. Latest supported version is AGP 7.2.1

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98937'>Zendesk ticket #98937</a>:<br><br>You are using an unsupported version of Android Studio for AGP 7.4.2. To resolve this, you will need to update your Android Studio to the latest version.
<br><p><em><small>°°°</small></em></p>
