### ISSUE TITLE
Question. Directory name and file name for photo in action.

### ISSUE THREAD

**Issue by Tin-moon** [dji-sdk/Mobile-SDK-Android-V5#246]
Hi, tell me how to set the folder name for photo? I generate mission file with actions? I try this way, but nothing changes:

    private fun transTakePhoto(fileSuffix: String = "", directoryName: String = ""): WaylineActionInfo {
        val payloadLensIndex = mutableListOf<CameraLensType>()
        payloadLensIndex.add(CameraLensType.WIDE)
        payloadLensIndex.add(CameraLensType.IR)

        val payloadPositionIndex = 0

        val param = ActionTakePhotoParam(payloadPositionIndex, true, payloadLensIndex, fileSuffix)
        param.payloadPositionIndex = payloadPositionIndex

        val customDirNameParam = ActionCustomDirNameParam(payloadPositionIndex, directoryName)
        customDirNameParam.payloadPositionIndex = payloadPositionIndex

        val info = WaylineActionInfo()
        info.actionType = WaylineActionType.TAKE_PHOTO
        info.customDirNameParam = customDirNameParam
        info.takePhotoParam = param
        return info
    }

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/98970'>Zendesk ticket #98970</a>:<br><br>In order to achieve the desired outcome, it is recommended that you configure two waypoint actions. The first waypoint action should involve creating a folder, while the second waypoint action should involve taking a photo. By doing so, the captured photos will be automatically saved into the folder created by the first waypoint action.
<br><p><em><small>°°°</small></em></p>

**Comment by Tin-moon** [comment]
Thanks

**Comment by Tin-moon** [comment]
@dji-dev Can I create complitly custom name? without prefix "DJI_yyyyMMddhhmm_nnn_" ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/98970'>Zendesk ticket #98970</a>:<br><br>We apologize for the inconvenience, but we regret to inform you that we do not support fully customizing photo names. However, you can only add a photo suffix.
<br><p><em><small>°°°</small></em></p>

**Comment by Tin-moon** [comment]
@dji-dev Hi, ok. I asked about the folder :), but I understand it’s also not possible?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/98970'>Zendesk ticket #98970</a>:<br><br>Sorry. It is also not possible.
<br><p><em><small>°°°</small></em></p>
