### ISSUE TITLE
Mini 3 Pro KeyStopTakeoff returns SYSTEM_ERROR

### ISSUE THREAD

**Issue by goggle555** [dji-sdk/Mobile-SDK-Android-V5#247]
When I run the sample app `StopTakeoff` on Mini 3 Pro, it returns an error and does not stop takeoff.

Error:
```
18:08:06:StartTakeoff 【ACTION】 == result: success
18:08:08:StopTakeoff 【ACTION】 == ActionErrorMsg==ErrorImp{errorType='CORE', errorCode='SYSTEM_ERROR', innerCode'', description='null', hint='error code = -7'}
```

Is there any way to resolve the error?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/99103'>Zendesk ticket #99103</a>:<br><br>We would like to inform you that it is not possible to immediately call the stopTakeoff command after invoking the startTakeoff command. It is necessary to ensure that the aircraft has already commenced the takeoff procedure before it can be stopped.
<br><p><em><small>°°°</small></em></p>

**Comment by goggle555** [comment]
OK :-)
I will check if there is a way to check the takeoff procedure and try again.
