### ISSUE TITLE
Question about Exposure and ISO

### ISSUE THREAD

**Issue by w109438907** [dji-sdk/Mobile-SDK-Android-V5#248]
无人机: mini3

问题：默认情况下，ExposureModeRange 返回值仅有一个元素 [PROGRAM],  但如果用户在 DJI FLY 中通过右下角按钮 pro 模式下设置 ISO 后，ExposureMode 会被设置成 [MANUAL]，经测试，ExporesureMode 可以被 set 成任意模式，且能设置成功。请问这是一种符合预期的行为吗?

复现: 可以将 ExposureMode 设置成 [MANUAL]，打开 Uxsdk 中的 Exposure Mode Setting Widget 和 Exposure Setting Panel ，可以正常拖动设置 ISO，但是点击 AUTO 后无法恢复成 MANUAL.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99258'>Zendesk ticket #99258</a>:<br><br>想和您确认一下是KeyExposureModeRange在mini 3上会稳定推送[PROGRAM]吗？你使用的是最新的5.8版本吗？能否在sample上通过Key复现到?
<br><p><em><small>°°°</small></em></p>

**Comment by w109438907** [comment]
1. KeyExposureModeRange在mini 3上稳定推送[PROGRAM]
2. SDK 5.8.0 1441
3. Sample 上可以通过 key / value 复现: EXposureMode set 除 UNKONWN 外任意值均可成功， ExposureModeRange get 则仍然只有 [PROGRAM]

另外，请问 V5 上有类似 V4 DJISDKManager.USB_ACCESSORY_ATTACHED 的尝试连接 API 吗?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99258'>Zendesk ticket #99258</a>:<br><br>请问 V5 上有类似 V4 DJISDKManager.USB_ACCESSORY_ATTACHED 的尝试连接 API 吗?  -- 目前给出的接口是没有的。


1. KeyExposureModeRange在mini 3上稳定推送[PROGRAM]
2. SDK 5.8.0 1441
3. Sample 上可以通过 key / value 复现: EXposureMode set 除 UNKONWN 外任意值均可成功， ExposureModeRange get 则仍然只有 [PROGRAM]
-->我将会在mini 3上进行测试，麻烦等待一段时间。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99258'>Zendesk ticket #99258</a>:<br><br>我复现到了这个问题，已经反馈给团队。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99258'>Zendesk ticket #99258</a>:<br><br>这个问题已经在5.9版本修复了。等待5.9正式版本发布之后，你们可以更新进行体验。
<br><p><em><small>°°°</small></em></p>
