### ISSUE TITLE
Creating a project with MSDK V4.16.1 and MSDK V5

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#25]
After i resolve all the conflicts i am left with:
Duplicate class com.secneo.sdk.Helper found in modules dji-sdk-v5-all-5.0.0-runtime.jar (com.dji:dji-sdk-v5-all:5.0.0) and jetified-dji-sdk-4.16.1-runtime.jar (com.dji:dji-sdk:4.16.1)

how do i fix that?

**Comment by DJI-William** [comment]
The mSDK 4.16.1 and MSDK v5 cannot exist together, which means you have to re-write a new app if you already have a v4 app. Please read this article, [Chapter 1 - Hello, MSDK V5!](https://sdk-forum.dji.net/hc/en-us/articles/5976502476441-Chapter-1-Hello-MSDK-V5-)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/68688'>Zendesk ticket #68688</a>:<br><br>Chapter 1 - Hello, MSDK V5!
<br><p><em><small>°°°</small></em></p>

**Comment by MichHighlander** [comment]
Is it possible to do something about it? i think it would help a good sum of developers

**Comment by DJI-William** [comment]
No, their base structure is the same, v5 is refactored by v4.
