### ISSUE TITLE
MSDK 5.8.0 M30T机型 调用MediaFile.pullOriginMediaFileFromCamera()多次失败，甚至一直失败

### ISSUE THREAD

**Issue by caibiPro** [dji-sdk/Mobile-SDK-Android-V5#253]
- 机型：M30T
- SDK版本：MSDK 5.8.0
- 问题场景：从 UP_TO_DATE 的 MediaFileListData 中拿到了需要的MediaFile，再调用pullOriginMediaFileFromCamera()时，几乎每一次任务中都会有一到两张照片会失败2～3次后才成功，甚至有出现过反复失败的情况。
- 错误代码：errorErrorImp{errorType='SDK', errorCode='-3', innerCode='null', description='null', hint='null'}
- 回滚到MSDK 5.7.1 时基本不会出现这个问题

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99406'>Zendesk ticket #99406</a>:<br><br>-3代表的是超时。是否有稳定出现失败的复现方法呢？

对于MediaFileListData，MediaFileListState会在拍照完成后从updating变为UP_TO_DATE ，这是可以直接在MediaFileListData拿到最新的媒体文件，不需要调用pullOriginMediaFileFromCamera。pullOriginMediaFileFromCamera在MediaFileListState为IDLE的时候用于刷新文件列表。
<br><p><em><small>°°°</small></em></p>

**Comment by caibiPro** [comment]
操作步骤就是正常的调用拉取原始航片，只不过在5.8中超时错误出现的概率大大增加了。
因为在pullOriginMediaFileFromCamera失败的回调中会重新拉取，经常在一个飞行任务中有一两张会重试多次
回退到5.7.1则基本没有这个问题。

另外，我就是通过最新的MediaFIleListData.getData()拿到新的MediaFile集合，但我需要原始文件保存到设备中，按官方文档的说法：

> “从相机中拉取原始的多媒体文件，拉取下来的多媒体文件会在回调方法中返回给开发者使用。MSDK不会在内存中保存原始的多媒体文件，你可以根据需要保存原始的多媒体文件。 ”

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99406'>Zendesk ticket #99406</a>:<br><br>操作步骤就是正常的调用拉取原始航片，只不过在5.8中超时错误出现的概率大大增加了。
因为在pullOriginMediaFileFromCamera失败的回调中会重新拉取，经常在一个飞行任务中有一两张会重试多次
回退到5.7.1则基本没有这个问题。
-->可以给到我们一个对应出现多次pullOriginMediaFileFromCamera超时的CSDK日志并告诉我们超时的时间吗？

CSDK日志存储的位置可以查看这篇文章：https://sdk-forum.dji.net/hc/zh-cn/articles/7296380174105-%E5%A6%82%E4%BD%95%E5%AF%BC%E5%87%BAMSDK-V5%E7%9A%84%E6%97%A5%E5%BF%97

日志可以上传到这个链接：https://pan-sec.djicorp.com/s/xSPs4NFwSLiieq4  密码是dji123
<br><p><em><small>°°°</small></em></p>
