### ISSUE TITLE
We are building a widget App to work over the DJI App

### ISSUE THREAD

**Issue by Grandpasoul** [dji-sdk/Mobile-SDK-Android-V5#256]
We want to get some data from the SDK. We installed the sdk on our widget app. This is just an app which take screenshots, but now we want to get some data from our drones. The problem is that the widget alone gets the data, but when we want to open it with the remote control DJI app, the widget+sdk returns all the data null or 0. 

I think this is a API Key problem. The remote is linked to just 1 app and the SDK cannot receive the data from 2 different apps.

So we have 2 questions:

1.- Is there a way to have the SDK working in our app in pararell with the DJI app?
2.- Is there a way to get the data from the DJI app through our app without the SDK?

We tested our app with Enterprice 3T Drone.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99654'>Zendesk ticket #99654</a>:<br><br>1.- Is there a way to have the SDK working in our app in pararell with the DJI app?
-->Currently, only the foreground app can access data in the App developed with MSDK and DJI App.

2.- Is there a way to get the data from the DJI app through our app without the SDK?
-->The DJI App cannot be developed further. However, if you are looking to access the data displayed on the DJI App, you might be able to obtain it through image analysis. Additionally, the DJI App supports HDMI to output the remote controller's screen to other devices.
<br><p><em><small>°°°</small></em></p>
