### ISSUE TITLE
你们xml能预览吗？我预览不了太难受了

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android-V5#257]
你们xml能预览吗？我预览不了太难受了

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/99840'>Zendesk ticket #99840</a>:<br><br>您说的是什么不能预览。APP的页面布局吗？
<br><p><em><small>°°°</small></em></p>

**Comment by SJJ-dot** [comment]
是的，在Android studio 预览布局
&nbsp;


978622005
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月25日(星期四) 中午11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dji-sdk/Mobile-SDK-Android-V5] 你们xml能预览吗？我预览不了太难受了 (Issue #257)





 
Agent comment from Hummels Lei in Zendesk ticket #99840:

您说的是什么不能预览。APP的页面布局吗？
 


°°°
