### ISSUE TITLE
Gimbal Yaw Output is relative to true north

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#259]
The SDK documentation suggests that all values set by `GimbalAngleRotation` are relative to the body frame of the Gimbal.
![Screenshot 2024-01-25 at 12 13 15 PM](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/11700939/fcfdf4fc-83cb-40f1-a277-609102a09074)

When listening to the values output for `KeyGimbalAttitude`, the `pitch` and `roll` are relative to the body frame. However for the yaw the values it appears the values are relative to true north. Is this expected behaviour?

```kotlin

gimbalAttitudeKey.listen(this) {
    scope.launch {
        if (it is Attitude) {
            println(it.pitch) // degrees relative to gimbal body frame
            println(it.roll) // degrees relative to gimbal body frame
            println(it.yaw)  // degrees relative to relative to true north
        }
    }
}
```

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/ccd135c9-0125-4dfc-a11f-a9700e6a200d)
You can take a look at the description of KeyGimbalAttitude. It does indeed reference the true north direction in the obtained attitude.

**Comment by brien-crean** [comment]
> You can take a look at the description of KeyGimbalAttitude. It does indeed reference the true north direction in the obtained attitude.

Thank you for the information, I missed that detail in the docs!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99949'>Zendesk ticket #99949</a>:<br><br>I'm glad I could help you.
<br><p><em><small>°°°</small></em></p>
