### ISSUE TITLE
DJI Dock simulation 

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#261]
Hi DJI,

I want to start using DJI Dock and I need to test it with simulating missions. Is there any software like DJI Assistant 2 to simulate the flight of DJI Dock?

**Comment by dji-dev** [comment]
Agent comment from yuhang.wang in <a href='https://djisdksupport.zendesk.com/agent/tickets/100303'>Zendesk ticket #100303</a>:<br><br>Hi，

We currently do not offer similar software.

When issuing a route mission, you can set the simulate_mission attribute. When this attribute is set to 1, the drone will report model flight data, but will not actually take off.

Best Regards,
DJI Developer Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/XUoqFqCzIzf0r9bgh6X4Bz2HU' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>
