### ISSUE TITLE
Photo/video toggle button not working (RC-N1 remote controller)

### ISSUE THREAD

**Issue by mitchrsm** [dji-sdk/Mobile-SDK-Android-V5#262]
Drone: Mini 3 pro
Remote: RC-N1
MSDK 5.8
software: SampleCode-V5

issue:
pressing the photo/video toggle button on the remote control nothing happens.
Furthermore, if the camera is in video mode, pressing the shutter button on the remote control does not start recording but switches to photo mode.

using the dji fly app with the same hardware, however everything works fine (toggle button switches between photo/video mode and shutter button starts/stops recording in video mode)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100501'>Zendesk ticket #100501</a>:<br><br>I think you are referring to the CameraControlWidget provided by UXSDK. This widget is not compatible with the mini 3 series. Could you please confirm if the camera mode changes when you press the button?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by mitchrsm** [comment]
I'm referring to the physical button on the RC-N1, the photo-video toggle button does nothing. I have yet to try but I think I should programmatically read the button press and change from video to photo mode and vice versa.
But what worries me the most right now is the physical button on the RC-N1 that is supposed to take photos in photo mode and start/stop recording in video mode. If I press it in video mode it doesn't start recording but it switches to photo mode and I don't know how to prevent it from doing so.
In the 4.x version of the MSDK there was "void setShootPhotoAndRecordButtonBindingEnabled(boolean enabled, final CompletionCallback callback)" but I didn't find the counterpart in the 5.8 MSDK (maybe I didn't look hard enough?)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100501'>Zendesk ticket #100501</a>:<br><br>I'm referring to the physical button on the RC-N1, the photo-video toggle button does nothing.
--->This is exactly what I said, the UXSDK controls are not compatible with RC-N1. For the mode switch button, you can listen to the button status using RemoteControllerKey.KeyRCSwitchButtonDown and then manually switch between photo and video modes. As for the photo and video buttons, you can listen to their status using RemoteControllerKey.KeyShutterButtonDown and then implement the shooting function.
<br><p><em><small>°°°</small></em></p>

**Comment by mitchrsm** [comment]
I didn't realize that it was the CameraControlWidget that created the problem, once removed there are no longer any strange behaviors with the RC Buttons

Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100501'>Zendesk ticket #100501</a>:<br><br>I'm glad you resolved the issue. I hope our response was helpful to you.
<br><p><em><small>°°°</small></em></p>
