### ISSUE TITLE
DJI MSDK 5.7 can't take off

### ISSUE THREAD

**Issue by naturalmechanics** [dji-sdk/Mobile-SDK-Android-V5#264]
I have this code:

```
FlightControllerKey.KeyStartTakeoff.create().action({
    Log.d("takeoff","TakeOff Success")
}, { e: IDJIError ->
    Log.d( "takeoff","DJI Takeoff error: " + e.description())
})

```

This does not work, and the error message is null. I also tried with this:

```

KeyManager.getInstance().performAction(KeyTools.createKey(FlightControllerKey.KeyStartTakeoff),


        object: CommonCallbacks.CompletionCallbackWithParam<EmptyMsg> {
            override fun onSuccess(
                    nil: EmptyMsg
            ) {
                Log.i(
                        "Monsoon Action",
                        "Taking off"
                )
            }

            override fun onFailure(
                    error: IDJIError
            ) {
                Log.i(
                        "Monsoon Action",
                        "Takeoff failed $error"
                )
            }
        }

        )

```

I get: **Takeoff failed ErrorImp{errorType='CORE', errorCode='SYSTEM_ERROR', innerCode='', description='null', hint='error code = -7'**

I also tried:

```
FlightControllerKey.KeyStartTakeoff.create().action({
    Log.d("Monsoon Command Execution : ", "takeoff success!")

}, { e: IDJIError ->

    val d = e.description()

   Log.d("Monsoon Command Execution : ", "takeoff error! $d")

})
```

I get **takeoff error ! null**

I am using MSDK V 5.7

Why do I get this kind of errors? Please, I need a quick solution. Thank you.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/100765'>Zendesk ticket #100765</a>:<br><br>Have you tried our sample code? Can you control the takeoff of the aircraft by calling KeyStartTakeoff with the sample code?
<br><p><em><small>°°°</small></em></p>

**Comment by naturalmechanics** [comment]
yes, i have. It does not work. Do I need to set the remote controller in a specific mode? Thank you

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/100765'>Zendesk ticket #100765</a>:<br><br>Could you please provide information on the aircraft you are using and the country where it was tested? Additionally, we recommend upgrading the aircraft firmware and SDK version to the latest available versions and try again.
<br><p><em><small>°°°</small></em></p>

**Comment by liyuanwu1** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #100765](https://djisdksupport.zendesk.com/agent/tickets/100765):Could you please provide information on the aircraft you are using and the country where it was tested? Additionally, we recommend upgrading the aircraft firmware and SDK version to the latest available versions and try again.
> 
> _°°°_
Normally, the above three codes, which can take off successfully?
