### ISSUE TITLE
Capture button not working 

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#267]
In Mavic 3 Enterprise capture button is not working when we record video like Dji Pilot 2,
when user take video he has also capture image but in our SDk this functionality  is not working in my app?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100842'>Zendesk ticket #100842</a>:<br><br>I have reproduced this issue and have already reported it to the team for confirmation. As for shooting during the recording process, you can try calling the shooting interface.
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
how should we use  shooting interface.

**Comment by 1232Ga** [comment]
we are using Widget of MSDK 5 then how to implement Shooting interface

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100842'>Zendesk ticket #100842</a>:<br><br>The functionality you are looking for is not available in the widget provided by MSDK V5. You will need to add it yourself. The interface for shooting is CameraKey.KeyStartShootPhoto.

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
ok Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100842'>Zendesk ticket #100842</a>:<br><br>I hope this was helpful to you.
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
sorry for that but i have quetion where we use this function in code, normal capture mode is working but when taking video capture is working then where we this method CameraKey.KeyStartShootPhoto.?
can you explain it or send me a bit code so i will use this on video taken time?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100842'>Zendesk ticket #100842</a>:<br><br>The camera of your Mavic 3 Enterprise supports taking photos while recording, so even in recording mode, you can still use CameraKey.KeyStartShootPhoto to take photos once the camera has started recording. This allows you to achieve the same effect as pressing a button on the remote controller.

I suggest setting up a button that is only visible in recording mode to trigger the photo capture action. Additionally, CameraKey.KeyIsRecording can be used to determine if the camera is currently recording.
<br><p><em><small>°°°</small></em></p>
