### ISSUE TITLE
Where is the documentation for the UXSDK library?

### ISSUE THREAD

**Issue by ernesto-oliva** [dji-sdk/Mobile-SDK-Android-V5#268]
I would like to have access to something like a guide and/or documentation about the UXSDK library. So far I used to use the example project as a guide and tried to replicate what was there but this turns out to be insufficient. For example, I am having a very specific problem because I do very specific things in my application and I suspect that maybe there is something I am missing, something that a documentation could tell.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100868'>Zendesk ticket #100868</a>:<br><br>The UXSDK library does not have dedicated documentation. However, this library is open source, so if you have any questions, you can directly refer to the code.
<br><p><em><small>°°°</small></em></p>
