### ISSUE TITLE
Compass showing off during flight

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android-V5#269]
Hi Team,

I have integrated your MSDK in our app, during flight compass showing off. I have attached a screenshot below kindly review once.
![MicrosoftTeams-image_1](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/40540336/e2124b90-9e75-43e2-97c9-b600e4fe1e98)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100964'>Zendesk ticket #100964</a>:<br><br>Do you have the obstacle avoidance feature enabled when performing tasks? Here, "OFF" refers to turning off the obstacle avoidance feature, not the compass.
<br><p><em><small>°°°</small></em></p>
