### ISSUE TITLE
Replacement for getFlightController().sendVirtualStickFlightControlData()

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#27]
Is there a replacement for getFlightController().sendVirtualStickFlightControlData() from MSDK v4?
I know that there is VirtualStickManager.getLeftStick(). setVerticalPosition() but i see the values are not in m/s but are from -660 to 660.

**Comment by DJI-William** [comment]
Yes, please have a read this article, [Chapter 6: The virtual stick](https://sdk-forum.dji.net/hc/en-us/articles/8697869415577-Chapter-6-The-virtual-stick).
