### ISSUE TITLE
Query on Wireless Connection Support for M350 and M300 in SDK v5.x.x

### ISSUE THREAD

**Issue by gongelosP** [dji-sdk/Mobile-SDK-Android-V5#270]
Hello,

I am currently working with SDK version 4.x.x, which, to my understanding, does not support wireless connections between the tablet and the controller for the DJI M350 and M300 drone models. I've been searching for information regarding the capabilities of SDK version 5.x.x, specifically whether it introduces support for wireless connections with these drone models, but have not found clear documentation on this matter.

Could anyone provide insights or direct me to resources where I can find detailed information about wireless connection support for the M350 and M300 in SDK v5.x.x? Understanding this capability is crucial for our project's development and planning.

Thank you for your assistance.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100989'>Zendesk ticket #100989</a>:<br><br>There is no wireless connection channel provided on the SDK between mobile devices and remote controllers.
If you want to achieve wireless communication between a tablet and a remote controller, I do have a way to do it, but it is not possible to directly wirelessly control a drone from the tablet. You need to at least develop an app using MSDK installed on the remote controller to control the drone through it.
<br><p><em><small>°°°</small></em></p>

**Comment by gongelosP** [comment]
Hey Yating Liao,

What i'm trying to achieve, is what is shown on this image. Currently i know the MSDK v4.x.x (which is the one we are currently using) doesn't support this for the M350 and M300 models. What i'm trying to figure it out if the MSDK v.5.x.x does support this for this drone models

<img width="207" alt="Screenshot 2024-02-26 at 09 39 32" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/22461241/c82a9b51-ce4e-4324-9103-d2d28c29b241">

**Comment by dji-lyt** [comment]
MSDK 4.17 already supports M350 and M300. For the communication method between MSDK v5 and the aircraft, you can refer to the images provided on the MSDK V5 official website below.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/4f16c5f6-fcdc-4ce6-8a71-4219c65e85a9)
The SDK does not provide a method to connect to WiFi and a remote control. However, you can design a transmission method so that commands sent from a mobile device are ultimately transmitted to the remote control, and then use the MSDK to execute them, for example, by transmitting commands over the internet.

**Comment by gongelosP** [comment]
Hey thanks for the response,

The MSDK doesn't provide any way to communicate wireless with the controller either with 4.x.x or 5.x.x? I'm trying to achieve a wireless connection between the Mobile device with the DJI remote controller with M350 and M300. Reading the documentation i see this is possible for some device (see image attached), i want to make sure if this is possible or not with the MSDK for the M300 and M350 wither either 4.x.x or 5.x.x.

Seeing the documentation (https://developer.dji.com/mobile-sdk/documentation/introduction/mobile_sdk_introduction.html) of the SDK V5.x.x.
<img width="880" alt="Screenshot 2024-02-27 at 10 20 40" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/22461241/d6887f9c-a6aa-44ba-9a7c-96358066de93">

**Comment by dji-lyt** [comment]
The article actually lists which models support WIFI and remote control connection, but M300 and M350 do not support this feature, so there are no supported interfaces in the SDK.

**Comment by gongelosP** [comment]
Hey, thanks for the response.

Yeah i see what you say, but also the M350 and M300 is not mention in any of the three list, so i wanted to confirm where there would be in this columns.

Regards

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100989'>Zendesk ticket #100989</a>:<br><br>I understand your intention. M300 and M350 indeed do not support this type of connection, and there are relatively few models that support WiFi connection.
<br><p><em><small>°°°</small></em></p>
