### ISSUE TITLE
Text Remove From Map

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#271]
How to change Name  on map on mavic3 Enterprise , attaching screenshot below
![mapmedia1](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/e6bfba9c-1b17-43ed-bd70-c26c18a5b88b)
![mapmedia2](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/29b021f3-614b-4943-903f-4416855e5183)

**Comment by 1232Ga** [comment]
change text in English language

**Comment by dji-lyt** [comment]
Could you please inform me of the country you are currently located in?

**Comment by 1232Ga** [comment]
india

**Comment by dji-lyt** [comment]
AMap provides the setMapLanguage interface to set the language type. You can try modifying the map control logic of UXSDK to add the map language setting.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/2c2ddb70-f0f2-40bf-a692-ae713c76db10)
You can try using MaplibreMap if you are in India.

**Comment by Vickyxdev** [comment]
Thanks... It works

**Comment by 1232Ga** [comment]
![MicrosoftTeams-image (26)](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/8235dc88-9542-4507-ad11-9310b4e3c079)
how to change this one

**Comment by 1232Ga** [comment]
change this one to English  language

**Comment by 1232Ga** [comment]
sateleitemap.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                map.setMapType(MaplibreMapDelegate.MapType.HYBRID);
                
            }
        });
        
        also when i am changing the map on icon click map name again remove English name

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101030'>Zendesk ticket #101030</a>:<br><br>I couldn't find a way to switch languages for the Amap icon, and it also doesn't support hiding. You can reach out to Amap's technical support for assistance.

After switching the map type, the language reverted to Chinese. Would resetting the map language be effective? The UXSDK widget is an open-source control that you can modify according to your needs.
<br><p><em><small>°°°</small></em></p>
