### ISSUE TITLE
Convert Feet to meter

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#272]
How to change compass value from ft to m ,
![MicrosoftTeams-image (25)](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/9b0c8bfd-1bf9-407a-8446-c194b5c232ee)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101031'>Zendesk ticket #101031</a>:<br><br>You need to modify the code of the AttitudeDashBoard control, below is the function that determines the unit to use. UnitUtils.UnitType.METRIC indicates the use of meters as the unit.


    protected String getAttributeUnit() { return UnitUtils.getUintStrByLength(UnitUtils.isMetricUnits() ? UnitUtils.UnitType.METRIC : UnitUtils.UnitType.IMPERIAL);}
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
Thanks its working fine

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101031'>Zendesk ticket #101031</a>:<br><br>I'm glad this has been helpful to you.
<br><p><em><small>°°°</small></em></p>
