### ISSUE TITLE
Waypoint mission does not start.

### ISSUE THREAD

**Issue by lukasz-bialek** [dji-sdk/Mobile-SDK-Android-V5#273]
Drone does not move after starting a kmz mission on Mavic 3E.

Last log in logcat has these values, but I cannot decode them: 

"lastMissionExcuteResult":5,"errorCode":48

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/101225'>Zendesk ticket #101225</a>:<br><br>Have you attempted to run your KMZ file in our sample code? Did you encounter any errors during the process?
<br><p><em><small>°°°</small></em></p>

**Comment by lukasz-bialek** [comment]
Yes, most of the time kmz missions run fine. But sometimes the drone is in a weird state, that after sending the kmz the mission does not start. The only weird thing in the logs is what I pasted. 

What does it mean?
"errorCode":48
"lastMissionExcuteResult":5,

It's in the logs from SDK V5.8 so I cannot track it.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/101225'>Zendesk ticket #101225</a>:<br><br>I kindly ask if you have the complete log available. If possible, could you also please export the CSDK logs?
<br><p><em><small>°°°</small></em></p>
