### ISSUE TITLE
Can't get the code to do anything

### ISSUE THREAD

**Issue by openSourceBugs** [dji-sdk/Mobile-SDK-Android-V5#274]
A problem occurred evaluating root project 'android-sdk-v5-sample'.
> Plugin with id 'com.android.application' not found.

**Comment by openSourceBugs** [comment]
I donwloaded and installed a fresh copy of android studio hedgehog and it this error happens when i try to sync gradle.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101238'>Zendesk ticket #101238</a>:<br><br>When importing the project, you need to select the 'android-sdk-v5-as' folder.
<br><p><em><small>°°°</small></em></p>

**Comment by openSourceBugs** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/5646010/b6256600-ee85-4b90-be7b-90cb829524bf)
there's something else going on with outdated gradle plugins.  Can you please state all of the supported versions of software that are required?  Gradle versions, Java versions etc?

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/eba67230-0961-4b65-abec-c1c4150bb5b6)
Here is the recommended version.
