### ISSUE TITLE
Drone Status

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#275]
when I fly Mavic 3 Enterprise drone from our app it is showing "Altitude Limit" in place of "Ready to Go"  in MSDK V5
and when I connect Drone in house not to fly then it is showing Ready to Go. What is the issue behind this

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101604'>Zendesk ticket #101604</a>:<br><br>”Altitude Limit" only appears when the drone has obtained the current location information and there is a height limit at the current location. It indicates that there is a height restriction in this area, but it does not affect the takeoff of the aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by 1232Ga** [comment]
Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101604'>Zendesk ticket #101604</a>:<br><br>I hope this is helpful to you.
<br><p><em><small>°°°</small></em></p>
