### ISSUE TITLE
Sample app connection problem

### ISSUE THREAD

**Issue by ersien** [dji-sdk/Mobile-SDK-Android-V5#277]
![WhatsApp Image 2024-02-28 at 15 07 26](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/2394112/333360a1-e285-45f2-99df-76633fad1949)
Hi, as you see in this image, i used sdk and built an apk.
Now i am trying to connect it.
It gives error : "Unable to takeoff"
Another strange message : "Remote controller not connected/still approving connection situation."

I do not understand, if it is not connected, how do I see camera stream and turn camera right left up down ?

Another thing is ; whenever I run the app , I see an android notification like "Another
Analyzing head dump"

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101709'>Zendesk ticket #101709</a>:<br><br>Could you please show me how DJI FLY performs?
<br><p><em><small>°°°</small></em></p>

**Comment by ersien** [comment]
Ok, I set up dji fly app, it wanted to re-sync between remote controller and drone. After that, both, dji fly and my sdk app worked!
Thank you so much!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101709'>Zendesk ticket #101709</a>:<br><br>I'm glad that my response was able to help you.
<br><p><em><small>°°°</small></em></p>
