### ISSUE TITLE
Ability to programmatically limit the horizontal speed for M300 / M350 in normal mode

### ISSUE THREAD

**Issue by Qubiz** [dji-sdk/Mobile-SDK-Android-V5#278]
When using the Mavic 3T it is possible to limit the horizontal speed of the aircraft in 'normal' mode through the following key: 
```kotlin 
FlightControllerKey.KeyHorizCurSpeedInNormal
```

It seems that this functionality is not currently implemented for M300 / M350. 

Is there an alternative approach to limit the horizontal speed in normal mode for these drone types? Are there plans to add support for this? 

Also, what is the following key used for and how does it differ from the previously mentioned key?

```kotlin
FlightControllerKey.KeyHorizMaxSpeedInNormal
```

Thanks in advance.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101762'>Zendesk ticket #101762</a>:<br><br>The keys you listed are not officially open for use, so we have very little knowledge about them.
Moreover, we do not recommend using keys that are not officially open.
<br><p><em><small>°°°</small></em></p>

**Comment by Qubiz** [comment]
Ah okay. Are there any plans to add the ability to configure the expo / gain settings through the MSDK?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/101762'>Zendesk ticket #101762</a>:<br><br>The official opening time is still uncertain. However, my team and I have confirmed that FlightControllerKey.KeyHorizMaxSpeedInNormal should be usable. As for the issue with M300/M350 using FlightControllerKey.KeyHorizMaxSpeedInNormal resulting in failure, I speculate that M300/M350 does not support remote controller manipulation of custom settings, as I did not find these two models among the supported aircraft types.

Additionally, KeyVertVelUpInNormal is the setting for ascending speed, and KeyVertVelDownInNormal is for descending speed. On the Pilot 2, these correspond to the Gain&Expo Turning in the flight control settings.
<br><p><em><small>°°°</small></em></p>
