### ISSUE TITLE
V5 for Mavic Mini

### ISSUE THREAD

**Issue by vbui901** [dji-sdk/Mobile-SDK-Android-V5#282]
Does V5 work with Mavic Mini? I got DJIDeviceStatus CANT_TAKEOFF_NOVICE (Cannot take off (No GPS)). What does this mean?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102184'>Zendesk ticket #102184</a>:<br><br>MSDK V5 does not support Mavic Mini. Without GPS in NOVICE mode, the drone cannot take off. Please turn off NOVICE mode. DJI FLY will prompt you on how to do this.
<br><p><em><small>°°°</small></em></p>
