### ISSUE TITLE
When will the SDK support DJI mini 4 pro

### ISSUE THREAD

**Issue by gangwang2020** [dji-sdk/Mobile-SDK-Android-V5#284]
Currently our customer want to use DJI mini 4 pro with SDK, could you help confirm it?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/102251'>Zendesk ticket #102251</a>:<br><br>The specific timing for when the Mini 4 will be supported has not been determined yet. Please keep an eye on the developer's official website for updates.
<br><p><em><small>°°°</small></em></p>

**Comment by brantje** [comment]
An idea would be nice, can you give us a Q? Like Q3 2024?

**Comment by tdrone993** [comment]
Supposedly Q1 of this year but since the lack of progress who knows when!

**Comment by brantje** [comment]
@dji-lyt Closed? So the SDK is available? If so you do have a link?
