### ISSUE TITLE
Mavic 3T Rotates When Pause A Mission And Start Again

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#285]
Hi DJI,

I I trying to run a mission on different drones like M3T and M300 RTK. In my mission, when we arrive the first point, I rotate the drone and gimbal, then I pause the mission and ask user to confirm the camera pitch, if it is not aligned correctly they can change the pitch of the camera.

It completely works in M300 RTK, but in mavic, when I pause the mission and start it again, mavic rotates about 30 degree by it self (this rotation is not an action) and then continue the mission. 

This only happens in Mavic. What is the resean and how can I solve it?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/102483'>Zendesk ticket #102483</a>:<br><br>Different aircraft have slightly different flight logics. Have you considered adjusting the aircraft's attitude through waypoint actions at the first waypoint? This way, there would be no need to pause and resume the mission.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Yes, the first actions added to the wayline are rotating the camera and drone to the correct position. but sometimes because of some problems like GPS, the camera is not completely aligned with the target we want so we ask the user to modify or confirm it before starting the mission.

this strategy is completely working in M300 RTK, but as I said, in Mavic, when I pause the mission and start it again, suddenly, it rotates about 30 degrees and then starts the rest of the mission.

I want to know the reason and find the solution.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/102483'>Zendesk ticket #102483</a>:<br><br>As far as I know, for the Mavic 3, when resuming a wayline mission, the aircraft will reset to the state it was in when the mission was paused. So manual adjustments are ineffective. There are currently no plans to change this logic.
<br><p><em><small>°°°</small></em></p>
