### ISSUE TITLE
I want to make "mapbox" compatible with Japanese.

### ISSUE THREAD

**Issue by SeyamaKota** [dji-sdk/Mobile-SDK-Android-V5#286]
I would like to make "mapbox" compatible with Japanese. Is it not possible with "Mobile-SDK-Android-V5"? I can't find a method to change the language.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102530'>Zendesk ticket #102530</a>:<br><br>The Mobile-SDK-Android-V5 uses the MapLibre map.
I would recommend you to consult MapLibre's technical support to find out if it supports Japanese and how to set it up, as MapLibre is not a map software development kit developed by Mobile SDK.
<br><p><em><small>°°°</small></em></p>
