### ISSUE TITLE
Memory Card Encryption and Decryption

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#287]
In the MSDK v4 for the Mavic 2 Enterprise Drone in Android Studio, there is a callback method available for ejecting the memory card?? Please provide me the callback method....

**Comment by 1232Ga** [comment]
I want know callback method in MSDK V4(For Mavic 2 Drone) not for MSDK V5(Mavic 3 `Drone)...`

**Comment by dji-lyt** [comment]
Greetings!
MSDK V5 requires the use of the listen interface to set up callback monitoring.
The listen interface is KeyManager.listen. The Key it requires can be created using KeyTools,such as：
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/c33847dd-5c04-46d8-8a7b-9d547e51603a)

The Key corresponding to the Storage information is CameraKey.KeyCameraStorageInfos.

**Comment by 1232Ga** [comment]
how to implement in Mavic 2 Drone in MSDK V4

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102693'>Zendesk ticket #102693</a>:<br><br>You can set up a listener for the storage of the aircraft using Camera.setStorageStateCallBack.
<br><p><em><small>°°°</small></em></p>
