### ISSUE TITLE
NoClassDefFoundError while Running the Sample Code

### ISSUE THREAD

**Issue by ikanor** [dji-sdk/Mobile-SDK-Android-V5#289]
Hi there! I'm trying to run the sample project `android-sdk-v5-as`, and after a successful compilation, the app is exiting with an error:

     Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.v5.manager.SDKManager"

I am not very experienced in Android development but to my understanding the package is missing the dependencies. It indeed fails at the first reference of the SDK classes. I also tried debugging and evaluating any other expression using SDK classes (i.e.: `DJISDKInitEvent.INITIALIZE_COMPLETE`) also fails with the same error. 

I tried with the recommended version of Android Studio `2021.2.1.16`, but also with `2022.3.1.18` and `2023.2.1.23`, with the same result. I'm developing in Ubuntu Linux and an x86_64 architecture (`uname` returns `Linux 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`), which by the way forced me to enable said architecture in the `build.gradle` file:

```
diff --git a/SampleCode-V5/android-sdk-v5-sample/build.gradle b/SampleCode-V5/android-sdk-v5-sample/build.gradle
index 737d179..64f0e1b 100644
--- a/SampleCode-V5/android-sdk-v5-sample/build.gradle
+++ b/SampleCode-V5/android-sdk-v5-sample/build.gradle
@@ -16,7 +16,7 @@ android {
         manifestPlaceholders["AMAP_API_KEY"] = project.AMAP_API_KEY
         manifestPlaceholders["GMAP_API_KEY"] = project.GMAP_API_KEY
         ndk {
-            abiFilters 'arm64-v8a'
+            abiFilters 'arm64-v8a', 'x86_64'
         }
     }
```
I am using the latest code from main, and dependencies point to the 5.8.0 version of the SDK:

```
    deps.aircraft = "com.dji:dji-sdk-v5-aircraft:5.8.0"
    deps.aircraftProvided = "com.dji:dji-sdk-v5-aircraft-provided:5.8.0"
    deps.networkImp = "com.dji:dji-sdk-v5-networkImp:5.8.0"
```

I do have the target Android SDK version 33 downloaded and I'm using a Pixel 3a API 33 x86_64 virtual device to install and run the app. I might be missing something obvious here but I am all out of ideas, so any hints would be much appreciated. Thanks in advance!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102806'>Zendesk ticket #102806</a>:<br><br>When importing the project into Android Studio, did you choose android-sdk-v5-as?

However, we have not tested it on a Linux system. Do you have a device that supports Windows or MacOS around you? Could you test it on them?
<br><p><em><small>°°°</small></em></p>

**Comment by ikanor** [comment]
Thank you for your quick response!

I am indeed opening the `android-sdk-v5-as` folder, Android Studio seems to be detecting all dependencies properly:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/5469238/51940e29-d233-4590-a129-737d8472cc59)

I tried my luck with [this version](https://github.com/dji-sdk/Mobile-SDK-Android-V5/pull/169), which has a newer Gradle version and also is based in version 5.6 of the SDK, with the same result.
 
Following your advice I tried booting Windows, installed the latest Android Studio, only to get the exact same error.

My money is now on the `x86_64` architecture, but sadly I do not have a Mac with ARM architecture to try. Thank you for your help anyways! Your documentation is thorough and I enjoyed learning about the capabilities of our DJI drone. Cheers!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102806'>Zendesk ticket #102806</a>:<br><br>If you are using the latest version of Android Studio, you should be able to run the project under the dev-sdk-main branch directly.

We are glad that you are interested in DJI drones. Feel free to reach out to us if you have any questions.
<br><p><em><small>°°°</small></em></p>
