### ISSUE TITLE
Waypoint Mission Resume Issue

### ISSUE THREAD

**Issue by wmurmann** [dji-sdk/Mobile-SDK-Android-V5#290]
V5.8.0
Drone: M3T & M3E

Issue: When resuming a mission with the global waypoint param's yaw mode set to `WaylineWaypointYawMode.MANUALLY` the drone will override yaw adjustments during pause and reset the yaw to where it was prior to the pause.

In the past with MSDK v4 we would have the AUTO heading mode which carried the yaw adjustments over during the pause state when the waypoint mission was resumed. Is this intended behavior? If so is there a way to recreate the heading mode AUTO behavior on MSDK v5?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/103101'>Zendesk ticket #103101</a>:<br><br>When the M3 series aircraft resumes its wayline the orientation of the aircraft will be completely restored to the state before the pause. You will need to adjust the aircraft orientation using the virtual joystick after the wayline is resumed.
<br><p><em><small>°°°</small></em></p>
