### ISSUE TITLE
KeyGoHomeStatus only return IDLE during RTH

### ISSUE THREAD

**Issue by lleoncini** [dji-sdk/Mobile-SDK-Android-V5#291]
At SDK v5.8.0 the KeyGoHomeStatus is only returning IDLE from the listener or getter.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103110'>Zendesk ticket #103110</a>:<br><br>Could you please inform us about the drone you are using and provide instructions on how we can reproduce this issue?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by lleoncini** [comment]
I'm using a Mavic 3 Multispectral (V09.00.0505) with it DJI RC Pro (V02.01.0202).

The way to reproduce is just creating a listener and press the RTH button from the RC or by calling the return to home method from the SDK while fliying.

        FlightControllerKey.KeyGoHomeState.create().listen(holder = this) { goHomeState ->
           ...             
        }
               
        Or
        
        FlightControllerKey.KeyGoHomeState.create().get()

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103110'>Zendesk ticket #103110</a>:<br><br>KeyGoHomeStatus and KeyGoHomeState are two different keys. I did not encounter the issue you described when using KeyGoHomeStatus. The version used for testing was 5.8.
<br><p><em><small>°°°</small></em></p>

**Comment by lleoncini** [comment]
You're right, KeyGoHomeState is not in the documentation and it seems to not be doing anything but looks very similar (it appear in the auto complete). I have tested again with KeyGoHomeStatus and it works fine.

Actually KeyGoHomeStatus returns a GoHomeState so that make it more confuse.

Thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103110'>Zendesk ticket #103110</a>:<br><br>I am pleased that your issue has been resolved.
Hope you have a wonderful day！
<br><p><em><small>°°°</small></em></p>
