### ISSUE TITLE
Default layout always black

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android-V5#292]
I run the sample code, and clicked Default Layout button, but view stream display always black
- DJI Air 2S
- Pixel 4xl (android 13)

Main branch
![Screenshot_20240320_092356](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/46671455/df1f9fb4-f9db-4b0c-9bf6-025b52c39002)

Alpha branch
![Uploading Screenshot_20240320_095020.png…]()

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103124'>Zendesk ticket #103124</a>:<br><br> Mobile V5 does not support AIR 2S. You need to use Mobile SDK V4, here is the sample code: https://github.com/dji-sdk/Mobile-SDK-Android
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
I installed this apk from link https://www.dji.com/downloads/djiapp/dji-fly
Why AIR 2S is supported?
This apk used SDK V4 or V5?
![Screenshot 2024-03-20 at 17 01 06](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/46671455/77ad4dca-0a35-4ace-894f-d401a6419b86)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103124'>Zendesk ticket #103124</a>:<br><br>The DJI Fly app is not developed using the SDK. It is a standalone software project.
<br><p><em><small>°°°</small></em></p>
