### ISSUE TITLE
Couldn't load lib

### ISSUE THREAD

**Issue by fail572872916** [dji-sdk/Mobile-SDK-Android-V5#293]
No implementation found for int djimrtc.natives.MRTCController.initNativeMRTCCore(java.lang.String) (tried Java_djimrtc_natives_MRTCController_initNativeMRTCCore and Java_djimrtc_natives_MRTCControl
ler_initNativeMRTCCore__Ljava_lang_String_2)
![微信截图_20240321132735](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/8bbe4595-84ce-405c-b93b-bb3aaabc5cdf)
This issue has been closed in #54, I can't change the version of another library, and now minSdk in msdk5.8.0 is also changed to 23, how should I deal with my problem?

**Comment by fail572872916** [comment]
我的配置如下
plugins {
id 'com.android.application'
id 'org.jetbrains.kotlin.android'
// id 'kotlin-android-extensions'
id 'com.google.devtools.ksp'
id 'kotlin-parcelize'

}

android {
namespace ''
compileSdk 33

defaultConfig {
    applicationId ""
    minSdk 24
    targetSdk 30
    versionCode 1
    versionName "1.0"


    ndk {
        abiFilters 'arm64-v8a' // 当前 MSDK 只支持 arm64-v8a 架构
    }

    // MSDK 相关的 so 库，加上一下配置
    packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }

    // MSDK 相关的 so 库，加上一下配置
    packagingOptions {
        doNotStrip "*/*/libconstants.so"
        doNotStrip "*/*/libdji_innertools.so"
        doNotStrip "*/*/libdjibase.so"
        doNotStrip "*/*/libDJICSDKCommon.so"
        doNotStrip "*/*/libDJIFlySafeCore-CSDK.so"
        doNotStrip "*/*/libdjifs_jni-CSDK.so"
        doNotStrip "*/*/libDJIRegister.so"
        doNotStrip "*/*/libdjisdk_jni.so"
        doNotStrip "*/*/libDJIUpgradeCore.so"
        doNotStrip "*/*/libDJIUpgradeJNI.so"
        doNotStrip "*/*/libDJIWaypointV2Core-CSDK.so"
        doNotStrip "*/*/libdjiwpv2-CSDK.so"
        doNotStrip "*/*/libFlightRecordEngine.so"
        doNotStrip "*/*/libvideo-framing.so"
        doNotStrip "*/*/libwaes.so"
        doNotStrip "*/*/libagora-rtsa-sdk.so"
        doNotStrip "*/*/libc++.so"
        doNotStrip "*/*/libc++_shared.so"
        doNotStrip "*/*/libmrtc_28181.so"
        doNotStrip "*/*/libmrtc_agora.so"
        doNotStrip "*/*/libmrtc_core.so"
        doNotStrip "*/*/libmrtc_core_jni.so"
        doNotStrip "*/*/libmrtc_data.so"
        doNotStrip "*/*/libmrtc_log.so"
        doNotStrip "*/*/libmrtc_onvif.so"
        doNotStrip "*/*/libmrtc_rtmp.so"
        doNotStrip "*/*/libmrtc_rtsp.so"
    }
}
signingConfigs {
    def alias = ""
    def password = ""
    def filePath = '../app/oneMap.jks'

    debug {


        storeFile file(filePath)
        storePassword password
        keyAlias alias
        keyPassword password
    }
    release {

        storeFile file(filePath)
        storePassword password
        keyAlias alias
        keyPassword password
    }
}
buildFeatures {

    viewBinding = true
    dataBinding = true
}
compileOptions {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
}
def room_version = "2.5.0"
def rxhttp_version = "3.2.4"
dependencies {
compileOnly deps.aircraftProvided
implementation deps.aircraft

/** <-----------------sample所需--------------------> **/
implementation project(':android-sdk-v5-uxsdk')
implementation deps.appcompat
implementation deps.constraintLayout
implementation deps.aacCommon
implementation deps.aacRuntime
implementation deps.kotlinLib
implementation deps.ktxCore
implementation deps.ktxFrag
implementation deps.ktxNavigation
implementation deps.ktxNavigationUi
implementation deps.recyclerview
implementation deps.legacySupport
implementation deps.lifecycleViewModel
implementation deps.lifecycleLiveData
implementation deps.leakcanary
implementation deps.glide
implementation deps.dynamicanimation
implementation deps.expandedit
implementation deps.rx3Kt
implementation deps.dom
ksp deps.glidecompiler

implementation(project(":basemattermap"))
implementation(project(":switchButton"))
implementation(project(":xpopup"))
implementation(project(":basefly"))
implementation(project(":TabLayout"))
implementation(project(":lib_circularavatar"))
implementation(project(":MapGeoJson"))
implementation("com.blankj:utilcodex:1.31.1")


implementation("com.afollestad.material-dialogs:core:3.3.0")
implementation("com.afollestad.material-dialogs:input:3.3.0")
implementation("com.afollestad.material-dialogs:files:3.3.0")
implementation("com.afollestad.material-dialogs:lifecycle:3.3.0")


// 权限请求框架：https://github.com/getActivity/XXPermissions
api("com.github.getActivity:XXPermissions:18.5")


api("io.github.jeremyliao:live-event-bus-x:1.8.0")
implementation("io.coil-kt:coil:2.4.0")

implementation("androidx.room:room-runtime:$room_version")
implementation("androidx.room:room-ktx:$room_version")
// To use Kotlin Symbol Processing (KSP)
ksp("androidx.room:room-compiler:$room_version")
implementation "io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.14"


//MQTT需要使用到Paho Android Service库
implementation ("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0")
implementation ("org.eclipse.paho:org.eclipse.paho.android.service:1.1.1")


//lottie动画
implementation "com.airbnb.android:lottie:5.2.0"


implementation 'com.squareup.okhttp3:okhttp:4.12.0'
implementation "com.github.liujingxing.rxhttp:rxhttp:$rxhttp_version"
// ksp/kapt/annotationProcessor choose one
ksp "com.github.liujingxing.rxhttp:rxhttp-compiler:$rxhttp_version"
implementation 'org.xutils:xutils:3.9.0'

implementation("io.coil-kt:coil:2.4.0")
implementation("com.github.BzCoder:EasyGlide:2.0.1")

implementation 'io.reactivex.rxjava3:rxjava:3.1.6'
implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
implementation 'com.github.liujingxing.rxlife:rxlife-rxjava3:2.2.2' //RxJava3, Automatic close request
// implementation 'com.squareup.okhttp3:okhttp:4.12.0'
// implementation ("com.github.liujingxing.rxhttp:rxhttp:$rxhttp_version")
// ksp/kapt/annotationProcessor choose one
// kapt ("com.github.liujingxing.rxhttp:rxhttp-compiler:$rxhttp_version")

**Comment by fail572872916** [comment]
![微信截图_20240321133401](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/e7a864eb-b14f-490a-84f2-261d02983117)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103255'>Zendesk ticket #103255</a>:<br><br>您直接在MSDK V5的示例代码上测试直播功能会出现相同的问题吗？
你遇到的这个崩溃在lib和第三方库存在冲突的时候也会出现，目前已知存在冲突的库有OpenCV和Mapbox 10。
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
官方的不会，我的也是个地图底层，我这边需要如何让直播顺利推流呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月21日 19:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dji-sdk/Mobile-SDK-Android-V5] Couldn't load lib (Issue #293) |

Agent comment from yating.liao in Zendesk ticket #103255:

您直接在MSDK V5的示例代码上测试直播功能会出现相同的问题吗？
你遇到的这个崩溃在lib和第三方库存在冲突的时候也会出现，目前已知存在冲突的库有OpenCV和Mapbox 10。



°°°

**Comment by fail572872916** [comment]
目前去掉地图可以正常进行直播，应该是底层冲突问题

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103255'>Zendesk ticket #103255</a>:<br><br>冲突问题在5.9版本有尝试修复，您可以到时候更新到5.9版本。它预计在4月份或者五月份发布。
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Hi I have the same issue, so I bumped to the release of yesterday (5.9.0) but the pb is still here.

Do you have a roadmap and an ETA for this fix regarding the streaming on RTMP server, pretty critical issue...

**Comment by fail572872916** [comment]
> Hi I have the same issue, so I bumped to the release of yesterday (5.9.0) but the pb is still here.
> 
> Do you have a roadmap and an ETA for this fix regarding the streaming on RTMP server, pretty critical issue...

friend,You can try according to my above configuration, I upgraded to 5.9.0 can push stream

**Comment by antonymarion** [comment]
OK Dude I will give it a try!

Just bump but didn't check if I have the same configuration as yours.

**Comment by antonymarion** [comment]
Hi bro,

my .so are the same, my minSdk can be 23 and upper until 25 but, still I get the unknown error, on MSDK 5.9.0.

**Comment by fail572872916** [comment]
> 嗨，兄弟，
> 
> 我的.so是一样的，我的minSdk可以是23和更高，直到25，但是，我仍然在MSDK 5.9.0上收到未知错误。

Does the error message start after starting the live broadcast

**Comment by antonymarion** [comment]
Hi again, I fixed it with https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/339, thks again ;)
