### ISSUE TITLE
Thermal Side-by-Side handled differently

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#298]
Drone: Mavic 3 Thermal
SDK: `5.8.0`

Thermal camera's side-by-side Aspect Ratio appears to be different in the my app compared to DJI Pilot. How do I make my Side-by-side feed look like DJI Pilot's?

My app:

![Screenshot 2023-11-10 at 4 16 19 PM](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7491879/c93c252d-9acf-4129-8dcb-41fa4a5694f4)

DJI Pilot:

<img width="1612" alt="Screenshot 2024-03-27 at 2 36 31 PM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7491879/1abf5d7d-913c-4d00-bfc7-ee149cc794bb">

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103740'>Zendesk ticket #103740</a>:<br><br>f you want to achieve the same effect as Pilot 2, you may need to implement the display of video data by yourself. Could you please first explain how you are displaying the images on your end?
From the images you provided to us, it seems like your application is displaying a lot of black. Does the sample code also produce the same effect?
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Camera feed is implemented utilizing the recommended `5.8.0` classes:

`MediaDataCenter.getInstance().cameraStreamManager?.putCameraStreamSurface()`

Sample code does not implement Side-by-side so I cannot verify (most thermal camera keys are not in the sample code)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103740'>Zendesk ticket #103740</a>:<br><br>You can use the Key/Value tool in the testing tool to call different keys to achieve camera output of side-by-side video streams. Then switch to the default layout page to see the display effect of the sample code.

Here is a reference article for achieving side-by-side output:https://sdk-forum.dji.net/hc/en-us/articles/16408994343577-How-do-I-display-both-the-visible-and-infrared-camera-feeds?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjEwMjgxOTM0NDg3OTYxLCJ0aWNrZXRfaWQiOjEwMzc0MCwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE3MTQyNzYyNDl9.DXfwbUCUlOS-r4DwFSoE6kiwLC7pSJ0kXO4Q1sAgLVE
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
It appears the sample app mirrors my app:

<img width="1612" alt="Screenshot 2024-03-29 at 8 19 23 AM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/7491879/bc868bea-e798-441c-bd2f-5e0fad15de43">

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103740'>Zendesk ticket #103740</a>:<br><br>If the sample code and the effect of your app are the same, then the ScaleType  provided by the SDK cannot achieve the same effect as Pilot 2.

If you can accept some loss of the screen, you can set the ScaleType to CENTER_CROP; if you can accept stretching of the screen, you can set the ScaleType to FIT_XY, both of these modes can reduce the black areas.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Thank you for this. For anyone looking at this in the future, implementing `ICameraStreamManager.ScaleType.CENTER_CROP` makes the Side-By-Side match DJI Pilot.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103740'>Zendesk ticket #103740</a>:<br><br>Thank you for sharing.
<br><p><em><small>°°°</small></em></p>
