### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by nedaalizadeh** [dji-sdk/Mobile-SDK-Android-V5#3]
Hello,

I developed an application using MSDK v4.16. For live video stream, the MSDK uses RTMP protocol which has latency. 
Does MSDK v5 support WebRTC for live video streaming? 

Thanks

**Comment by dji-dev** [comment]
we will support it on 5.0.0-beta2

**Comment by Hoker-** [comment]
we will support it on 5.0.0-beta2

**Comment by nedaalizadeh** [comment]
What is the release date of MSDK 5.0.0-beta2?

**Comment by nedaalizadeh** [comment]
As I noticed on Github, MSDK 5.0.0-beta2 released today. I checked video type for live streaming. The types are: UNKNOWN, RTMP, RTSP, GB28181, AGORA. Still no WebRTC? Am I correct?

**Comment by john-davis-2000** [comment]
i checked sample code on release beta2 but webrtc was not  for video live streaming.

**Comment by Michael-DJI** [comment]
AGORA  type is WebRTC based

**Comment by DanLongChen** [comment]
agora is based on WebRTC, see details（https://www.agora.io/cn）

**Comment by DJI-William** [comment]
> What is the release date of MSDK 5.0.0-beta2?

beta 2 is now released, please update your sample now.
