### ISSUE TITLE
uxsdk 部分组件显示无效

### ISSUE THREAD

**Issue by The-WindRises** [dji-sdk/Mobile-SDK-Android-V5#30]
RadarWidget、GridLineView引入不显示、FPVWidget的uxsdk_videoChannelType选择primaryStreamChannel不显示

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69844'>Zendesk ticket #69844</a>:<br><br>你用sample可以正常显示RadarWidget、GridLineView吗？
FPVWidget的uxsdk_videoChannelType选择primaryStreamChannel不显示？ -- 您有确定主视频通道是打开的吗？
<br><p><em><small>°°°</small></em></p>

**Comment by The-WindRises** [comment]
主视频通道打开是那句代码？

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69844'>Zendesk ticket #69844</a>:<br><br>可以参考官网的教程打开视频通道：https://developer.dji.com/doc/mobile-sdk-tutorial/cn/tutorials/video-stream.html#%E6%8E%A5%E5%8F%A3%E8%B0%83%E7%94%A8%E6%B5%81%E7%A8%8B

FPV默认使用的是主视频通道，你打开主视频通道看看
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
请问问题解决了吗？

**Comment by The-WindRises** [comment]
原因是之前运行了msdk v4，未卸载然后运行了v5出现的问题

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69844'>Zendesk ticket #69844</a>:<br><br>是同时运行V4和V5出现的问题吗？单独使用V5还存在这类问题吗？
<br><p><em><small>°°°</small></em></p>
