### ISSUE TITLE
Marker Angle rotation 

### ISSUE THREAD

**Issue by 1232Ga** [dji-sdk/Mobile-SDK-Android-V5#300]
how to rotate marker on given flight path according to there angle ,but in our app marker not rotated, it is moving only one direction, below i am attaching screenshot of  DJi mavic 2 Enterprise
![Image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/22fd7ebc-6e25-48f1-b7d9-581c58c6206c)
![Image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/154498755/cafd1386-159b-4265-aa7a-7d0600c7ec10)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103788'>Zendesk ticket #103788</a>:<br><br>How do you go about adding marker ? I believe you can update the Rotation of the marker .
<br><p><em><small>°°°</small></em></p>
