### ISSUE TITLE
M3M: cannot get all multispectral images

### ISSUE THREAD

**Issue by gianlu33** [dji-sdk/Mobile-SDK-Android-V5#301]
Hi,

I'm trying to capture some multispectral images using my DJI M3M. However, it seems that some multispectral bands are not being stored on the SD card. For example, these are the images that I could get from the drone after taking a single photo:

```
DJI_20240329124328_0001_F.JPG
DJI_20240329124328_0001_MS_NIR.TIF
DJI_20240329124328_0001_MS_R.TIF
DJI_20240329124328_0001_D.JPG
```

As you can see, the `G` and `RE` TIFF images are not there. 

Before shooting the photo, I set the `KeyCaptureCameraStreamSettings` value to `[RGB_CAMERA, NDVI_CAMERA, MS_G_CAMERA, MS_R_CAMERA, MS_RE_CAMERA, MS_NIR_CAMERA]`, as described in the [documentation](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html#key_camera_msdkcapturecamerastreamsettings_inline).

Am I missing something? I'm using version `5.8.0` of the SDK.

Thanks.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103919'>Zendesk ticket #103919</a>:<br><br>Currently, it is indeed not possible to obtain TIFF images for `G` and `RE` using the MSDK. The same issue occurs when trying to access them through Pilot 2, as the aircraft does not currently provide us with a method to retrieve photos for these two bands. However, they are actually being generated in the SD card.
<br><p><em><small>°°°</small></em></p>

**Comment by gianlu33** [comment]
Thanks for the response. So, if I have understood correctly, this is a firmware issue of the Mavic 3M? Do you have any indication about if and when this will be resolved?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103919'>Zendesk ticket #103919</a>:<br><br>Yes, the reason why MSDK cannot retrieve all the images is that the aircraft did not provide it. I am not sure if there will be any changes in the future to provide all the photos, so currently M3M design does not provide photos for `G` and `RE`. I will pass on your request to the team.
<br><p><em><small>°°°</small></em></p>

**Comment by lleoncini** [comment]
This is still not working, why is closed? I have tested several times from the main app DJI Pilot or the SDK and the those two images (G and RE) are not comming.
