### ISSUE TITLE
Connecting custom Built APP with Mavic 3E 

### ISSUE THREAD

**Issue by usamahamayun123** [dji-sdk/Mobile-SDK-Android-V5#302]
We have developed our custom andoid app using MSDK v5  for Mavic 3E.and we want to run this app in another android device instead of RC Controller android device. Is there any way to do that ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104196'>Zendesk ticket #104196</a>:<br><br>If you want to control the Mavic 3T using the Mobile SDK on other Android devices, I believe it is not possible. The Mobile SDK does not have the capability to directly connect to the drone or enable the remote controller to connect to Android devices.

To control the Mavic 3T, the only current options are through the remote controller or direct communication with the flight controller. The Mobile SDK can be used on the remote controller, and the Payload SDK can communicate with the flight controller.

If you use the Mobile SDK as an intermediary to transmit control commands and aircraft status, you can transfer the data obtained from the Mobile SDK to other platforms in various ways.
<br><p><em><small>°°°</small></em></p>
