### ISSUE TITLE
在 MSDK 5.8.0 中，VideoDecoder 的解码行为是否发生了变更？

### ISSUE THREAD

**Issue by Merpyzf** [dji-sdk/Mobile-SDK-Android-V5#304]
在 MSDK 5.6.0 中，我可以通过以下方式获取与当前控件大小相匹配的码流（根据业务需求，我需要以非等比例的方式拉伸码流）。下面是我的构造方法：

```
val width = 1920
val height = 1200

VideoDecoder(
    context,
    videoChannelType,
    DecoderOutputMode.SURFACE_MODE,
    fpvSurfaceView.holder,
    width,
    height,
    true
)
```

在 5.6.0 之前，VideoDecoder 会根据给定的 width 和 height 对码流进行解码。然而，从 MSDK 5.6.0 升级到 5.8.0 后，似乎 VideoDecoder 根据码流的实际宽高比进行解码。我在更新日志中没有找到关于这个行为变更的说明。由于无法查看 VideoDecoder 的实现，我不清楚发生了什么。

希望能提供解决方案和此处的变更说明。谢谢！

**Comment by Merpyzf** [comment]
https://sdk-forum.dji.net/hc/en-us/articles/27446278636825-How-do-I-go-full-screen-with-version-5-8-of-FPVWidget，我已经在 [DJI SDK Forum](https://sdk-forum.dji.net/hc/en-us) 中找到了解决方案，还是希望 DJI 的工程师们可以把 SDK 更新所涉及的变更列举的更详细些。

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104433'>Zendesk ticket #104433</a>:<br><br>感谢您的反馈。您所提交的VideoDecoder的变化其实在教程文档里有进行说明：https://developer.dji.com/doc/mobile-sdk-tutorial/cn/tutorials/video-stream/video-stream2.html
我们会将您的建议提交给文档工程师进行后续的优化。
<br><p><em><small>°°°</small></em></p>
