### ISSUE TITLE
Mavic 3 PRO Supported?

### ISSUE THREAD

**Issue by slamgo** [dji-sdk/Mobile-SDK-Android-V5#305]
when will the MSDK support  Mavic 3 Pro ?  We bought 40 Mavic 3 Pro drones  ，but the MSDK still   unsupported...

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/104582'>Zendesk ticket #104582</a>:<br><br>We regret to inform you that there are no plans to support MSDK for the Mavic 3 Pro. In the future, MSDK will prioritize support for enterprise drones. The majority of consumer drones will no longer be supported by the SDK.
<br><p><em><small>°°°</small></em></p>
