### ISSUE TITLE
Display Scaling Discrepancy in DJI Fly App

### ISSUE THREAD

**Issue by darkangel20156** [dji-sdk/Mobile-SDK-Android-V5#306]
Mobile: Samsung Galaxy S20 FE

Firstly, I have a query regarding the scaling of the display when running the DJI Fly App. The code I'm using is meant to display video from the DJI Mini 3 on a Surface View. However, the result I'm getting is that the video displayed on my app doesn't match the quality of the video shown on the DJI Fly App.

This is my code:
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/123035738/ade65ff2-c977-466c-b6bf-ae52aeca3b0d)
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/123035738/26dd7a12-16e2-409e-9c3c-7d2581e5d530)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>Could you please tell us about the version of MSDK you are using? If you are not using version 5.8, would you be willing to try the sample code for version 5.8? Version 5.8 includes the feature of camera screen adaptive view.

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
I'm using MSDK version 5.6. Since I've been using 5.6 for a while, I want to continue developing on it.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>The code you provided us with is correct. What do you think is the difference between it and the display image in DJI Fly?

If version 5.6 needs to achieve the same effect as DJI FLY, it may require implementing video image display on its own.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
Example: With the same drone flight position, I look at a tree, DJI Fly captures the entire tree and displays it on the screen, but my app is missing some details (top of the tree). 
Can you introduce me to a different way than mine? Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>I think there should be no difference in the content of the drone's footage. The video stream data obtained from the SDK should be the same as DJI FLY.

Do you encounter the same issue when using the sample code? In the sample code, the width and height passed to VideoDecoder are -1, which indicates that the default width and height of the surfaceView are used.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
Yeah, I conducted a test, and the results were consistent between the sample code and the DJI Fly app. They both provided the same outcome.

I have another question: I'm curious about the drone's IMU. Does MSDK support retrieving the IMU altitude value?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>The SDK cannot obtain the altitude value of the IMU. The altitude obtained by the SDK is a fusion of data from multiple sensors, and it is not possible to solely obtain the altitude from the IMU .
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
I'm interested in learning more about the IMU altitude shown in this image. I understand that the owner used a flight log and the Phantom Help website to obtain this picture. Could you provide further details?
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/123035738/e53101d2-f47f-4ead-98be-bde43bcab779)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>In flight records, the aircraft's altitude will indeed be recorded, but it should reflect the aircraft's relative altitude to the takeoff point and the altitude of the takeoff point.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
Oh, thank you for your help!
Besides, I'm interested in KeyAutoLanding. I want to ask what factors need to be met for automatic landing, is it related to GPS...
If possible, could you provide me with details about this part?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104650'>Zendesk ticket #104650</a>:<br><br>Landing does not require GPS. Returning and landing are different processes. Returning involves the aircraft flying towards a point identified by latitude and longitude coordinates, while landing is when the aircraft begins to descend and stops on the ground. Typically, drones analyze the environment of the landing location to determine its suitability. If the location is deemed unsuitable for landing, the aircraft will hover in the air. At this point, it is possible to manually request the aircraft to complete the landing.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
Regarding environmental issues: "Typically, drones analyze the environment of the landing location to determine its suitability. If the location is considered unsuitable for landing, the aircraft will hover in the air. At this point, it is possible to manually request the aircraft to complete the landing."

You said it will analyze the environment, to determine the appropriate environment. So I want to ask, what elements does a reasonable environment include?

**Comment by dji-lyt** [comment]
You can refer to the description on the image. The visual sensor below the aircraft will determine if the current ground is flat. Uneven ground will be considered unsuitable for landing.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/1c78a3b6-acd4-4b29-9e0c-84eebeaec9ee)

**Comment by darkangel20156** [comment]
Thank you for your help
