### ISSUE TITLE
Gimbal Attitude Precision

### ISSUE THREAD

**Issue by timothyolt-dronesense** [dji-sdk/Mobile-SDK-Android-V5#307]
Environment
Drone: DJI Matrice 300 RTK
Controller: DJI Smart Controller Enterprise
DJI Pilot 2 app version: 7.0.2.2
Mobile SDK version: 5.8.0
Aircraft Firmware version: 09.00.0503
Sensor: H20T w/ Firmware 07.00.01.05
RC Firmware version: 09.00.0501

Angle precision only includes tenths of a degree on the following keys:
- `GimbalKey.KeyRotateByAngle`
- `GimbalKey.KeyGimbalAttitude`
- `GimbalKey.KeyFineTuneYawInDegrees`
- `GimbalKey.KeyFineTuneYawTotalDegree`

While attempting to tune the gimbal by hundredths of a degree, it does not seem to have an effect. 
This makes it difficult to tell exactly what the H20T sensor is looking at when fully zoomed in, because the total field of view is in the realm of 0.35 degrees.

Here is screenshots of the MSDK attempting to use the fine tune controls:
![Screenshot_20240409-115907](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/e35be880-a64e-4632-8e0f-9e3594a5ed6a)

And here is screenshots of attempting to use the normal gimbal angle controls:
![Screenshot_20240409-120406](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/8cfca730-16d7-4c88-8ad9-2644d7616652)
![Screenshot_20240409-120410](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/2af1b20c-4bf9-47c9-9561-4c91f55b2795)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104654'>Zendesk ticket #104654</a>:<br><br>Have you tried rotating the gimbal by controlling the speed? Although it may be difficult to rotate the gimbal when the zoom ratio is large due to anti-shake protection, the gimbal will still rotate when the speed is high enough.
<br><p><em><small>°°°</small></em></p>

**Comment by timothyolt-dronesense** [comment]
I had considered that. However my goal is to know which building an aircraft is looking at, and then adjust the gimbal by a small amount to look at another specific building. 

Just rotating by speed would not solve my issue. I would like to rotate the gimbal by a precise amount, such as 0.02 degrees, or 0.38 degrees. I may be able to achieve that precision by rotating by speed and cancelling it after a certain amount of milliseconds, however because the precision issue also affects reading `GimbalKey.KeyGimbalAttitude`, I cannot know how much I need to rotate the gimbal.

When fully zoomed in on the H20T, `GimbalKey.KeyGimbalAttitude` is only precise enough to tell me which third of the screen the pilot is looking at, rather than being able to know exactly which building.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104654'>Zendesk ticket #104654</a>:<br><br>Do you require such precise control of the gimbal to have a specific target position in the center of the frame? If so, have you tried KeyTapZoomAtTarget? It can take a screen coordinate point and center the target at that point on the screen.
<br><p><em><small>°°°</small></em></p>

**Comment by timothyolt-dronesense** [comment]
If we had tap zoom that would work really well for one of our use cases. Do you have a list of which sensors are supported with this feature?
Last time I tested that key, I do not remember it working on the Matrice 30 or Mavic 3 Enterprise.

Our other use case it does not help us with, which is similar to rendering POI's. To render POI's properly, we would need more accurate aircraft and gimbal attitude while zoomed in to 200x.

**Comment by timothyolt-dronesense** [comment]
After testing on the H20T, it seems like KeyTapZoomAtTarget suffers from a similar lack of precision at high zooms.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104654'>Zendesk ticket #104654</a>:<br><br>I need to confirm with the camera team whether the camera supports high-precision adjustments. Please wait for a while. However, based on the test results you provided, it is likely that the camera cannot achieve this level of precision. If there is a way to make slight adjustments, I will contact you proactively.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104654'>Zendesk ticket #104654</a>:<br><br>I have confirmed that H20T cannot achieve the accuracy you require. This is indeed a limitation in the H20T , and the same issue may arise with the M30 series.
<br><p><em><small>°°°</small></em></p>
