### ISSUE TITLE
FPVWidget 下推流失败

### ISSUE THREAD

**Issue by GQ105501** [dji-sdk/Mobile-SDK-Android-V5#31]
示例中提示【在当前页面必须得有Surface画面渲染】，但是我看了源码  在FPVWidget 创建的时候同时也创建了surface，因为在FPVWidget.kt类中存在surfaceCreated方法和surfaceChanged方法，那么在FPVWidget 组件存在的界面中，即使在界面中添加SurfaceView控件也是可以正常直播的，但是我的直播一直是开启失败。下面是开启失败后的报错信息，我有点看不懂是什么意思。
【can't find dl_node by prot_name dji,rtmp
can't find dl_handle_node in lib handle list】

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>你是执行到哪个部分提示的报错呢？FPVWidget的videoDecoder里是没有开启推流选项的，你可以参考这篇问题添加上：第五章：视频流解码
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
我是在DefaultLayoutActivity.java文件中添加了直播功能；
添加了一个按钮，通过点击按钮执行开启直播的方法，虽然直播开启后执行到了success方法，但是成功之后的 isStreaming为false，而且流没有接收到；
【FPVWidget的videoDecoder里是没有开启推流选项的】这个我没有理解是什么意思？
因为在V4版本的SDK中  我也是在飞行界面中去做直播开启的功能，而且可以正常进行直播推流；

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>VideoDecoder有一个参数isForLiveStream，这个参数表示是否支持推流。实现推流前，需要在构造VideoDecoder的时候将这个参数设置为true，不然拿不到是视频流。
具体可以看这篇文章：第五章：视频流解码 然后再参考直播流程完成直播：第六章：推流直播
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>文章链接：第五章：视频流解码 - https://sdk-forum.dji.net/hc/zh-cn/articles/6663343101337
第六章：推流直播 - https://sdk-forum.dji.net/hc/zh-cn/articles/6663305630105
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
好的  我试试看

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>sample可以正常直播的话，那么接口上就是没有问题的。如果还存在问题可以继续咨询。
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
额  我这边在官方示例已经推流成功了   但是在自己的代码中  使用同样的方法   开启直播时就onFailure了 并且提示【直播开启失败】，然后  我看了还有RTMP的报错 【com.example.hhch_dji_inspection E/LOG_JNI: [MRTC-E find_dl_handle_node_by_prot_name:   70]: : can't find dl_node by prot_name dji,rtmp】
这能看看是什么问题嘛

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>你再次测试推流的时候有按照文章中的说明修改FPVWidget上videoDecoder的构建方法吗？也就是添加上isForLiveStream。
 ![](https://djisdksupport.zendesk.com/attachments/token/1iZzoWjQqyYkq6DvDuOu4HlUP/?name=image.png)<br><a href='https://djisdksupport.zendesk.com/attachments/token/1iZzoWjQqyYkq6DvDuOu4HlUP' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
已经修改过了，sample项目里面的，android-sdk-v5-uxsdk下的DefaultLayoutActivity.java中添加直播功能是可以正常使用的，但是同样的代码在我自己的工程里面就不能使用。直播一直是失败；
![微信截图_20220901143803](https://user-images.githubusercontent.com/40254744/187848372-4a93e3dd-870b-4beb-8563-5dec610bb937.png)
![微信截图_20220901143812](https://user-images.githubusercontent.com/40254744/187848379-15b87241-67f8-4f6d-beaa-92035db3ba95.png)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>你可以对比sample修改，我们不了解你自己的工程所以没办法提供精准的解决方案。需要注意的是直播推流是需要当前有画面显示的，没有就会导致失败。
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
好的  我再研究研究

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>好的，如果定位到是MSDK发生了错误，要麻烦你告诉我们复现路径，确认问题之后我们会转交给研发人员排期处理。
<br><p><em><small>°°°</small></em></p>

**Comment by GQ105501** [comment]
问题已经找到   可以正常进行推流。 感谢解答~
麻烦问一下，地图的mapweight组件什么时候可以正常使用？

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/69927'>Zendesk ticket #69927</a>:<br><br>地图控件目前还不清楚是在哪个版本，但是sample已经上传的widget后面会完善的。
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
mapWidget在下半年会排期去集成一些常用的地图，目前优先级不高，你们可以自行集成你们喜欢的地图。
