### ISSUE TITLE
Video stream from side and bottom cameras

### ISSUE THREAD

**Issue by mtpdog** [dji-sdk/Mobile-SDK-Android-V5#310]
Mavic 3 (consumer) received an option to display video from side cameras in the Fly app.
Do we have an option in SDK to get a video stream from bottom and side cameras on enterprise drones?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104830'>Zendesk ticket #104830</a>:<br><br>It seems that there is currently no function to view sensor images for drones adapted with MSDK. If industrial drones already have this feature, it is possible for the SDK to provide it.

The Mavic 3 (consumer) is not supported by the SDK.
<br><p><em><small>°°°</small></em></p>

**Comment by juliano-souza000** [comment]
Hello, Any Update on this?
I tried looking at the ticket above but it seems it's not available anymore

**Comment by dji-lyt** [comment]
For Mavic 3 custom series, there is no support plan now.
