### ISSUE TITLE
UpgradeManager.getUpgradableComponents returns an empty collection

### ISSUE THREAD

**Issue by danekpilar01** [dji-sdk/Mobile-SDK-Android-V5#311]
Hello, after I make sure the aircraft is connected, I try to check if the firmware is up to date. I figured that I should get that information from the UpgradeManger class. When i call the getUpgradableComponents, it always returns an empty list. What could be the reason?

Thank you in advance ;)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/104839'>Zendesk ticket #104839</a>:<br><br>May I inquire about the model of your aircraft? Additionally, please be advised that after the aircraft is connected, it is necessary to wait for each module to complete initialization before calling the getUpgradableComponents method immediately.
<br><p><em><small>°°°</small></em></p>

**Comment by danekpilar01** [comment]
It is Mavic 3 Enterprise.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/104839'>Zendesk ticket #104839</a>:<br><br>It is essential to wait for each module to finish initialization after the aircraft is connected before promptly invoking the getUpgradableComponents method, as mentioned earlier.
<br><p><em><small>°°°</small></em></p>
