### ISSUE TITLE
unable to connect phone to RC

### ISSUE THREAD

**Issue by Mulham6** [dji-sdk/Mobile-SDK-Android-V5#312]
Hi, the sample app is registering correctly on my phone, but the connection with the RC using a USB C doesn't seem work.

Normally, the RC connects to the drone without issues, but as soon as I plug in the usb c cable with the phone the RC is unable to find the aircraft:
![screenshot](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/52281056/266c1425-654f-47c2-b55a-bd40fed24636)
Obviously everything in the sample app is blank showing that there's no RC or aircraft connected.

I'm using Samsung A21s DJI mini 3 and DJI RC with display.
Help would be really appreciated.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104991'>Zendesk ticket #104991</a>:<br><br>The DJI RC cannot connect to a mobile phone, only the DJI RC-N1 can connect to a mobile phone:https://sdk-forum.dji.net/hc/en-us/articles/17524981906585-Which-RC-supports-MSDK-in-DJI-Mini-3-series?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjMxMDExMzgzNTU3MDE3LCJ0aWNrZXRfaWQiOjEwNDk5MSwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE3MTU3NzQ0OTV9.pUabKifRPmoZpx8ptBg7M7AtCwfMCu6ljXfLWHqh8rY
<br><p><em><small>°°°</small></em></p>
