### ISSUE TITLE
V5.9版本什么时候发布？

### ISSUE THREAD

**Issue by Noah1991** [dji-sdk/Mobile-SDK-Android-V5#313]
如题，新版本啥时候发布啊？目前这个三方载荷使用CUS-H264不显示的问题，已经影响到产品测试开发。

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105063'>Zendesk ticket #105063</a>:<br><br>5.9版本预计在近两个月发布，即4月或者5月发布。
<br><p><em><small>°°°</small></em></p>
