### ISSUE TITLE
EXIF DateTimeOriginal timezone does not match MediaFile.getDate() from KeyNewlyGeneratedMediaFile

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#315]
Timestamps returned by the SDK when new images are written to the SD card do not use the specified timezone set in Android.

Expected:
`DateTimeOriginal` EXIF tag time stamps on images to match the `MediaFile.getDate()` timestamps returned by the `KeyNewlyGeneratedMediaFile` listener triggered when new images are created.

Test:
I have a Mini 3 with an RC-N1 controller connected to an Android device and I am located in the PDT (UTC-7:00) timezone.

As a test, I set the timezone on the Android to EDT (UTC-4:00) and shot some images. EXIF data from the images taken with the drone have the EDT timezone in the DateTimeOriginal EXIF tag. However the MediaFile.getDate() returned from the SDK (KeyNewlyGeneratedMediaFile) at the time the image is created returns time stamps in the PDT (UTC-7:00) timezone.

Is the SDK getting the time zone information from somewhere else?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105163'>Zendesk ticket #105163</a>:<br><br> The data obtained by KeyNewlyGeneratedMediaFile is the data pushed by the drone. From your test results, it may be using the time zone of the drone's location.

Why do you need to match the photo time across time zones?
<br><p><em><small>°°°</small></em></p>
