### ISSUE TITLE
Customize L1,L2,L3,R1,R2,R3 buttons

### ISSUE THREAD

**Issue by AppDev999** [dji-sdk/Mobile-SDK-Android-V5#316]
How to customize these buttons? what is the correct key to do that?, I can't find the correct information in the documentation.
Thanks in advance

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105331'>Zendesk ticket #105331</a>:<br><br>You can detect the status of these buttons through the Android onKeyDown listener, there is no interface in the SDK to monitor these buttons.
<br><p><em><small>°°°</small></em></p>

**Comment by AppDev999** [comment]
Thank you, this solves my problem

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105331'>Zendesk ticket #105331</a>:<br><br>I am glad to help you.
<br><p><em><small>°°°</small></em></p>
