### ISSUE TITLE
Create Folder Action Does Not Work In DJI Dock1

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#319]
Hi DJI,

I am trying to create folders in Wayline mission with action, both with the dji hub portal and dji sdk (creating kmz file).
the key file that I created with dji SDK is completely working with Mavic and Matriec, but with dji dock1, it does not create the folders.

what is the reason?

![photo_2024-04-22_10-47-15](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/f78c5949-2579-4813-ae55-70393a6bdf6c)
![photo_2024-04-22_10-47-18](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/79d90470-306a-4a6b-b5c2-47793cdfe5eb)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/105680'>Zendesk ticket #105680</a>:<br><br>I would like to inquire if you are able to successfully create folders using the kmz file generated by Flight Hub. It appears that the KMZ version supported by the dock differs from that of the aircraft.
<br><p><em><small>°°°</small></em></p>
