### ISSUE TITLE
SEARCH RESTRICTED ZONE BY LOCATION 

### ISSUE THREAD

**Issue by GiangGiang11051999** [dji-sdk/Mobile-SDK-Android-V5#321]
Dear DJI team, 

I use DJI SDK your team to handle restricted zone for aircraft. I was get list restricted zone from aircraft but I can't search restricted zone by location. For example, I am in Da Nang, Vietnam but I want to search for restricted zone in Ho Chi Minh, Vietnam. I see your app has solved this problem. Specifically as attached image below: 
![IMG_1743](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/121371676/2a6ce372-5de4-49d6-9047-d34c22550299)
![IMG_1744](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/121371676/669fdf6d-b6ae-4bb2-9655-71c6ae6055b3)

Please offer for us function to handle this feature. 

Thank you team very much!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105780'>Zendesk ticket #105780</a>:<br><br> If you are using MSDK V5, it already provides the function to query nearby flight zones based on latitude and longitude coordinates. The interface is getFlyZonesInSurroundingArea.
<br><p><em><small>°°°</small></em></p>

**Comment by GiangGiang11051999** [comment]
I try use getFlyZonesInSurroundingArea and pass params latitude and longitude but I don't see any callback data. I check app DJI Fly on Store, your app not connected aircraft still search restricted zone.  If My app not connected aircraft, callback return message error. Please check again and offer document help me.  Thank team very much.

**Comment by dji-lyt** [comment]
Could you please provide the model of the drone you are using? I have tested the getFlyZonesInSurroundingArea interface on RC PRO and found that it is possible to retrieve surrounding flight zones without connecting to the aircraft. You can directly test the functionality of this interface using the sample code.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/3e7e2057-5f47-4ee0-822c-51af82a90b1a)

**Comment by GiangGiang11051999** [comment]
I run example follow link github: https://github.com/DJI-Mobile-SDK-Tutorials/Android-GEODemo. But I couldn't find any surrounding flight zones. 
I use DJI Air 2S model to get it. What is class contain getFlyZonesInSurroundingArea interface that you use? I use function as bellow to get restricted zone at RC location. If my app connected with aircraft, I received data from callback but data incorrect as hope. Else, I couldn't find any data from it, it return error message " Not connect aircraft ". 

![Screenshot 2024-04-25 at 09 33 06](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/121371676/85b2aae2-d08e-4253-be3e-fb459010ccc0)

And I use function getFlyZonesInSurroundingArea(latitude, longitude, callback) to get data that want to search. Follow image as bellow to see all my code for this issue. I tried pass params latitude and longitude but I couldn't get any data.  

![Screenshot 2024-04-25 at 09 38 35](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/121371676/ada4ebea-14be-4d17-a406-dca5c0a5e72f)

Please check my code and offers all issue in it. I hope I will resolve this issue by your instruction.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105780'>Zendesk ticket #105780</a>:<br><br>My previous test was conducted on MSDK V5, which supports this feature.However, the AIR 2S you are using does not support MSDK V5, it only supports MSDK V4.
Unfortunately, MSDK V4 cannot retrieve flight zone information without being connected to the aircraft. You can check the flight zone on the flight zone website, here is the URL:https://fly-safe.dji.com/nfz/nfz-query

In addition, if you are using MSDK V4, you can submit issues under this repository so that I can know the MSDK version you are using promptly:https://github.com/dji-sdk/Mobile-SDK-Android
Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by GiangGiang11051999** [comment]
When I connected AIR 2S with my app. My app retrieve flight zone information with list size = 1. However, I check flight zone information on https://fly-safe.dji.com/nfz/nfz-query with this location. I found many flight zone information at here. I receive data incorrect with DJI geo map on website.Please confirm this issue help me.

**Comment by dji-lyt** [comment]
The SDK interface can only retrieve flight zone information within a radius of 20 kilometers centered on the aircraft's position. The website allows you to freely query flight zones. The point has been clearly explained in the API documentation.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/2790d74f-14e2-4484-b216-b6a7392e7516)

**Comment by GiangGiang11051999** [comment]
Yes, I do know this. However, sometimes my app returns the same data as on the web, but other times it only returns a list with size = 1. Although, I stand at a constant position. Can you help me clarify what this is?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105780'>Zendesk ticket #105780</a>:<br><br>Could you confirm if I understand correctly that the position of your aircraft has not changed, but the information retrieved from multiple calls to getFlyZonesInSurroundingArea is different?
Would you be able to record a video for us to confirm this issue? Currently, we have not encountered the same problem in our testing.
Here is the address for uploading files:https://pan-sec.djicorp.com/s/JTQYJJtany59S73  password:dji123
<br><p><em><small>°°°</small></em></p>

**Comment by GiangGiang11051999** [comment]
Thank you team supported
