### ISSUE TITLE
M300 RTK，手柄外接手机时，接收不到飞行任务的执行进度

### ISSUE THREAD

**Issue by 98kWarning** [dji-sdk/Mobile-SDK-Android-V5#322]

**Comment by 98kWarning** [comment]
sdk版本：5.8
手柄系统版本：andorid7.0
手机系统版本：android13

场景：
使用usb线连接手机与手柄，在手机上操作开发的APP执行飞行任务，发现没有`onMissionStateUpdate`事件，即`WaypointMissionExecuteStateListener`里的事件没有响应，其他的如`WaylineExecutingInfoListener`、`WaypointActionListener`都没有响应。
**但是同样的APP，同样的代码，安装到手柄上执行就没有问题**，以上事件都有响应。

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106079'>Zendesk ticket #106079</a>:<br><br>从你描述的情况来看，你所使用的遥控器和手机没有成功连接。你使用的是什么遥控器？
<br><p><em><small>°°°</small></em></p>

**Comment by 98kWarning** [comment]
> Agent comment from yating.liao in [Zendesk ticket #106079](https://djisdksupport.zendesk.com/agent/tickets/106079):从你描述的情况来看，你所使用的遥控器和手机没有成功连接。你使用的是什么遥控器？
> 
> _°°°_

连接应该没问题，视频画面能正常显示，没有断开。其他的事件都能正常收到，比如上传任务文件的事件，温度电池等

**Comment by 98kWarning** [comment]
> Agent comment from yating.liao in [Zendesk ticket #106079](https://djisdksupport.zendesk.com/agent/tickets/106079):从你描述的情况来看，你所使用的遥控器和手机没有成功连接。你使用的是什么遥控器？
> 
> _°°°_

遥控器型号是 PJ001

**Comment by dji-lyt** [comment]
您使用示例代码会有相同的问题吗？我们没有遇到过类似的情况。
