### ISSUE TITLE
M30T 无法通过 MSDK 5.8.0 执行航线文件，报错：WPMZ_FILE_LOAD_ERROR

### ISSUE THREAD

**Issue by Merpyzf** [dji-sdk/Mobile-SDK-Android-V5#323]
**环境：**
无人机型号：M30T
无人机固件版本：0.9.01.0006
遥控器固件版本：0.3.02.0907
MSDK版本：5.8.0

**问题描述：**
在对 M30T 飞机进行适配时，我发现了一个问题。航线无法执行，会报告 "WPMZ_FILE_LOAD_ERROR" 错误。值得注意的是，相同的航线在 M350 飞机上可以正常执行。我仔细检查了航线文件，并确保无人机型号和负载型号都正确匹配。然而，无论我尝试多少次，都无法生成可执行的航线。

**为了进一步排除问题，我通过 DJI Pilot2 在地图上手动选点创建了一条航线，并将航线文件导出。然后，我尝试使用 MSDK 的 "pushKMZFileToAircraft()" 方法执行航线，但结果仍然报告了相同的错误："WPMZ_FILE_LOAD_ERROR"。我在 M350 上进行了相同的实验，结果是能够正确执行的。**

通过这些实验，我初步确定问题可能不在我这里。我非常希望您能尽快提供解决方案。

以下是通过 DJI Pilot2 创建的无法在 M30T 飞机上执行的航线文件。

[航线文件.zip](https://github.com/dji-sdk/Mobile-SDK-Android-V5/files/15127907/default.zip)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106089'>Zendesk ticket #106089</a>:<br><br>您可以检查一下开启航点任务的时候传入的misssionName是否带后缀？如果带后缀，你需要把后缀去掉。
<br><p><em><small>°°°</small></em></p>

**Comment by Merpyzf** [comment]
感谢，问题已经解决。
