### ISSUE TITLE
Any Roadmap updates?

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#324]
Hi there,

There hasn't been an update for SDK 5 in some time. Just wondering what does the roadmap look like for the next release? Are there any plans to add support for drone models like the Mini 4?

Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106419'>Zendesk ticket #106419</a>:<br><br>The next version will not support the DJI Mini 4. The next version is already in preparation and is expected to be released soon.
<br><p><em><small>°°°</small></em></p>

**Comment by uas470** [comment]
Noticing a large lack of effort on the MASK this year. So much for the Mini 4 projected support.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106419'>Zendesk ticket #106419</a>:<br><br>I apologize for any inconvenience this may have caused you.
<br><p><em><small>°°°</small></em></p>

**Comment by johnnokomis** [comment]
Has Active Track made it on the v5 roadmap yet? This has been available on past releases but is strangely not been made available at all on v5.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106419'>Zendesk ticket #106419</a>:<br><br>Active Track does not have support in the recently released version 5.9. I have not received any definite plans regarding whether this feature will be compatible in future versions.
<br><p><em><small>°°°</small></em></p>
