### ISSUE TITLE
DJIMarkerOptions Title

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#325]
Hi DJI,

In my application, I am using Mapbox (map widget of uxsdk) and I want to add some markers with text as their number.

Would you please tell me what is the problem?

This is the code I use but no text or title apears on the map.

![Capture](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/343b8a0b-99f4-4556-813d-8034acbbe220)

and this is th result:

![Screenshot_20240507-131041](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/22c5b9a6-78dd-4b43-abc1-b95c700b1fff)

I need this type of marker with text :

![Screenshot_20240507-131656](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/5d9e377c-6928-4a8c-8b33-81eb11676f76)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106714'>Zendesk ticket #106714</a>:<br><br>You can check out the sample code at https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-sample/src/main/java/dji/sampleV5/aircraft/pages/WayPointV3Fragment.kt#L757

The sample code actually adds numbers to markers in the form of icons.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
I exactly use this method to add marker to map but it does not have the title yet :

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/4f7addb4-26d5-4d95-b8d4-dc00e3f13c61)

is it because of the map provider of the mapwidget ? I have selected mapbox as the provider

**Comment by dji-lyt** [comment]
We can successfully display numbers when adding markers on MapLibre. The following image shows the result of changing the map type to MapLibre in our sample code.
If you make changes to the map type, I guess it might affect the display of markers.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/5968dfc5-ec29-40df-a47c-da93ff86393b)

**Comment by PeimanAtaei** [comment]
Thank you for your response but the problem was not because of the map type. 

to be able to add title to markers when we use UXSDK, we have to use "getMarkerRes" method to create the icons of the marker. then our title will be apear on the marker.

So problem is solved.

![1](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/eda69ea4-74dd-4d8e-b606-5168b7bf9179)

![3](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/0cd66ca9-d5c8-450b-bb6d-4527dc5e9a2e)

![2](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/4dadac59-f459-4056-9a9e-5e18ddbf281c)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106714'>Zendesk ticket #106714</a>:<br><br>I am pleased to inform you that your issue has been resolved.
<br><p><em><small>°°°</small></em></p>
