### ISSUE TITLE
Drone not responding with sendVirtualStickAdvancedParam

### ISSUE THREAD

**Issue by Mulham6** [dji-sdk/Mobile-SDK-Android-V5#327]
Hi, my Mini 3 is not responding at all with sendVirtualStickAdvancedParam. So far takeoff, landing and taking pictures have worked just fine on my app.

This is what I'm using to setup VirutalStick:
```
VirtualStickManager.getInstance().init()
        VirtualStickManager.getInstance()
            .enableVirtualStick(object : CommonCallbacks.CompletionCallback {
                override fun onSuccess() {
                    ToastUtils.showToast("VirtualStick enabled")
                }
                override fun onFailure(error: IDJIError) {
                    ToastUtils.showToast("Error enabling VirtualStick $error")
                }
            })
VirtualStickManager.getInstance().setVirtualStickAdvancedModeEnabled(true)
```

After that I send VirtualStickFlightControlParam at 5Hz for a few seconds:
```
// I've also tried different values here
private val virtualStickParam = VirtualStickFlightControlParam(
    0.0,
    0.0,
    90.0,
    0.0,
    VerticalControlMode.VELOCITY,
    RollPitchControlMode.VELOCITY,
    YawControlMode.ANGLE,
    FlightCoordinateSystem.GROUND
)
private var iterations: Int = 0
Timer().scheduleAtFixedRate( object : TimerTask() {
    override fun run() {
        if (iterations < 30) {
            iterations++
            Log.i(TAG, "transmitting")
            VirtualStickManager
                .getInstance()
                .sendVirtualStickAdvancedParam(virtualStickParam)
        }
    }
}, 0, 200)
```

The drone doesn't respond at all. I made sure the RC is under normal mode.
What am I missing here? Help would be really appreciated.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>I did not see any incorrect parts in your code. Can you reproduce the issue you encountered on the sample code?
In fact, there is no need to call VirtualStickManager.getInstance().init().
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
This same function in the sample code doesn’t work as well.
Thing that confuses me about this problem is that it doesn’t occur in my home when I tried it there. Even my code itself worked at home but didn’t work at the other location.
Could there be a reason why this is happening?

**Comment by Mulham6** [comment]
I just tried my code on a third location (a different park) and still didn’t work.

**Comment by dji-lyt** [comment]
If the aircraft can take off, taking the watch indicates that the aircraft can fly in this place. The only reason the aircraft does not respond to virtual joystick commands is that it has not received the command. Have you confirmed that the aircraft has entered VIRTUAL_STICK mode?
https://developer.dji.com/api-reference-v5/android-api/Components/SDKManager/DJISDKManager.html

**Comment by Mulham6** [comment]
Thanks for the reply. 
I was able to confirm that the aircraft does not enter VIRTUAL_STICK mode when this problem occurs.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>The aircraft will not respond to virtual joystick commands unless it enters VIRTUAL_STICK mode. Did you encounter any errors when calling enableVirtualStick?
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
When calling enableVirtualStick the overridden onSuccess() method of the callback object is being called.
Right around calling enableVirtualStick I notices these two error messages logged which could be related:

`05-20 12:40:31.131 28936 28936 E DJIV5/RXUtil: (onFailure:1) CeRegulatoryRestrictionEnable-onFailure true ErrorImp{errorType='CORE', errorCode='REQUEST_TIMEOUT', innerCode='', description='null', hint='error code = -3'} 
05-20 12:40:31.133 28936 29106 E DJIV5/AreaCodeManager@5fc9be5: (co_b:3) set regulatory enable failed: ErrorImp{errorType='CORE', errorCode='REQUEST_TIMEOUT', innerCode='', description='null', hint='error code = -3'} `

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>This log is only related to the EU region. Was your aircraft taking off in the EU region?
Could you please provide us with a video showing the issue of not being able to use the virtual stick? If the issue also exists in the sample code, we would appreciate it if you could test it using the sample code.

Here is the upload link for the video:https://pan-sec.djicorp.com/s/eiip3iLBZqeKYPp  password:YfbfmP
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
Aircraft was taking off in the EU region. Please keep in mind it works fine in my apartment (4.th floor) which is also in EU.
I‘ll upload the video soon.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>I will wait for you to upload the video.
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
I just uploaded the video.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>I think you can try calling enableVirtualStick after the aircraft has completed takeoff to put the aircraft into Virtual Stick mode.
<br><p><em><small>°°°</small></em></p>

**Comment by Mulham6** [comment]
It worked! Can’t believe it was that simple.
Thanks a lot for the help!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107116'>Zendesk ticket #107116</a>:<br><br>I am glad to help you.
<br><p><em><small>°°°</small></em></p>
