### ISSUE TITLE
SpeedDisplay and Attitude Display Widgets Options

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#329]
Hi DJI,

To show speed and height information I am using SpeedDisplayWidget and AttitudeDisplayWidget of UXSDK in my project but the value types are not what we need. for speed I need m/s but it is mph and there is no option to change it.

Also for attitude we need the value in "m" but it is in "ft" and also no option to change it.

Would you please help me change these types?

![Screenshot_20240513-095553](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/3d94eed3-62d7-4c99-a313-cdadef3bd032)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107216'>Zendesk ticket #107216</a>:<br><br>SpeedDisplayWidget and AttitudeDisplayWidget source code provide tools for modifying units, namely UnitUtils. You can modify units by viewing the source code of these two widgets and using UnitUtils.
<br><p><em><small>°°°</small></em></p>
