### ISSUE TITLE
[Feature Request] Extracting SRT files from drone via Android V5 Sdk

### ISSUE THREAD

**Issue by rstfmt** [dji-sdk/Mobile-SDK-Android-V5#332]
I think it would be highly beneficial if we are able to retrieve all SRT files from the drone along side the media files. Unfortunately the SDK currently does not support this. Is this currently in the SDK roadmap?
The drone I am using is the Mavic 3ET

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107402'>Zendesk ticket #107402</a>:<br><br>Currently, we do not have any plans to implement the feature of obtaining SRT files. This could be a feature that needs evaluation for the SDK, or even for drones. What do you intend to achieve by using an SRT file? Perhaps we can find a way to implement this feature in the current version.
<br><p><em><small>°°°</small></em></p>

**Comment by rstfmt** [comment]
We are currently using DJI drones to record mp4 files when doing inspections.  Each inspection requires the drone to fly along the same flight path say 1 month apart. We want to be able to easily look for differences from one inspection to the next on a frame by frame basis. Using the frame number alone is not enough because the drone doesn't take exactly the same duration to fly along the designated flight path because of a number of factors including wind, or sometimes the drone pauses during flight before continuing. As a result, we want to know the position of the drone for each frame in the mp4 file to make these comparisons easier to do.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107402'>Zendesk ticket #107402</a>:<br><br>Based on the situation you described, it seems that you strongly need a stable correspondence between the video and the aircraft's position. If that's the case, currently only SRT files can meet your needs. If a weaker correspondence is also acceptable, the SDK can provide real-time access to the aircraft's position.

I will gather your requirements. If possible, you can also submit a request at this address and inform us of the name of your company：https://sdk-forum.dji.net/hc/en-us/requests/new
<br><p><em><small>°°°</small></em></p>

**Comment by rstfmt** [comment]
I have submitted the request. 
Thank you.
