### ISSUE TITLE
Selected Lens For Capture Images

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#333]
Hi DJI,

In my application I just need to capture Thermal and Zoom images during the mission.

as we can see in this image, we have a widget to manage it but I need to use the sdk methods to handle it

But I can not find the related method. would you please tell me which method can give me the access to hndle it?

![Screenshot_20240516-112617s](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/868d3a6e-026c-4d09-8974-41c56f596b97)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107540'>Zendesk ticket #107540</a>:<br><br>MSDK currently does not provide similar widget, but it does offer configuration interfaces. You can refer to this article:https://sdk-forum.dji.net/hc/en-us/articles/27711939648025-How-to-configure-which-photos-are-stored-from-the-lenses
<br><p><em><small>°°°</small></em></p>
