### ISSUE TITLE
`ICameraStreamManager.FrameFormat.NV21` Produces Incorrect Colors

### ISSUE THREAD

**Issue by jreedy-riis** [dji-sdk/Mobile-SDK-Android-V5#334]
While working with the MSDK 5.8.0, we have noticed an issue present in the frame formats for the `cameraStreamManager.addFrameListener()`. It seems that the `FrameFormat.YUV420_888`, `FrameFormat.YUV444_888`, `FrameFormat.YUY2`, and `FrameFormat.NV21` produce a frame with incorrect colors. The only format that currently doesn't is `FrameFormat.RGBA_8888`. In my testing, this became present in the very first alpha version of 5.8.0 and is still present in 5.9.0. 

I have attached sample images to show the issue. The first image is a screenshot from the `putCameraStreamSurface`, the second image is from the `addFrameListener` with the format of `RGBA_8888` and the last image is of `NV21`. As you can see, the image from the controller and the `RGBA_8888` look very similar, however, when you compare it to the image taken from `NV21`, the image has colors that appear much darker, almost as if a filter is being applied on top. In addition, during my testing I have noticed details in darker areas of the image have become lost when using `NV21`.

Because of this issue, I cannot use the `NV21` frame format directly, I must first convert the `RGBA_8888` byte array to an NV21 byte array in order to get the correct format.

In my further testing, it also looks like the deprececated `.addYuvDataListener` also experiences this same issue on 5.8.0, but not on 5.7.0.

## Image Pulled from DJI RC Plus
![5 9-app_screen-cropped](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/87768696/3caf6a78-b140-4daf-b04d-8848f03d2779)

## Frame with `RGBA_8888`
<img width="1728" alt="5 9-normal-cropped" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/87768696/60a7ff91-cccd-4a01-b27d-a50225d51923">

## Frame with `NV21`
<img width="1728" alt="5 9-nv21-cropped" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/87768696/49fc9330-4d13-47e3-be54-de836f228491">

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107571'>Zendesk ticket #107571</a>:<br><br>Thank you for providing the photos, but the color differences don't seem to be significant, and they won't affect the recognition of the image. What are you trying to achieve with NV21?

Thank you.
<br><p><em><small>°°°</small></em></p>
