### ISSUE TITLE
uxsdk_setting_menu_title_hd_channel_mode and other trad missing

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#335]
Hi,

It seems some trads are missing in this file https://github.com/dji-sdk/Mobile-SDK-Android-V5/blob/dev-sdk-main/SampleCode-V5/android-sdk-v5-uxsdk/src/main/res/values/strings.xml

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/0bfd37df-e3c0-45a4-be35-f8f46ab37e7a)

Can you confirm and fix it if this is the case (I won't be able to get the right chinese translation myself) ?

Thks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107651'>Zendesk ticket #107651</a>:<br><br>It is possible to correctly obtain them in the 5.9 version of the UXSDK library.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes I did the bump last week, thks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107651'>Zendesk ticket #107651</a>:<br><br> You're welcome, I hope it helped you.
<br><p><em><small>°°°</small></em></p>
