### ISSUE TITLE
Error Handle LiveStream

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#336]
Hi,

Could you be more informative on error please:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/ade72be8-41da-482c-b986-842a23c6d021)

thks,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107667'>Zendesk ticket #107667</a>:<br><br>Could you please let us know how you triggered the issue you encountered? Also, what is the version of the SDK you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
cf  https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/339

We use last agp version and it seems to break the startStream function with unknown error

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107667'>Zendesk ticket #107667</a>:<br><br>Could lowering the AGP version prevent this issue from occurring? It seems that I don't encounter this problem when using the default AGP version{7.4.2) in the sample code.
<br><p><em><small>°°°</small></em></p>
