### ISSUE TITLE
IVideoStreamManager is deprecated since MSDK 5.8.0 but is still used in DefaultLayoutActivity and FPVWidget

### ISSUE THREAD

**Issue by EliasSSL** [dji-sdk/Mobile-SDK-Android-V5#337]
In the release notes of MSDK 5.8.0 the following is stated:
IVideoStreamManager will be deprecated starting from MSDK 5.8.0. Please use ICameraStreamManager for stream management functions.
Even though this was deprecated, the default layout activity and the FPVWidget in the UXSDK still  use those deprecated functionalities in version 5.9.0. When will this be updated?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107673'>Zendesk ticket #107673</a>:<br><br>I have not received any plans for the update of FPVWidget at the moment.
In fact, although the 5.8 version of FPVWidget uses VideoDecoder, the underlying layer is already CameraStreamManager of 5.8.
<br><p><em><small>°°°</small></em></p>
