### ISSUE TITLE
Couldn't load lib

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#339]
This ticket (https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/293) has been closed, but it seems that since last release  MSDK 5.9.0 with minSDK 23 we get the "Unkown error" on startLiveStream method.

The doc tells to change the min sdk to 21 but we can't because of conflicting version:
https://sdk-forum.dji.net/hc/en-us/articles/13201276673689-What-happen-if-the-startLiveStream-returns-an-unknown-error

What is the "normal solution" here to get the startLiveStream working here with last release

By the way, would you consider to merge this PR https://github.com/dji-sdk/Mobile-SDK-Android-V5/pull/242 since it seems critical too 

Thks,

**Comment by antonymarion** [comment]
Ok fixed, for your information the bug appears when left part is active

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/d96d29cf-18a0-4bc0-9be4-f3bf82c8aaf3)

So it seems that the SDK is very sensitvie to gradle and android versions

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107865'>Zendesk ticket #107865</a>:<br><br>The issue of users encountering exceptions on Gradle version 8 has been brought to our attention. Therefore, we would like to advise users to consider using the recommended version provided in the sample code, which is 7.4.2.

Thank you.
<br><p><em><small>°°°</small></em></p>
