### ISSUE TITLE
Live Streaming is buggy (lagged)

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#340]
Hi,

We bumped to last release and use the startStream

but we get this log (it was not the case before)

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/713ac90e-6049-4bda-87d1-dc19e41dfafb)

Regards

**Comment by antonymarion** [comment]
For your information we tested both on our app using the SDK from DJI and on the DJI sample app (this repo) without changing anything to the repo... and we get the same issue: red logs and laggy stream

If we use ffmpeg over linux (to check if it comes from our side) there is no issue and the stream is not lagged.

The device we use is a Mavic 300 RTK.

**Comment by antonymarion** [comment]
=> https://dl.djicdn.com/downloads/matrice-300/20240516RN/M300_RTK_Release_Notes_en_20240516.pdf

OK just read the RN here, and I believe with last firmware it should do the trick

**Comment by antonymarion** [comment]
I checked my firmware's versions and it is ok (up to date), so opened instead a ticket here: https://sdk-forum.dji.net

It looks like 0x19100002 is MRTC_ERROR_TIMEOUT ERROR code and code = 420478978 is https://sdk-forum.dji.net/hc/zh-cn/articles/12585337259033-%E4%B8%BA%E4%BB%80%E4%B9%88%E7%9B%B4%E6%92%AD%E6%8E%A8%E6%B5%81%E6%97%B6%E7%A0%81%E7%8E%87%E4%BC%9A%E7%AA%81%E7%84%B6%E9%99%8D%E5%88%B00

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107883'>Zendesk ticket #107883</a>:<br><br>I have tested the sample code based on your description and did not encounter a similar issue. Could you please inform us about the type of live streaming you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I am using liveStream.setRTMPConfig with the same RTMP server as previously and the same channel (and the same 300 RTK :D )

**Comment by antonymarion** [comment]
In case the information is usefull for your debugging purpose, here is the log I get from OvenMediaStream

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/584adf25-31bb-4044-9357-71f6dc879cca)

SRS does not show human readable logs, so I prefer OvenMediaEngine

**Comment by antonymarion** [comment]
Reverting to 5.8.0 fixed my issue

**Comment by dji-lyt** [comment]
“If we use ffmpeg over linux (to check if it comes from our side) there is no issue and the stream is not lagged.”
How should I interpret this sentence? Will there be no latency issues if you switch to using ffmpeg to get the live stream?

**Comment by antonymarion** [comment]
Exactly, no issue if I use ffmpeg instead to send a live stream to RTMP server

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107883'>Zendesk ticket #107883</a>:<br><br>Could you please provide us with two versions of sample code for starting a live stream for comparison? Here is the upload link:https://pan-sec.djicorp.com/s/aKr4oE2T59nBREY password:dji123
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
The issue has been identified with a reproducible method and will be escalated to the engineers for resolution.

**Comment by antonymarion** [comment]
Just to have an ETA, when can we expect to have the hoftix for this?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107883'>Zendesk ticket #107883</a>:<br><br>We are currently analyzing this issue. I will notify you here once I have the estimated time.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Just to let you know I reproduced the same issue on the mini 3 Pro too.

So I believe it is general (at least it exists for mini 3 Pro and 300 RTK)

**Comment by antonymarion** [comment]
I saw you released v5.9.1 for this ticket.

I am going to integrate it, thks

**Comment by antonymarion** [comment]
Tested. Fixed.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107883'>Zendesk ticket #107883</a>:<br><br>I'm glad that your issue has been resolved. If you encounter any exceptions while using the Mobile SDK, feel free to reach out to us.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes I did it already here:

- #365 
- #364 
- #367

the new release has breaking change regarding the API. It makes the code not maintenable when switching to last published version.

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/f92db4d1-3f65-4df3-aa66-708182969614)
The CameraStreamListVM has not been modified in versions 5.9.0 and 5.9.1. You can view its modification history on GitHub. In fact, we cannot guarantee that the ViewModel of the sample code will remain unchanged, but we will ensure that the SDK interface will not change casually.
Could you please provide us with a more detailed description if I have misunderstood your question?

**Comment by antonymarion** [comment]
One of our developpers has changed your source code that's why ...

Sorry for the disturbance!
