### ISSUE TITLE
Bit rate change in release 5.9.0

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#341]
Hello Dear DJI's developpers,

I see this change regarding the versions 5.8.0 versus 5.9.0

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/5c442188-fc58-4b7c-9f35-a5e3fb1b7aea)

But Youtube recommends the following bitRate for instance
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/d7177922-7c4f-4358-9d63-eb8ff937c820)

Could you explain to us why you did this change, and maybe it is not worth to bump to last release in this case, right (because I noticed some degraded frames sometimes like below) ?

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/1d5115d6-e110-40c4-a729-5e99207e0f36)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107932'>Zendesk ticket #107932</a>:<br><br>We have confirmed the live streaming bitrate with the team. Version 5.9 has not made any changes to the live streaming bitrate, so it is the same as version 5.8. However, there have been changes in the API documentation. The reason for this is that the bitrate provided in the previous documentation was not accurate, and this update has now made it accurate. The bitrate for HD mode should be 168KByte/s.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Good to know, so doc is now synchronized, thks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107932'>Zendesk ticket #107932</a>:<br><br>I'm glad I could help you.
<br><p><em><small>°°°</small></em></p>
