### ISSUE TITLE
Suggestion to remove dependency on kotlin-android-extensions in UXSDK.

### ISSUE THREAD

**Issue by Merpyzf** [dji-sdk/Mobile-SDK-Android-V5#343]
In Kotlin 1.8, Android has removed **kotlin-android-extensions** (this happened in 2022), while UXSDK still includes a dependency on **kotlin-android-extensions**. This means that I cannot use Kotlin versions greater than 1.8 in my project. If I want to use Kotlin 1.8 or above, I must manually remove kotlin-android-extensions from UXSDK (I have tried this and it can be done within half an hour. If 100 people have the same requirement, it will take 100 * 30 minutes to do this migration, which is very inconvenient. Time is precious☹️).

In 2024, most developers will choose to use Compose for UI development. The latest Compose requires Kotlin version 1.9 or above. I hope the official team can remove **kotlin-android-extensions**.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108296'>Zendesk ticket #108296</a>:<br><br>The UXSDK component is developed based on kotlin 1.7, it indeed use **kotlin-android-extensions**. I understand your requirement, and I will convey it to the team, but it may not be achievable . In terms of usage, the presence of kotlin-android-extensions does not prevent you from using the UXSDK, and optimization issues of the UXSDK will have a lower priority than those of the MSDK.
<br><p><em><small>°°°</small></em></p>
