### ISSUE TITLE
Problem accessing the DNS

### ISSUE THREAD

**Issue by fail572872916** [dji-sdk/Mobile-SDK-Android-V5#344]
rtmp地址正确，用poliot2可以直播
用sdk5.9.0不可以
![QQ截图20240529133250](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/19763500/b48b7e3c-e130-446e-a619-9d894cf93e9e)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108494'>Zendesk ticket #108494</a>:<br><br>日志显示RTMP初始化失败了。相同网络的情况下，Pilot 2推流正常，您使用MSDK 5.9的示例代码可以推流吗？
<br><p><em><small>°°°</small></em></p>

**Comment by fail572872916** [comment]
> Agent comment from yating.liao in [Zendesk ticket #108494](https://djisdksupport.zendesk.com/agent/tickets/108494):日志显示RTMP初始化失败了。相同网络的情况下，Pilot 2推流正常，您使用MSDK 5.9的示例代码可以推流吗？
> 
> _°°°_

用了5.9的示例也有一样的错误

**Comment by dji-lyt** [comment]
您尝试使用最新的示例代码是否还会有一样的错误？如果有，能否提供给我们一份完整的日志？

**Comment by fail572872916** [comment]
> 您尝试使用最新的示例代码是否还会有一样的错误？如果有，能否提供给我们一份完整的日志？
目前没有发生了
