### ISSUE TITLE
How to reset Sharpness and Noise to 0 via SDK 5?

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android-V5#346]
When attempting to reset the Camera Sharpness and Noise levels to 0 I get the error: `KEY_MISS_EXECUTION_FUNCTION`

Code:
```kotlin
CameraKey.KeyDigitalDenoising.create().set(0, {
    Log.d("KeyDigitalDenoising", "KeyDigitalDenoising completed successfully")
}, { error ->
    Log.e("KeyDigitalDenoising",error.errorCode())
})

CameraKey.KeySharpness.create().set(0, {
    Log.d("KeySharpness", "KeySharpness completed successfully")
}, { error ->
    Log.e("KeySharpness",error.errorCode())
})
```

Is this the right way to reset these settings? These are the corresponding settings in DJI Fly:

![Screenshot 2024-05-29 at 5 33 30 PM](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/11700939/13e5ca01-d478-4bc5-adb6-850f8ea40484)

Mini 3 Pro
SDK Version: 5.8.0

**Comment by brien-crean** [comment]
I also tried resetting all camera parameters and the completion handler never runs. The command never completes.

```kotlin
CameraKey.KeyResetCameraSetting.create().set(null , {
    Log.d("KeyResetCameraSetting", "KeyResetCameraSetting COMPLETE")
}, {
    Log.d("KeyResetCameraSetting", "KeyResetCameraSetting ERROR ${it.errorCode()}")
})
```

**Comment by dji-lyt** [comment]
Please wait for a while for the sharpness and noise reduction settings, as we are currently confirming with the team.
KeyResetCameraSetting is an action interface, so instead of using "set," you should use "performAction.
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/446557a6-8ad3-499b-ad32-b6574dd0773b)

**Comment by brien-crean** [comment]
Thank you @dji-lyt I will try that. We would prefer to just reset the sharpness and noise settings on their own if possible so I will wait for your reply on that question. Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108562'>Zendesk ticket #108562</a>:<br><br>KeySharpness is a Key for setting sharpness, but it is also an no open Key. I tested its effect on the DJI MINI 3 PRO and obtained the same results as the issue you described. I believe the current version of the SDK does not support settings for the DJI MINI 3 PRO.

In what scenarios would you use this feature? What purpose does it serve?
<br><p><em><small>°°°</small></em></p>
