### ISSUE TITLE
GpsSignalWidget Bug Report

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#347]
Hi DJI,

I use UXSDK in my project and GpsSignalWidget in my toolbar. during the flight with Mavic 3T, as you can see in the picture, the RTK was connected (to RTK base station), but the icon in the toolbar was showing no connection.

it does not happen always, but some time I see it. how can I solve it ?

![photo_2024-05-30_09-06-55](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/9bf7f524-3279-4dc6-84b0-677af3e21dbf)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108619'>Zendesk ticket #108619</a>:<br><br>
Which version of the UXSDK library that you are using was released with which MSDK version? Additionally, will the same issue appear in our sample code?
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaei** [comment]
I am using the latest version of the UXSDK and Mobile SDK (5.9). I did not test the sample code because I was during a real mission.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108619'>Zendesk ticket #108619</a>:<br><br>We would like to know the steps to reproduce this issue and also confirm if this issue can be replicated in the project that we have access to.
<br><p><em><small>°°°</small></em></p>
