### ISSUE TITLE
御三消费机无人机可以使用这个sdk吗

### ISSUE THREAD

**Issue by CtrlAndZ** [dji-sdk/Mobile-SDK-Android-V5#349]
御三系列的消费级无人机可以使用这个sdk开发自定义的功能吗

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/108687'>Zendesk ticket #108687</a>:<br><br>抱歉，御3消费级无人机不支持SDK开发。
<br><p><em><small>°°°</small></em></p>
