### ISSUE TITLE
How does KeyLookAt works?

### ISSUE THREAD

**Issue by IakovlevAA** [dji-sdk/Mobile-SDK-Android-V5#350]
Hi, I tried to run this function on Mavic Mini 3 Pro simulator(with SimulatorManager.getInstance().enableSimulator), but can't get anything. However, app indicates that executing command return success. In my thoughts, when I use KeyLookAt drone will calculate azimuth between 2 coordinates and rotate to it, but heading of drone doesn't change

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108741'>Zendesk ticket #108741</a>:<br><br>The LookAt feature is not supported on the Mini 3 Pro, so you won't be able to see the effect on the Mini 3 Pro.
<br><p><em><small>°°°</small></em></p>
