### ISSUE TITLE
KeyGimbalAttitudeRange returns bad values..

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#351]
Hi Dji,

the following key returns, for instance, for 300 RTK and for the pitch

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/bc340d16-bf40-4cc3-ba1d-1e1298194b2a)

and using GimbalKey.KeyGimbalAttitudeRange, it returns for the max  45

But it is, according to the specification: 30

Cheers,

**Comment by dji-lyt** [comment]
KeyGimbalAttitudeRange is a key that is not open. In fact, it cannot return the correct gimbal attitude range on some drones. You need to use the rotatable range provided by the drone to determine the rotation range.
https://enterprise.dji.com/zenmuse-h20-series/specs
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/c859d836-a3cb-4c22-ac1d-805a342d9eee)

**Comment by antonymarion** [comment]
Well, good to know, do you have the whole list of DJI's drones that returns erronous values?

On top of that can you provide us please the information of the keys we should (open) use versus the key we should not use (closed?)

Regards,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108769'>Zendesk ticket #108769</a>:<br><br>
We currently do not have a comprehensive list of drone errors. Below are the meanings of common errors:


- errorCode='REQUEST_TIMEOUT' hint='error code=-3' -- Timeout
- NOT_SUPPORT -- Not supported
- REQUEST_HANDLE_NOT_FOUND -- Incorrect parameter or device not supported

All keys provided in the API documentation are open. For keys not found in the API documentation, we will consider them as closed keys. You need to verify their effectiveness before considering their use.。
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I have found several "open" keys still not working.. ProduckKey for instance. 

cf https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/358

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108769'>Zendesk ticket #108769</a>:<br><br>You can check the latest replies at https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/358. KeyProduceType is available for use, perhaps there is an error in your invocation timing.
<br><p><em><small>°°°</small></em></p>
