### ISSUE TITLE
GimbalKey.KeyFirmwareVersion returns null on Mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#354]
Hi Dji,

The same code on 300 RTK or Mini 3 pro does not behave the same.

Working on 300 RTK, but null on Mini 3 pro.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108809'>Zendesk ticket #108809</a>:<br><br>It seems that DJI FLY has not provided the firmware version for the Gimbal. What do you need to achieve with this version?
<br><p><em><small>°°°</small></em></p>
