### ISSUE TITLE
CameraKey.KeyCameraZoomRatiosRange returns bad values on mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#355]
Hi Dji,

Calling CameraKey.KeyCameraZoomRatiosRange along with cameraIndex and lens, returns, on mini 3 Pro (if Aircraft is disconnected): `[2,5,10,20,40,80,160,200]`

It should return `null`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br> I obtained the range [1,2] using the latest version to test CameraKey.KeyCameraZoomRatiosRange. This is the correct value.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I will test it again then and let you know, thks

**Comment by antonymarion** [comment]
I checked twice (again), here are the values:

"zoomRatiosRange":[2,5,10,20,40,80,160,200]
"thermalZoomRatiosRange":[1,2,4]

Dji Aicraft is OFF, RC PRO is used
I connected (registered) a mini3Pro to this this RC Pro

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br>Could you obtain the correct range if RC connect to the aircraft?
How does this issue currently affect you? I have replicated this issue on the remote controller.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes if I connect it it's ok, but it should not return erronous values otherwise.. that's the bug

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br>Could you please share with us the impact it has had on your usage process to assess the severity of this issue? We would appreciate your feedback.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
it's quite critical for us since we rely on the values transmitted, and for instance I notice that if there is no GPS then we will get this kind of values...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br>Could you confirm if the situation you mentioned, where not having GPS results in this value, refers to another scenario that triggers this issue? I believe this problem should only occur when the remote control is not connected to the drone while calling CameraKey.KeyCameraZoomRatiosRange.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
It should not happen at all. Connected or not.

If not connected why does it return erronous values and not null (since not connected) ?

Or throw an error.

It happens when rc is not connected to aircraft.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br>The absence of GPS signal on the aircraft is not another triggering method for the issue you mentioned, is that correct?

I understand the information you provided, but practically speaking, when the remote controller is not connected to the drone, even if you receive an incorrect range, you won't be able to set up the drone. From this perspective, it won't hinder your normal usage. We would like to assess the impact of this issue on your usage to understand its severity.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
it is critical since it means the SDK is not reliable when drone is disconnected (battery off, or starting but not connected yet).

A normal behaviour should be to return an error on the call to the SDK or to return null

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108810'>Zendesk ticket #108810</a>:<br><br>I will provide the team with your feedback.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
Version 5.10 has fixed it.
