### ISSUE TITLE
DJI SDK V5 LRF  

### ISSUE THREAD

**Issue by hyunah96** [dji-sdk/Mobile-SDK-Android-V5#356]
Hello, is the LRF feature implemented in DJI SDK V5? I am using the M300 with the H20T

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108880'>Zendesk ticket #108880</a>:<br><br>Is the LRF feature you mentioned referring to video compression functionality? The Mobile SDK V5 does not have this feature.
<br><p><em><small>°°°</small></em></p>

**Comment by hyunah96** [comment]
I'm curious if the LRF (Laser Range Finder) feature available in the DJI Pilot 2 app can be implemented using SDK v5

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/5f5a5d30-4a8a-4026-af4e-4b5029946f1d)

MSDK V5 can enable laser ranging and obtain ranging information. The image shows the corresponding interface.
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html

**Comment by hyunah96** [comment]
MSDK V5 mentions that laser range finding can be activated and distance measurement information can be obtained. Where is the button to activate the laser range finding?

![Screenshot_20240814-133816](https://github.com/user-attachments/assets/1c7341a3-5be8-4d57-9e78-60de018de650)
![Screenshot_20240814-133810](https://github.com/user-attachments/assets/c276e824-1321-403d-a411-2d84e65827c9)

**Comment by hyunah96** [comment]
I am currently working with DJI SDK V5 and I need to use the KeyLaserWorkMode. However, I couldn’t find any information, sample code, or official documentation that explains how to use KeyLaserWorkMode. Could you please provide guidance or examples on how to properly implement and utilize this function?
Thank you for your support.

mycode
```
            LaserWorkMode laserWorkMode = LaserWorkMode.OPEN_ALWAYS;
        LaserMeasureInformation laserMeasureInformation = new LaserMeasureInformation();


        KeyManager.getInstance().setValue(DJIKey.create(CameraKey.KeyLaserWorkMode), LaserWorkMode.OPEN_ALWAYS, new CommonCallbacks.CompletionCallback() {
            @Override
            public void onSuccess() {
                Log.d("test","key onSuccess");
                if(laserMeasureInformation.getDistance() != null)
                Log.d("test","laserMeasureInformation.getDistance();" + laserMeasureInformation.getDistance());
            }

            @Override
            public void onFailure(@NonNull IDJIError idjiError) {
                Log.d("test","key onFailure");

            }
        });
```
