### ISSUE TITLE
Getting UAS on SDK V5 with both 300 RTK and mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#357]
Hi Dji,

This does not seem to work

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/5276e4b1-8f7f-43a0-845a-5df672d1fc07)

How could I make it work?

Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108921'>Zendesk ticket #108921</a>:<br><br>If you have set a registration number, you can use this interface to obtain the registration number information.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
```
UASRemoteIDManager.getInstance().setUARegistrationNumber(
            "MYUAS",
            object : CommonCallbacks.CompletionCallback {
                override fun onSuccess() {
                    Log.d("DJI", "setUARegistrationNumber success")
                }

                override fun onFailure(error: IDJIError) {
                    Log.e("DJI", "setUARegistrationNumber error: " + error.description())
                }

            })

```

returns ` setUARegistrationNumber error: Not supported.`

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/fda48ec3-8070-4b58-b82e-adc1383ef18e)
Could you please inform us of your location? The API documentation indicates that setUARegistrationNumber is not a feature supported in all regions. For example, in Japan, pilots need to obtain a registration code to demonstrate their qualifications, so this interface can be used to set the registration code.

**Comment by antonymarion** [comment]
We live in France (and love wine and cheese)

cheers,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108921'>Zendesk ticket #108921</a>:<br><br>https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/compliance-eu.html
you could review this article first. Not all aircraft in EU countries require the use of setUARegistrationNumber to set the registration code. Among the aircraft you mentioned, the M300 RTK does require it. Please verify if the aircraft firmware is up to date and then follow the process outlined in the tutorial to set the registration code.
<br><p><em><small>°°°</small></em></p>
