### ISSUE TITLE
Same code working on 300 RTK but not on Mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#358]
Hi Dji

I am printing the datalink type, firmware version and product Uuid

OK on 300 RTK
Same code fails on mini 3 Pro

`uavDataLinkType = KeyManager.getInstance().getValue(KeyTools.createKey(
                        ProductKey.KeyDataLinkType)).toString()
                    uavFirmwareVersion  = KeyManager.getInstance().getValue(KeyTools.createKey(
                        ProductKey.KeyFirmwareVersion)).toString()
                    uavProductUUid  = KeyManager.getInstance().getValue(KeyTools.createKey(
                        ProductKey.KeyProductUUID)).toString()
`

Notice: 

SN and ProductEdition does not work on both drones..

` uavProductType = KeyManager.getInstance().getValue(KeyTools.createKey(
                        ProductKey.KeyProductType)).toString()
                    uavProductEdition = KeyManager.getInstance().getValue(KeyTools.createKey(
                        ProductKey.KeyProductEdition)).toString()
`

Please provide us a list of working/non working features in your SDK

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>API documentation provides interfaces that have been verified to be stable for use. We cannot guarantee the effectiveness of interfaces not documented, so they may present different issues on different device models.
https://developer.dji.com/api-reference-v5/android-api/Components/SDKManager/DJISDKManager.html
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
These keys are in your doc; So how should I know there are not working?

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/91ea143c-046a-4939-9521-c238d85e40e1)

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/aa00a658-9c29-47d1-bb8f-422a226e5bb3)
The KeyProductType is functioning properly. You may consider utilizing a callback to retrieve the results. It is important to ensure that the Product is connected before attempting to retrieve the ProductType.

**Comment by antonymarion** [comment]
Could you please add in the doc the information of the Key that needs callback/subscribe/listening mechanism versus other ?

It would ease developpers' usage of this SDK (since now the only way to discover it is investigating the Sample DJI Code..)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>KeyProductType is not a Key that can only be used with a listener. If this is your first time calling KeyProductType, we recommend using listen. This is because the SDK takes some time to recognize the device, and calling the get interface before the device is recognized can lead to the issue you are experiencing, whereas the listener will not.

I will try to pass your suggestion on to the documentation engineer.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I used the following ProductVM class.

I put some breakpoint to debug what happens.
It goes to the `listenProductKey` fun but never goes in the callback of the` listen(this) { }`

```
class ProductVM : DJIViewModel()  {
    private var productType: ProductType? = null

    init {
        listenProductKey()
    }

    private fun listenProductKey(){
        ProductKey.KeyProductType.create().listen(this) {
            Log.d("DGEO", "productType=$it")
            if (it != ProductType.UNRECOGNIZED && productType != it) {
                productType = it
            }
        }
    }

}
```

Could you please show us a working code snippet, thks (I am testing it on 300 RTK)

**Comment by antonymarion** [comment]
I updated to last firmware and it's OK on mini 3 Pro

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>Could you please confirm if this issue will still occur on the M300 RTK? It is important to note that the Key listener should be set after a successful registerApp.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
No it's ok once updated on mini 3 Pro, I will test it also on M300 RTK and let you know

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>Thank you, I will wait for the results of your test.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
It is not working after test for both productEdition and productType for 300 RTK..

**Comment by antonymarion** [comment]
For your information it does not come from a timing issue, since I tested also with a 5s timer and productEdition and Type are still not filled...

Whereas uavFirmwareVersion is filled using the same kind of call (`Key.listen(this) {}`)

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/f46abc39-4ce7-4acc-a1eb-df8080f0eb08)
I have no problem testing the value of KeyProductType.

**Comment by antonymarion** [comment]
Well you modified the source code of the MSDKManagerVM kotlin file.

I don't believe the SDK should be used modifying the source files.

Could you please provide a working snippet calling the SDK in a separated file (DJIMainActivity.kt for instance) and calling the SDK

For instance using observer `msdkManagerVM.lvRegisterState.observe(this) {` and depending on the `resultPair`, for instance here:
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/d5844b73-346f-461c-9b1e-a240088e08f7)

Will ProductKey work here instead ?

**Comment by dji-lyt** [comment]
The correct way is actually to set the listener after OnRegisterSuccess. If you are unable to get the listener in the sample code, Could you provide me with the steps you followed to reproduce the issue？
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/2bcc217d-12be-40a6-83ca-0757579953f9)

**Comment by antonymarion** [comment]
Well it goes to observeSDKManager

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/1685281e-bdb4-49fd-ae53-5b3275f7ff16)

but never to the resultPair.first { ... }

OK got it, it never goes to the resultPair when the RC is in standby Mode (dark screen)

By the way I believe the pb is the same with the productKey: if the RC screen is Black (kind of standby mode, no access to productsKey).

But this behaviour is very weird, since with blackScreen on RC we can move Gimbal, set Zoom, change lenses etc etc..

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>Could you confirm if using the MSDK interface to set the zoom length on the remote control while it is in standby mode was successful?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Well, I dont get it..

I If use the RC it will not be any more in standby mode.

So it wil surely work because using your app we have to touch the screen.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108923'>Zendesk ticket #108923</a>:<br><br>How should I interpret this sentence “But this behaviour is very weird, since with blackScreen on RC we can move Gimbal, set Zoom, change lenses etc etc..”？
Could you perform these actions using the buttons on the remote control?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Why was it closed, is it fixed?

**Comment by dji-lyt** [comment]
It appears that you have not updated this issue, and based on the context, we are unable to replicate your problem.

**Comment by antonymarion** [comment]
Ok I will provide you on November more details to ease reproduction scenario
