### ISSUE TITLE
WaylineAltitudeMode.REAL_TIME_SURFACE_FOLLOW

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#359]
Hi DJI,

I want to ask you a question about "WaylineAltitudeMode.REAL_TIME_SURFACE_FOLLOW". 

currently I am using "WaylineAltitudeMode.RELATIVE_TO_START_POINT" for my missions to have a flat flight based on the flight height I send to the drone.

But If I want to flight on some curved places like Hills, if I set "WaylineAltitudeMode.REAL_TIME_SURFACE_FOLLOW" and set flight height 15, it will fly 15 meter above the ground and follow dtm automatically ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/109088'>Zendesk ticket #109088</a>:<br><br>Yes. The aircraft will fly at a position 15m above the ground. The aircraft will automatically track the DTM.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Thank you so much for your response. to use this feature, do we need to upload any specific file or setting? or just adding the WaylineAltitudeMode to REAL_TIME_SURFACE_FOLLOW is enought to active this feature?

**Comment by PeimanAtaeiJPDroni** [comment]
And one more question, also there is one more option: "WaylineAltitudeMode.ABOVE_GROUND_LEVEL"

1- What is the difference between "ABOVE_GROUND_LEVEL" and "REAL_TIME_SURFACE_FOLLOW" ?

2- and to use "ABOVE_GROUND_LEVEL" I should upload any dtm file also?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/109088'>Zendesk ticket #109088</a>:<br><br>Please use the REAL_TIME_SURFACE_FOLLOW mode for terrain following. This mode allows terrain following without the need to upload terrain files. However, please note that this feature is only supported on M3E, M3T, and M3M. Additionally, ABOVE_GROUND_LEVEL cannot be achieved through the mobile SDK.
<br><p><em><small>°°°</small></em></p>
