### ISSUE TITLE
Is WebRTC implemented?

### ISSUE THREAD

**Issue by John2397** [dji-sdk/Mobile-SDK-Android-V5#36]
Is WebRTC protocol supported on MSDK V5? (As mentioned [here](https://github.com/dji-sdk/Mobile-SDK-Android/issues/1103#issuecomment-1031047802)?)

Is there a documentation on how to start the Web RTC live stream?

**Comment by DJI-William** [comment]
Yes, please read this article, [Chapter 6: Live Streaming](https://sdk-forum.dji.net/hc/en-us/articles/6663305630105-Chapter-6-Live-Streaming). Also, the webRTC demo is embeded inside this sample.
