### ISSUE TITLE
MSDK 5.9.0 causes app to start multiple processes

### ISSUE THREAD

**Issue by rayw-dronesense** [dji-sdk/Mobile-SDK-Android-V5#360]
## Environment

**MSDK:** 5.9.0
**Devices:** Samsung S23 (SM-S911U1), DJI RC Pro Enterprise

## Repro steps

1. Pull down MSDK Sample App for 5.9.0
2. Install SDK API keys
3. Build and install the app on the device

**Expected behavior:** One process is started when app is run

**Actual behavior:** Multiple processes for the app are started at the same time

```
---------------------------- PROCESS STARTED (2976) for package com.dji.sampleV5.aircraft ----------------------------
---------------------------- PROCESS STARTED (3006) for package com.dji.sampleV5.aircraft ----------------------------
```

This did not occur with MSDK 5.8.0.

**Comment by antonymarion** [comment]
Got the same issue today on RC Pro too

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109109'>Zendesk ticket #109109</a>:<br><br>Could you please inform us about the impact caused by the two processes on your usage?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
It's critical since we send informations regularly to remote desktops and then we have duplicates..

And I noticed (as a side effect of this bug) that once we have 2 processes at least, then our messaging system with the Remote Control and the Desktops does not work any more. Surely because we have the same client twice on the RC, and that breaks the communication.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109109'>Zendesk ticket #109109</a>:<br><br>I will go and check the issue you mentioned. Please wait for a while.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
thks, I confirm this is still on last release too
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/5cacc511-0aa5-477d-98a1-1f8105d4b118)

**Comment by dji-lyt** [comment]
I found that there is only one process when testing with a empty project of version 5.9.1, but there are indeed two processes in the sample code. Does the software in the actual production environment also have this issue?
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/28735d06-2a57-4845-9e75-314170a5c789)

**Comment by antonymarion** [comment]
Of course in production the issue occurs too

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109109'>Zendesk ticket #109109</a>:<br><br>I have conducted further testing on this issue. If you install the example code of MSDK 5.9.1 using the release version of the APK, only one process will run at this time.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Does not seem to be resolved on RC for 300 RTK guys.

For instance I have messages from RC sent twice from my sample App modified and it comes from the same issue on the multiprocess (2 to be precise) bug..

![image](https://github.com/user-attachments/assets/e5b2e090-1e0b-442b-8c92-512b32cdb6e1)

and we use a version integrating your release 5.9.1
![image](https://github.com/user-attachments/assets/054f10fb-fc80-4d20-84c2-9f95f4b20297)

**Comment by antonymarion** [comment]
For more precision, we are not using release version but this bug should not depend of the type of the build.

A debug or release build should produce the same behaviour for testing the RC right ?

**Comment by antonymarion** [comment]
In order to test the release build and compare what do we have to put inside the jks file please:
![image](https://github.com/user-attachments/assets/056e80d0-67a4-494b-a372-9db384ad846e)

**Comment by antonymarion** [comment]
OK found the issue with the release build:  the msdkkeystore.jks does not seem to be store in the right place when pulling the repo, I moved it to the path looked for by Android Studio then..

**Comment by antonymarion** [comment]
Does last version 5.10 fix that in debug mode too ? Since in the release note, it does not mention any fix about the multiprocess issue for debug..
