### ISSUE TITLE
Widget to adjust manual focus?

### ISSUE THREAD

**Issue by ljustice-riis** [dji-sdk/Mobile-SDK-Android-V5#362]
Is there an equivalent to the `ManualFocusWidget` from the v4 SDK to adjust the focus of the camera while manual focus is enabled? Or do all developers using manual focus need to create a custom slider to adjust KeyCameraFocusRingValue?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/109113'>Zendesk ticket #109113</a>:<br><br>
We regret to inform you that MSDK V5 does not have such a widget. You will need to implement it yourself.
<br><p><em><small>°°°</small></em></p>

**Comment by ljustice-riis** [comment]
Noted. Thanks for the heads up. This widget would be much appreciated if it was added later down the line as it would work very nicely with the default manual focus toggle widget.

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/109113'>Zendesk ticket #109113</a>:<br><br>I apologize for the inconvenience. At the moment, there are no immediate plans for this. To avoid any impact on the progress of your project, we recommend that you implement this widget on your own.
<br><p><em><small>°°°</small></em></p>
