### ISSUE TITLE
Release 5.9.1 - Breaking Change

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#365]
Hi Dji

On previous releases, availableCameraListData used to be :

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/31145bb9-d8a2-4971-ae13-aa9b466f3cbf)

it is now a simple String from following Enum:

`LEFT_OR_MAIN,
    RIGHT,
    UP,
    FPV,
    UP_TYPE_C,
    AGGREGATION,
    UNKNOWN`

As we are using your SDK to trigger some behaviour based on it, could you please take care to mention this breaking change in the release Note, and to avoid this kind of breaking change to ease usability and maintenance of the code

Regards,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109466'>Zendesk ticket #109466</a>:<br><br>I'm having trouble understanding your question. Are you asking if there are differences in AvailableCameraUpdatedListener between versions 5.8 and 5.9?

It's important to note that AvailableCameraUpdatedListener is a new listener type introduced in version 5.8. Prior to version 5.8, StreamSourceListener was used, but it is now deprecated.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
the format of the object `availableCameraListData` has changed

**Comment by dji-lyt** [comment]
CameraStreamListVM has not been modified since version 5.8. Also, the definition of availableCameraListData has not changed. What version were you using before?

**Comment by antonymarion** [comment]
One of our developpers has changed your source code that's why ...

Sorry for the disturbance!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109466'>Zendesk ticket #109466</a>:<br><br>Don't worry about it. As long as you have found the cause of the issue, it's fine.
<br><p><em><small>°°°</small></em></p>
