### ISSUE TITLE
AF/MF Wide Camera

### ISSUE THREAD

**Issue by ignacioalpiste** [dji-sdk/Mobile-SDK-Android-V5#366]
Hi,
Product: M30T
By default, in the uxsdk the MF is activated. When I press AF/MF widget when showing the video from the wide camera, the widget highlights AF and then returns the highlight to MF. 

However, for the Zoom camera it works fine.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109555'>Zendesk ticket #109555</a>:<br><br>The wide lens of the M30T cannot be set to focus mode. This can be confirmed on the Pilot 2. When the display shows a wide view, the focus option will disappear, and it will appear when switching to the zoom view.
<br><p><em><small>°°°</small></em></p>
