### ISSUE TITLE
Laser Range Finder Limitations

### ISSUE THREAD

**Issue by ignacioalpiste** [dji-sdk/Mobile-SDK-Android-V5#368]
As far as I understand, the distance captured by the LaserRangeFinder (within LaserMeasureInformation) represents the distance to the ground at the centre of gravity of the screen. By default, the targetPoint is set to (50,50).

Upon exploring the LaserRangeFinder API, I noticed that the targetPoint can be set between 0 and 1000. However, when attempting to retrieve the distance for a different part of the screen, the distance value remains unchanged.

1) Is it possible to obtain the distance to an object at different areas of the screen using the targetPoint parameter?
2) Why is the default targetPoint set to (50,50) instead of (500,500), which would be the center of the screen in a 1000x1000 coordinate system?
3) Is this behaviour a limitation of the LaserRangeFinder API, or is it due to hardware constraints?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109701'>Zendesk ticket #109701</a>:<br><br>Setting the targetPoint in LaserMeasureInformation is invalid, as LaserMeasureInformation is just a data class. Currently, the camera cannot set the measurement point and defaults to using the center point.
<br><p><em><small>°°°</small></em></p>
