### ISSUE TITLE
V5.9.1 Sample App Crash after small modification

### ISSUE THREAD

**Issue by esieke** [dji-sdk/Mobile-SDK-Android-V5#371]
Sample App V5.9.1
Device samsung SM-G990B2 Android API 34 and Pixle 5

**Reproduce the crash**
1. build and run (debug) the APP
2. the APP works as expected
3. change line 81 of MSDKInfoVm.kt to ```LogUtils.i(tag, "test KeyConnection:$it")```
4. build and run (debugmode) the APP
5. the APP crashes and exits

**Cause research**
The error seems to happen when calling ```com.secneo.sdk.Helper.install(this)```
 in file DJIAircraftApplication.kt line 17.

If you uninstall the APP after the crash, it can be started again without crashing.

[log.txt](https://github.com/user-attachments/files/15838884/log.txt)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>Could the issue be related to the device you are using? Have you tried running your code on a device with Android 11 or Android 10?
We have received reports of similar crashes from other developers on Android 12 devices. I am currently trying to reproduce this issue.

Mobile SDK cannot run on an Android emulator.
<br><p><em><small>°°°</small></em></p>

**Comment by esieke** [comment]
Thanks for your response. I have the issue on Galaxy S21 FE 5G and Google Pixle5.  
  
Unfortunately both devices run on Android 14.
I think Android 14 is not supported? In this case you can close the issue, was my fault.
  
Hadn't problems with version V5.8.0. Therefore I didn't notice my mistake.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>If you haven't changed the TargetSDKVersion to 34, then there should be no issue. We will analyze your logs, so please wait for some time.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/104296295/58abbd08-b93e-42f7-979c-c0f5948a8d34)
If you encounter this crash while debugging App on Android Studio, you can try checking this option and then attempt to run it.

**Comment by esieke** [comment]
Hello,
looks good so far. Hadn't issues today using your suggested solution.
Thanks a lot!

Should I use this Solution permanently? Or is this issue still related to a bug?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109804'>Zendesk ticket #109804</a>:<br><br>The bug you encountered is actually related to installing the app in Android Studio, so this option helps you solve the crash issue. You can continue using it.
<br><p><em><small>°°°</small></em></p>

**Comment by mitchrsm** [comment]
i was developing on MSDK 5.8 till today , I upgraded to 5.10 and encountered this same crash, luckily the proposed "fix" worked for me too..
