### ISSUE TITLE
Look At Mode

### ISSUE THREAD

**Issue by ignacioalpiste** [dji-sdk/Mobile-SDK-Android-V5#372]
The [documentation](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/DJIValue.html?search=look_at_gimbal_following&i=0&#value_flightcontroller_lookatmode_inline) has description for the first 2 options:

- LOOK_AT_GIMBAL_FREE: Gimbal free mode, only control the gimbal to look at the target, it will automatically exit after completion.
- LOOK_AT_GIMBAL_FOLLOWING: Gimbal following mode, control gimbal and aircraft to look at the target, it will automatically exit after completion.
- LOOK_AT_ZOOM_CIRCLE: _**No current description in the docs.**_

Also, how to stop the mission before completing?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>Could you explain to us why it is necessary to stop before completion? If there is an error , I think we can reissue the correct instructions after completing the LookAt action.
<br><p><em><small>°°°</small></em></p>

**Comment by ignacioalpiste** [comment]
Two possible scenarios: 

1) In dynamic environments where the point of interest may change frequently, it is crucial to be able to stop the current "LookAt" action to redirect focus to a new point.
2) Users might want to manually interrupt the "LookAt" action. The user might decide to change the viewpoint before the drone arrives to the specific location.

Also, what is the description for "LOOK_AT_ZOOM_CIRCLE"? 

Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109913'>Zendesk ticket #109913</a>:<br><br>The property LOOK_AT_ZOOM_CIRCLE is unverified, its definition is not provided in the API documentation, and we do not recommend its usage.
Currently, LookAt does not have a stop function. In fact, LookAt is not a continuous action; it is a short-term action. When you call KeyLookAt, the aircraft will face towards that point, but it does not follow that target.
<br><p><em><small>°°°</small></em></p>
