### ISSUE TITLE
DTM Follow

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#373]
Hi DIJ,

In the DJI app, we have the possibility to upload our DTMfile or download the DTM file of the selected area.

is there any documentation or sample to know how to use this feature in our application too ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109968'>Zendesk ticket #109968</a>:<br><br>The functionality related to DTM files is not included in MSDK. Are you referring to importing flight zone information ?
https://developer.dji.com/api-reference-v5/android-api/Components/IFlyZoneManager/IFlyZoneManager.html#iflyzonemanager_importflysafedynamicdatabasetomsdk_inline
https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/compliance-eu.html
<br><p><em><small>°°°</small></em></p>
