### ISSUE TITLE
Set White balance and ISO - H20T

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#375]
Hi Dji, 

On 300 RTK H20T

```
KeyManager
                                        .getInstance()
                                        .setValue(createCameraKey(CameraKey.KeyWhiteBalance, cameraIndex, lensType),
                                        whiteBalanceinfo, object : CompletionCallback {
                                            override fun onSuccess() {
                                                Log.i("LOG", "Set white Balance success")
                                            }

                                            override fun onFailure(error: IDJIError) {
                                                Log.e("LOG- ERROR", error.toString())
                                            }
                                        });

```

Using the code below I am getting:

`errorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='', description='null', hint='error code = -1'}`

**Comment by antonymarion** [comment]
To set the ISO with
 ```
KeyManager.getInstance().setValue(
                                            KeyTools.createCameraKey(CameraKey.KeyISO, cameraIndex, lensType),
                                            targetIso, callbackFn (like above)
```
 I am getting `CANNOT_START_TASK_VLOTAGE_ALARM`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110006'>Zendesk ticket #110006</a>:<br><br>The information I found indicates that the lenses in the H20 series do not have a white balance adjustment function. Can you adjust this in the official app?

The adjustment of ISO usually needs to be done in manual exposure mode, as mentioned in the KeyISO interface description. Did you set it in manual mode? Also, what is the lens displaying the current image on the H20T?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
```
KeyManager.getInstance().setValue(
                                            createKey(CameraKey.KeyExposureMode, cameraIndex), CameraExposureMode.MANUAL, callback
```

gives `errorCode='INVALID_PARAMERTERS', innerCode='', description='null', hint='error code = -483'`

**Comment by antonymarion** [comment]
`Can you adjust this in the official app?` 

=> Could you just please provide the information in the official Doc from DJI; for instance a list of compability will be appreciated here:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/3190699a-e561-49f5-a015-cdb35824869b)


It would help developpers to access the right info at the right place (and avoid to navigate in ticket on Github to get the info)

regards

**Comment by antonymarion** [comment]
By the way can you confirm ISO is only working for ZOOM camera on RTK, normal?

**Comment by antonymarion** [comment]
And what is the limit of H20T for ISO:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/5cdb0336-713d-4140-9105-54bbea9eb6e5)

I get the following range from SDK

`"isoRange":["ISO_100","ISO_200","ISO_400","ISO_800","ISO_1600","ISO_3200","ISO_6400","ISO_12800"]`

But I succeed to put `"iso":"ISO_25600",` ... normal?

For greater values then I get an error as expected.

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/84c56176-b743-4cf3-8be5-802bc72f4aa4)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110006'>Zendesk ticket #110006</a>:<br><br>The maximum value provided by KeyISORange is the maximum value currently supported by the lens. Have you set the lens type to zoom lens when obtaining the range? If the lens type is set to default, the data retrieved may not be from a zoom lens.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes, but... why does it returns range values with other lenses if we cannot use ISO for other lenses than Zoom ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110006'>Zendesk ticket #110006</a>:<br><br>I assume that you have set the lensType to default when obtaining ["ISO_100","ISO_200","ISO_400","ISO_800","ISO_1600","ISO_3200","ISO_6400","ISO_12800"], which is actually a method we do not recommend for camera parameters. For cameras, I suggest setting the camera position and lens type unless this interface is unrelated to the lens type, such as the photo-taking interface. You may want to consider using the correct method of use, as incorrect usage may result in obtaining inaccurate data.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Could we consider instead that the SDK always returns correct values and does not return incorrect values ?

Incorrect SDK usage should not return misleading values.

If default camera should not be used for getting iso, then SDK should return an error with a descriptive message, for instance: "ISO not available for default camera, please switch to zoom"

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110006'>Zendesk ticket #110006</a>:<br><br>Yes, I will submit your suggestion to the team. Perhaps we should provide explanations for users in the API documentation.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
@dji-lyt : just to make sure: is the API documentation explaining the point above now?
