### ISSUE TITLE
function  pushFlyZoneLicensesToAircraft in Mini 3 error Fly safe error : LicenseUnlockNotSupported.

### ISSUE THREAD

**Issue by apatheticL** [dji-sdk/Mobile-SDK-Android-V5#376]
I want to unlock license in Mini 3 device but when i download License done then i push this license to device then error 
{errorType='FLY_SAFE', errorCode='COMMON_ERROR', innerCode='null', description='Fly safe error : LicenseUnlockNotSupported.', hint='common error'} 

Step: 
Step1: call function downloadFlyZoneLicensesFromServer state => done i have license of category 

`{"countryId":0,"cylinderHeight":-1,"cylinderLatitude":0.0,"cylinderLongitude":0.0,"cylinderRadius":0.0,"description":"Unnamed1","enabled":false,"endTimeStamp":1718989140,"flyZoneIDs":[],"isValid":true,"licenseId":26550716,"licenseType":"PENTAGON_UNLOCK_AREA","limitedHeight":-1,"polygonPoints":[{"latitude":21.202978134155273,"longitude":105.77156066894531},{"latitude":21.201696395874023,"longitude":105.77842712402344},{"latitude":21.19817543029785,"longitude":105.77842712402344},{"latitude":21.197856903076172,"longitude":105.76915740966797},{"latitude":21.202978134155273,"longitude":105.77156066894531}],"ridUnlockType":"UNKNOWN","sn":"687XM120020HUC","startTimeStamp":1718730000}`

Step 2: then i call function pushFlyZoneLicensesToAircraft then error 
{errorType='FLY_SAFE', errorCode='COMMON_ERROR', innerCode='null', description='Fly safe error : LicenseUnlockNotSupported.', hint='common error'} 

this is my code https://gist.github.com/apatheticL/f98b85cd56fce8c14b6c99905f9491d8

Please help me how to fix it. Thank so much.

**Comment by apatheticL** [comment]
In document of unlock license has note is 
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/49410976/37fa77a3-e911-4c41-a870-c112b3c753e3)
https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/flyzone.html.
So why when i call function with this doc then error. Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110086'>Zendesk ticket #110086</a>:<br><br>The error message refers to the current device not supporting this license.
Have you made sure that the license you obtained is intended for the current aircraft ? The serial number (SN) is visible on the license.
<br><p><em><small>°°°</small></em></p>

**Comment by apatheticL** [comment]
Yes I am sure that the license is properly registered for that aircraft. I updated firmware in my aircraft then it worked . But i want to ask question. 
How to remove a license in my aircraft?
I try search in document then has function is deleteflyzonelicensesfromaircraft but it try it then errror
ErrorImp{errorType='FLY_SAFE', errorCode='COMMON_ERROR', innerCode='null', description='Fly safe error : RemoveLicensesNotSupported.', hint='common error'}
How to fixed it. Thank so much.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110086'>Zendesk ticket #110086</a>:<br><br>The interface for deleting licenses is deleteFlyZoneLicensesFromAircraft. Did you confirm that you were logged into your DJI account and connected to the drone when deleting the license?

The function of deleteFlyZoneLicensesFromAircraft should be to remove all licenses from the drone.Could you let us know the firmware version of the drone you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by apatheticL** [comment]
Hi @dji-dev i logged my DJI account  and drone is connected but when i call deleteFlyZoneLicesesFromAircraft then it show error RemoveLicensesNotSupported . My firmware is 01.00.0500

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110086'>Zendesk ticket #110086</a>:<br><br>I will attempt to replicate the issue you are experiencing. If convenient for you, you may also provide a video by uploading it to this address. I will then pass it directly to our engineers for analysis.
https://pan-sec.djicorp.com/s/9HcMsaCy6et3z2z  password:dji123
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110086'>Zendesk ticket #110086</a>:<br><br>Could you  take a look at the test video in this address? https://pan-sec.djicorp.com/s/9HcMsaCy6et3z2z  password:dji123
I tested deleteFlyZoneLicesesFromAircraft on DJI MINI 3 PRO using version 5.9.1, and the result was successful.
<br><p><em><small>°°°</small></em></p>
