### ISSUE TITLE
MediaManager enable returns an error

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#378]
Hi Dji,

Calling `MediaDataCenter.getInstance().mediaManager.enable`, it returns this descriptive message:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/e5a403c2-9b29-4539-95c8-910df1b3ae1c)

cf https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/377 

> mediaManager.enable always fails

**Comment by namnhbhtech** [comment]
Hi,
did you try
```
MediaManager.getInstance().enable(...);
```

**Comment by antonymarion** [comment]
Nope, but it sounds good, thks !

**Comment by antonymarion** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/9bb0d24b-27f6-497c-9afb-170fa45896c1)
 
sounded goot but red :D

**Comment by IakovlevAA** [comment]
Did you manage to get it to work? For me both methods fail
