### ISSUE TITLE
minSDK 26 support

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#379]
Hi Dji, 

Do you have a roadmap to support min SDK 26 ?

DJI RC for 300RTK is still in Nougat.

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/38420b16-4d1d-485a-a336-4435b4c61c77)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110140'>Zendesk ticket #110140</a>:<br><br>Are you referring to updating the Android version used for DJI RC for M300 RTK to version 8? I understand that there is currently no plan for this.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
cf https://github.com/minio/minio-java/issues/1471

With Android SDK < 26 we cannot use libraries like these
