### ISSUE TITLE
MediaManager.getInstance().disable callback does not fire

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#38]
SDK Version: `5.0.0`

In utilizing the `MediaManager` class, and following the guide outlined [here](https://developer.dji.com/doc/mobile-sdk-tutorial/en/tutorials/media-file.html#interface-calling-process), I have found that there is no way to tell if the `MediaManager` is enabled or disabled _without tracking outside of the SDK_. This causes problems as calling `MediaManager.getInstance().disable()` when it is already disabled will result in the calling thread indefinitely hanging. The required callback methods for `disable()` never fire. An example:

```
suspend fun closeMediaManager(): Boolean {
        if (!isMediaManagerEnabled) { // Variable used in my application to track MediaManager state
            return true
        }

        return suspendCoroutine { continuation ->
            MediaManager.getInstance().disable(object : CompletionCallback {
                override fun onSuccess() {
                    Log.e(TAG, "disable onSuccess") // Never fires
                    isMediaManagerEnabled = false

                    // Clear local data to save memory
                    MediaManager.getInstance().release()

                    continuation.resume(true)
                }

                override fun onFailure(error: IDJIError) {
                    Log.e(TAG, "Failed to disable mediaManager: $error") // Never fires
                    continuation.resume(false)
                }
            })
        }
    }
```

I tried implementing `MediaManager.getInstance().addMediaFileListStateListener` in hopes that this would return something unique when the `MediaManager` is disabled. However, the only values I've seen are `IDLE`, `UPDATING`, and `UP_TO_DATE` and the values never change when `enable()` or `disable()` is called.

If the intended behavior is for the user to never call `disable()` when it is already disabled, is there a way to tell if the `MediaManager` is enabled utilizing the SDK?

**Comment by DJI-William** [comment]
Indeed, you cannot know your enable or disable is successful or not. And also you cannot know whether your mediaManager is enabled or not. So you have 2 issues now.
1. The disable callback does not return when you have called disable.
2. You need a isEnabled function to tell you whether the mediaManager is enabled or not.

**Comment by tkocik92** [comment]
If either of those two issues is resolved, then this issue can be closed. It wouldn't be worth reporting about the second option if the first option is fixed.

**Comment by DJI-William** [comment]
@tkocik92 Sorry, this is not a bug. Please see the attachement screenshot. The sample hasn't print out for you because you are using the release version of SDK. The LogUtils.d will not print in release version but in debug version of SDK. You can just change the LogUtils.d to native Android Log.d or change to LogUtils.i will work.
![image](https://user-images.githubusercontent.com/77274755/190992193-3737d942-92f9-41eb-9ef2-6d75e9c0a870.png)

**Comment by DJI-William** [comment]
We have changed all logutils.d to logutils.i to make sure there is a log generated.
