### ISSUE TITLE
Set wind speed in simulator

### ISSUE THREAD

**Issue by IakovlevAA** [dji-sdk/Mobile-SDK-Android-V5#380]
Is it possible to set wind speed via SDK? If not, do you have it in plans? Or maybe there is another software from it?
Drone: Mavic Mini 3 Pro

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110180'>Zendesk ticket #110180</a>:<br><br>Could you share with us the value of this feature to you? Currently, the emulator function provided by MSDK does not have a wind speed interface .
<br><p><em><small>°°°</small></em></p>

**Comment by IakovlevAA** [comment]
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/43800616/d4eab0dc-33c6-49ea-a380-e61de37392d2)
I think it will be great, if I can add to InitializationSettings not only coordinates of drone and sattelites, but wind speed and wind direction.
As for example
```
val coordinate2D = LocationCoordinate2D(simulator_latitude, simulator_longitude)
val num_sat = 15
val wind_speed = 10
val wind_direction = WindDirection.NORTH
val sett = InitializationSettings.createInstance(coordinate2D, num_sat, wind_speed, wind_direction)
enableSimulator(sett, object : CommonCallbacks.CompletionCallback {
    override fun onSuccess()
    {
        ToastUtils.showToast("start simulator Success")
    }

    override fun onFailure(error: IDJIError)
    {
        ToastUtils.showToast("start Failed " + error.description())
    }
})
```

**Comment by brien-crean** [comment]
@dji-dev I would also love to see this feature in SDK 5. The old SDK 4 iOS MSDK used to have this feature and it helped us greatly. It is very useful for testing Virtual stick flight when there is wind. Would it be possible to request this feature in a future update please?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110180'>Zendesk ticket #110180</a>:<br><br>The current plan does not include this feature. I can submit this requirement to the team for evaluation.
<br><p><em><small>°°°</small></em></p>
