### ISSUE TITLE
ISO AUTO renders black/dark on 300 RTK

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#381]
Hi Dji,

When testing on 300 RTK, I noticed on H20T that is very dark, normal?

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/d6d0ec90-4508-48c8-b3b5-9a05170d6c50)

Nevertheless, using 6_400 it is ok

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>You can check if other exposure parameters are causing the screen to appear very dark. A quick way to do this is by switching to Pilot 2 to see its performance and all the exposure parameters it displays.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes during testing it appears that when I set ISO using the SDK or using the RC then the shutter speed moves too.

Is it normal, expected?

My comprehension of ISO is that is a way to brighten your photos if you can’t use a longer shutter speed or a wider aperture. It is typically measured in numbers, a lower number representing a darker image, while higher numbers mean a brighter image. 

But here, both with RC or SDK it changes shutter speed too when setting ISO

It should not, right?

**Comment by dji-lyt** [comment]
In manual exposure mode, the shutter speed should not change with ISO. Can you verify if you are correctly monitoring the shutter speed?
Could the same issue also occur with Pilot 2?

**Comment by antonymarion** [comment]
I am using 300 RTK remotely I will ask this to the person who handled the RC.

**Comment by antonymarion** [comment]
There is no bug (the shutter speed does not change when changing ISO) on DJI Pilot 2, but there is no ISO_AUTO either in Pilot 2.

And I believe the bug only appear when shutter speed is at AUTO since this morning there was no issue after setting the shutter speed to a fixed value (1/100 which seems to be the default value) before playling with the ISO on the SDK.

But still when I set back to ISO_AUTO, this is very dark as above, I would expect ISO_AUTO to be clear (normal).

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>Here is a video of a test I did on H20. The result I got is that the shutter speed does not change after setting ISO_AUTO. Perhaps you can provide us with a way to reproduce it.
https://pan-sec.djicorp.com/s/gxPL8YpAfp9oiPa
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I saw your video. you are using the testing tools; But I believe this issue appeared on the Default Layout App while targeting the SDK.

I will ask to the people remote using the 300 RTK to produce the video for you.

By the way, this does not answer to the issue we notice above the ISO_AUTO which darken the video/photo, which was the primary issue (main subjet of the ticket).

thks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>Could you provide us with a method to reproduce this issue on the default demo page? so we can better understand the scenario in which you are experiencing the problem.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Sure, I will provide you the infos for friday.

But before friday, I can tell you that if you use the default layout page, and if you call the SDK to set ISO_AUTO while you already are in Zoom Mode; then it will produce a very dark screen.

And if you call the the SDK while using the default Layout page to change the ISO it will moves the shutter speed too (if you are in Shutter Auto)

It will be checked twice on friday for you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>I will go and observe the default layout page while waiting for you to provide us with the steps that triggered this issue.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
I will provide you the video soon. 

By the way I opened #385 since maybe it comes from the exposure mode manual in photo Mode that creates this dark effect on ISO AUTO ?

Changing to Video Mode does not the show the issue, so I believe that the exposure Mode manual is not appropriate for photo Mode since in both SDK call from our app or using the default layout App it shows the same behaviour.

In any case the documentation for exposure Mode should be updated..

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>Yes, the camera image is like the photo you provided when asking the question, and the camera's exposure mode is probably manual. If you have observed the exposure mode after switching to video mode, you may notice that the camera's exposure mode in video mode can be different from the exposure mode in photo mode. For example, when you tested it, the camera may have been in PROGRAM mode in video mode.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
https://we.tl/t-1VdHWiCYue

As you can see, playing with iso using the SDK changes the ISO but...

ISO in photo Mode is always clearer/brighter than in Camera Mode.

In this video I am in photo,  I change the ISO it is OK.

Then I create a video record in video Mode and the same iso is darker..

Then I play with iso it is OK the iso changes. 

I then take a photo and I am in photo Mode and the same ISO shows a clearer/brighter image.


The reason I believe is that setting the Camera Mode to video Mode changes the shutter speed from shutter_speed2 to shutter 100 as you can see in the video. 

Still, I did not make any call to the shutter speed with the SDK..

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>The final presentation of the image is not only influenced by ISO, but also by the shutter speed. When the camera switches to recording mode, you can see the shutter speed change from 2 to 1/100. However, the shutter speed range of the camera in recording mode will indeed be smaller than in photo mode.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes this is exactly what I have written above :)

Nominal behaviour should be that switching from Photo to Video Mode does not change the shutter speed, right, or if not possible that the displayed image with the given ISO does not change when switching from Photo Mode to Video Mode?

Otherwise we will have strange change of luminosity in the displayed image on the app or the RC (as we have right now...), and this is not acceptable from the users's perspective.

So how can we cope with this with the SDK since it changes the shutter speed when switching from Photo Mode to Video Mode.

Is there any auto behaviour in the SDK that can keep a smooth transition from Photo To Video Mode when playing with ISO ?

thks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110182'>Zendesk ticket #110182</a>:<br><br>Nominal behaviour should be that switching from Photo to Video Mode does not change the shutter speed, right, or if not possible that the displayed image with the given ISO does not change when switching from Photo Mode to Video Mode?
-->
The reason why the camera exhibits this behavior is that different exposure parameters can be set in recording and shooting modes.This refers to the fact that taking photos and recording videos can have separate exposure parameter settings. The exposure parameters required for photos and videos are often different.

For example, if you have selected the automatic mode in photo mode, but want to use fixed exposure parameters when switching to recording mode. Then switch the recording mode to manual mode and adjust the parameters. This is useful in automatic shooting such as waypoint missions, because the camera starts taking photos or recording after switching camera modes.
<br><p><em><small>°°°</small></em></p>
