### ISSUE TITLE
Set home coordinates manually?

### ISSUE THREAD

**Issue by IakovlevAA** [dji-sdk/Mobile-SDK-Android-V5#383]
Hi Dji,
I've found this key:

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/43800616/12354f6b-edd0-4235-bf76-4f2bcba28abe)

I tested it in simualtor and got strange behaviour. When drone gets location, home coordinates are null. If I set them manually with FlightControllerKey.KeyHomeLocation.create().set(LocationCoordinate2D(30.0,30.0)), home location is the one I set, but if I call FlightControllerKey.KeyStartGoHome.create().action() drone returns to its takeoff position
My steps are:
1. Set simulator with coords - lat:30.01 lon:30.01
2. Get home coordinates with FlightControllerKey.KeyHomeLocation.create().get - home_lat: null home_lon: null
3. Set home coordinates with FlightControllerKey.KeyHomeLocation.create().set - home_lat: 30.0 home_lon: 30.0
4. Get home coordinates with FlightControllerKey.KeyHomeLocation.create().get -  home_lat: 30.0 home_lon: 30.0
5. Call FlightControllerKey.KeyStartGoHome.create().action()
6. Drone changes Home to takeoff position and flies to lat:30.01 lon:30.01

Using Mini 3 pro

**Comment by IakovlevAA** [comment]
Calling FlightControllerKey.KeyStartTakeoff.create().action() sets home point. That goes against what is written in the documentation...
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/43800616/45cd465f-ee07-49cc-917d-c3f95862c3d5)

**Comment by IakovlevAA** [comment]
Also, when home is not set, FlightControllerKey.KeyHomeLocation.create().get() lat. and lon. must be null, but it returns very big number
![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/43800616/609980b0-2594-4ae2-b8f0-f18c2c66c56b)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110664'>Zendesk ticket #110664</a>:<br><br>I managed to replicate the process of obtaining the home point location when the aircraft has no signal. However, after opening the simulator, it is possible to obtain the home point location. You may want to try using a callback to retrieve it.
Here is a test video: https://pan-sec.djicorp.com/s/FGsB7bDjNgBnX8X  password:dji123

As for “returns to its takeoff position”，The function of KeyStartGoHome is to fly to the home point. From your description, it seems to be working fine.
<br><p><em><small>°°°</small></em></p>

**Comment by IakovlevAA** [comment]
By "returns to its takeoff position” I meant that after setting custom homepoint location, taking off and sending return to home command, drone doesn't fly to my custom point, it immediately lands where it took off

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110664'>Zendesk ticket #110664</a>:<br><br>This is normal. The current strategy the aircraft is using is to set the current position as the home point after takeoff. If you need the aircraft to return to a different location, you can reset the home point after the aircraft takes off.
<br><p><em><small>°°°</small></em></p>
