### ISSUE TITLE
Reading radar data

### ISSUE THREAD

**Issue by GregCornis** [dji-sdk/Mobile-SDK-Android-V5#384]
We'd like to use the [radar made for the M300](https://boutique.dji-paris.com/radar-csm-pour-dji-matrice-300-et-350-rtk-25674.html), and we're wondering how (or if?) we can read the distances through the mobile SDK.
There's a [RadarManager](https://developer.dji.com/api-reference-v5/android-api/Components/IPerceptionManager/IRadarManager.html) in the SDK, but it seems to only provide information about obstacle avoidance. Is there a way to have the distances measured by the radar ?

Does [PerceptionInformation::ObstacleDataListener](https://developer.dji.com/api-reference-v5/android-api/Components/IPerceptionManager/IPerceptionManager.html#iperceptionmanager_addobstacledatalistener_inline) give the distances from the stereo sensors, or from the radar (when there is one) ?

Thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110927'>Zendesk ticket #110927</a>:<br><br>Could you please provide more details on the distance you need to measure between the drone and what specifically? Currently, the MSDK only allows for obtaining obstacle distances.

Does PerceptionInformation::ObstacleDataListener give the distances from the stereo sensors, or from the radar (when there is one) ?
-->This is the distance of obstacles detected by the visual system.

The CSM Radar needs to use the `setObstacleAvoidanceEnabled` method from RadarManager to control the switch, and also use the listener interface of RadarManager to obtain obstacle distances.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
We'd like to fly the drone roughly 1-2m in front of a wall, and know exactly how far we are from the wall. The stereo sensors are not precise enough, because the wall is white. So there is no way to have access to the raw distance from the radar ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110927'>Zendesk ticket #110927</a>:<br><br>The original data of the radar cannot be obtained by MSDK. However, in your use case, obstacles seem to be walls. Can obstacle distance be used directly?
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Yes that could be an option, is that done via [PerceptionManager::addObstacleDataListener](https://developer.dji.com/api-reference-v5/android-api/Components/IPerceptionManager/IPerceptionManager.html?search=obstacledata&i=2&#iperceptionmanager_addobstacledatalistener_inline) ? So this information is more precise when the radar is plugged in ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110927'>Zendesk ticket #110927</a>:<br><br>Yes, the information obtained by PerceptionManager::addObstacleDataListener is obstacle data. When the aircraft is equipped with radar, this interface will integrate the radar detection data to improve measurement accuracy.
<br><p><em><small>°°°</small></em></p>

**Comment by GregCornis** [comment]
Alright thanks, we'll have a look !

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/110927'>Zendesk ticket #110927</a>:<br><br>Glad to help you.
<br><p><em><small>°°°</small></em></p>
