### ISSUE TITLE
Set custom HeightLimitRange

### ISSUE THREAD

**Issue by IakovlevAA** [dji-sdk/Mobile-SDK-Android-V5#387]
Hi Dji,
My default Height range on Mini 3 pro is {min: 20, max: 50, default: 120}. Is there any possibilities to change this limitation?  I want to set 600m height with FlightControllerKey.KeyHeightLimit, but because of Height range it's impossible to set value bigger than 500

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/111122'>Zendesk ticket #111122</a>:<br><br>I apologize for the inconvenience. Currently, only industrial-grade drones support altitude limits of over 500 meters. Consumer-grade drones are limited to 500 meters in altitude.
<br><p><em><small>°°°</small></em></p>
