### ISSUE TITLE
LiveStreamManager start stream working but cannot see stream/

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#39]
Hello,
I am trying to start stream in my app and after i do startStream() i get a success message but no stream appear on my backend.
When i try this with the sample it does work.
This is my code to start the stream:

 LiveStreamManager.getInstance().addLiveStreamStatusListener(new LiveStreamStatusListener() {
                            @Override
                            public void onLiveStreamStatusUpdate(LiveStreamStatus status) {
                                Log.d("LOG", "Status; " + status.isStreaming() + ", " + status.getFps() + ", " + status.getPacketCacheLen() + ", " + status.getResolution().getWidth() + ", " + status.getPacketLoss() + ", " + status.getVbps());
                            }

                            @Override
                            public void onError(IDJIError error) {
                                Log.d("LOG", "Status; " + error.description());
                            }
                        });
                        LiveStreamSettings settings = new LiveStreamSettings.Builder()
                                .setLiveStreamType(LiveStreamType.RTMP)
                                .setRtmpSettings(new RtmpSettings.Builder()
                                        .setUrl(url).build()).build();
                        LiveStreamManager.getInstance().setLiveStreamQuality(StreamQuality.FULL_HD);
                        LiveStreamManager.getInstance().setLiveVideoBitrateMode(LiveVideoBitrateMode.AUTO);
                        LiveStreamManager.getInstance().setVideoChannelType(VideoChannelType.PRIMARY_STREAM_CHANNEL);
                        LiveStreamManager.getInstance().setLiveStreamSettings(settings);
                        LiveStreamManager.getInstance().startStream(new CommonCallbacks.CompletionCallback() {
                            @Override
                            public void onSuccess() {
                                Log.d("LOG", "onSuccess");
                            }

                            @Override
                            public void onFailure(@NonNull IDJIError error) {
                                Log.d("LOG", "onFailure");
                            }
                        });

I am also implementing in the gradle:
implementation "com.dji:dji-sdk-v5-all:5.0.0"
compileOnly "com.dji:dji-sdk-v5-all-provided:5.0.0"
implementation "com.dji:dji-sdk-v5-networkImp:5.0.0"

Why is it working in the sample but when i try it in my app it doesn't?
I am using Java not Kotlin.
And i'm using the M30 aircraft.

**Comment by DJI-William** [comment]
1. Do you have a video stream display on your page?
2. Are you using a FPVWidget? If yes, you need to change the constructor of its VideoDecoder.
3. Please read this article, [Chapter 6: Live Streaming](https://sdk-forum.dji.net/hc/en-us/articles/6663305630105-Chapter-6-Live-Streaming).
