### ISSUE TITLE
Difference between MSDK sample Aircraft App Launching with 300 RTK vs Mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#391]
Hi Dji,

I noticed on mini 3 Pro if I run the sample aircraft MSDK app, the left panel with buttons are actived by default, after the app show the toast "connection status: success".

Nevertheless it is not the case when using the same App on 300 RTK: I have to touch the screen in order to see the left panel with enabled buttons (not disabled any more).

Could you fix this please, since it means that some event will not be triggered on the 300 RTK if we do not touch the screen manually...
And I expect that the behaviour of the App is not drone dependant and as follow:

"Once I double click on the App, the toast "Connection status: Success" shows up and at the same time the buttons on the left panel are actives (not disabled any more).

Regards,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111745'>Zendesk ticket #111745</a>:<br><br>Could you take a look at this video？https://pan-sec.djicorp.com/s/3eG8nbTcdcN7xHB
Do you mean that the button on the left side of the page can only be used after touching the screen?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Yes exactly, but here in your video, it seems to be ok, so that's weird..

I will give a try with the default sample app then!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111745'>Zendesk ticket #111745</a>:<br><br>No problem. If you have a stable way to trigger this issue, please let us know so we can address it.
<br><p><em><small>°°°</small></em></p>
