### ISSUE TITLE
Operating mechanism of MSDK

### ISSUE THREAD

**Issue by darkangel20156** [dji-sdk/Mobile-SDK-Android-V5#392]
I'd like to understand the operating mechanism of MSDK. Specifically, when a control function button (e.g., 'Take off') is pressed within the application, what specific information does MSDK transmit to the hardware side?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111889'>Zendesk ticket #111889</a>:<br><br>MSDK transmits information according to proprietary protocols. The protocol is classified information, and we regret to inform you that we are unable to access specific details, as it is also not open to the public.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
I understand that your protocol is confidential, so I didn't want to delve too deeply. My lecturer assigned me to learn about this issue, and I just need a bit more information for clarification. Could you help me with that? Thank you very much!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111889'>Zendesk ticket #111889</a>:<br><br>I'm sorry, but we don't actually have a deep understanding of the internal details. The MSDK simply transmits information as required by the protocol, but the SDK does not understand how to establish the wireless link between the remote controller and the drone, or how to transmit data to the drone according to the protocol. These aspects are transparent to the SDK.
<br><p><em><small>°°°</small></em></p>

**Comment by darkangel20156** [comment]
I understand. Thank you for your help!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/111889'>Zendesk ticket #111889</a>:<br><br>Sorry for that I am unable to provide you with the information you are looking for.
<br><p><em><small>°°°</small></em></p>
