### ISSUE TITLE
Thermal Camera Pointer

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#393]
Hi DJI,

inside the DJI app, when we switch to thermal camera, there is an option which let us click on the screen to see the temperature of that point.

is there any component in ux sdk to add to our application this feature ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/112000'>Zendesk ticket #112000</a>:<br><br>I'm sorry, the UXSDK currently does not have temperature widget. If you need to display temperature measurements, you will implement it yourself.
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Is There any documentation or sample how to implement it ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/112000'>Zendesk ticket #112000</a>:<br><br>You can use this article along with the API documentation to understand how to implement the temperature measurement feature.
https://sdk-forum.dji.net/hc/en-us/articles/9125637605913-Chapter-9-Camera
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html<br><a href='https://djisdksupport.zendesk.com/attachments/token/TAIIRYjKxA04e40MnVFgCw4oi' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Thank you so much. 

To do this at first we should set the "KeyThermalTemperatureMeasureMode":

![1](https://github.com/user-attachments/assets/dc0e17b8-4c59-4580-a266-e486474db3f6)

Then set ther point and listen to temperatures :

![2](https://github.com/user-attachments/assets/2078ae8e-f8c9-41a0-b785-b0afd4964005)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/112000'>Zendesk ticket #112000</a>:<br><br>I'm glad you've achieved it.
The points used for temperature measurement are relative to the position on the camera screen.
<br><p><em><small>°°°</small></em></p>
