### ISSUE TITLE
Start Mission gives 'Command timed out' error for DJI Mavic 3E / 3T

### ISSUE THREAD

**Issue by DevRobi** [dji-sdk/Mobile-SDK-Android-V5#394]
Hi DJI,

wayPointV3VM.startMission gives me a 'Command timed out' error on the Mavic 3E/ 3T drones. I first do pushKMZFileToAircraft() and then call startMission(). The mission starts fine for M300 drones but not for the Mavic 3E/3T. I did not change anything in the source code, I was just trying the run the sample app from source, I tried version 5.9.1 and 5.9.2.

So git cloned the source and then ran it in Android Studio, connected the DJI remote controller and ran the sample app. The sample app shows up just fine. Then my aircraft is linked and I do:

Testing tools > Waypoint. I import a .kmz file and press the uploadkmz button. Then, I press Start Mission. The mission starts fine for the M300 but it throws 'Command timed out' for the Mavic 3E / 3T. The .kmz file is the same for both drones. I tried removing the .kmz suffix for the Mavic 3E / 3T but that didn't work either. If I need to clarify sth just ask. I think my steps are easy to reproduce.

Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/112437'>Zendesk ticket #112437</a>:<br><br>https://pan-sec.djicorp.com/s/7Pri2MAQKeJAHK4
Here is our test video in the Mavic 3T. We did not encounter the timeout issue you mentioned. We would appreciate it if you could inform us of the drone firmware version you are using and provide us with a video showing when the issue occurred.
<br><p><em><small>°°°</small></em></p>

**Comment by DevRobi** [comment]
I managed to replicate what you just did. The issue turned out to be that the kmz file that I was passing to the drone could not be parsed (for some unknown reason) by the Mavic. It was strange because the same kmz file worked just fine when I was using the DJI Pilot 2 app but it did not work with the MSDK sample app. After changing some things in my kmz generation, it seems that the issue is fixed. Thanks for your time and timely responses!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/112437'>Zendesk ticket #112437</a>:<br><br>Glad to hear this news.
<br><p><em><small>°°°</small></em></p>
