### ISSUE TITLE
Cancel Listener Bug

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#396]
Hi DJI,

I try to add a listener to thermal temperature point and I can successfuly get the results:

![2](https://github.com/user-attachments/assets/0e052b8b-8b5b-4b13-834e-e7eceb57c85e)

But I need to cancel this listener when user disable this feature in the app. I use this code but it does not cancel the listener :

`
KeyManager.getInstance().cancelListen(CameraKey.KeyThermalSpotMetersureTemperature)
`

and after calling this method I still receive the results. how can I completely remove a listener ?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113327'>Zendesk ticket #113327</a>:<br><br>Which version of MSDK are you using?
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Im using version 5.9.2

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113327'>Zendesk ticket #113327</a>:<br><br>Could you try the following code to see if it successfully cancels the listener? The `cancelListen` method requires a `DJIKey` instance, so you will need to use `KeyTools` to create the corresponding key.


    KeyManager.getInstance().cancelListen(KeyTools.createCameraKey(CameraKey.KeyThermalSpotMetersureTemperature, ComponentIndexType.LEFT_OR_MAIN, thermalLensType));
<br><p><em><small>°°°</small></em></p>

**Comment by PeimanAtaeiJPDroni** [comment]
Yes it works like this and the listener is canceled successfuly 

Thank you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113327'>Zendesk ticket #113327</a>:<br><br>Glad to help you.
<br><p><em><small>°°°</small></em></p>
