### ISSUE TITLE
能不能改改代码结构哇

### ISSUE THREAD

**Issue by Potato-2020** [dji-sdk/Mobile-SDK-Android-V5#397]

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113931'>Zendesk ticket #113931</a>:<br><br>你方便告诉我们您对示例代码的结构的建议吗？如果有不好的地方，我可以将你的建议转交给团队。
另外，你可以告诉我们你希望使用的示例代码结构。
<br><p><em><small>°°°</small></em></p>
