### ISSUE TITLE
DefaultLayoutActivity中的MapWidget在设置高德地图定位没有回调

### ISSUE THREAD

**Issue by dou23** [dji-sdk/Mobile-SDK-Android-V5#399]
使用项目Demo的5.9.1版本，修改了包名并设置了对应的AIRCRAFT_API_KEY和AMAP_API_KEY，DefaultLayoutActivity中的MapWidget在设置高德地图定位没有回调，展示为北京。
SDK版本5.9.1

**Comment by dou23** [comment]
当前我所在位置在福建，FlightCOntrollerKey.keyHomeLocation并没有回调福建的坐标

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/114382'>Zendesk ticket #114382</a>:<br><br>MSDK的地图使用的是无人机的位置信息。您需要确认飞机是否有GPS信号。室内是没有GPS信号的。
<br><p><em><small>°°°</small></em></p>

**Comment by dou23** [comment]
感谢回复，展开无人机的机翼就拿到Key的监听回调了

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/114382'>Zendesk ticket #114382</a>:<br><br>很高兴有帮助到你。
<br><p><em><small>°°°</small></em></p>
