### ISSUE TITLE
Question on Implementing H20T LRF

### ISSUE THREAD

**Issue by hyunah96** [dji-sdk/Mobile-SDK-Android-V5#402]
Hello, I am developing my own app using SDK V5. I want to implement a feature that receives real-time distance information of the focused target using the LaserMeasureInformation method. However, I'm not sure which callback method to use. It seems that setLaserMeasureInformationCallback is not available in V5. Can you inform me about the appropriate callback method? Or is there any example code? The code in the current release notes is for version V4

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/115086'>Zendesk ticket #115086</a>:<br><br>Please refer to this article, which provides information on the type of Key you should use to activate laser ranging and monitor ranging information on MSDK V5.
Chapter 9: Camera  （https://sdk-forum.dji.net/hc/en-us/articles/9125637605913-Chapter-9-Camera?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjI3MzUxNTU3OTAzNzY5LCJ0aWNrZXRfaWQiOjExNTA4NiwiY2hhbm5lbF9pZCI6NjMsInR5cGUiOiJTRUFSQ0giLCJleHAiOjE3MjY3NDYxNjh9.EyXE87JjkVPGg7FJ6kM5HYQks87NZl6M4eAXRHLE5hQ）
<br><p><em><small>°°°</small></em></p>

![image](https://github.com/user-attachments/assets/21002f3c-bf45-432f-a622-c9681088fa83)
