### ISSUE TITLE
Capture frame with CameraStreamManager

### ISSUE THREAD

**Issue by IakovlevAA** [dji-sdk/Mobile-SDK-Android-V5#404]
Hi DJI,
I found in sample app possibilty of catching frames from camera stream. Is it possible, that I can capture frames and turning them into .png pictures? This is code from Sample 
```
 MediaDataCenter.getInstance().cameraStreamManager.addFrameListener(
            cameraIndex,
            format,
            object : ICameraStreamManager.CameraFrameListener {
                override fun onFrame(frameData: ByteArray, offset: Int, length: Int, width: Int, height: Int, format: FrameFormat) {
                    try {
                        val dirs = File(DiskUtil.getExternalCacheDirPath(ContextUtil.getContext(), "CameraStreamImageDir"))
                        if (!dirs.exists()) {
                            dirs.mkdirs()
                        }
                        val file = File(dirs.absolutePath, "$formatName.image")
                        FileOutputStream(file).use { stream ->
                            stream.write(frameData, offset, length)
                            stream.flush()
                            stream.close()
                            ToastUtils.showToast("Save to : ${file.path}")
                        }
                        LogUtils.i(TAG, "Save to : ${file.path}")
                    } catch (e: Exception) {
                        ToastUtils.showToast("save fail$e")
                    }
                    // Because only one frame needs to be saved, you need to call removeOnFrameListener here
                    // If you need to read frame data for a long time, you can choose to actually call remove OnFrameListener according to your needs
                    MediaDataCenter.getInstance().cameraStreamManager.removeFrameListener(this)
                }

            })
```
Does .image format can be changed to another(.yuv) ? If I save frame as .yuv and convert to .png I can't get normal picture

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/115208'>Zendesk ticket #115208</a>:<br><br>The LiveStream does not have an interface to obtain frame data. The image pushed by LiveStream is the camera's image; can we use the camera's frame data as a substitute?
<br><p><em><small>°°°</small></em></p>

**Comment by IakovlevAA** [comment]
Yes, I meant obtaining frames from camera and converting them to Bitmap

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/115208'>Zendesk ticket #115208</a>:<br><br>You may want to take a look at this issue. If you obtain the YUV data, you can implement the conversion to bitmap on your own.
https://sdk-forum.dji.net/hc/en-us/community/posts/33709871608089-YUV-to-Bitmap
<br><p><em><small>°°°</small></em></p>

**Comment by IakovlevAA** [comment]
Yes, thanks. This approach helped me, for anyone who will wonder I'll leave sample of code that works for me
```
val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
val byteBuffer = ByteBuffer.wrap(frameData)
bitmap.copyPixelsFromBuffer(byteBuffer)
val stream = ByteArrayOutputStream()
bitmap?.compress(Bitmap.CompressFormat.JPEG, 100, stream)
val image = stream.toByteArray()
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/115208'>Zendesk ticket #115208</a>:<br><br>I am pleased to help you.
<br><p><em><small>°°°</small></em></p>
