### ISSUE TITLE
Compatibility with Avata 2

### ISSUE THREAD

**Issue by anislerouge** [dji-sdk/Mobile-SDK-Android-V5#406]
Hi,

Will there be compatibility with Avata 2 available soon?

Best regards,
Anis

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/115488'>Zendesk ticket #115488</a>:<br><br>I apologize for any inconvenience. Currently, there are no such plans. In the short term, Avata 2 will not support the SDK.
<br><p><em><small>°°°</small></em></p>
