### ISSUE TITLE
m30 gimbal control

### ISSUE THREAD

**Issue by lineOfSightGui** [dji-sdk/Mobile-SDK-Android-V5#409]
My question is: does controlling gimbal using GimbalKey.KeyRotateBySpeed
 overrides the stabilize function of the gimbal?
So if I move the drone while controlling gimbal what will be the priority my command or stabilize commands, considering that my gimbal is on freeMode.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116078'>Zendesk ticket #116078</a>:<br><br>Could you please explain what stable functionality is?

In free mode, when the drone rotates, the gimbal will maintain a different absolute angle, guiding it to reach the maximum angle, and then it will rotate along with the drone.
<br><p><em><small>°°°</small></em></p>

**Comment by lineOfSightGui** [comment]
I mean by stable functionality that gimbal will keep its orientation regardless the drone movement.
so my question is, if I am controlling gimbal by speed using GimbalKey.KeyRotateBySpeed, and at the same time the body of the drone is moving, will gimbal then maintain stabilization and accept control commands I send, or controlling gimbal speed will affect the stabilization?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116078'>Zendesk ticket #116078</a>:<br><br>According to the definition of free mode, the gimbal and the aircraft operate independently and are not affected by each other. Are you currently experiencing interference between them on the M30 series?
<br><p><em><small>°°°</small></em></p>

**Comment by lineOfSightGui** [comment]
yes, when i send control command by speed to the gimbal and rotate M30 body at the same time, stabilize is not good.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116078'>Zendesk ticket #116078</a>:<br><br>Could you tell us why this method is necessary? The situation you are encountering is likely due to the mechanical structure limitations of the M30 series, and it is probable that the SDK will not be able to resolve the issue you are facing.
<br><p><em><small>°°°</small></em></p>
