### ISSUE TITLE
Getting the FlightMode of the aircraft.

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#41]
Hello,
In MSDK v4.16.2 i could get the Aircraft's FlightMode from: 
`FlightControllerState .getFlightMode()`
And i would get values like: "ATTI, GPS_ATTI, GO_HOME, Etc.."
I don't see a way now to get the FlightMode like the old SDK.
how do i get that?

**Comment by DJI-William** [comment]
The doc hasn't release the FlightMode  yet, we will release the doc about FlightMode in the next 5.1 version in the end of September.
