### ISSUE TITLE
Mini 3 Pro still crash if launched with usb connected

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#411]
Hi Dji team,

I have no crash indeed if RC Pro is disconnected.

Nevertheless if usb is connected (for instance for seeing logs with android studio), it still crashed as before...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>You may refer to the first method mentioned in this article:Common errors and solutions when running sample code.
(https://sdk-forum.dji.net/hc/en-us/articles/36883481123225-Common-errors-and-solutions-when-running-sample-code)
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Thks but none of these solutions corresponds to the fix for the behaviour on the mini 3 Pro that still crashes.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>You could provide us with the crash logs.
I would like to confirm that you are referring to the RC PRO crashing after connecting via USB and Android Studio, correct?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Correct; I will try to find some spare time for you to provide the logs

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>I will await your response.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>Have you experienced any similar crashes?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Hello @dji-dev, our dev is quite busy actually, I will let you know next month for this issue

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>I will keep this issue open and await your response. If this crash is difficult to reproduce, you can also reach out to us when the developers encounter it again.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
After stopping Dji Fly App, this has never happened then, so it seems to be ok now with this method

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116348'>Zendesk ticket #116348</a>:<br><br>Thank you for your patience testing and for your feedback.
<br><p><em><small>°°°</small></em></p>
