### ISSUE TITLE
Gimbal on yaw axis not working any more for mini 3 Pro - last release

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#412]
Hi Dji Team,

On last release my Yaw axis is not working any more. It used to work before (cf first UI on left panel, has not effect any more on stream)

Pitch and zoom are ok still since I can still use it as you can see below..

![image](https://github.com/user-attachments/assets/ca3350b2-f9cd-4dee-af57-c1b70fb5a6ee)
![image](https://github.com/user-attachments/assets/aca23ba6-c558-4151-8ee4-ff8ed101b46d)
![image](https://github.com/user-attachments/assets/9a853ce3-c540-42e5-ad02-03622e7fe855)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116349'>Zendesk ticket #116349</a>:<br><br>How do you change the yaw? Could you please share the interface and method you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Of course, depending on axisInString, the same code is working well on 300 for instance

` 

                                    val gimbalAngleRotation = GimbalAngleRotation()
                                    gimbalAngleRotation.mode =
                                        GimbalAngleRotationMode.ABSOLUTE_ANGLE
                                    gimbalAngleRotation.pitchIgnored = true
                                    gimbalAngleRotation.yawIgnored = true
                                    gimbalAngleRotation.rollIgnored = true
                                    gimbalAngleRotation.duration = 4000.0

                                    // https://developer.dji.com/api-reference/android-api/Components/Gimbal/DJIGimbal.html#djigimbal_workmode_inline
                                    //  GimbalKey.KeySet.setMode GimbalMode.FPV
                                    //  getCapabilities

                                    when (axisInString) {
                                        "pitch" -> {
                                            gimbalAngleRotation.pitch = value.toDouble()
                                            gimbalAngleRotation.pitchIgnored = false
                                        }

                                        "roll" -> {
                                            gimbalAngleRotation.roll = value.toDouble()
                                            gimbalAngleRotation.rollIgnored = false
                                        }

                                        "yaw" -> {
                                            gimbalAngleRotation.yaw = value.toDouble()
                                            gimbalAngleRotation.yawIgnored = false
                                        }
                                    }

                                    
                                    KeyManager.getInstance()
                                        .performAction(KeyTools.createKey(GimbalKey.KeyRotateByAngle),
                                            gimbalAngleRotation,
                                            object :
                                                CommonCallbacks.CompletionCallbackWithParam<EmptyMsg> {
                                                override fun onSuccess(t: EmptyMsg?) {
                                                    Log.d("DGEO - INFO", "move gimbal success")
                                                }

                                                override fun onFailure(error: IDJIError) {
                                                    Log.d(
                                                        "ERROR",
                                                        "move gimbal error" + error.description()
                                                    )
                                                    isMovingGimbal = false
                                                    targetGimbalRotation = null
                                                }
                                            })

                                    gimbalAngleRotation.run { }


`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/116349'>Zendesk ticket #116349</a>:<br><br>Thank you for providing the code. Based on the title, I believe the situation you are experiencing is normal. The DJI MINI 3 PRO cannot move the yaw axis. I have confirmed this in its manual.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
My bad, I forgot this one did not have yaw capabilities, you're right

**Comment by antonymarion** [comment]
> Agent comment from yating.liao in [Zendesk ticket #116349](https://djisdksupport.zendesk.com/agent/tickets/116349):Thank you for providing the code. Based on the title, I believe the situation you are experiencing is normal. The DJI MINI 3 PRO cannot move the yaw axis. I have confirmed this in its manual.
> 
> _°°°_

There is some yaw by the way on mini 3 Pro guys

cf [https://we.tl/t-zx1YNuMRQ9](https://we.tl/t-zx1YNuMRQ9?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)
