### ISSUE TITLE
base_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

### ISSUE THREAD

**Issue by zyc50** [dji-sdk/Mobile-SDK-Android-V5#42]
base_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

**Comment by DJI-William** [comment]
This is an IDE issue, normally I fixed this by clear the cache.
![image](https://user-images.githubusercontent.com/77274755/192214686-802ad0ec-4d35-43f7-9268-9632da7523f3.png)

**Comment by zyc50** [comment]
> This is an IDE issue, normally I fixed this by clear the cache. ![image](https://user-images.githubusercontent.com/77274755/192214686-802ad0ec-4d35-43f7-9268-9632da7523f3.png)

都试过了，重建错误一直这样的错误，资源无法引用，检查gradle.properties、build.gradle文件并无异样。。。。。


/transformed/jetified-aircraft-provided-5.0.0_525.jar!/META-INF/base_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
/transformed/jetified-kotlin-android-extensions-runtime-1.6.10.jar!/META-INF/kotlin-android-extensions-runtime.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
uxsdk_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
transformed/jetified-aircraft-provided-5.0.0_525.jar!/META-INF/base_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

/transforms-3/81703aba57dcc61957d8d078814c98b9/transformed/jetified-kotlin-android-extensions-runtime-1.6.10.jar!/META-INF/kotlin-android-extensions-runtime.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

/transforms-3/92c5364627ef6ed82883dfa89bd0bf18/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

/transforms-3/e6f8a9f49890a68422ac2179419da979/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

/transforms-3/b9871d1e82b78eb6f1c1769c5e8e49b6/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

**Comment by DJI-William** [comment]
需要删除所有的.gradle和.idea文件后再清除缓存，重启。
