### ISSUE TITLE
java.lang.UnsatisfiedLinkError in Android14 using version 5.11.0-a1

### ISSUE THREAD

**Issue by punto338** [dji-sdk/Mobile-SDK-Android-V5#428]
Hello, I have my app with succesful initialization and registration. In my activity I have this Java code:

![image](https://github.com/user-attachments/assets/a940ff64-fbe3-4827-a037-77d581636892)

and I get this error:

**`MRTCController    E  Couldn't load libJNI_ERR returned from JNI_OnLoad in "/data/app/~~gHq_QrxcDaKlbGt5JuYvwA==/com.myapp.app-41P7upOnZbnEjCM4y9K7Qg==/lib/arm64/libmrtc_core_jni.so"`**

![Sin nombre](https://github.com/user-attachments/assets/e072d9a2-7799-4daa-9f8a-7c4d2d23d4ae)

I am using these dependencies and testing in Android 14

`    withDJIImplementation "com.dji:dji-sdk-v5-aircraft-alpha:5.11.0-a1"
    withDJICompileOnly "com.dji:dji-sdk-v5-aircraft-provided-alpha:5.11.0-a1"`

    id 'com.android.application' version '8.5.2' apply false
    id 'com.android.library' version '8.5.2' apply false

`AGP Version: distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
`
I also tried with these configurations, but problem is the same:

```
  id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
```

`distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.2-bin.zip
`

how can this error be solved?

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/118387'>Zendesk ticket #118387</a>:<br><br>Dear developers,

Hello, thank you for contacting DJI Innovation.

Will there be an error when running the official sample? Looks like it's not in the official library

I hope our solution can help you, thank you for your email, wish you a happy life!

Best Regards,
Dji innovation SDK technical support<br><a href='https://djisdksupport.zendesk.com/attachments/token/a6ggH2bxqnNz8k26vVcQPozCY' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by punto338** [comment]
Official sample is not building correctly, I get the same error as #424 

https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/424

**Comment by punto338** [comment]
It happens also in the sample, but the sample can livestream without issues. So may I have to initialize anything else than 

`com.cySdkyc.clx.Helper.install(this);
`

and

![image](https://github.com/user-attachments/assets/fa099232-7b56-47fb-846e-5dc7702b23ab)

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/118387'>Zendesk ticket #118387</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

May I ask what is the latest error reported at present? Can you provide the error information?

I hope our solution can help you, thank you for your email, wish you a happy life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>

**Comment by punto338** [comment]
Using this code:

![image](https://github.com/user-attachments/assets/82bf0ad4-51b1-4d2b-a4dc-846b6a682762)

using gradle 7.4.2 is working fine, livestream is OK, but in gradle 8.7 I get this error:

error trying to stream: UNKNOWN => Live stream error is unknown

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/118387'>Zendesk ticket #118387</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

You can check out this document:
https://sdk-forum.dji.net/hc/zh-cn/articles/13201276673689-%E5%BC%80%E5%90%AF%E7%9B%B4%E6%92%AD%E6%8A%A5%E9%94%99Unknown%E6%80%8E%E4%B9%88%E5%8A%9E?auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjEzMDAxMDc0NzA3MDk3LCJ0aWNrZXRfaWQiOjc0MzQzLCJjaGFubmVsX2lkIjo2MywidHlwZSI6IlNFQVJDSCIsImV4cCI6MTY3Mjk3NTQwNH0._aiRmu2ghuG3g6IgXcltUKVq_lGLV3Uu_xP0Lo7_Gm0&source=search

Thank you for your understanding and support, I wish you a happy life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>
