### ISSUE TITLE
Compile app for non arm64-v8a architecture

### ISSUE THREAD

**Issue by punto338** [dji-sdk/Mobile-SDK-Android-V5#429]
I have an app which has  the DJI SDK as an extra feature. I want to install this app in any architecture, and only initialize the SDK if you have a x64 architecture, using this code:

` public static boolean has64bitsArch() {
        return Build.SUPPORTED_64_BIT_ABIS.length > 0;
    }`

The issue is that app is not compiling due to the abiFilter, but its compiling and seems working removing the ndk abiFilter part. Can the DJI SDK be part of a non x64 app but initializing the SDK only checking if the app has x64 ABI, or can have an unexpected behaviour?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/119204'>Zendesk ticket #119204</a>:<br><br>If you are using MSDK V5, it only supports the arm64 architecture. Other architectures will not function properly.

The arm64-v8a architecture is indeed a widely used architecture, and among the models compatible with MSDK V5, there are quite a few drones that require the app to be installed internally on the remote controller.
<br><p><em><small>°°°</small></em></p>

**Comment by punto338** [comment]
I have an application with many features that are unrelated to the DJI SDK; it's an app that should be installable on any device. One of those features requires the DJI SDK, so through code, I only initialize the DJI SDK if the device supports 64-bit. However, in order to compile the app, I must add the dependency regardless. Will this cause any issues, or should it work fine as long as I only initialize the DJI SDK if the architecture of the device running the app is 64-bit?

I don't need to run MSDK V5 on a non arm64 archicture. I need to add the dependency in my app, which has other features that can be installed in any architecture device. The issue is if the app will run properly without initializing the SDK in the non arm64 architecture.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/119204'>Zendesk ticket #119204</a>:<br><br>I don't need to run MSDK V5 on a non arm64 archicture. I need to add the dependency in my app, which has other features that can be installed in any architecture device. The issue is if the app will run properly without initializing the SDK in the non arm64 architecture.
-->
You are able to configure other architectures for your own project, but please note that MSDK V5 can only run on ARM64 devices.
<br><p><em><small>°°°</small></em></p>

**Comment by punto338** [comment]
Using this code:

![image](https://github.com/user-attachments/assets/82bf0ad4-51b1-4d2b-a4dc-846b6a682762)

using gradle 7.4.2 is working fine, livestream is OK, but in gradle 8.7 I get this error:

error trying to stream: UNKNOWN => Live stream error is unknown

The only change I make is the gradle version, so no doubt is gradle issue.
