### ISSUE TITLE
DJIPolyline lost ability to read points?

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android-V5#43]
Our apps specifically used the ability to read the point's value to calculate center lines and such as points are manipulated.  Will this be returning, or do I need to create abstractions for missing properties needed?

Specifically, just reading point's list

V4:

public interface DJIPolyline {
    void remove();

    void setWidth(float var1);

    float getWidth();

    void setPoints(List<DJILatLng> var1);

    List<DJILatLng> getPoints();

    void setColor(@ColorInt int var1);

    @ColorInt
    int getColor();

    void setZIndex(float var1);

    float getZIndex();
}

V5: 

public interface DJIPolyline {
    void remove();

    void setWidth(float var1);

    void setPoints(List<DJILatLng> var1);

    void setColor(int var1);
}

**Comment by DJI-William** [comment]
The DJIPolyline is a class in mapkit jar file. You cannot overritten it. You should use its child class which contains the the setZIndex and the rest of the methods such as MapLibrePolyline. They are the acutally polyline used in the map. Anyway, we will continue working on the mapkit jar file in 5.2 MSDK.

**Comment by kenargo** [comment]
Technically, I can create an override using encapsulation, but that is not the point.  As V5 is said to be an upgrade from V4.x and required if we want to fly M30s I am finding a significant amount of functionality loss between the versions.  Enough functionality loss that we might be precluded from purchasing and using M30 aircraft for the upcoming 2023 season.  Can you share v5.2 schedule?

**Comment by DJI-William** [comment]
I will talk with the dev team about the mapkit core and make sure this lib is up to date! Any other modules you have found that is is older than v4?

**Comment by kenargo** [comment]
Until the V5 SDK is up to par with 4.16.x I cannot see the new SDK as a valid replacement.  Also missing are large numbers of key values, but that is another issue.

**Comment by DJI-William** [comment]
Need to upgrade the mapkit.so.

**Comment by DJI-William** [comment]
@kenargo The MapKit and MapWidget were done and uploaded into this Github now.
