### ISSUE TITLE
No PHOTO_HIGH_RESOLUTION (48mp) for M3T

### ISSUE THREAD

**Issue by AhmedHMoustafa** [dji-sdk/Mobile-SDK-Android-V5#437]
Hello. 

I am unable to set the **CameraMode** of M3T to PHOTO_HIGH_RESOLUTION for 48mp photos through the SDK even though it is possible to do so through DJI Pilot.

Calling **KeyCameraModeRange**  does not list PHOTO_HIGH_RESOLUTION. It returns only `[PHOTO_NORMAL, PHOTO_INTERVAL, PHOTO_PANORAMA, PHOTO_HYPER_LIGHT, VIDEO_NORMAL, PHOTO_SUPER_RESOLUTION]`.
And ofcourse trying to change the **CameraMode** to PHOTO_HIGH_RESOLUTION  anyway is unsuccessful and causes an error.

Is there something I'm missing? 

Thanks!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/120682'>Zendesk ticket #120682</a>:<br><br>Could you share with us how you achieved this on Pilot?
<br><p><em><small>°°°</small></em></p>

**Comment by AhmedHMoustafa** [comment]
Thank you for your reply. 

Here's how I switch to high resolution photos on DJI Pilot 2. 

Simply through the settings menu on the right, I select 8K resolution for photos. The photos taken end up being 48mp (8000x6000) as expected. 

![sc_1](https://github.com/user-attachments/assets/f1629680-5ae0-4237-a1ff-c9a8692e03dc)
![sc_2](https://github.com/user-attachments/assets/7456ca6d-4e88-4804-92fe-b8117a2b2b03)

PHOTO_NORMAL in the sdk only produces 12mp photos (4000x3000). I would expect PHOTO_HIGH_RESOLUTION to produce 48mp as described in the documentation [here](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/DJIValue.html?search=high_resolu&i=0&#value_camera_enum_cameramode_inline), but as I explained before, that mode is not available for M3T.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/120682'>Zendesk ticket #120682</a>:<br><br>You can refer to this article to SELECT 8K:https://sdk-forum.dji.net/hc/en-us/articles/16809007486745-How-to-set-the-captured-photo-size
<br><p><em><small>°°°</small></em></p>

**Comment by AhmedHMoustafa** [comment]
That seems to do it, Would be great to have it a bit clearer in the documentation though :D Thanks a lot for the prompt response. I will close this now.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/120682'>Zendesk ticket #120682</a>:<br><br>Starting from MSDK 5.6.0, the **KeyPhotoCSize** is officially used to set the size of photos. If the article mentioned above is valid, I suggest you use this for your settings.
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_Camera_CameraKey.html?search=photosize&i=2&#key_camera_photosize_inline

Regarding the issue with the document description, I will relay this to the appropriate engineer.
<br><p><em><small>°°°</small></em></p>
