### ISSUE TITLE
Where is MapWidget?

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android-V5#44]
The map code is 100% commented out.

**Comment by DJI-William** [comment]
We will work on mapkit core first and then the mapWidget in 5.2, probs happen in the next sprint.

**Comment by kenargo** [comment]
Until MapWidget is released, and the missing key values re-added I cannot see V5 as a replacement or overly usable.  We will be delaying its use until functionality is on-par with prior SDK.

**Comment by DJI-William** [comment]
@kenargo The MapKit and MapWidget were done and uploaded into this Github now.
