### ISSUE TITLE
Sample having Debug errors

### ISSUE THREAD

**Issue by Jhug87-Trade** [dji-sdk/Mobile-SDK-Android-V5#440]
I am getting stopped by errors in the debugging, does this have to do with which version of Android Studio or gradle I use?
:sample:checkDebugAarMetadata
:sample:checkDebugAndroidTestAarMetadata
:sample:checkDebugAndroidTestDuplicateClasses
:sample:checkDebugDuplicateClasses
:sample:desugarDebugFileDependencies
:sample:mapDebugSourceSetPaths
:sample:mergeDebugResources
:uxsdk:processDebugManifest
:sample:mergeDebugAndroidTestAssets
:uxsdk:checkDebugAndroidTestAarMetadata
:sample:mergeDebugNativeLibs
:sample:mergeDebugAssets
:uxsdk:generateDebugRFile
:uxsdk:mapDebugAndroidTestSourceSetPaths
:uxsdk:mergeDebugAndroidTestResources
:uxsdk:mergeDebugAndroidTestAssets
:uxsdk:checkDebugAndroidTestDuplicateClasses
:uxsdk:desugarDebugAndroidTestFileDependencies
:uxsdk:mergeDebugAndroidTestNativeLibs

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/120689'>Zendesk ticket #120689</a>:<br><br>This might be related to the version of Gradle you are using. If you are currently using Gradle 8.x, please change it to Gradle 7.x.

Additionally, there is a known issue with the current sample code. You can refer to this article to modify the repository configuration:https://sdk-forum.dji.net/hc/en-us/articles/37229365477657
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
Thank you, 
Does this hold true even for the new 5.11.0 version?

**Comment by Jhug87-Trade** [comment]
I used the 5.11.0 and followed your instructions and I was able to get this to work.  Thank you for your help!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/120689'>Zendesk ticket #120689</a>:<br><br>I’m glad to hear that this has been helpful to you.
<br><p><em><small>°°°</small></em></p>
