### ISSUE TITLE
Link to Aircraft : Not Linking

### ISSUE THREAD

**Issue by Jhug87-Trade** [dji-sdk/Mobile-SDK-Android-V5#442]
I am Using the 5.11.0 release of the sample MSDK.  I have the app successfully running on a Google Pixel 7.  I am attempting to Link to a Mavic 3T.  However, when I click to link I get the error **"ErrorImp{error Type='CORE', errorCod.."**  I dont see the rest of the error and I do not know how to try to troubleshoot this error.

![Screenshot_20241108-170502](https://github.com/user-attachments/assets/be11dc32-87ae-4fd8-b969-08c2fa6d74fc)
![Screenshot_20241108-170449](https://github.com/user-attachments/assets/cf1378e6-1e96-4cbb-aa65-b646914ea4c9)
![Screenshot_20241108-170556](https://github.com/user-attachments/assets/62895fa2-3c48-4cb3-8604-58831f1cf2f3)

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/121467'>Zendesk ticket #121467</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

What are the instructions being executed? What does a link mean?
Did you force Pilot 2 to shut down?

Thank you for your email and have a nice life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
According to the Logcat this is the error: 
2024-11-11 16:14:42.949 10173-10173 V5_RUNNING_INFO         com.dji.sampleV5.aircraft            E  io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | RxError{djiError=ErrorImp{errorType='CORE', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='FLIGHTCONTROLLER.AircraftName:-1', description='null', hint='error code = -1'}}

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/121467'>Zendesk ticket #121467</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

The information you provided did not pinpoint the problem,

1. What instruction did you execute that caused this error?
2. If the startup program times an error, can you provide and record the video before and after the failure?

Thank you for your email and have a nice life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
This occurs once the sample app opens.  It shows Registration Status: Registered but it can not seem to connect to my aircraft (Mavic 3T).  I get this same CORE error on the landing dashboard, the Widget List --> RC Pairing Widget and the Default Layout --> Link to Aircraft .

I ensure the Remote controller does connect correctly to the Mavic 3T and the firmware has been fully updated

![Screenshot_20241111-212001](https://github.com/user-attachments/assets/6b7f4ff0-d76d-4ccb-97d8-3297be0108a3)
![Screenshot_20241111-212033](https://github.com/user-attachments/assets/fe1e2b66-9083-4b54-a701-289645628d7f)

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/121467'>Zendesk ticket #121467</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

Is your app on the remote?

Thank you for your understanding and support, I wish you a happy life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
The app is on a Pixel 7.  It ran successfully and opens on the phone it just does not connect to Aircraft.

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/121467'>Zendesk ticket #121467</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

You need to run it on the remote, otherwise you won't be able to connect to the drone

Thank you for your understanding and support, I wish you a happy life!
Best Regards,
Dji innovation SDK technical support<br><a href='https://djisdksupport.zendesk.com/attachments/token/Vu0yZBPD8lKxY51ix0OFd8WbN' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
That worked Thank you!!!
