### ISSUE TITLE
live stream with RTSP error

### ISSUE THREAD

**Issue by Chen-Zhihui** [dji-sdk/Mobile-SDK-Android-V5#444]
试用示例应用中的RTSP直播选项时
![Screenshot_20241113-161849](https://github.com/user-attachments/assets/a217ebb1-a4d8-41d0-a0b6-feef2140a290)
遥控器使用Wifi接入网络
![Screenshot_20241113-162546](https://github.com/user-attachments/assets/5e011a3b-4126-4259-aae8-481962e22dd3)
从电脑上可以ping通遥控器
![image](https://github.com/user-attachments/assets/9cb8dc59-733e-4d3b-95ab-e64957228245)

遥控器版本
![Screenshot_20241113-162610](https://github.com/user-attachments/assets/19b386f6-6138-4e36-b8d6-8d9f48471006)
![Screenshot_20241113-162624](https://github.com/user-attachments/assets/398da32a-8b61-418f-83dd-4eb38e1b9dee)

采用VLC拉流时出错
![image](https://github.com/user-attachments/assets/2cb75b03-212d-4bae-a336-0194f60d87fe)

![image](https://github.com/user-attachments/assets/d69bf5a8-5d04-4a0e-b1e2-d63015d6e79a)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121794'>Zendesk ticket #121794</a>:<br><br>遥控器和拉流设备是在一个网络下吗？RTSP需要在一个网络下使用。
<br><p><em><small>°°°</small></em></p>

**Comment by Chen-Zhihui** [comment]
> Agent comment from yating.liao in [Zendesk ticket #121794](https://djisdksupport.zendesk.com/agent/tickets/121794):遥控器和拉流设备是在一个网络下吗？RTSP需要在一个网络下使用。
> 
> _°°°_

是的，挂在同一个Wifi AP下，用同一网段
