### ISSUE TITLE
KeyCameraZoomRatios inaccurate first value

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#445]
SDK: `5.11.0`
Drones: Mavic 3 Series (Enterprise + Thermal)

I have implemented the `CameraKey.KeyCameraZoomRatios` (see below) and display the value. Majority of the time, this works as intended. Problems arise when launching the app and drone from a cold start.

```
keyManager.listen(
    KeyTools.createCameraKey(
        CameraKey.KeyCameraZoomRatios,
        ComponentIndexType.LEFT_OR_MAIN,
        CameraLensType.CAMERA_LENS_ZOOM
    ),
    this
) { _, newValue ->
    Log.e("TEST", "Camera Lens Zoom zoom: $newValue")
    // Display newValue
}
```

If I:
1. Launch my app (it was not previously running and neither is Pilot)
2. Turn on my drone (Mavic 3E or 3T)

The value I see is `10.6`. If I attempt to change this value to `1.0`:

```
keyManager.setValue(
    cameraKey,
    1.0,
    object : CompletionCallback {
        override fun onSuccess() {
            // Do nothing
            Log.e("TEST", "setFocusDistance success")
        }

        override fun onFailure(error: IDJIError) {
            Log.e("TEST", "setFocusDistance failed: $error")
        }
    }
)
```

The value changes to `1.5` (full log shows `Camera Lens Zoom zoom: 1.5141955835962144`). I cannot change it to anything less then `1.5` even though `setFocusDistance success` always shows up in my log. This continues until I completely close and re-launch the app. This does not occur in Pilot (shows an initial value of `7.0` and I can set the value to `1.0` without issue).

Interestingly, when I check the value of `CameraKey.KeyCameraZoomFocalLength`:

```
keyManager.listen(
    KeyTools.createCameraKey(
        CameraKey.KeyCameraZoomFocalLength,
        ComponentIndexType.LEFT_OR_MAIN,
        CameraLensType.CAMERA_LENS_ZOOM
    ),
    this
) { _, newValue ->
    Log.e("TEST", "Zoom focal length: $newValue")
}
```

The value logged is `Zoom focal length: 24` even regardless of the value logged by `CameraKey.KeyCameraZoomRatios` (`1.5141955835962144` or `1.0`).

Is there another key that can effect the value returned by getting/listening `CameraKey.KeyCameraZoomRatios`? Or should I perform a calculation on `CameraKey.KeyCameraZoomFocalLength` to determine the zoom level instead?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121830'>Zendesk ticket #121830</a>:<br><br>I am unable to replicate the issue as you described. Can you trigger this error using the sample code?
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
I can.

1. Power down the drone and close the sample app.
2. Launch the sample app
3. Navigate to `Widget List` -> `Focal Zoom Widget`. Zoom value should be `2.0X`.
4. Turn on the drone
5. Notice the zoom value changes to `10.6X` instead of `7.0X`
6. Push the power button (black screen)
7. Push the power button again to resume using the app. Notice the zoom value changes to `7.0X`

This is as far as I can go without modifying the Sample App code (the lower bounds of the zoom remains `2.0X` regardless of what I do). If you modify `FocalZoomWidgetView.mFocalLengthGears` to update more frequently, you can get the lower bounds to be `1.0X` and reproduce the issue in full (same steps as above).

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121830'>Zendesk ticket #121830</a>:<br><br>I will follow the steps you provided to replicate this issue. Please hold on for a moment.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121830'>Zendesk ticket #121830</a>:<br><br>If you test using DefaultLayoutActivity, this issue will not occur.
 The updateCameraSource function in FocalZoomWidget updates the zoom range supported by the current lens. Since updateCameraSource is not used in widgetList, the default range is displayed.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Testing in `DefaultLayoutActivity` shows that `FocalZoomWidget.updateCameraSource` gets called early and often. The contents of `updateCameraSource` show that the related listeners to `CameraKey.KeyCameraZoomRatios` get _reset by reassigning variables_ which is "fixing" the issue. This doesn't seem to be a fix as much as hiding the problem.

If this is intended behavior, what this tells me is that the following:

```
keyManager.listen(
    KeyTools.createCameraKey(
        CameraKey.KeyCameraZoomRatios,
        ComponentIndexType.LEFT_OR_MAIN,
        CameraLensType.CAMERA_LENS_ZOOM
    ),
    this
) { oldValue, newValue -> }
```
is being called too early. When should I initialize this listener? I currently call this (and about 50 or more other keys) on application startup AFTER successful registration. I have not come across any documentation that says when listening to keys should be started.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121830'>Zendesk ticket #121830</a>:<br><br>You need to ensure that the registration in MSDK has been completed and that the camera connection is confirmed before making the call.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121830'>Zendesk ticket #121830</a>:<br><br>The most important point here is that the MSDK registration is completed.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Registration was never the issue. As mentioned, registration was completed prior to initializing the listener.

For anyone who ends up here, make sure to initialize most `CameraKey` listeners after `CameraKey.KeyConnection` is returning a value of `true`. It will look something like this:

```
keyManager.listen(
    KeyTools.createKey(
        CameraKey.KeyConnection,
        ComponentIndexType.LEFT_OR_MAIN
    ),
    this // Or whatever object is going to be bound to the callback
) { _, newValue ->
    if (newValue == true) {
        // Initialize other keyManager.listen()
    } else {
        // Remove any active listeners. Accomplished by:
        //     keyManager.cancelListen(CameraKey.XXXXX)
    }
}
```

The original issue is resolved by doing this. Please note it is not explicitly documented anywhere and may change.
