### ISSUE TITLE
RTSP live Stream error

### ISSUE THREAD

**Issue by Chen-Zhihui** [dji-sdk/Mobile-SDK-Android-V5#448]
试用示例应用中的RTSP直播选项时出错。网络连接情况如下图，测试电脑（播放器）与遥控器连在同一个wifi下。

![未命名绘图 drawio](https://github.com/user-attachments/assets/855925aa-4ac9-4356-ae89-b26988246750)

直播选项
![image](https://github.com/user-attachments/assets/fa4748cf-5652-404f-9700-489488b9398f)

从电脑上可以ping通遥控器
![image](https://github.com/user-attachments/assets/217f4193-ae78-42d7-a965-e67c99c3566e)

遥控器版本
![image](https://github.com/user-attachments/assets/eb4449ba-3cdd-4b6f-a9d5-8ed051700130)
![image](https://github.com/user-attachments/assets/6a68078d-8913-4d68-97bd-3dd86673ed7a)

采用VLC拉流时出错
![image](https://github.com/user-attachments/assets/d97a194f-baff-4a99-a5ec-7347421f8b82)
![image](https://github.com/user-attachments/assets/332ff299-ae9f-40a7-8177-46d490ec36de)

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/122093'>Zendesk ticket #122093</a>:<br><br>尊敬的开发者，

您好，感谢您联系DJI 大疆创新。

RTSP live Stream error
==》
RTSP开启成功了吗？
错误截图可以提供吗？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Chen-Zhihui** [comment]
> Agent comment from SHENRONG.LE in [Zendesk ticket #122093](https://djisdksupport.zendesk.com/agent/tickets/122093):尊敬的开发者，
> 
> 您好，感谢您联系DJI 大疆创新。
> 
> RTSP live Stream error ==》 RTSP开启成功了吗？ 错误截图可以提供吗？
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！ Best Regards, 大疆创新SDK技术支持
> 
> _°°°_

RTSP开启了，没有报错
