### ISSUE TITLE
msdkv5 没有MOP吗，要怎么连接OSDK呢

### ISSUE THREAD

**Issue by ccccwb** [dji-sdk/Mobile-SDK-Android-V5#45]

**Comment by DJI-William** [comment]
MSDK v5还没设计MOP功能，预计下个版本开始开发，即使开发完成后也只支持PSDK v3，PSDK v3已经和OSDK合并。

**Comment by DJI-William** [comment]
@ccccwb MOP功能正式开放要等到御3行业版系列得MOP做好后同一开放，目前仅支持M300RTK的MOP，没有API文档，需要调用内部类，我已经写了一个知识库文章，用法基本和v4的MOP一样，你只要有v4的基础马上就明白了。请阅读这篇文章，[第十八章：第三方负载](https://sdk-forum.dji.net/hc/zh-cn/articles/9882836266649-%E7%AC%AC%E5%8D%81%E5%85%AB%E7%AB%A0-%E7%AC%AC%E4%B8%89%E6%96%B9%E8%B4%9F%E8%BD%BD)
