### ISSUE TITLE
`VideoResolutionFrameRate` key does not provide a value for the thermal lens of M3T

### ISSUE THREAD

**Issue by sreedy-riis** [dji-sdk/Mobile-SDK-Android-V5#456]
We have noticed that the `VideoResolutionFrameRate` Key for the M3T on the thermal lens does not succeed on newer versions of the MSDK. If we obtain the value using the MSDK sample app with 5.8 we get the response 

```== success ('resolution":26. frameRate:37)```

and on 5.11 (and I believe 5.10) we get 
``` 
=- Errorimp(errorType-'CORE, errorCode='REQUEST_HANDLER_NOT_FOUND,innerCode='CAMERA.VideoResolutionFrameRate:-1',description='null',hint='errorcode
=-1').
```

These were both checked by setting the subtype to `2` and leaving the subindex at `0` for the `LEFT_OR_MAIN` component index. This key still seems to work fine on wide and zoom lens. 

Were there any changes to how this key should be used on later SDK versions?

Thanks

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124017'>Zendesk ticket #124017</a>:<br><br>Dear developer,
Hello, thank you for contacting DJI Innovations.

We reproduced the issue you raised on version 5.11, but I asked our R&D colleagues and found that this interface actually does not support infrared lenses to obtain camera lens video resolution and frame rate. Thank you for your feedback.

Thank you for your email. Wishing you a happy life!
Best Regards,
DJI Innovation SDK Technical Support
<br><p><em><small>°°°</small></em></p>

**Comment by sreedy-riis** [comment]
The M3T has two valid frame rate options, 640x512 @ 9FPS and 640x512 @ 30 FPS. How would we toggle between these if its not supported?

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124017'>Zendesk ticket #124017</a>:<br><br>Dear developer,
Hello, thank you for contacting DJI Innovations.

I asked my R&D colleagues and they said that I can only use one 30 and cannot switch.

Thank you for your email. Wishing you a happy life!
Best Regards,
DJI Innovation SDK Technical Support
<br><p><em><small>°°°</small></em></p>

**Comment by sreedy-riis** [comment]
Got it, thank you

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124017'>Zendesk ticket #124017</a>:<br><br>Dear developers,
Hello, thank you for contacting DJI Innovation.

you are welcome

Thank you for your email and have a nice life!
Best Regards,
Dji innovation SDK technical support
<br><p><em><small>°°°</small></em></p>
