### ISSUE TITLE
Which RC supports MSDK in Mavic 3T

### ISSUE THREAD

**Issue by Jhug87-Trade** [dji-sdk/Mobile-SDK-Android-V5#457]
Hello,

Can you please explain does the MSDK run on the Mavic 3T Remote with screen on an android device or does the SDK need to be installed on the remote?

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124142'>Zendesk ticket #124142</a>:<br><br>Dear developer,
Hello, thank you for contacting DJI Innovations.

Need to install and run MSDK in the remote control

Thank you for your email. Wishing you a happy life!
Best Regards,
DJI Innovation SDK Technical Support
<br><p><em><small>°°°</small></em></p>

**Comment by Jhug87-Trade** [comment]
Thank you for the clarification

**Comment by dji-dev** [comment]
Agent comment from SHENRONG.LE in <a href='https://djisdksupport.zendesk.com/agent/tickets/124142'>Zendesk ticket #124142</a>:<br><br>Dear developer,
Hello, thank you for contacting DJI Innovations.

 you are welcome

Thank you for your email. Wishing you a happy life!
Best Regards,
DJI Innovation SDK Technical Support
<br><p><em><small>°°°</small></em></p>
