### ISSUE TITLE
Hotpoint Support

### ISSUE THREAD

**Issue by wooldridgetm** [dji-sdk/Mobile-SDK-Android-V5#46]
Is there any plan to support [hotpoints](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIHotpointMissionOperator.html) (orbitals)?

Using the v5.1 SDK, there is no mention of hotpoints or orbitals anywhere in the docs or the API.

**Comment by DJI-William** [comment]
We have no plan to support this function in 5.1 as there are no many people using this function in 4.16.2 version based on our investigation.

**Comment by zt1983811** [comment]
Hello @DJI-William , is there anything new for support the hotpoint mission in SDK 5.6 or future?
