### ISSUE TITLE
Mavic 3 WPML Codes

### ISSUE THREAD

**Issue by wooldridgetm** [dji-sdk/Mobile-SDK-Android-V5#47]
For the mavic 3 enterprise and its thermal equivalent, the [documentation](https://developer.dji.com/doc/cloud-api-tutorial/en/specification/dji-wpml/common-element.html) doesn't explicitly specify the required information for the `<wpml:droneInfo>` and `<wpml:payloadInfo>` elements.

Do the mavic 3 enterprise and mavic 3 thermal support flight planning? If so, then what values should be set for the `droneEnumValue`,`droneSubEnumValue`, `payloadEnumValue`, `payloadSubEnumValue`, and `payloadPositionIndex`?

```
<wpml:droneInfo>
    <wpml:droneEnumValue>67</wpml:droneEnumValue>
    <wpml:droneSubEnumValue>0</wpml:droneSubEnumValue>
</wpml:droneInfo>
<wpml:payloadInfo>
    <wpml:payloadEnumValue>52</wpml:payloadEnumValue>
    <wpml:payloadSubEnumValue>0</wpml:payloadSubEnumValue>
    <wpml:payloadPositionIndex>0</wpml:payloadPositionIndex>
</wpml:payloadInfo>
```

**Comment by dji-dev** [comment]
Agent comment from sean in <a href='https://djisdksupport.zendesk.com/agent/tickets/71786'>Zendesk ticket #71786</a>:<br><br>Yes，Mavic 3E or Mavic 3T support wpml.
This is Mavic 3E.
 ![](https://djisdksupport.zendesk.com/attachments/token/j3lUNGtfBgy1BcZOZn5Ik913M/?name=image.png)
This is Mavic 3T.
 ![](https://djisdksupport.zendesk.com/attachments/token/4KHLNbGeZkKGJVLaZDgQdSGd6/?name=image.png)<br><a href='https://djisdksupport.zendesk.com/attachments/token/j3lUNGtfBgy1BcZOZn5Ik913M' target='zd_attach'>image.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/4KHLNbGeZkKGJVLaZDgQdSGd6' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
We need to update the KMZ documentation and write an article in the knowledge base about this.

**Comment by PeimanAtaeiJPDroni** [comment]
> Agent comment from sean in [Zendesk ticket #71786](https://djisdksupport.zendesk.com/agent/tickets/71786):Yes，Mavic 3E or Mavic 3T support wpml. This is Mavic 3E. ![](https://camo.githubusercontent.com/8dbb252225896f33aef21aa7fe6956944901ea31830a817efada9e04072b6c86/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f6a336c554e4774664267793142635a4f5a6e35496b3931334d2f3f6e616d653d696d6167652e706e67) This is Mavic 3T. ![](https://camo.githubusercontent.com/5bc08346286932b759c445b67b2e1e61fa5c494c2011ca3aa42e7ee8b8ce52b3/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f344b484c4e6247655a6b4b474a564c615a44675164534764362f3f6e616d653d696d6167652e706e67)[image.png](https://djisdksupport.zendesk.com/attachments/token/j3lUNGtfBgy1BcZOZn5Ik913M)[image.png](https://djisdksupport.zendesk.com/attachments/token/4KHLNbGeZkKGJVLaZDgQdSGd6)
> 
> _°°°_

Excuse me I have the same problem and as I see this issue is completed but you did not provide the solution.

the 2 images you uploaded are not accessable to me, I do not know why

would you please tell me what info I should insert for droneEnumValue,droneSubEnumValue, payloadEnumValue, payloadSubEnumValue, and payloadPositionIndex for drone M3T?

**Comment by wooldridgetm** [comment]
All of the information is available in their [WPML documentation](https://developer.dji.com/doc/cloud-api-tutorial/en/api-reference/dji-wpml/common-element.html).

**Comment by PeimanAtaeiJPDroni** [comment]
Yes but as you can see the code and the document are not the same. 

for example, in document we know payload type is 67 (Mavic 3T Camera). 

![payload](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/262a1191-bfed-402c-9c90-f01fd7324a44)

But in the code we do not have any option to choose it (as you can see in the image):

![photo_2023-11-16_18-49-25](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/128388408/61c8969f-103a-46b4-81ab-be7fbbabb86f)

so for the M3T, which one is correct ?
