### ISSUE TITLE
V5.1 Unable to use Surface in VideoDecoder

### ISSUE THREAD

**Issue by sjhunn** [dji-sdk/Mobile-SDK-Android-V5#48]
When trying to instantiate a VideoDecoder with a Surface, I get this exception:

10-11 12:35:49.240 29184 29434 D ACRA    : starting video channel: PRIMARY_STREAM_CHANNEL PORTSIDE SURFACE_MODE
10-11 12:35:49.241 29184 29434 D ACRA    : outputSurface: Surface(name=null)/@0xeb7425b
--------- beginning of crash
10-11 12:35:49.705 29184 29375 D ACRA    : primary channel state changed: from CLOSE to ON
10-11 12:35:49.705 29184 29375 D ACRA    : primary channel state changed: from ON to CLOSE
10-11 12:35:49.883 29184 29375 D ACRA    : primary channel state changed: from CLOSE to ON
10-11 12:35:50.342 29184 29184 D ACRA    : startVideoCallback success
10-11 12:35:52.268 29184 29434 E ACRA    : ACRA caught a IllegalArgumentException for com.---.---.---.dji
10-11 12:35:52.268 29184 29434 E ACRA    : java.lang.IllegalArgumentException: The outputSurface must be a object of Surface, SurfaceHolder, SurfaceTexture, SurfaceView
10-11 12:35:52.268 29184 29434 E ACRA    :      at dji.v5.common.video.decoder.VideoDecoder.<init>(VideoDecoder.java:112)
10-11 12:35:52.268 29184 29434 E ACRA    :      at dji.v5.common.video.decoder.VideoDecoder.<init>(VideoDecoder.java:42)
10-11 12:35:52.268 29184 29434 E ACRA    :      at com.---.---.---.dji.DJIInterface.startChannel(DJIInterface.java:4281)
10-11 12:35:52.268 29184 29434 E ACRA    :      at com.---.---.---.dji.DJIInterface.access$13100(DJIInterface.java:131)
10-11 12:35:52.268 29184 29434 E ACRA    :      at com.---.---.---.dji.DJIInterface$155.run(DJIInterface.java:4240)
10-11 12:35:52.268 29184 29434 E ACRA    :      at java.lang.Thread.run(Thread.java:919)

**Comment by DJI-William** [comment]
Please read this article, [What kind of outputSurface does the VideoDecoder support?](https://sdk-forum.dji.net/hc/en-us/articles/11408372476569-What-kind-of-outputSurface-does-the-VideoDecoder-support-)

**Comment by sjhunn** [comment]
Thanks William. We were able to use a Surface in v5.0.0. Something changed in v5.1.0 and I need to know if the removal of using a Surface is a permanent change? Or just a bug?

**Comment by DJI-William** [comment]
In v5.1, we banned the TextureView and SurfaceTexture, it is the design.
