### ISSUE TITLE
VideoDecoder cannot accept TextureView

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#49]
In V5.0.0 i used TextureView to create the VideoDecoder and it worked, but after i upgraded to 5.1.0 i got an exeption:
`java.lang.IllegalArgumentException: The outputSurface must be a object of Surface, SurfaceHolder, SurfaceTexture, SurfaceView`
But i am using the SurfaceTexture of the SurfaceView.

**Comment by DJI-William** [comment]
Please read this article, [What kind of outputSurface does the VideoDecoder support?](https://sdk-forum.dji.net/hc/en-us/articles/11408372476569-What-kind-of-outputSurface-does-the-VideoDecoder-support-)
