### ISSUE TITLE
v5.1.0 VideoChannel On/Close/On Initialization

### ISSUE THREAD

**Issue by sjhunn** [dji-sdk/Mobile-SDK-Android-V5#50]
When attaching a state change listener to a VideoChannel after SDK initialization/registration, the state of the channel flips between ON and CLOSE one or more times. I assume this is just the initialization process of the channel.

Is there any way to tell when the video channel is done initializing and is ready to use?

Is there something in v5 like the ComponentListener in v4?

Or do I just need to wait ~10 secs before I start using video channels?

**Comment by DJI-William** [comment]
Are you using our Sample or you start from scratch? You may know for multi video stream aircraft, you need to set the cameraVideoStreamSource to define which video stream is the primary source and which one is the secondary. Initially, the videoChannel is on, and in our Sample, we do the cameraVideoStreamSource set automatically for you so the videoChannel will change to cloase while setting it. Later on it changes to on again. If you develop your project from scratch, this issue shouldn't occur, the videoChannel is available whenever it becomes to on.
