### ISSUE TITLE
Getting Bitmap from FPVWidget

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android-V5#53]
Hello,
In MSDK v4 i could get a bitmap from the codec manager of the FPVWidget.
How can i do that with MSDK v5?

**Comment by DJI-William** [comment]
The FPVWidget is open sourced in MSDK v5. Since it is using SurfaceView, you may receive the video data and save it to bitmap by yourself. I am afraid there is no getBitmap method in the SurfaceView.
