### ISSUE TITLE
No camera image.

### ISSUE THREAD

**Issue by xakermonkey** [dji-sdk/Mobile-SDK-Android-V5#55]
Hello. I'm running the app out of the box as it is and I can't get an image from the drone (the api key is of course installed). The registration of the application is successful, all indicators are read from the drone, but there is no image. I also tried to build from SDK 5.0, but the application crashes there immediately after registration, nothing can be done. Please tell me what I should pay attention to. I have removed all third-party applications (official dji), nothing interferes with the work.
Mavic 3

Thanks

**Comment by DJI-William** [comment]
Are you using the Mavic 3 or Mavic 3 Enterprise series? MSDK v5 currently does not support Mavic 3.

**Comment by xakermonkey** [comment]
Is this Mavic 3 or Mavic 3 Enterprise?
What sdk do i need to use?

![B4FF833E-F3A7-4683-BCFC-4DBA5EB60E0A](https://user-images.githubusercontent.com/78655754/201830545-36dabc8c-5236-4ecf-b247-9b4389624123.jpeg)

**Comment by DJI-William** [comment]
This seems like Mavic 3 not a Mavic 3 Enterprise, there is no SDK for it.

**Comment by xakermonkey** [comment]
Yes, there are no inscriptions of the Enterprise. However, everything is read from the drone except for the image. Can this be fixed somehow? It is very strange that Mavic 3 is not supported. When will there be official support?

**Comment by DJI-William** [comment]
We don't have plans to support Mavic 3 now so some of the functiosn may work and some of them may not work.

**Comment by xakermonkey** [comment]
Wow, very strange.. Tell me how to make support? Where to look?

**Comment by DJI-William** [comment]
The support can only be done by our dev team but currently we don't have plans to support Mavic 3.
