### ISSUE TITLE
A problem occurred evaluating project ':android-sdk-v5-uxsdk'.

### ISSUE THREAD

**Issue by hiimthetwos** [dji-sdk/Mobile-SDK-Android-V5#58]
Trying to add the SDK to an empty project. After uxsdk is added, gradle fails to build project and gives the error

A problem occurred evaluating project ':android-sdk-v5-uxsdk'.
> Could not get unknown property 'deps' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

after adding dependencies to build.gradle of uxsdk

**Comment by DJI-William** [comment]
Just import your UXSDK as a module, please read this article, [Chapter 3: Integrate the SDK into your project](https://sdk-forum.dji.net/hc/en-us/articles/9168348360345-Chapter-3-Integrate-the-SDK-into-your-project).

**Comment by hiimthetwos** [comment]
Thanks! I also had to downgrade the gradle build to 7.2.2

**Comment by DJI-William** [comment]
@hiimthetwos Is the problem solved?
