### ISSUE TITLE
Disable remote controller when virtual sticks are enabled

### ISSUE THREAD

**Issue by wooldridgetm** [dji-sdk/Mobile-SDK-Android-V5#59]
Using the V5 SDK, is it possible to disable the RC sticks and gimbal movement when virtual sticks are enabled?

I've tested this against the M3T and M30T M3T, and the RC is still able to control the drone when virtual sticks are enabled.

**Comment by DJI-William** [comment]
Once you have enabled the setVirtualStickAdvancedModeEnabled, you have to keep sending the sendVirtualStickAdvancedParam to blocking the remote controller stck command. If you want the aircraft stays hover in air, just sending (0, 0, 0, 0) as flight control data.
