### ISSUE TITLE
Add SDK access to auxiliary lights

### ISSUE THREAD

**Issue by eric-dk** [dji-sdk/Mobile-SDK-Android-V5#60]
Applies to Matrice 300 RTK, Matrice 30, and Mavic 3 Enterprise. In the previous V4 SDK [there were calls](https://developer.dji.com/api-reference/android-api/Components/IntelligentFlightAssistant/DJIIntelligentFlightAssistant.html#djiintelligentflightassistant_getdownwardfilllightmode_inline) to enable and disable the auxiliary lights. These remain unavailable in the V5 SDK.

**Comment by DJI-William** [comment]
Please read this article, [How to enable the auxiliary light functions?](https://sdk-forum.dji.net/hc/en-us/articles/9876028900121-How-to-enable-the-auxiliary-light-functions-)
