### ISSUE TITLE
Flight Logs data structure for *.DAT files

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-SDK-Android-V5#62]
Hello!

- SDK version: 5.1.1
- DJI drone model: Mavic 3T 

Official SDK documentation contains information about accessing flight logs  via [FlightLogManager](https://developer.dji.com/api-reference-v5/android-api/Components/IFlightLogManager/IFlightLogManager.html?search=logmana&i=0&). But there are only two methods that return the directory path where the files can be located. Browsing that directory reveals the following structure:
- FlightRecord
  - *.txt files
  - MCDatFlightRecords
    - *.DAT files

Unfortunately both *.txt files and *.DAT files are not readable in text editors. Not sure if *.txt files is encrypted or is perhaps even a binary file even though it has *.txt extension. The *.DAT file is also not easily readable.

Therefore, could we perhaps get either:
1. SDK methods that would return parsed flight log information from these files.
2. Binary data structure of these files so we can read them by ourselves.

**Comment by DJI-William** [comment]
It tells you how to find the .txt and .DAT files. We will release an online tool later to allow you upload the FlightRecord.txt file to the online tool to parse. Then you will get a parsed result for your aircraft's flying path and telemetry data. The MCDatFlightRecords.DAT file can be only decrypted and analysed internally by our dev teams. It is used for analysing a crash accidently and it records the internal logs for flight controller. Both of the files cannot be readed by outsiders.

**Comment by jeryini** [comment]
I understand that you can't release the keys to decrypt the MCDatFlightRecords.DAT files as those are private nature. But if you are going to provide the online public tool to parse the FlightRecord.txt files, wouldn't make sense to also release the specification of the file structure so that developers can also parse it themselves?

**Comment by DJI-William** [comment]
For FlightRecord.txt, we do provide a method to apply for [Flight Record Parse API](https://developer.dji.com/policies/flight_record/). But it requires you to have a aggrement with us and we have no workforces to provide techinical support regardst to this API. That is why we want to build an online tool for people.

**Comment by jeryini** [comment]
Hello @DJI-William !

I suppose this project [FlightRecordParsingLib](https://github.com/dji-sdk/FlightRecordParsingLib) is the one that you mentioned that is going to be released. But using the FlightRecord txt files generated by using app that runs on v5 SDK gives me error (see https://github.com/dji-sdk/FlightRecordParsingLib/issues/3#issuecomment-1474901360). Is therefore v5 SDK logs not yet supported by that library? Could we now get the full specification of the files?

Also noticed that txt flight logs are not generated if simulator mode is used on the drone, but the DAT files do appear. Is that correct?

**Comment by DJI-William** [comment]
It can only decrypt the FlightRecord.txt files. It cannot decrypt the .Dat fiile. There is nothing different with the MSDK v5 and DJI official generated Flight Record files.

**Comment by Daria-Shevchenko** [comment]
> It can only decrypt the FlightRecord.txt files. It cannot decrypt the .Dat fiile. There is nothing different with the MSDK v5 and DJI official generated Flight Record files.


Are there any updates on this issue? I'm seeking a solution to retrieve flight logs using the DJI SDK. Could you possibly provide some information?
