### ISSUE TITLE
Looking for a video streaming example...

### ISSUE THREAD

**Issue by neilyoung** [dji-sdk/Mobile-SDK-Android-V5#64]
... as like the old AndroidVideoStreamDecoding example for the 4.x version

**Comment by DJI-William** [comment]
There is no custom decoding sample for v5 now. But the method is the same. In MSDK v5, there is no H.264 video output, every aircraft will output H.265. You can use an Android library called MediaCodec to decode it into YUV data and render the surface.

**Comment by neilyoung** [comment]
Thanks. Any sample for the MediaCodec handling? I would be fine with YUV. In the 4.x versions I got the H.264 from the SDk and put it back to the SDK in order to get YUV. 

Could you please briefly outline how this has to be done in v5?

**Comment by DJI-William** [comment]
You will know our VideoDecoder class in MSDK v5 can receive the H.265 data and output the YUV data. Actually inside the VideoDecoder we are using the MediaCodec. You can google lots of example how to covert H.265 data into YUV data.

**Comment by neilyoung** [comment]
Thanks a lot. I will go and try and report here

**Comment by neilyoung** [comment]
Could you please elaborate where `DJICocedManager` is? It is still documented, but the documentation has no relation to the SDK version. https://developer.dji.com/api-reference/android-api/Components/CodecManager/DJICodecManager.html

**Comment by neilyoung** [comment]
I admit, I'm confused. Above you are saying there is no H.264 support, but H.265 instead. This documentation talks about H.264 either https://sdk-forum.dji.net/hc/en-us/articles/6663343101337-Chapter-5-Video-decode

**Comment by DJI-William** [comment]
[What is the encoding type of the output data from the StreamDataListener?](https://sdk-forum.dji.net/hc/en-us/articles/11417166355481-What-is-the-encoding-type-of-the-output-data-from-the-StreamDataListener-) I will edit the relevant articles.

**Comment by neilyoung** [comment]
Great thanks. I was trying to follow your Chapter 2 to no avail. Issue here https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/74

Pointers appreciated.

**Comment by neilyoung** [comment]
> Could you please elaborate where DJICocedManager is? It is still documented, but the documentation has no relation to the SDK version. https://developer.dji.com/api-reference/android-api/Components/CodecManager/DJICodecManager.html

Disregard the first part of the question. But am I right to assume, that the quoted documentation is outdated and covers 4.x only?

**Comment by DJI-William** [comment]
Of course, the MSDK v5 has a full separate doc.

**Comment by neilyoung** [comment]
Sure, but it is really hard to see, what is what if the existing documentation is not marked as "4.x" or so. I don't see such remark in the quoted doc
