### ISSUE TITLE
RTH does not work within a certain range

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#68]
Drone: Mavic 3E
SDK Version: `5.2.0`
Drone Firmware: `05.02.0506`
Remote Firmware: `02.00.0303`

Let me start by saying this is a really bizarre issue and I'm not sure if it is a bug with the Mobile SDK. It exists in both the app I am writing AND in the Pilot app.

While executing a waypoint mission, if I:

- Attempt to RTH AND
- The drone is <= 65ft away (horizontally) from the home point AND
- The drone has an altitude of ~90ft

Then the drone will stop executing the waypoint mission (correct), but will not return to the home point.

It does not matter if RTH was started using the remote controller's RTH button or using Mobile SDK commands. If the horizontal distance exceeds 65ft (roughly) or drone's altitude exceeds a certain height, RTH works fine.

**Comment by DJI-William** [comment]
This is a firmware bug and it will be fixed in the next firmware. Sometimes the RTH speed downs to 0.

**Comment by tkocik92** [comment]
Confirmed fix in the latest firmware update
