### ISSUE TITLE
VideoFrame already in the pool polluting log output when using additional YUV VideoDecoder

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-SDK-Android-V5#71]
Hello!

* SDK version: 5.2.0
* DJI drone model: Mavic 3T

I'm seeing a lot of these lines outputted into the run log:
```
E/VideoFrame: (co_y:3) Already in the pool!
```

It does not impact anything, video works as expected. But it's annoying. I should say that I'm using both SURFACE_MODE decoder output mode as well as YUV_MODE to render at outputSurface and receive YUV data simultaneously:
```
if (videoDecoderOutputSurface == null) {
            videoDecoderOutputSurface = VideoDecoder(
                context,
                videoChannelType,
                DecoderOutputMode.SURFACE_MODE,
                fpvSurfaceView.holder,
                fpvSurfaceView.width,
                fpvSurfaceView.height,
                false
            )
        } else if (videoDecoderOutputSurface?.decoderStatus == DecoderState.PAUSED) {
            videoDecoderOutputSurface?.onResume()
        }

        if (videoDecoderYuvData == null) {
            videoDecoderYuvData = VideoDecoder(
                context,
                videoChannelType,
                DecoderOutputMode.YUV_MODE,
                fpvSurfaceView.holder,
                fpvSurfaceView.width,
                fpvSurfaceView.height,
                false
            )
            (videoDecoderYuvData as VideoDecoder).addYuvDataListener(yuvDataListener)
        } else if (videoDecoderYuvData?.decoderStatus == DecoderState.PAUSED) {
            videoDecoderYuvData?.onResume()
        }
```

If I remove YUV video decoder then it stops showing that error in the log output. I've also tested trying to set the output surface to null when constructing YUV VideoDecoder, but it still shows the errors in the log:
```
videoDecoderYuvData = VideoDecoder(
                context,
                videoChannelType,
                DecoderOutputMode.YUV_MODE,
                null
            )
```

**Comment by DJI-William** [comment]
We will remove the log later. By they way, you can filter the log if you don't want to see.

**Comment by jeryini** [comment]
Great, thank you! How can I filter that output? Is there a configuration on one of the DJI SDK methods? Because this is not being output to Logcat tab but to the Run tab.

**Comment by DJI-William** [comment]
In your Android Studio, there is a tag you can input to filer out the log.
![image](https://user-images.githubusercontent.com/77274755/218945224-7677cc2e-588f-4f96-a6a8-81a522aad796.png)

**Comment by jeryini** [comment]
Yes, that is applied to Logcat tab, but the error message is showing in the Run tab and there is no way to filter that out.

**Comment by dji-dev** [comment]
This has been done on 5.3.0.
