### ISSUE TITLE
v5.2.0 不支持兴趣点环绕飞行吗？

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#72]

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/77425'>Zendesk ticket #77425</a>:<br><br>MSDK V5还没有兴趣点环绕的相关接口。
智能任务可以先了解pilot是否已经具有这一功能，因为有一部分智能任务没有支持是因为固件不支持，这一只能自己基于虚拟摇杆开发。
<br><p><em><small>°°°</small></em></p>
