### ISSUE TITLE
M3T - Can't take photos using WIDE or ZOOM lens using V5.2

### ISSUE THREAD

**Issue by wooldridgetm** [dji-sdk/Mobile-SDK-Android-V5#79]
I'm developing an application that works with the M3T, but I can't take a photo using the WIDE or ZOOM lens using v5.2 SDK and the latest firmware versions.

### **Versions:**
v5.2.0 SDK.
M3T V5.02.0506.
RC Pro Enterprise V02.00.0303

### **Description:**
Previously, if I wanted to take a photo using the `CameraVideoStreamSourceType.WIDE_CAMERA`, then I would set the CaptureCameraStreamSettings to include `WIDE_CAMERA` as denoted below. 

```
val info = CameraStreamSettingsInfo(false, listOf(CameraVideoStreamSourceType.WIDE_CAMERA))
CameraKey.KeyCaptureCameraStreamSettings.create(ComponentIndexType.LEFT_OR_MAIN).set(info, onSuccess = { }, onFailure = { })
```

Then, the next time I took a photo, an image would be saved using the `CameraVideoStreamSourceType.WIDE_CAMERA` lens. I followed the same process with `CameraVideoStreamSourceType.ZOOM_CAMERA`.

**This process no longer works using v5.2 SDK and latest firmware on the M3T**. 

*  The M3T doesn't recognize `WIDE_CAMERA` and `ZOOM_CAMERA` even though `CameraKey.KeyCameraVideoStreamSourceRange` returns `WIDE_CAMERA, ZOOM_CAMERA, INFRARED_CAMERA`. 
* The M3T now only recognizes `INFRARED_CAMERA` and `VISION_CAMERA`. `VISION_CAMERA` isn't [documented in the SDK](https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/DJIValue.html?search=cameravideostreamsourcetype&i=0&#value_camera_enum_cameravideostreamsourcetype_inline).

### **Questions/Comments:**
* What does `VISION_CAMERA` mean? Which lens does it apply to? 
* Which drones (M3E, M3T, M30, M30T, M300) use `VISION_CAMERA`?
* Which drones (M3E, M3T, M30, M30T, M300) recognize `WIDE_CAMERA`?
* Which drones (M3E, M3T, M30, M30T, M300) recognize `ZOOM_CAMERA`? 
* Is it possible to save a photo using the WIDE lens on the M3T? If so, then how?
* Is it possible to save a photo using the ZOOM lens on the M3T? If so, then how?

**Comment by DJI-William** [comment]
As you can see, there are only _V and _T photos in M3T. It is because the camera can only know the photo is captured by the visual camera(Both zoom and wide camera are visual camera). You cannot control the photo is captured by zoom or wide. This is deisgned in hardware. Both zoom and wide camera is connected into the same wire. Apart from Mavic 3 enterprise series, the zoom and wide camera can capture photos individually so the setting will work.
