### ISSUE TITLE
rtmp推流花屏

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android-V5#8]
运行demo后使用rtmp进行推流，遥控器和推流画面都存在花屏，是因为现在是beta版本没有开发好吗

**Comment by Michael-DJI** [comment]
你好，请问你是基于哪款机型测试的？

**Comment by Swordce** [comment]
M300

**Comment by Swordce** [comment]
而且在M300上推流的时候，也会出现crash的情况

**Comment by Swordce** [comment]
推流的问题请问有复现修复吗

**Comment by Michael-DJI** [comment]
@Swordce MSDK V5版本目前只适配了M30，还没有适配好M300，不过您现在遇到的问题我们可以尝试复现下，请问您是直接安装在M300的带屏控上测试的吗？复现概率是100%吗？我们已经发布了最新的Beta3版本，您也可以尝试在用下最新版本，谢谢

**Comment by Swordce** [comment]
好的，我是直接在带屏控上使用的，复现的概率比较高

**Comment by DJI-William** [comment]
外出测试发现M30直播推流效果很好，M300直播推流的时候遥控器上画面正常，推流网页端发现飞行器起飞的时候画面模糊、马赛克，需要优化。

**Comment by Swordce** [comment]
大概会在什么时候会发版本优化这个问题

**Comment by DJI-William** [comment]
下个Sprint会尝试优化，下个版本发布预计8月底。

**Comment by DJI-William** [comment]
9月发布的5.1版本会优化这个问题，但是如果app安装在遥控器上还是有花屏，如果外接手机则画面良好，是遥控器本身的问题。M30系列无此问题。

**Comment by DJI-William** [comment]
5.1版本已经解决。
