### ISSUE TITLE
M3T 无人机返航的物理按键无用

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#82]
当打开无人机后,通过继承msdk开发的app进行飞行,但是物理按键返航按了没用

**Comment by DJI-William** [comment]
对于物理按键的点击事件你是怎么监听地呢？可以看看这篇文章，[第十三章：遥控器](https://sdk-forum.dji.net/hc/zh-cn/articles/9849289626265-%E7%AC%AC%E5%8D%81%E4%B8%89%E7%AB%A0-%E9%81%A5%E6%8E%A7%E5%99%A8)。
