### ISSUE TITLE
LOG/CSDK路径内，日志不断增大，直到撑满设备存储

### ISSUE THREAD

**Issue by doncc** [dji-sdk/Mobile-SDK-Android-V5#83]
复现过程：
在M300遥控器上，在操作MOP功能读取信息时，使用while循环不断操作PipelinesManager.readData(PipelineIdentifier var0, byte[] var1)此方法；

现象：
如果用while不断读取信息，且当遥控器和飞机并未建立连接时，会导致存储路径：/sdcard/Android/data/xxx(包名)/files/LOG/CSDK/ 路径下文件内容持续生成，最终导致设备存储撑满;

另外，还有PipelinesManager.readData()方法，在二次读取时，会有接收数据偏移的问题。
详细描述，请参考论坛内沟通记录。https://sdk-forum.dji.net/hc/zh-cn/requests/78237?page=1

**Comment by DJI-William** [comment]
日志增加和数据偏移问题已经和研发确认修复了也合入代码了，新版本在3月31日发布。

**Comment by doncc** [comment]
非常感谢👍
