### ISSUE TITLE
V5 SDK 如何设置照片为8k?

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#85]

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/79009'>Zendesk ticket #79009</a>:<br><br>您可以使用KeyPhotoSize去设置照片尺寸。SIZE_LARGE指的是8K。
<br><p><em><small>°°°</small></em></p>
