### ISSUE TITLE
请问怎么获取拍摄出来的图片？一张原图，一张灰图

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#87]
拍照行为完成以后，再通过MediaDataCenter.getInstance().mediaManager.mediaFileListData获取到多媒体文件；但是获取出来的图片文件会有2张，一张原图，一张灰图，而我仅仅只需要原图

**Comment by DJI-William** [comment]
灰图应该是红外照片，你是想要过滤红外照片嘛？这个没有办法过滤，目前的接口会把所有照片拉取，你可以依靠名称过滤掉红外照片。

**Comment by xwdz** [comment]
红外照片名称的特征告知一下 谢谢

**Comment by DJI-William** [comment]
名字的尾缀有个T。

**Comment by xwdz** [comment]
这里确定个问题；名字我会自定义一下 比如：DJI默认名称+我自己的扩展名称+_T ？是这样吗？

**Comment by DJI-William** [comment]
是的。
