### ISSUE TITLE
MSDK无法在Android12 或更高版本运行

### ISSUE THREAD

**Issue by q3920687** [dji-sdk/Mobile-SDK-Android-V5#88]
当APP的targetSdkVersion设置为32或更高时链接无人机后会可能会导致demo报错，程序崩溃。并不是100%触发
FATAL EXCEPTION: dji_background_thread
Process: com.dji.sampleV5.all, PID: 8850
java.lang.IllegalArgumentException: com.dji.sampleV5.all: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:674)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:661)
	at dji.sdk.datalink.usb.co_a.co_a(DJIUsbAccessoryReceiver.java:36)
	at dji.sdk.datalink.usb.co_a.co_i(DJIUsbAccessoryReceiver.java:5)
	at dji.sdk.datalink.usb.co_a.co_d(DJIUsbAccessoryReceiver.java:1)
	at dji.sdk.datalink.usb.co_a$co_b.handleMessage(DJIUsbAccessoryReceiver.java:2)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by DJI-William** [comment]
目前v5只能支持到29。

**Comment by q3920687** [comment]
> 目前v5只能支持到29。

什么时候才能支持29以上版本

**Comment by DJI-William** [comment]
时间上不会很快。

**Comment by andrewdittmer** [comment]
Does this mean that MSDK5 currently supports about 30% of Android devices worldwide? I feel like this issue should be given high priority.

**Comment by q3920687** [comment]
> Does this mean that MSDK5 currently supports about 30% of Android devices worldwide? I feel like this issue should be given high priority.

Android builds support Android13 by default, so I think it's important to deal with relatively widespread bugs, such as version adaptation

**Comment by DJI-William** [comment]
Currently the majority of the MSDK can only run on DJI RC which are Android 7 and 10.

**Comment by andrewdittmer** [comment]
Thanks for that explanation. I can understand that because DJI is focused on the MSDK working on its controllers, it is not a high priority for DJI. However, for us, we are wanting to make an app to support enterprise level drones and the fact that the MSDK5 won't work on 75% of devices in our target countries is unnacceptable for us. I don't think it is reasonable to expect our customers to try and find a 4+ year old phone in order to use our solution. Because of this, can I please ask that  you will reconsider this as a high priority issue and please provide an expected fix time estimate to support up to Android 13?

**Comment by DJI-William** [comment]
MSDK v5 relies on a base level SDK. If it does not pgrade to support Android 13, MSDk v5 cannot support it. But all DJI offical apps also relies on that SDK. This upgrade will influence every DJI app, this is a huge project. We will discuss internally about this.

**Comment by andrewdittmer** [comment]
Understood. Thanks for for bringing this into an internal discussion.

**Comment by Richard-CRT** [comment]
Is there any update on this? Given that the Mini 3 Pro is on the enterprise app it's really annoying that I can't use any 3rd party apps to control a very much non-enterprise product

**Comment by RoLoTo** [comment]
+1, limiting support to older versions of Android will only cause more contention between DJI and its customers going forward.  I'l considering returning my DJI Mini Pro 3 at this point.

**Comment by dji-lyt** [comment]
5.5版本已经完成了对Android 13的适配，将会在近期发布。
Version 5.5 has finished adapting to Android 13 and will be released in the near future.
