### ISSUE TITLE
使用mVideoDecoder: IVideoDecoder会有卡顿现象

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#90]
SDK Version: 5.2.0
机器: M3T

背景：有一个hostAcivity，两个Fragment，一个Fragment是显示SurfaceView，一个是显示多媒体列表；
当打开多媒体列表fragment时，切回SurfaceView Fragment，SurfaceView Fragment视频流会直接卡住，同时回调DecoderStateChangeListener.onUpdate()函数；我通过一行一行注释代码发现了产生这个问题的原因
```
  MediaDataCenter.getInstance().mediaManager.enable(object :
            CommonCallbacks.CompletionCallback {
            override fun onSuccess() {
                if (!isload) {
                    mediaVM.init()
                    isload = true
                }

                mediaVM.mediaFileListData.observe(viewLifecycleOwner) {
                    adapter!!.updateData(changed(it.data))
                    ui.refreshLayout.finishLoadMore()
                }
            }

            override fun onFailure(error: IDJIError) {
            }
        })
```

当我的多媒体Fragment注释了如上代码时候，切换回SurfaceView Fragment就不会卡住

**Comment by DJI-William** [comment]
enable的时候，图传就会断开。你是什么机型？M300的H20系列、M30系列和御3行业系列可以跳过enable和disable这两个步骤。enable的意思是相机进入回放模式，此时图传通道会被关闭。上述三个机型已经支持不进入相机回放模式拉取媒体文件并且预览。

**Comment by xwdz** [comment]
难怪！本人飞机御3行业系列
