### ISSUE TITLE
 (onFailure:66) fetch failedErrorImp{errorType='SDK', errorCode='MEDIA_MANAGER_FETCH_FILE_LIST_FAILED', innerCode='null', description='无法执行', hint=''} 

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#91]
前两天还正常,今天晚上获取列表一直报这个错误;
官方的App也是读不出来相册

**Comment by xwdz** [comment]
@dji-dev @DJI-William 能否帮忙解决一下

**Comment by DJI-William** [comment]
你的飞行器是什么型号？固件版本是多少？MSDK版本是多少？手动拍照是否能获取媒体文件还是仅仅航线拍照无法获取？航线拍照是否定义了后缀名？后缀名是什么？

**Comment by xwdz** [comment]
飞机型号 : 御3行业版；
固件版本号：目前在上班没法确定，飞机在家里，不过是刚刚更新的最新固件版本（这个问题好像也是升级了最新的固件才发现？我不确定，不过确定的是前段时间都一直正常）；
MSDK:5.2.0；
目前现象就是飞机都能正常飞正常拍照，然后就是相册无法读取，使用原生App也没发读取，使用SDK就如标题报错，我把SD卡拿下来用读卡器看的话拍照，录像的照片都生成了，就是app和MSDK都读不出来；
没有使用航线任务；
后缀名我自己有定义：DJI默认名字+业务唯一ID；
@DJI-William

**Comment by xwdz** [comment]
@DJI-William 能否尽快帮忙看看问题

**Comment by DJI-William** [comment]
这个问题就是文件后缀名的问题，最新固件开始后缀名不可以以数字开头，你换成英文字母或者汉字开头就可以了，后续固件版本会优化。

**Comment by xwdz** [comment]
没太懂；  DJI默认名字+业务唯一ID（修改成汉字还是说改成（A_业务唯一ID） ？

**Comment by DJI-William** [comment]
修改成 DJI默认名字+A_业务唯一ID问题应该就解决了。

**Comment by xwdz** [comment]
这样的话我以前的图片要怎么办呢？ 相当于都要适配以前的老版本啊，需要拼接id A_业务Id；

**Comment by DJI-William** [comment]
那你先降固件到前一个版本吧。

**Comment by xwdz** [comment]
怎么降级呢？ 发一下教程

**Comment by DJI-William** [comment]
直接连上DJI Assistant 2，选择上一个版本升级即可。这个软件在官网的御3行业版页面有下载。

**Comment by xwdz** [comment]
好的

**Comment by xwdz** [comment]
通过避免文件名包含数字解决该问题;
