### ISSUE TITLE
每次拍照完毕后，需要立马下载图片

### ISSUE THREAD

**Issue by xwdz** [dji-sdk/Mobile-SDK-Android-V5#96]
1. 先通过CameraKey.KeyNewlyGeneratedMediaFile 获取到照片的index
2. 然后通过PullMediaFileListParam.Builder().mediaFileIndex(newValue.index)获取到index
3. 最后通过list拿到这张图片进行下载，但是偶尔下载的时候回报错 onFailure ErrorImp{errorType='SDK', errorCode='MEDIA_MANAGER_PULL_ORIGIN_FILE_FAILED', innerCode='null', description='无法执行', hint=''}

**Comment by xwdz** [comment]
SDK: v5.2.0

**Comment by DJI-William** [comment]
下载照片需要占用一定的图传带宽，若图传信号不好可能会下载失败。如果是偶现，重试就好。

**Comment by 98kWarning** [comment]
```kotlin
 fun getNewMediaFile(): GeneratedMediaFileInfo? {
       return KeyManager.getInstance().getValue(createKey(CameraKey.KeyNewlyGeneratedMediaFile))
 }
```
请问一下，我代码是这些写的，拍完照后直接调用就返回null。
然后我设置了监听
```kotlin
  KeyManager.getInstance().listen(KeyTools.createKey(CameraKey.KeyNewlyGeneratedMediaFile), this) { _, newValue ->
            Log.d("====KeyNewlyGeneratedMediaFile====",newValue.toString())
   }
```
监听也是不走的，咋回事呢
