### ISSUE TITLE
5.3 Pending Intent Crash

### ISSUE THREAD

**Issue by lucas-skyebrowse** [dji-sdk/Mobile-SDK-Android-V5#98]
Using latest SDK got this crash on the crash log sdk:

IllegalArgumentException
argeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

![obraz](https://user-images.githubusercontent.com/130150425/231522808-b7188242-8c9a-468f-92f2-07d9a2573cd9.png)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81044'>Zendesk ticket #81044</a>:<br><br>Could you send us your configuration file?  The SDK does not currently support a targetversion of the API above 29.
 ![](https://djisdksupport.zendesk.com/attachments/token/J7VXGxxTwnywvF2CwHOgjIvws/?name=image.png)<br><a href='https://djisdksupport.zendesk.com/attachments/token/J7VXGxxTwnywvF2CwHOgjIvws' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by lucas-skyebrowse** [comment]
Could that be updated to allow publishing on Google Play? Mini3 on smartphones could be used in this case.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81044'>Zendesk ticket #81044</a>:<br><br>We have fed back to the team the need to support newer Android versions.
<br><p><em><small>°°°</small></em></p>

**Comment by Richard-CRT** [comment]
+1 to need for supporting newer Android versions. Phones nowadays are coming out with A12 or A13 and the inability to run the MSDK in 3rd party apps is very limiting

**Comment by GregCornis** [comment]
+1 here, it seems absurd that the SDK be so outdated compared to Android releases. It would be great to have something up to date

**Comment by RoLoTo** [comment]
+1, limiting support to older versions of Android will only cause more contention between DJI and it's customers going forward.  I'l considering returning my DJI Mini Pro 3 at this point.

**Comment by dji-lyt** [comment]
Version 5.5 has finished adapting to Android 13 and will be released in the near future.
