### ISSUE TITLE
5.3 WaypointMissionManager.pushKMZFileToAircraft() not working on Mini3

### ISSUE THREAD

**Issue by lucas-skyebrowse** [dji-sdk/Mobile-SDK-Android-V5#99]
Are Waypoint missions supported on the Mini3/Mini 3 pro? 

Trying to use kmz file missions I get: 
errorCode: REQUEST_HANDLER_NOT_FOUND

and:
ErrorImp{errorType='WAYPOINT', errorCode='REQUEST_HANDLER_NOT_FOUND', innerCode='null', description='null', hint='null'}

**Comment by DJI-William** [comment]
Mini 3/Mini 3 Pro's firmware does not support the native waypointMission function so SDK cannot support this feature as well.

**Comment by bettisfr** [comment]
How can we "emulate" a waypoint mission on Mini 3 pro then?
